### ISSUE TITLE
About some errors when using nDMaterial

### ISSUE THREAD

**Issue by JESSEEZZ** [OpenSees/OpenSees#1023]
Hello Administrator
I am performing a seismic analysis of a liquefaction site.
I built a two-dimensional soil column with twenty "Four Node Quad u-p Element". The lower ten elements used PDMY material with tag 1 and the upper ten elements used PIMY material with tag 2.
After that, I changed the tag of the upper ten elements to 3, and the calculation result changed.
This problem also occurred in the soil column where both soil layers were PDMY. That is, the calculation results are biased when nDMaterial is used with numbers of 3 and above.
How can I avoid this mistake?

**Comment by mhscott** [comment]
The issues on this repo are for issues with the source code, e.g., bugs, improvements, etc.
Your issue appears to be one of modeling approach and choices. Please post your question on the OpenSees message board or Facebook group. If you find there is a bug in the source code, re-open this issue on GitHub.
