### ISSUE TITLE
Fail to send stdBrick elements in OpenSeesSP after recent updates

### ISSUE THREAD

**Issue by jf-huang** [OpenSees/OpenSees#1031]
I was using the recent code (after #1024 ) for OpenSeesSP while it failed to send stdBrick elements during the partition process due to a segmentation fault, as shown below. This was for a minimal (not) working example consisting of 4 stdBrick elements and would fail when np>=2.
![image](https://user-images.githubusercontent.com/44045796/196240871-74d7f300-496e-4ffa-b2ae-d49060b11e9c.png)

Note I also did tests using elasticBeamColumn or dispBeamColumn elements and they worked fine. This indicates that the issue may have come from the sendSelf() and recvSelf() functions in Brick.cpp after recent changes. The test model I used is attached.

Thanks in advance!
[main_stdbrick.zip](https://github.com/OpenSees/OpenSees/files/9803084/main_stdbrick.zip)

**Comment by mhscott** [comment]
Thanks for providing a simple example!

@yulee The error is here. You want to check `theDamping[0]`, not `theDamping`
![image](https://user-images.githubusercontent.com/13142652/196247482-21b5a01c-d943-472d-a6a3-8244ccf036df.png)

Please check all elements for similar errors in sendSelf/recvSelf

**Comment by jf-huang** [comment]
Appreciate the swift responses @mhscott @yulee !! The problem is fixed after also changing "theDamping" on line 1399 to "theDamping[0]" in #1032  @yulee . Closing now.
