### ISSUE TITLE
About the loading problem of OpenFresco and Opensees

### ISSUE THREAD

**Issue by Lo-Jay-Benny** [OpenSees/OpenSees#1038]
Hi，
I am using OpenFresco with Opensees for research
I use OpenSees version 3.3.0/64bits - Openfresco 2.7.0
But I get error message:
Could not find function: OpenFresco
command returned bad code: -1
If I change the Opensees version to 2.4.5, 
it can load package OpenFresco v2.7.0.
But I have new elements added in Opensees v3.3.0 so I have to use this version.

Can't I use the OpenFresco Package with versions 3.3.0 of OpenSees?
I'm a novice using this software, please forgive me if I ask too strange questions

**Comment by fmckenna** [comment]
@aschellenberg74 ..

**Comment by aschellenberg74** [comment]
Please [download](https://openfresco.berkeley.edu/users/openfresco/) or [build](https://github.com/aschellenberg74/OpenFresco) OpenFresco 2.7.2 which will work with the latest OpenSees 3.4.0. I hope you can incorporate your new elements into that version of OpenSees.

**Comment by Lo-Jay-Benny** [comment]
@fmckenna @aschellenberg74 Thank you for your help!
I replaced both Opensees and OpenFresco with these two versions, but still have the problem of 
Could not find function: OpenFresco
command returned bad code: -1
What else can I do to adjust?
Thank you again for your help!

**Comment by Lo-Jay-Benny** [comment]
I used OpenFresco v2.7.2 to get Opensees to load package.
Experimental command (expControlPoint, expControl, expSetup......) show the error as shown in the figure.
WARNING invalid number of arguments
command returned bad code: -1
I don't know what I'm doing wrong
![image](https://user-images.githubusercontent.com/112811962/197990506-60ed7c81-403a-46fd-8a43-43cc2c052415.png)
