### ISSUE TITLE
participating mass in a eigenvalue analysis

### ISSUE THREAD

**Issue by MedSaadMor** [OpenSees/OpenSees#104]
is there a code calculating participating mass and mass ratios, other than rSpectrum which appairs to presents several issues. 

thanks you

**Comment by JianYZHANG** [comment]
I have a similar problem, and whether you find the related code. If possible, please send me a copy, and Thank you for your help.

**Comment by mhscott** [comment]
This script may help: https://github.com/volkanozsarac/ModalAnalysis-OpenSeespy
