### ISSUE TITLE
Are OpenSeesMP and SP ready in Windows?

### ISSUE THREAD

**Issue by fslurrehman** [OpenSees/OpenSees#1051]
Hi, 

I cannot compile OpenSeesMP and SP on windows. All targets can be compiled on linux and mac but windows has problem in MP and SP. 

There are build steps for mumps, OpenSeesMP and SP in documentation. Though there are some compilation issues as per the steps for mumps and OpenSees, I managed to compile mumps, OpenSees and OpenSeesPy. But I get following compilation error for OpenSeesMP:

```
71>mumps_common.lib(mumps_io.c.obj) : error LNK2019: unresolved external symbol __imp_remove referenced in function MUMPS_OOC_REMOVE_FILE_C
71>mumps_common.lib(mumps_io_err.c.obj) : error LNK2019: unresolved external symbol __imp_strdup referenced in function mumps_io_sys_error
71>OLDNAMES.lib(strdup.obi) : error LNK2001: unresolved external symbol __imp_strdup
71>mumps_common.lib(mumps_io_basic.c.obj) : error LNK2019: unresolved external symbol __imp_ferror referenced in function mumps_io_do_write_block
71>C:\Users\fr\OpenSees\build\bin\OpenSeesMP.exe : fatal error LNK1120: 3 unresolved externals
71>Done building project "OpenSeesMP.vcxproj" -- FAILED.
========== Build: 70 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by fmckenna** [comment]
you can build them following the instructions on the website:

https://opensees.github.io/OpenSeesDocumentation/
