### ISSUE TITLE
Adding self weight to tetraedon elements 

### ISSUE THREAD

**Issue by mlaura1996** [OpenSees/OpenSees#1053]
Dear @mhscott, 
I am working with solid elements (tetrahedron mesh) to model unreinforced masonry buildings. I am using the @jaabell converter from gmsh (https://joseabell.com/posts/2022/eosd2022-summer-school-ssi-modeling.html) after attending EOS summer school. My question is: I need now to apply self-weight to each element, how can I do it? I think that the best way would be to use "EleLoad", in order to apply the load directly to the element, but I see that this has been not implemented for continuum elements (https://opensees.berkeley.edu/wiki/index.php/EleLoad_Command). Is there any straightforward way to apply self weight to the elements? Should I use nodal loads? is there any example?
Thank you!

**Comment by mhscott** [comment]
Please post modeling questions to the OpenSees message board or Facebook group, or contact @jaabell directly. The issues on this repo are for bug fixes, enhancements, implementation, source code, etc.

**Comment by jaabell** [comment]
> 

I'd be happy to help.

**Comment by silviamazzoni** [comment]
@jaabell, she has posted on the facebook page. that page has become the de facto opensees support group, lots opportunities to help there.

**Comment by mlaura1996** [comment]
Thank you @jaabell! Is there a way I can contact you?

**Comment by jaabell** [comment]
Hi, my github user at uandes dot cl is my email.
