### ISSUE TITLE
How to obtain the up-to-date win64 libraries for building OpenSees 3.4.0

### ISSUE THREAD

**Issue by yoyo-chen** [OpenSees/OpenSees#1066]
I am building OpenSees 3.4.0 using Visual Studio 2022 on a Win64 PC. I found the following libraries from the internet and copied them into the folder "OpenSees-3.4.0/Win64/lib". 
ifconsol.lib
libdecimal.lib
libifcoremt.lib
libifport.lib
libirc.lib
libm.lib
libmmt.lib
svml_dispmt.lib

However, those libraries are compiled by VisualStudio versions earlier than 2015, so LNK2001 and LNK2019 errors occur. 
Therefore I wonder how to obtain those libraries compiled by VisualStudio versions later than 2015. 

The error messages are listed below.

Error	LNK1120	2 unresolved externals	OpenSees	C:\Program Files\OpenSees-3.4.0\Win64\bin\OpenSees.exe	1	
Error	LNK2019	unresolved external symbol "void * __cdecl OPS_HarmonicSteadyState(void)" (?OPS_HarmonicSteadyState@@YAPEAXXZ) referenced in function "int __cdecl specifyIntegrator(void *,struct Tcl_Interp *,int,char const * *)" (?specifyIntegrator@@YAHPEAXPEAUTcl_Interp@@HPEAPEBD@Z)	OpenSees	C:\Program Files\OpenSees-3.4.0\Win64\proj\openSees\tcl.lib(commands.obj)	1	
Error	LNK2001	unresolved external symbol __iob_func	OpenSees	C:\Program Files\OpenSees-3.4.0\Win64\proj\openSees\libifcoremt.lib(for_nt_open_proc.obj)	1	
Error	LNK2001	unresolved external symbol __iob_func	OpenSees	C:\Program Files\OpenSees-3.4.0\Win64\proj\openSees\libmmt.lib(libm_error.obj)	1	
Error	LNK2019	unresolved external symbol __iob_func referenced in function for__issue_diagnostic	OpenSees	C:\Program Files\OpenSees-3.4.0\Win64\proj\openSees\libifcoremt.lib(for_diags_intel.obj)	1	

By the way, I have added the legacy_stdio_definitions.lib to Menu->Project->Property->Linker->Input->Additional Dependencies, so the LNK2001 about sprintf has been solved. 
However, I can't figure out how to solve the other errors above. I think using the up-to-date win64 library files may solve them. Other methods will also be appreciated.

**Comment by fmckenna** [comment]
follow the instruction is doc for building with cmake on windows. visual studio projects are going away soon.

**Comment by yoyo-chen** [comment]
> follow the instruction is doc for building with cmake on windows. visual studio projects are going away soon.

Thank you so much, Frank! I will try building with CMake following the instruction in OpenSeesdocumentation.

**Comment by yoyo-chen** [comment]
I found those library files in the following directory on my PC,
C:\Program Files (x86)\Intel\oneAPI\compiler\2022.2.1\windows\compiler\lib\intel64_win

I added this directory to the OpenSees Property->Linker->Additional Library Directories, and the build succeeded.

**Comment by yuc-Zhao** [comment]
> I found those library files in the following directory on my PC, C:\Program Files (x86)\Intel\oneAPI\compiler\2022.2.1\windows\compiler\lib\intel64_win
> 
> I added this directory to the OpenSees Property->Linker->Additional Library Directories, and the build succeeded.

I did the same thing, but VS encountered the following error again.
错误	LNK2019	无法解析的外部符号 vsprintf，函数 for__issue_diagnostic 中引用了该符号	OpenSees	D:\OSbj\OpenSees-3.5.0\OpenSees-3.5.0\Win64\proj\openSees\libifcoremt.lib(for_diags_intel.obj)	1	

错误	LNK2001	无法解析的外部符号 vsprintf	OpenSees	D:\OSbj\OpenSees-3.5.0\OpenSees-3.5.0\Win64\proj\openSees\libirc.lib(irc_msg_support.obj)	1	

错误	LNK2019	无法解析的外部符号 __iob_func，函数 for__issue_diagnostic 中引用了该符号	OpenSees	D:\OSbj\OpenSees-3.5.0\OpenSees-3.5.0\Win64\proj\openSees\libifcoremt.lib(for_diags_intel.obj)	1	

错误	LNK2001	无法解析的外部符号 __iob_func	OpenSees	D:\OSbj\OpenSees-3.5.0\OpenSees-3.5.0\Win64\proj\openSees\libifcoremt.lib(for_nt_open_proc.obj)	1	

错误	LNK2001	无法解析的外部符号 __iob_func	OpenSees	D:\OSbj\OpenSees-3.5.0\OpenSees-3.5.0\Win64\proj\openSees\libmmt.lib(libm_error.obj)	1	

错误	LNK2019	无法解析的外部符号 _snprintf，函数 write_message 中引用了该符号	OpenSees	D:\OSbj\OpenSees-3.5.0\OpenSees-3.5.0\Win64\proj\openSees\libmmt.lib(libm_error.obj)	1	

错误	LNK2001	无法解析的外部符号 _snprintf	OpenSees	D:\OSbj\OpenSees-3.5.0\OpenSees-3.5.0\Win64\proj\openSees\libirc.lib(tbk_display.obj)	1	

错误	LNK1120	3 个无法解析的外部命令	OpenSees	D:\OSbj\OpenSees-3.5.0\OpenSees-3.5.0\Win64\bin\OpenSees.exe	1	

I don not know how to solve this problme , if you can give me some suggestion , I would greatly appreciate it.
