### ISSUE TITLE
cNodeTag argument Not working for getRetainedNodes 

### ISSUE THREAD

**Issue by BijanSeif** [OpenSees/OpenSees#1068]
Hi,

In the [OpenSeesOutputCommands.cpp,](https://github.com/OpenSees/OpenSees/blob/master/SRC/interpreter/OpenSeesOutputCommands.cpp) command getRetainedNodes or getConstrainedNodes get one argument. Here is the part that it checks it.

```
    if (OPS_GetNumRemainingInputArgs() > 2) {
	  if (OPS_GetIntInput(&numdata, &cNodeTag) < 0) {
		opserr << "WARNING getRetainedNodes <cNodeTag?> - could not read cNodeTag\n";
		return -1;
	  }
	all = 0;
    }
```

It seems that it asks for the Constrained node tag, and it returns the retained node that cNodeTag is retained to. In the follwoing python code it does not work:

```
ops.wipe()
ops.model('basic','-ndm',3)

i=0
ops.node(1,0,0,0)
ops.node(2,1,0,0)
ops.node(3,2,0,0)
ops.node(4,3,0,0)
ops.node(5,4,0,0)
ops.node(6,5,0,0)
ops.node(7,4,0,0)
ops.node(8,5,0,0)
ops.node(9,4,0,0)
ops.node(10,5,0,0)


ops.equalDOF(8,9,1)

ops.rigidLink('bar',1,2)
ops.rigidLink('bar',1,4)
ops.rigidLink('bar',3,5)
ops.rigidLink('bar',3,6)



print('Constrained=',ops.getConstrainedNodes(1))
print('Retained=',ops.getRetainedNodes(2))
```

and its results is:

Constrained= [2, 4, 5, 6, 9]
Retained= [1, 3, 8]

As you see it returns all Constrained or Retained Tags instead of those that node2 has constrained to or node1 has retained to!

**Comment by sewkokot** [comment]
@BijanSeif, Thank you for reporting this bug. I will fix it and send a PR.

**Comment by BijanSeif** [comment]
Thanks, dear Dr. @sewkokot
