### ISSUE TITLE
setParameter backward compatibility issue after recent commit

### ISSUE THREAD

**Issue by MassimoPetracca** [OpenSees/OpenSees#1072]
Dear @mhscott ,  due to a recent commit https://github.com/OpenSees/OpenSees/commit/b15a2e575f9442e0f5f57bca32f92d858547f288, the **setParameter** command will not work anymore as before.

In fact, this command assumed that a parameter with tag = 0 is not added to the domain, but only invoked. But I understand the reason for the changes in the commit. In fact, it is not stated anywhere that a tag = 0 has a particular meaning for a Parameter.

Therefore, I was thinking about a nice way to keep backward compatibility in the setParameter command, between the 2 following options.

1. In the **setParameter** command, find a non-existing parameter tag, use it for the new Parameter, add it to the domain to execute it, and remove it.
2. Add a **boolean flag in the Parameter** class (bool is_temporary = false, by default). The setParameter command sets it to true. In the domain class, do a check (similar to the one removed in the commit): _if (theParam->isTemporary()) -> invokeOnly_

What do you suggest?

**Comment by mhscott** [comment]
@MassimoPetracca Option 1 is probably better as it's localized and doesn't require changes to Parameter or Domain classes. Thanks!

**Comment by MassimoPetracca** [comment]
@mhscott Fixed in #1078 
I'll close this issue
