### ISSUE TITLE
Best element for handling axial load and biaxial bending?

### ISSUE THREAD

**Issue by epsi1on** [OpenSees/OpenSees#1076]
Hi,
I need to analyze a structure consist of armed concrete beam and columns (say for example single span single level frame at simplest form)
Need static nonlinear (both material and geometrical non-linearity) analysis .
I'm aware of fiber element, which could be used to model material non-linearity. is there any other 1D element which can be used to model material non-linearity of concrete beam or column? note that to reduce computation cost, I rather to reduce DoFs by use of 1d elements (like beam column) instead of 2d (like shell) or 3d (like brick).

Thanks

**Comment by mhscott** [comment]
Issues are for bugs in the source code or requested features. Modeling questions should be asked in the OpenSees message board or in the OpenSees Facebook group.
