### ISSUE TITLE
 Building project "OpenSeesSP.vcxproj" -- FAILED

### ISSUE THREAD

**Issue by sunxiaoling** [OpenSees/OpenSees#1080]
Hi OpenSees developers:
I have been trying to build OpenSeesMP and OpenSeesSP on my PC (Windows 10 system 21H2) for a while now.
I am using the installation scripts and up-to-date sources(2022.12.01) available here (I am using Intel compilers 2022 , VS2019):
I was able to successfully build and run OpenSees and OpenSeesMP with the document setup.
However, for OpenSeesSP, I keep getting the following errors:
Thank you very much for your help！Best wishes!

D:\Users\OpenSources\OpenSees\build>cmake --build . --config Release --target OpenSeesSP

Microsoft Visual Studio 2019 Version 16.11.21.
Copyright (C) Microsoft Corp. All rights reserved.
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking File Globs
2>------ Build started: Project: OpenSeesSP, Configuration: Release x64 ------
2>Building Custom Rule D:/Users/OpenSources/OpenSees/CMakeLists.txt
2>mpiMain.cpp
2>tclMain.cpp
2>commands.cpp
2>D:\Users\OpenSources\OpenSees\SRC\analysis\integrator\Houbolt.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\analysis\integrator\ParkLMS3.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>PartitionedDomain.cpp
2>PartitionedDomainEleIter.cpp
2>PartitionedDomainSubIter.cpp
2>FEM_ObjectBrokerAllClasses.cpp
2>D:\Users\OpenSources\OpenSees\SRC\material\uniaxial\ViscousDamper.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\element\zeroLength/ZeroLengthContactNTS2D.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\element\zeroLength/ZeroLengthInterface2D.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\element\zeroLength/ZeroLengthContactASDimplex.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\element\mvlem/MVLEM.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\element\mvlem/SFI_MVLEM.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\element\RockingBC/RockingBC.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\analysis\integrator\KRAlphaExplicit.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\analysis\integrator\KRAlphaExplicit_TP.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>D:\Users\OpenSources\OpenSees\SRC\domain\pattern\drm/H5DRM.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2>MPI_MachineBroker.cpp
... ...
2>ometis.c
2>Generating Code...
2>   Creating library D:/Users/OpenSources/OpenSees/build/lib/OpenSeesSP.lib and object D:/Users/OpenSources/OpenSees/build/lib/OpenSeesSP.exp
2>OPS_InterpTcl.lib(myCommands.obj) : error LNK2019: unresolved external symbol "class Domain theDomain" (?theDomain@@3VDomain@@A) referenced in function "int __cdecl specifyModelBuilder(void *,struct Tcl_Interp *,int,char const * *)" (?specifyModelBuilder@@YAHPEAXPEAUTcl_Interp@@HPEAPEBD@Z)
2>OPS_InterpTcl.lib(Tcl_generateInterfacePoints.obj) : error LNK2001: unresolved external symbol "class Domain theDomain" (?theDomain@@3VDomain@@A)
2>  Hint on symbols that are defined and could potentially match:
2>    "class PartitionedDomain theDomain" (?theDomain@@3VPartitionedDomain@@A)
2>D:\Users\OpenSources\OpenSees\build\bin\OpenSeesSP.exe : fatal error LNK1120: 1 unresolved externals
2>Done building project "OpenSeesSP.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 69 up-to-date, 0 skipped ==========

**Comment by mhscott** [comment]
The Visual Studio projects will not function for SP and MP.
Try the CMake build instead: https://opensees.github.io/OpenSeesDocumentation/developer/build.html
