### ISSUE TITLE
nodeEigenvector Error

### ISSUE THREAD

**Issue by BijanSeif** [OpenSees/OpenSees#1098]
Hi 

As it is shown in the following, for a 2D model I got 4 numbers for a node eigen vector while the other nodes give 3 that is compatible with what I expect. I thought maybe it is an error that should be check. I'm trying to provide a MWE for this issue.

![image](https://user-images.githubusercontent.com/82403633/209333101-6435d162-9cd3-4ef5-bf0b-62c5633f59b5.png)

As it is seen in the following there are some other nodes with similar results:

![image](https://user-images.githubusercontent.com/82403633/209333165-9f259f8d-8c7b-44e8-9939-0761eabe5c3b.png)

**Comment by mhscott** [comment]
@BijanSeif What type of elements are connected to the nodes where you get four eigenvector components? Are you using multi-point constraints of some kind, like equalDOF or rigidDiaphragm?

**Comment by BijanSeif** [comment]
Prof. @mhscott I'm Using [Joint2D](https://opensees.berkeley.edu/wiki/index.php/Joint2D_Element) element that as you said this element uses multipoint constraints internally. So, because of your prediction, it means that we should get extra eigen vector for multipoint constraints and there is no error for nodeEigenvector command. Does the extra value have different meaning? (I mean that probably it is not a node eigenvector value because of DOF numbers or I'm wrong)

**Comment by mhscott** [comment]
The Joint2D element creates an internal node with 4 DOFs and adds that node to the domain. The meaning of the internal node DOFs can be determined from the element implementation. Not an error, so closing the issue.
