### ISSUE TITLE
how to comppilethe opensees source code on VS

### ISSUE THREAD

**Issue by Ljz6332056** [OpenSees/OpenSees#114]
Hello, when I tried to compile the opensees source code on VS2017, it returned an error: unable to open the file libmmt.lib.How do I get this file?

**Comment by afei190** [comment]
You need the library. One way to get it is to install Intel C++ compiler. Student can get the libraries with the compiler for free: 
https://software.intel.com/en-us/parallel-studio-xe/choose-download/student-windows

**Comment by Ljz6332056** [comment]
thanks for your help! I have found libmmt.lib file in the old opensees source code, but anther error returned: unable to open the file libdecimal.lib! Then I tried your idea,but the web site is not allow register,a bad news~can i solve it by Visual Studio?

**Comment by mhscott** [comment]
Try this video if you haven't solved the issue: https://youtu.be/BLcY1w7a5Ec
