### ISSUE TITLE
Standard brick material

### ISSUE THREAD

**Issue by siddharthfcb** [OpenSees/OpenSees#1164]
The following code creates a standard brick element but does not assign material parameter to it. I am trying to do this according to the command manual.. When I print model, then there is no material information. I am not sure if the code assigns any material to the element. printA also does not return anything. Any suggestions would be much appreciated. 
```python
import openseespy.opensees as ops
import os as os
import numpy as np
import matplotlib.pyplot as plt
import time as tmes
import numpy.matlib as mtlib
ops.wipe()
ops.model('basic', '-ndm', 3, '-ndf', 3)
    
ops.node(13,   -40,   -35,    -5)
ops.node(200,   -35,   -35,    -5)
ops.node(189,   -35 ,  -40,    -5)
ops.node(2,   -40,   -40,    -5)
ops.node(12 ,  -40 ,  -35,     0)
ops.node(199,   -35,   -35 ,    0)
ops.node(188 ,  -35,   -40 ,    0)
ops.node(1  , -40 ,  -40 ,    0)

ops.nDMaterial('ElasticIsotropic', 1000000000000, 100000000, 0.3, 20000)

ops.element('stdBrick',1,13,200,189,2,12,199,188,1, 1000000000000)

ops.fix(13,1,1,1)
ops.fix(200,1,1,1)
ops.fix(189,1,1,1)
ops.fix(2,1,1,1)

ops.printModel()
ops.printA('-file','A.txt')
```

**Comment by mhscott** [comment]
The print flags are not used consistently in the source code between the brick element and the material.

You get nothing from `printA` because you have not done an analysis yet.
