### ISSUE TITLE
Deterioration Parameter lamda (Haselton) does not work in IMKPeakOriented Material

### ISSUE THREAD

**Issue by shakeri-aliakbar** [OpenSees/OpenSees#1167]
@amaelkady
Hi,
I use IMKPeakOriented material with parameters determined by Haselton et al (2008) and the lambda is 65.0,
No deterioration is occurred with this value even when I use your Subroutine Spring_IMK_RC in FM-2D.

uniaxialMaterial IMKPeakOriented 133 49860073440.5 0.014 0.031 0.054 410697523.9 1.162 0.01 0.014 0.031 0.054 410697523.9 1.162 0.01 65.1 65.1 65.1 65.1 1 1 1 1 1 1

lambda=170.7	* 0.27^(PPc)*0.1^(s/d)

**Comment by amaelkady** [comment]
@shakeri-aliakbar The model, based on your definition above, works/deteriorates fine under a generic cyclic deformation history, as shown below. Please revise your model units as well as the definition of lambda Λ per Lignos & Krawinkler (2011). Note that there are Λ and λ, where Λ = λ · θp. The former, Λ is used in the IMK models.

![image](https://user-images.githubusercontent.com/39971525/221514124-854c346d-075b-4602-a01f-b21c7d84be90.png)

**Comment by mhscott** [comment]
@amaelkady Also, to avoid confusion, perhaps use different letters instead of different cases for lambda and LAMBDA

**Comment by shakeri-aliakbar** [comment]
@amaelkady 
Thanks,

Two questions:
In subroutine Spring_IMK_RC.tcl:
https://github.com/amaelkady/FM-2D/blob/master/src/Spring_IMK_RC.tcl

1. Ke is not modified by (n+1) !
2. lambda is not multiplied by theta_p !

**Comment by mhscott** [comment]
@shakeri-aliakbar Please post issues with FM-2D at its GitHub page: https://github.com/amaelkady/FM-2D

**Comment by shakeri-aliakbar** [comment]
@mhscott  Sure, Thanks.

**Comment by amaelkady** [comment]
@mhscott done; definition has been clarified in the documentation. Please commit the pull requests.

**Comment by amaelkady** [comment]
@mhscott please close this issue as well.
