### ISSUE TITLE
Ain't opening of Opensees website

### ISSUE THREAD

**Issue by Tahminev** [OpenSees/OpenSees#1175]
I can't enter to OpenseesWiki
When i click on (openseeswiki) or ( command manual) I receive this message <<Forbidden
You don't have permission to access /wiki/index.php on this server>>
Please help me

**Comment by mhscott** [comment]
Yes, the website seems to be down.

Please note, this is the source code repo for OpenSees, not the wiki or the website. Issues should be about the source code.

**Comment by Tahminev** [comment]
What should i do right now?
How can I access the codes?
