### ISSUE TITLE
website to be down

### ISSUE THREAD

**Issue by Tahminev** [OpenSees/OpenSees#1177]
i can not access to <<openseeswiki & command manual>> it seems that website to be down!
how can I access to command manual to obtain structural modeling codes?

**Comment by Tahminev** [comment]
Why do you close my message as complete while I didn't get any answer from
you?

**Comment by mhscott** [comment]
The status of opensees.berkeley.edu is not an issue related to this GitHub repository.

Until the website is back up, you can find other resource online, e.g., https://opensees.github.io/OpenSeesDocumentation/ or OpenSeesPy https://openseespydoc.readthedocs.io/en/latest/

**Comment by Tahminev** [comment]
Thank you so much for your reply
Where can I write issues about opensees website?
