### ISSUE TITLE
analysis problem!!

### ISSUE THREAD

**Issue by nohaelsaied** [OpenSees/OpenSees#1180]
> hi every one , I developed a code simulating 3-span T-girder bridge using opensees tcl version 3.30  , the mass of superstructure is 700 ton /span 
> i have assigned the load corresponding to each span at girder nodes, and checked the code before analyzing gravity load 
> however, the program gives me the following error and the recorder files aren't created
> "Node::addunbalLoad - load to add of incorrect size 3 should be 6"
> could any one help me solving this issue? 
> i will be very grateful,

The following elements are used:
1.elastic beam column element for longitudinal t girder, and diaphrams
2.spring element for shear key and for abutment backfill
3.flat slider bearing element for rubber bearing and expansion bearing.
4.Fiber section for R.C  column

thank you,

**Comment by mhscott** [comment]
Please post modeling questions on the OpenSees message board or the Facebook group.

The issues here are for bugs and changes in the source code.
