### ISSUE TITLE
OpenSees > analyze failed, returned: -3 error flag 0.0

### ISSUE THREAD

**Issue by Mat6935** [OpenSees/OpenSees#1190]
Good morning. I started to model a shell with openseespy in 3 dimensions. I use a basic rectangular shell with 4 nodes and I want to obtain the vertical displacement at a fifth node located at the center of this shell. I face problems to analysis step.

Could you help me please ? Here is the script I wrote and the message error.
![Captureopensees](https://user-images.githubusercontent.com/132265276/235623033-fe57a7d5-7020-4cea-875d-c4bb1b695390.PNG)
![Captureopensees2](https://user-images.githubusercontent.com/132265276/235623066-82bbc93b-4e18-4c91-9224-0c389881de78.PNG)
![Captureopensees3](https://user-images.githubusercontent.com/132265276/235623192-4c135440-9a78-42c0-8c9f-0de8baf2e8b3.PNG)

**Comment by mhscott** [comment]
You don't have sufficient boundary conditions to prevent rigid body motion.

This repo is for bugs and improvements in the source code of OpenSees. In the future, please post modeling questions and issues on the OpenSees message board or the OpenSees Facebook group.
