### ISSUE TITLE
OpenSees Wiki - Images not loading

### ISSUE THREAD

**Issue by morgankmcbain** [OpenSees/OpenSees#1202]
I've been having an issue viewing the png images on the OpenSees wiki (https://opensees.berkeley.edu/wiki/index.php/Main_Page), and my peers are having this same problem. For example, when I try to view "Hysteretic2.png" (https://opensees.berkeley.edu/wiki/index.php/Hysteretic_Material) I ultimately get an error saying "You don't have permission to access /wiki/images/9/95/Hysteretic2.png on this server." I'm trying to access the image on my university's wifi. 
Restoration of the ability to view the images describing object definition would be much appreciated!

**Comment by zhangheng1198** [comment]
我也遇到了同样的问题

**Comment by mhscott** [comment]
The wiki is not part of the source code on this repo, but @fmckenna will look into it today.
