### ISSUE TITLE
Possible memory leak caused by using section("Fiber") and patch("quad") simultaneously.

### ISSUE THREAD

**Issue by zAlexliu-8895** [OpenSees/OpenSees#1214]
Hi Professor  Scott,

There is a possible memory leak when using section("Fiber") and patch("quad") together.
An MWE is attached below:

```
import openseespy.opensees as ops

Counter = 0
while Counter < 100000000:
    Counter += 1
    ops.wipe()

    ops.model('basic', '-ndm', 2, '-ndf', 3)
    
    ops.uniaxialMaterial("Concrete02", 1, -33, -0.0015, -20, -0.005, 0.1, 2.2, 1100)
    
    ops.section("Fiber", 1, "-GJ", 200e9)
    ops.patch("quad", 1, 40, 10, -200, -38, 200, -38, 200, 62, -200, 62)
```

Note that using section("Fiber") or patch("quad") alone does not cause a memory leak. It happens only if two commands are used simultaneously.

Thank you.

**Comment by mhscott** [comment]
@zAlexliu-8895 Thanks for making the MWE! I'll take a look.

**Comment by zAlexliu-8895** [comment]
@mhscott Hi Professor Scott, thank you for fixing it.
Just a quick follow-up question, how do I update OpenSeesPy? I tried `pip install git+https://github.com/OpenSees/OpenSees.git` and it failed with `fatal: No url found for submodule path 'Win64/s3hark' in .gitmodules`.

**Comment by mhscott** [comment]
Use `pip install openseespy --upgrade`
