### ISSUE TITLE
OpenSeesSP Building Issue

### ISSUE THREAD

**Issue by paysheen** [OpenSees/OpenSees#1227]
I managed to build Opensees, OpenseesPy and OpenseesMP (ver 3.5.1) perfectly fine. But when building OpenseesSp as was instructed here, the errors below showed up:

2>   Creating library D:/Opensees Developer Master/OpenSees/build/lib/OpenSeesSP.lib and object D:/Opensees Developer Master/OpenSees/build/lib/OpenSeesSP.exp
2>OPS_InterpTcl.lib(myCommands.obj) : error LNK2019: unresolved external symbol "class Domain theDomain" (?theDomain@@3VDomain@@A) referenced in function "int __cdecl specifyModelBuilder(void *,struct Tcl_Interp *,int,char const * *)" (?specifyModelBuilder@@YAHPEAXPEAUTcl_Interp@@HPEAPEBD@Z)
2>OPS_InterpTcl.lib(Tcl_generateInterfacePoints.obj) : error LNK2001: unresolved external symbol "class Domain theDomain" (?theDomain@@3VDomain@@A)
2>  Hint on symbols that are defined and could potentially match:
2>    "class PartitionedDomain theDomain" (?theDomain@@3VPartitionedDomain@@A)
2>D:\Opensees Developer Master\OpenSees\build\bin\OpenSeesSP.exe : fatal error LNK1120: 1 unresolved externals
2>Done building project "OpenSeesSP.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 69 up-to-date, 0 skipped ==========

**Comment by szl-opensees** [comment]
i meet the same problem

**Comment by zxh804159854** [comment]
Refer here，https://github.com/OpenSees/OpenSees/issues/1101。This will solve your problem。

**Comment by zxh804159854** [comment]
> > Refer here，#1101 This will solve your problem。
> 
> Thx It worked! Are you able to run the opensees executives independently on your machine? Is there a must to have API one installed?

run the opensees without oneAPI，but compile  the opensees with oneAPI

**Comment by paysheen** [comment]
> > > Refer here，#1101 This will solve your problem。
> > 
> > 
> > Thx It worked! Are you able to run the opensees executives independently on your machine? Is there a must to have API one installed?
> 
> run the opensees without oneAPI，but compile the opensees with oneAPI

When I dont have oneAPI installed i get this error:

![image](https://github.com/OpenSees/OpenSees/assets/76900139/f4dac811-d957-4c7a-9659-91688b02210d)

**Comment by zxh804159854** [comment]
> and this: ![image](https://user-images.githubusercontent.com/76900139/257534453-ba2589e9-af0e-4315-b1fb-95131e155ce2.png)

openseesSP and openseesMP runing need oneAPI for Parallel , because you need to type commands" mpiexec.exe -np 4 .\OpenSeesMP.exe  ../../EXAMPLES/SmallMP/Example.tcl".mpiexec.exe is oneAPI's software.
But your MP.exe lack xxx.dll,I don't know why.

**Comment by paysheen** [comment]
> > and this: ![image](https://user-images.githubusercontent.com/76900139/257534453-ba2589e9-af0e-4315-b1fb-95131e155ce2.png)
> 
> openseesSP and openseesMP runing need oneAPI for Parallel , because you need to type commands" mpiexec.exe -np 4 .\OpenSeesMP.exe ../../EXAMPLES/SmallMP/Example.tcl".mpiexec.exe is oneAPI's software. But your MP.exe lack xxx.dll,I don't know why.

These above errors pop up even for opensees.exe (It seems to me that when opensees is compiled using oneApi therefore the built files works on machines that has oneAPI). Don't you have the same problem?

**Comment by zxh804159854** [comment]
> > > and this: ![image](https://user-images.githubusercontent.com/76900139/257534453-ba2589e9-af0e-4315-b1fb-95131e155ce2.png)
> > 
> > 
> > openseesSP and openseesMP runing need oneAPI for Parallel , because you need to type commands" mpiexec.exe -np 4 .\OpenSeesMP.exe ../../EXAMPLES/SmallMP/Example.tcl".mpiexec.exe is oneAPI's software. But your MP.exe lack xxx.dll,I don't know why.
> 
> These above errors pop up even for opensees.exe (It seems to me that when opensees is compiled using oneApi therefore the built files works on machines that has oneAPI). Don't you have the same problem?

opensees do not have this problem，I think you don't  compile opensees correctly.
