### ISSUE TITLE
Why the PDelta effect cannot be included in gradientInelasticBeamColumn element?

### ISSUE THREAD

**Issue by abench363219** [OpenSees/OpenSees#1229]
Dear, 
    I downloaded the source code from doctor Pideris (https://github.com/msalehi2004/GradientInelasticBeamColumnElement/commits?author=psideris) and modified it  from 'geomTransf Corotational' to 'geomTransf PDelta'  to consider the P-Delta effect. However, it failed, and  the stiff degration cannot be included in the hysteristic curve.
   Great thanks to anyone who can help me here.
   Sincerely
   Andy

**Comment by mhscott** [comment]
This question is best asked of the authors of the element.
