### ISSUE TITLE
Display not working with OpenSees 3.5

### ISSUE THREAD

**Issue by silviamazzoni** [OpenSees/OpenSees#1250]
Frank,
the model-display functions do not work in the latest version of OpenSees.exe. they don't give an error, but there is no display.
I tested the same script on 3.3, and it works.

**Comment by mhscott** [comment]
@fmckenna will update CMakeLists

**Comment by azlanadnan** [comment]
how is the progress updating CMakelist? because it is still not working.. thanks..

**Comment by silviamazzoni** [comment]
closed this -- I have moved to OpenSeesPy!

**Comment by ambaker1** [comment]
Is this going to be fixed any time soon? I use the display features in the Tcl version of OpenSees, and was disappointed to find that the newest version of OpenSees does not support it.
