### ISSUE TITLE
Validation of ShellMITC4 element

### ISSUE THREAD

**Issue by vryy** [OpenSees/OpenSees#1257]
Hello,

I'm interested in using the ShellMITC4 element for analysis. Does anyone know if a validation or test case existed, e.g. pinching cylinder problem?

Thanks

**Comment by mhscott** [comment]
Please post general inquiries like this to the OpenSees message board or Facebook group.

The issues here are for issues with the source code.

**Comment by vryy** [comment]
Oh, sorry. I did not realize that. Please delete this thread if needed.
