### ISSUE TITLE
Issue with stress-strain response recorders while recording the extreme values- 3.5.0(TCL)

### ISSUE THREAD

**Issue by sjena98** [OpenSees/OpenSees#1268]
In order to reduce the amount of recorder files, I typically record the stress-strain response of fibres (W-section) for a variety of elements in a single file, such as all the columns in a story. Since I often record the stress-strain response at the extreme ends of each segment, my previous practise was to assign huge values to the coordinates that represented either end. I was able to record stress strain numbers at either end since the recorder stores the value that is closest to it. Because the depth of the columns changed depending on the story, I was still able to capture the response in a single file using this method.

For instance, I could use (1000,1000) to record the response of the one end and (-1000,-1000) for the other. 
![image](https://github.com/OpenSees/OpenSees/assets/137056585/d153c445-dfef-42b0-9f31-031f15e321d7)

This functioned properly with OS 3.3.0 (TCL).

When using OS 3.5.0, if I enter coordinate values that are inside the section, the response is accurately recorded at both ends. However, the recorded response for both cases is the same when I use greater values for the extreme ends, i.e., the recorded response of (-1000,-1000) is same for the case with coordinates (1000,1000).

If the problem can be resolved, it will be very beneficial because it will be difficult for me to record each column's response with precise coordinates, which will increase the recorder files and make it difficult to record other responses..

**Comment by mhscott** [comment]
Please post a minimal example that demonstrates the issue. Something like a fiber section in a zero length section element.

**Comment by sjena98** [comment]
#units KN,mm,sec
	wipe;
	model BasicBuilder -ndm 2 -ndf 3

	node 1 0.0 0.0
	node 2 0.0 1000.0

	fix 1 1 1 1
	fix 2 0 0 0

	set matTag 1;
	set E 200; #KN/mm2

	uniaxialMaterial Elastic $matTag $E;

	set secTag 1;
	# section- rectangle 100mmX100mm
	set numSubdivY 10
	set numSubdivZ 10
	set yI -50
	set zI -50
	set yJ 50
	set zJ 50



	section Fiber $secTag {
	patch rect $matTag $numSubdivY $numSubdivZ $yI $zI $yJ $zJ

	}
	geomTransf Linear 1
	element forceBeamColumn 1 1 2 5 1 1;
	set axialload 200;

	pattern Plain 1000 "Constant" {
		load 2 0.0 $axialload 0.0
	}



	# Define analysis parameters
	integrator LoadControl 0 1 0 0
	system BandGeneral 
	test EnergyIncr  1.0e-9 10
	numberer Plain
	constraints Plain
	algorithm Newton
	analysis Static

	# Do one analysis for constant axial load
	analyze 1

	# Define reference moment
	pattern Plain 2000 "Linear" {
		load 2 1.0 0.0 0.0 
	}

	integrator DisplacementControl 2 1 1
	analyze 10;
	puts "*************************"
	puts "A1-Exact cordinate values Stress Strain_extreme end1: [eleResponse 1 section 1 fiber -50.0 0.0 stressStrain]"
	puts "A2-Exact cordinate values Stress Strain_extreme end2: [eleResponse 1 section 1 fiber 50.0 0.0 stressStrain]"
	puts "*************************"
	puts "B1-Larger cordinate values Stress Strain_extreme end1: [eleResponse 1 section 1 fiber -1000.0 0.0 stressStrain]"
	puts "B2-Larger cordinate values Stress Strain_extreme end2: [eleResponse 1 section 1 fiber 1000.0 0.0 stressStrain]"
	puts "Issue while using Opensees 3.5.0, B1=B2=A1, which should have been A1=B1, and B1=B2 (OS 3.3.0)"

**Comment by mhscott** [comment]
@sjena98 Thanks for the example. The issue was fixed: https://github.com/OpenSees/OpenSees/pull/1271
