### ISSUE TITLE
Print JSON does not include updated model parameters

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#1272]
Looks like a not-so-easy fix, but for the record, print JSON prints the state of the model at the time of model building, even if the print JSON is issued at the end of an analysis.

```python
E = 29000
ops.uniaxialMaterial('Elastic',1,E)
ops.element('truss',1,1,2,2.0,1)
ops.parameter(1,'element',1,'E')
# Do some analysis
ops.updateParameter(1,30000)
# Do some more stuff
ops.printModel('-JSON','-file','model.json')
```

The JSON file will have 29000 for the material and not 30000

**Comment by fmckenna** [comment]
you are printing the original material .. the element has it's own cloned material and that has the updated material property
