### ISSUE TITLE
Memory leak calling modalDamping every timestep?

### ISSUE THREAD

**Issue by steeletc** [OpenSees/OpenSees#1277]
I've recently updated some analysis files to call eigen and modalDamping each timestep as suggested by mhs in the OpenSees Community. When only eigen is called and modalDamping isn't called, memory for the analysis hangs out around 8.4 MB for the analysis. Calling modalDamping adds to memory use at a rate of roughly 0.02 MB per time step, leading to nearly 1 GB of memory taken by the end of one analysis. Does calling modalDamping not overwrite the previous damping matrix?

No MWE currently but can provide with some time.

**Comment by mhscott** [comment]
@steeletc I hope I didn't suggest re-doing modal damping at every time step. That seems pretty unnecessary considering how much of a farce damping is in the first place. Even eigen every time step is overkill. But anyway, sounds like a possible memory leak.

**Comment by steeletc** [comment]
@mhscott that's what I took away from it, but perhaps it was the right answer to a bad question:

[](https://opensees.berkeley.edu/community/viewtopic.php?t=71703)

I agree with you regarding the approach to damping in general but I am hoping to make some comparisons in as fair a way as possible to Rayleigh damping with updated frequencies/parameters and Uniform damping. Results are all over the place as it is (a bit of a farce as such) but I don't want feedback to suggest it was because models were applied inconsistently or poorly. 

Seems, at least to me, that damping is particularly important for structures with significant gap openings and collapse modelling for example. Where good damping modelling may be nebulous, bad damping modelling seems to lead to highly erroneous results. To start I'm quite interested to see if there would be significant differences between a constant modal Damping and an updated modalDamping for certain systems and for collapse modelling.

If there's a leak this is still possible but time consuming - I can ultimately run just one OpenSees otherwise other instances will crash.

**Comment by mhscott** [comment]
@steeletc OK, please post a MWE when you are ready.

**Comment by mhscott** [comment]
Leak should be plugged now: https://github.com/OpenSees/OpenSees/commit/33e4119a96ccac06f1a0420991f83c06969b78c3
