### ISSUE TITLE
Issue with sendSelf / recvSelf for ParallelMaterial

### ISSUE THREAD

**Issue by gaaraujo** [OpenSees/OpenSees#1287]
Hello, I tried using the save and restore commands in a mode today and got the following error:

Material with tag 600 is a ParallelMaterial that combines Pinching4 and ENT materials.
Element with tag -800 is a ZeroLength element that uses material with tag 600

![image](https://github.com/OpenSees/OpenSees/assets/24374005/8815d38b-0af3-4e04-85c6-a2a11e196f2b)

**Comment by mhscott** [comment]
@gaaraujo Are you using the latest GitHub code? Pinching4 `sendSelf`/`recvSelf` was updated a few weeks ago: https://github.com/OpenSees/OpenSees/pull/1264

**Comment by gaaraujo** [comment]
My bad! I'm using the latest OpenSeesPy pip release.
