### ISSUE TITLE
Error when using OpenSeesSP

### ISSUE THREAD

**Issue by mosayed86** [OpenSees/OpenSees#129]
Hi all,

I am trying to perform transient analysis with OpenSeesSP on a Lİnux system. It always returns an error message "Error! Unknown CType: -1". Does anyone know the source of error or how to fix it.

~thanks

**Comment by mhscott** [comment]
Can you provide a script? This error is coming from Petsc.

**Comment by mhscott** [comment]
Closing. Re-open if you can demonstrate the issue with a minimal working example.
