### ISSUE TITLE
Error in FileDatastore::recvID() - Failed to Restore State in ZeroLength

### ISSUE THREAD

**Issue by shishitao** [OpenSees/OpenSees#1290]
**Issue Description:**

Hi all, I encountered the following error message while executing `restore_database`:
```
FileDatastore::recvID() - failed
ZeroLength::recvSelf -- failed to receive ID data
Domain::recv - Ele with dbTag 372 failed in recvSelf()
FE_Datastore::restoreState - domain failed to recvSelf
WARNING - database failed to restoreState

while executing
"restore 1"
    (procedure "restore_database" line 4)
    invoked from within
"restore_database $filename"
```

**Steps to Reproduce:**
1. Build a model with a ZeroLength element in OpenSeespy.
2. Save that model in the database.
3. Attempt to restore the database of that model in OpenSees.

**Environment:**
- Operating System: [Win]
- Software Version: [OpenSees 3.3.0, OpenSeespy 3.5, Python 3.10]

Thank you for your attention to this issue. Your help is greatly appreciated!

**Comment by mhscott** [comment]
Please post a minimal example that reproduces the error

**Comment by shishitao** [comment]
> Please post a minimal example that reproduces the error

Professor Scott, thank you for your prompt response. I appreciate your attention to this matter. After downgrading OpenSeespy to a previous version and reverting to Python 3.8, the error no longer occurs with this configuration. Given this change, I believe it may have been related to the software versions or some compatibility issue with the specific environment I was using.

**Comment by mhscott** [comment]
@shishitao Sorry, downgrading is never a viable solution. Please post a minimal example that produced the error with the latest version of OpenSeesPy.
