### ISSUE TITLE
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGBSV

### ISSUE THREAD

**Issue by laxmandahal** [OpenSees/OpenSees#1295]
Hi, 

I am trying to run a model on an HPC cluster using OpenSeesMP but I get the following error: 

```
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGBSV .
WARNING BandGenLinLapackSolver::solve() - OpenSees code error
WARNING NewtonRaphson::solveCurrentStep() -the LinearSysOfEqn failed in solve()
StaticAnalysis::analyze() - the Algorithm failed at iteration: 0 with domain at load factor 0.01
OpenSees > analyze failed, returned: -3 error flag

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 132918 RUNNING AT n6443
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 132919 RUNNING AT n6443
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
```

Has anyone encountered a similar error? How do I resolve this? Please note that the model runs fine using OpenSees. 

Any help is highly appreciated!

Thanks, 
Laxman

**Comment by mhscott** [comment]
Hard to help on individual clusters. You'll have to reproduce the error on another system.

**Comment by laxmandahal** [comment]
Hi Prof. Scott and Frank, thanks for being willing to take a second look at the issue. I have added the joblog file that shows the issue. 
[OpenseeMP_MKL_error.txt](https://github.com/OpenSees/OpenSees/files/12805448/OpenseeMP_MKL_error.txt)

**Comment by mhscott** [comment]
We need a simple input file. Not the output log.

**Comment by silviamazzoni** [comment]
We need a little more info on your script as well. What do you mean that it runs fine on OpenSees?

**Comment by silviamazzoni** [comment]
I also recommend you terminate your script when gravity analysis fails.

**Comment by silviamazzoni** [comment]
and maybe work with the latest version of OpenSees.

**Comment by laxmandahal** [comment]
Thank you for that recommendation, Prof. Mazzoni. I will update my model. Unfortunately, I don't have a single script that will help recreate the issue. However, I set up a [GitHub repo](https://github.com/laxmandahal/test_openseesMP/tree/main) with the scripts and input files for an example model. Hopefully, it won't be too much of a hassle to run the script. Thank you again for looking into this!

**Comment by mhscott** [comment]
I recommend you make a minimal example to find the issue. It's possible the error is a modeling issue and not an MP issue.

Re-open or start a new issue if you find an issue with OpenSeesMP.
