### ISSUE TITLE
beamWithHinges not recognized in latest OpenSees.exe

### ISSUE THREAD

**Issue by gaaraujo** [OpenSees/OpenSees#1300]
I was trying to run an OpenSees Tcl script using beamWithHinges. 
```
wipe
model basic -ndm 3 -ndf 6

set b 20.0
set h 20.0
set L 240.0
set A [expr {$b * $h}]
set Iy [expr {1/12 * $h * $b ** 3}]
set Iz [expr {1/12 * $b * $h ** 3}]
set J [expr {0.141 * $h * $b ** 3}]
set Lp [expr {$h/2}]
set LpMax [expr {$L/8}]
if {$Lp > $LpMax} {
	set Lp $LpMax
}

set E 3607.0
set G [expr {0.4 * $E}]

node 1 0.0 0.0 0.0
node 2 $L  0.0 0.0

fix 1 1 1 1 1 1 1
fix 2 1 1 0 0 0 1

section Elastic 3 $E $A $Iz $Iy $G $J

geomTransf Linear 5 0.0 0.0 1.0

element beamWithHinges 4 1 2 3 $Lp 3 $Lp $E $A $Iz $Iy $G $J 5
```
However, I get the following error:

![image](https://github.com/OpenSees/OpenSees/assets/24374005/f84664a1-e808-419a-9587-d14be86141bb)

The error does not occur when executing the equivalent script in OpenSeesPy.

I know this error comes from [TclElementCommands.cpp, Line 2032](https://github.com/OpenSees/OpenSees/blob/963bd75f82dffc93c5f16745af343da396ec7ab4/SRC/element/TclElementCommands.cpp#L2032), but I wasn't able to find why does the code reach that line if it seems that `OPS_BeamWithHinges()` is added to the list. I am not sure if the issue was addressed recently and the latest OpenSees.exe has not been updated.

**Comment by mhscott** [comment]
This was fixed after the last release: https://github.com/OpenSees/OpenSees/commit/3b044915fb817607475c6a05ed605562b88b96fd

You should update your scripts to use `forceBeamColumn` instead of `beamWithHinges`

**Comment by mhscott** [comment]
You know these will be zero, right?
```tcl
set Iy [expr {1/12 * $h * $b ** 3}]
set Iz [expr {1/12 * $b * $h ** 3}]
```

**Comment by silviamazzoni** [comment]
actually, 0.0! :)

**Comment by gaaraujo** [comment]
> You know these will be zero, right?
> 
> ```tcl
> 
> set Iy [expr {1/12 * $h * $b ** 3}]
> 
> set Iz [expr {1/12 * $b * $h ** 3}]
> 
> ```

Oops! I was trying to come up with a minimal example. Good catch!

Also, thanks for the clarification on beamWithHinges!
