### ISSUE TITLE
updateparameter command is unavailable for some materials

### ISSUE THREAD

**Issue by zhongdigood** [OpenSees/OpenSees#1301]
I found that the cpp source code of some materials does not contain **setparameter and updateparameter**. If I need to develop this command, what conditions need to be met?

**Comment by zhongdigood** [comment]
For example, if I use the updateparameter in IMKbilin material, it will occur error "Parameter::addComponent 2 -- no objects were able to identify parameter".

**Comment by zhongdigood** [comment]
I tried to modify the source code (refer to steel01, concrete01, boucwen and another material) to implement updateparameter command for one material, but I found that no errors were reported after compilation, but update was not implemented either. It seems that I still need to acquire some knowledge. Do you have any suggestions?

**Comment by mhscott** [comment]
I'm sorry, your explanations of what you've modified and the results are unclear.

**Comment by zhongdigood** [comment]
Professor, I just copy the setparameter and updateparameter from Boucwen material, added it to the end of IMKbilin.cpp, and fixed error displayed by VS. Thank you very much!
