### ISSUE TITLE
ERROR AL CORRER EL PROGRAMA

### ISSUE THREAD

**Issue by JOSE76ROJAS** [OpenSees/OpenSees#1304]
aludos, Dr. Silvia , mi nombre e s JOSE ROJAS soy de BOGOTA, en estos momentos estoy empezando a estudiar  OPEENSEES , le estoy escribiendo para que me oriente en donde podría estudiar mas  sobre el programa ya que me encuentro realizando mi tesis de maestría y la voy hacer con OPENSEES, también me encuentro realizando los ejemplos del libro   del ING LUIS VELASCO pero al correr el programa me sale el siguiente error  si me puede orientar sobre que trata estoy trabajando con el CYPRESS EDITOR se lo agradecería ya que no he podido solucionarlo.

![CypressEditor_kCQiHJ7x7T](https://github.com/OpenSees/OpenSees/assets/151029877/0e8d5a18-7cf3-4327-bb0c-be8f5135c1ae)

Cordialmente+

Jose Rojas

**Comment by silviamazzoni** [comment]
Yes the error message says to contact the developer, but please make every effort to make sure this is an actual but in OpenSees and not in your input, or not the latest version of OpenSees
