### ISSUE TITLE
'cFactor' in H5DRM load pattern not recovered correctly in OpenSeesSP via sendSelf() / recvSelf()

### ISSUE THREAD

**Issue by jf-huang** [OpenSees/OpenSees#1310]
Hi, when trying to scale the DRM motions using the [$factor parameter](https://opensees.github.io/OpenSeesDocumentation/user/manual/model/pattern/H5DRM.html?highlight=drm), the corresponding [cFactor variable](https://github.com/OpenSees/OpenSees/blob/77631c6397a840f6b75582969591c45de3aabc53/SRC/domain/pattern/drm/H5DRM.cpp#L1890C2-L1890C10) is not recovered correctly via sendSelf() / recvSelf() in OpenSeesSP, tested using the latest source code. The variable is correct in rank 0 but the remaining processes all have the default value (1.0). Is this a bug and is there a way to fix this? Thanks.

**Comment by mhscott** [comment]
Please provide a minimal example and follow up with @jaabell

**Comment by jf-huang** [comment]
Yep it looks related to the cmake compilation and now resolved on my end, I
will do a PR when finished the testing.

**Comment by mhscott** [comment]
Awaiting PR. Closing this issue
