### ISSUE TITLE
can not use recorder Drift in openseespy

### ISSUE THREAD

**Issue by zxh804159854** [OpenSees/OpenSees#1311]
recorder Drift can not use in openseespy 3.5.1.12.
tcl ref https://opensees.berkeley.edu/wiki/index.php/Drift_Recorder
openseespy error 
![Snipaste_2023-12-17_00-41-22](https://github.com/OpenSees/OpenSees/assets/23044636/b97b6a2c-b356-4344-821c-1e9f02976e06)

I noticed that the relevant code has been commented out，code link https://github.com/OpenSees/OpenSees/blob/master/SRC/interpreter/OpenSeesOutputCommands.cpp

//recordersMap.insert(std::make_pair("Drift", &OPS_DriftRecorder));
        //recordersMap.insert(std::make_pair("Pattern", &OPS_PatternRecorder));

 What is the reason for this .

**Comment by silviamazzoni** [comment]
I vote we remove the drift recorder! :)

**Comment by zxh804159854** [comment]
> I vote we remove the drift recorder! :)

Thank you, Professor. I want to know the reason, for example, recording results is not accurate.

**Comment by mhscott** [comment]
I don't recall the reason Drift recorder is not in OpenSeesPy. However, the drift is easily computed from post-processing nodal displacements.

**Comment by zxh804159854** [comment]
> I don't recall the reason Drift recorder is not in OpenSeesPy. However, the drift is easily computed from post-processing nodal displacements.

Thank you, Professor.

**Comment by zhuminjie** [comment]
It’s submitted as PR now

https://github.com/OpenSees/OpenSees/pull/1312
