### ISSUE TITLE
HELP PLEASE: Cannot create example elasticPPcpp.dll

### ISSUE THREAD

**Issue by ntosic87** [OpenSees/OpenSees#132]
Hi,

My name is Nikola Tošić and I'm a Fulbright Visiting Scholar at the University o Notre Dame, IN (from the University of Belgrade's Faculty of Civil Engineering) and I'm going to work here in OpenSees.
In fact, one of the previous PhD candidates developed a very nice time-dependent model for concrete that I want to continue working on. He compiled it for Mac, but I'm trying to repeat the process for Windows.
I'm first learning to create a .dll in Visual Studio 15 and working on the provided example elasticPPcpp.
However, following the steps doesn't work.

First, I'm required to add bool.h and SectionForceDeformation.h as Header files and then I get the following errors:
![image](https://user-images.githubusercontent.com/54485694/63643067-782bab80-c697-11e9-99df-72147152e827.png)
The first two are related to the Domain.obj file that is created and the third one to the elasticPPcpp.dll (that isn't created).

I appreciate that it's probably something basic I'm overlooking but any help would be so welcome!

Kind regards,
Nikola

**Comment by mhscott** [comment]
Have you tried compiling the source code within the OpenSees Visual C++ project as part of OpenSees.exe?  Unless there is a good reason, e.g., the model formulation is not yet published or access is restricted by a sponsoring agency, why use a dll?  It only limits those who will be able to use the model within the open source framework.

**Comment by ntosic87** [comment]
Dear prof. Scott,

Thank you kindly for your quick reply! Indeed, there is no obstacle to do it as a .dll, I'm just trying to repeat what the former student did for Mac (he compiled a .dylib file). Actually, I have all his source files (he edited commands.cpp and OPS_Globals.h; added two analysis files CreepAnalysis.cpp and CreepAnalysis.h as well as two material models TDConcerete.cpp, TDConcrete.h and TDConcreteEXP.cpp and TDConcreteEXP.h). Attached are the former student's notes on compiling OpenSees with his code, which I do not know how to do in Windows (I have a Mac executable running).

Unfortunalely, I am only now learning both OpenSees and Visual Studio, so currently I don't know how I would do what you are suggesting. I'm not managing to find tutorials for doing that, if they exist, I would very much appreciate if you could share them.
For any information, or sharing the documents, my email is ntosic@nd.edu

Thank you for your help and apologies for the inconvenience.

Kind regards,
Nikola

P.S. at the link below is his thesis, Chapter 9 explains the code and model (all code is also given as Appendix). It's a very good idea he developed that we now want to take further:
https://curate.nd.edu/show/bk128912n6w 
[OpenSees Notes.docx](https://github.com/OpenSees/OpenSees/files/3537721/OpenSees.Notes.docx)

**Comment by erikemondt** [comment]
I patched the second LNK 2019 error by commenting out the line in the code that caused the error. This line only print some model information to a .json file, which is not used as input somewhere. It appears to be for debugging purposes and is not used by OpenSees under normal circumstances.

Go to the following file:
\DEVELOPER\core\Domain.cpp (or access it in the source files of visual studio)
comment out this line: "OPS_printCrdTransf(s, flag);"

It's wise to insert an additional print statement here, denoting that code was commented out.

**Comment by mhscott** [comment]
Clearing out old issues. I think this was resolved, but please start a new issue if there are further problems.
