### ISSUE TITLE
Can not compile current openseespy (windows)

### ISSUE THREAD

**Issue by Omar-A-M** [OpenSees/OpenSees#1325]
I just pulled the current version of OpenSeespy and I am trying to compile it before adding any new material. After going back and forth with compiling errors. Now I am getting fatal LNK errors as shown in the output bellow:

1>------ Build started: Project: OpenSeesPy, Configuration: Release x64 ------
1>   Creating library .\..\..\bin\opensees.lib and object .\..\..\bin\opensees.exp
1>PythonWrapper.obj : error LNK2019: unresolved external symbol "int __cdecl OPS_Damping(void)" (?OPS_Damping@@YAHXZ) referenced in function "struct _object * __cdecl Py_ops_damping(struct _object *,struct _object *)" (?Py_ops_damping@@YAPEAU_object@@PEAU1@0@Z)
1>.\..\..\bin\opensees.pyd : fatal error LNK1120: 1 unresolved externals
1>Done building project "OpenSeesPy.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 23 up-to-date, 0 skipped ==========

Thanks in advance

**Comment by mhscott** [comment]
Pull the latest code and try again. The OpenSeesDampingCommands.cpp file was missing from the visual studio project files.

**Comment by Omar-A-M** [comment]
Thank you Prof Scott.

I have managed to compile openseespy on windows. I am trying now to compile on Mac and I am getting errors but I will open a new issue for that.
