### ISSUE TITLE
SFI_MVLEM 2D with vertical ground motion excitation

### ISSUE THREAD

**Issue by zwaezi84** [OpenSees/OpenSees#1333]
Hello,

I have been wondering if there is any limitations for SFI_MVLEM implementation. Because, when I used the official example here:
https://opensees.berkeley.edu/wiki/images/2/23/Example_2-SFI_MVLEM.zip
and just change the ground motion direction from 1 to 2, opensees TCL closes without producing any results. I think this is cuased by wipe or wipeAnalysis.

I would be sincerely grateful if you could help me.

Best
Zak

**Comment by mhscott** [comment]
Try turning off the display options. If that doesn't help, contact @kkolozvari

**Comment by mhscott** [comment]
Any updates, @zwaezi84? This element adds internal nodes with 1 DOF, so the element may not be able to handle vertical ground motion. Is this correct @kkolozvari?

**Comment by kkolozvari** [comment]
@zwaezi84, @mhscott it is possible that internal nodes are creating problems. Try applying multi-node instead of uniform acceleration. Also, try using E_SFI_MVLEM_3D element in which internal nodes are eliminated.

**Comment by zwaezi84** [comment]
@mhscott @kkolozvari Yes. The uniform pattern tries to allocate forces to DOFs that don't exist for the internal nodes. I temporarily fixed my problem by adding a condition to the pattern series that if a node's DOF is less than DOF corresponding to the model's dimension, no forces shall be assigned to tat node.

**Comment by mhscott** [comment]
@kkolozvari It seems that instead of defining internal nodes for the sake of static condensation, you could use the `"BeamFiber2d"` option when calling `getCopy()` on the ND materials. Could simplify the implementation of this element.

**Comment by zwaezi84** [comment]
@mhscott Thank you very much for the hint. Is there any workaround to eliminate the need for creating an internal node connecting multiple truss elements?

**Comment by mhscott** [comment]
The implementation would need to be changed. I doubt there's a workaround.

**Comment by kkolozvari** [comment]
@zwaezi84 if you describe the problem you're working on we could try to find a workaround. The internal nodes are part of the model formulation as described in corresponding papers. We later introduced new formulations that doesn't have the internal nodes (E-SFI model for 2D and E-SFI-MVLEM-3D for 3D problems, both available). These models are not completely based on mechanics like SFI-MVLEM, but they do an OK job.

**Comment by zwaezi84** [comment]
We have an element as follows and we want to eliminate the internal node. The element has 4 external nodes and only one internal node that has one DOF. We only need a static condensation for the internal node's DOF but it requires an iterative procedure within the element and it may not converge, is it right?
![ZW Element](https://github.com/OpenSees/OpenSees/assets/133272845/3e711c0b-61f3-4481-84a8-de058b222c6a)

**Comment by mhscott** [comment]
@zwaezi84 This is getting off-issue. Please communicate directly with @kkolozvari on your element formulation and the need for static condensation.
