### ISSUE TITLE
WARNING using SANISAND MS in OpenSees 3.3.0

### ISSUE THREAD

**Issue by MekPAME** [OpenSees/OpenSees#1344]
Hi! Nice to meet you to all the OpenSees developers and users.

I am using the version of OpenSees 3.3.0 with TCL 8.6.10. They are compatible, I've checked.

I want to use the costitutive law SANISAND-MS for the soil elements that are all stdBrick, but when I run the analysis I get this warning:

"WARNING could not create nDMaterial: SAniSandMS"

What is the problem? Maybe this version of OpenSees does not have SANISAND-MS yet?

Could you show me the way to add it?

Thanks in advance!

**Comment by mhscott** [comment]
Version 3.3.0 is almost four years old, so likely the model is not there. Use the latest version, 3.6.0.

**Comment by MekPAME** [comment]
@mhscott Thanks for your advice. This time the easiest solution worked out! The 3.6.0 works with tcl 8.6.11.
It's great to have your help!

Kind greetings!
