### ISSUE TITLE
I can´t install properly OpenSees

### ISSUE THREAD

**Issue by AvionZapador** [OpenSees/OpenSees#1347]
![image](https://github.com/OpenSees/OpenSees/assets/99684283/8b502528-25bd-466f-a135-9c7488f6e795)
Hello, I can not run properly OpenSees. First, problem with the libiomp5md.dll and then, problem with the version of package Tcl 8.6.10
I have forget that my laptop run with windows 11

**Comment by Josileissu** [comment]
Talvez você tenha que configurar o caminho para a pasta do tcl. você pode fazer isso da seguinte maneira: clique com o botão direito em propriedades da solução opensees... 
![image](https://github.com/OpenSees/OpenSees/assets/53374605/6967f947-4f5f-45ae-bd4d-619c97b513be)
depois disso vá para c/c++ e incluir diretórios.
![image](https://github.com/OpenSees/OpenSees/assets/53374605/e14bc9fe-bc0a-4a35-b8db-75f17f51d0e3)
aí você pode incluir o caminho para o tcl...

**Comment by fmckenna** [comment]
i have updated the .zip file

**Comment by AvionZapador** [comment]
> Talvez você tenha que configurar o caminho para a pasta do tcl. Você pode fazer isso da seguinte maneira: clique com o botão direito em propriedades da solução opensees...

MUITO OBRIGADO! :-)
