### ISSUE TITLE
Problem installing Opensees

### ISSUE THREAD

**Issue by hszhang1** [OpenSees/OpenSees#1348]
Hi,

Today I tried using Opensees. But I have encountered this issue and I could not solve this problem. Does anyone know how to solve this issue
![pic](https://github.com/OpenSees/OpenSees/assets/161295618/33146d3a-bd75-4685-828f-7c116b16155b)

Thanks!

**Comment by hszhang1** [comment]
Hi, thanks for your help! I have used the updated .zip file opensees.exe and I have installed activetcl but it still did not work out.

**Comment by fmckenna** [comment]
you do not need activetcl to run OpenSees .. try removing it to see if that fixes the problem

**Comment by hszhang1** [comment]
Hi Frank, Thanks for your help! I can use Opensees now on my computer in my office! Although it still does not work out for my personal computer, I can use my office computer to operate it.

Thanks for your help!

Best,

Hanshu
