### ISSUE TITLE
Triaxial test on SANISAND-MS issue

### ISSUE THREAD

**Issue by MekPAME** [OpenSees/OpenSees#1350]
Hi! @jaabell and OpenSees community.

I am working at the TU Delft on my master thesis in geotechnical engineering.

I am simulating a compressive drained triaxial test with 100kPa of backpressure with the following code. I am getting troubles because I get the final experimental displacement in z direction but with a very high vertical stress in compression (The right value is -460kPa). I tried also with transient analysis but it did not work out. 

Also what is weird is that using the older version of the costitutive model called ManzariDafalias and putting the same parameters the results are much more reasonable. But they shoud give the same results in monotonic loading!

What is not working with SANISAND-MS?

Could you help me please?!

The code:

wipe

set test_type "drained_triaxial"

model BasicBuilder -ndm 3 -ndf 3

node      1            0            1            1
node      2            0            0            1
node      3            0            1            0
node      4            1            1            1
node      5            1            0            1
node      6            1            1            0
node      7            0            0            0
node      8            1            0            0

fix      1   1   0   0   
fix      2   1   1   0   
fix      3   1   0   1   
fix      4   0   0   0   
fix      5   0   1   0   
fix      6   0   0   1   
fix      7   1   1   1    
fix      8   0   1   1   

set devDisp -0.06  

set G0        110.  ; # [Adimensional]
set nu        0.05  ; # [Adimensional]
set e_init    0.67  ; # [Adimensional]
set Mc        1.27  ; # [Adimensional]
set c         0.712 ; # [Adimensional]
set lambda_c  0.049 ; # [Adimensional]
set e0        0.845 ; # [Adimensional]
set ksi       0.27  ; # [Adimensional]
set P_atm     101.3 ; # [kPa]
set m         0.01  ; # [Adimensional]
set h0        5.95  ; # [Adimensional]
set ch        1.01  ; # [Adimensional]
set nb        2.0   ; # [Adimensional]
set A0        1.06  ; # [Adimensional]
set nd        1.17  ; # [Adimensional]
set z_max     4     ; # For SAniSand [Adimensional]
set cz            0     ; # For SAniSand [Adimensional]
set mu0       0.  ; # For SAniSand [Adimensional]
set zeta      0.0005; # For SAniSand [Adimensional]
set beta      1     ; # For SAniSand [Adimensional]
set w1        0.5   ;
set w2        2     ;
set Den       0 ; # [Mg/m^3]
set intScheme 3     ; # Corresponds to Modified-Euler integration scheme
set TanType   1     ; # 0: elastic stiffness, 1: continuum elastoplastic stiffness
set JacoType  1     ; # Not used in explicit methods
set TolF      1.0e-6; # Tolerances, not used in explicit
set TolR      1.0e-6; # Tolerances, not used in explicit

set type "RK"

set P_ref $P_atm

nDMaterial SAniSandMS  328 $G0 $nu $e_init $Mc $c $lambda_c $e0 $ksi $P_atm $m $h0 $ch $nb $A0 $nd $zeta $mu0 $beta $Den  $intScheme $TanType $JacoType $TolF $TolR

set type "RK"

element SSPbrick    1      5      4      6      8      2      1      3      7    328

recorder Element -file ${type}_${test_type}_stress.out -ele 1  -time stress
recorder Element -file ${type}_${test_type}_strain.out -ele 1 -time strain

puts "Running interval 1"

constraints Transformation
test        NormDispIncr 1.0e-8 200 0
algorithm   Newton
numberer    RCM
system      BandGeneral
integrator  LoadControl 0.0001
analysis    Static

puts "Start analysis"
set startT [clock seconds]

pattern Plain 1 {Series -time {0 1 100} -values {0 1 1} -factor 1} {
    load      1        0      -25      -25       
    load      2        0        0      -25       
    load      3        0      -25        0       
    load      4      -25      -25      -25        
    load      5      -25        0      -25        
    load      6      -25      -25        0        
    load      7        0        0        0        
    load      8      -25        0        0       
} 

analyze 10000  

loadConst

set vDisp     [nodeDisp 5  3]
set lvalues   [list 1 [expr 1+$devDisp/$vDisp] [expr 1+$devDisp/$vDisp]]
set ts "{Series -time {1 2 1000} -values {$lvalues} -factor 1}"

eval "pattern Plain 2 $ts {
sp  5  3 $vDisp
sp  2  3 $vDisp
sp  4  3 $vDisp
sp  1  3 $vDisp
}"

integrator LoadControl 0.0001
analyze 10000

puts "Finish analysis"
set endT [clock seconds]

wipe

**Comment by mhscott** [comment]
The GitHub issues are for bug reports and obvious coding issues.

Modeling questions should be directed elsewhere, in this case to the authors of the model.

**Comment by MekPAME** [comment]
Hi! @mhscott 
I've found this advice on the github page of the costitutive model: 
"Please report bugs as an issue on the main OpenSees repositoy and tag @jaabell"

That's why I am here.

**Comment by jaabell** [comment]
> Hi! @jaabell and OpenSees community.
> 
> I am working at the TU Delft on my master thesis in geotechnical engineering.
> 
> I am simulating a compressive drained triaxial test with 100kPa of backpressure with the following code. I am getting troubles because I get the final experimental displacement in z direction but with a very high vertical stress in compression (The right value is -460kPa). I tried also with transient analysis but it did not work out.
> 
> Also what is weird is that using the older version of the costitutive model called ManzariDafalias and putting the same parameters the results are much more reasonable. But they shoud give the same results in monotonic loading!
> 
> What is not working with SANISAND-MS?
> 
> Could you help me please?!
> 
> The code:
> 
> wipe
> 
> set test_type "drained_triaxial"
> 
> model BasicBuilder -ndm 3 -ndf 3
> 
> node 1 0 1 1 node 2 0 0 1 node 3 0 1 0 node 4 1 1 1 node 5 1 0 1 node 6 1 1 0 node 7 0 0 0 node 8 1 0 0
> 
> fix 1 1 0 0 fix 2 1 1 0 fix 3 1 0 1 fix 4 0 0 0 fix 5 0 1 0 fix 6 0 0 1 fix 7 1 1 1 fix 8 0 1 1
> 
> set devDisp -0.06
> 
> set G0 110. ; # [Adimensional] set nu 0.05 ; # [Adimensional] set e_init 0.67 ; # [Adimensional] set Mc 1.27 ; # [Adimensional] set c 0.712 ; # [Adimensional] set lambda_c 0.049 ; # [Adimensional] set e0 0.845 ; # [Adimensional] set ksi 0.27 ; # [Adimensional] set P_atm 101.3 ; # [kPa] set m 0.01 ; # [Adimensional] set h0 5.95 ; # [Adimensional] set ch 1.01 ; # [Adimensional] set nb 2.0 ; # [Adimensional] set A0 1.06 ; # [Adimensional] set nd 1.17 ; # [Adimensional] set z_max 4 ; # For SAniSand [Adimensional] set cz 0 ; # For SAniSand [Adimensional] set mu0 0. ; # For SAniSand [Adimensional] set zeta 0.0005; # For SAniSand [Adimensional] set beta 1 ; # For SAniSand [Adimensional] set w1 0.5 ; set w2 2 ; set Den 0 ; # [Mg/m^3] set intScheme 3 ; # Corresponds to Modified-Euler integration scheme set TanType 1 ; # 0: elastic stiffness, 1: continuum elastoplastic stiffness set JacoType 1 ; # Not used in explicit methods set TolF 1.0e-6; # Tolerances, not used in explicit set TolR 1.0e-6; # Tolerances, not used in explicit
> 
> set type "RK"
> 
> set P_ref $P_atm
> 
> nDMaterial SAniSandMS 328 $G0 $nu $e_init $Mc $c $lambda_c $e0 $ksi $P_atm $m $h0 $ch $nb $A0 $nd $zeta $mu0 $beta $Den $intScheme $TanType $JacoType $TolF $TolR
> 
> set type "RK"
> 
> element SSPbrick 1 5 4 6 8 2 1 3 7 328
> 
> recorder Element -file ${type}_${test_type}_stress.out -ele 1 -time stress recorder Element -file ${type}_${test_type}_strain.out -ele 1 -time strain
> 
> puts "Running interval 1"
> 
> constraints Transformation test NormDispIncr 1.0e-8 200 0 algorithm Newton numberer RCM system BandGeneral integrator LoadControl 0.0001 analysis Static
> 
> puts "Start analysis" set startT [clock seconds]
> 
> pattern Plain 1 {Series -time {0 1 100} -values {0 1 1} -factor 1} { load 1 0 -25 -25 load 2 0 0 -25 load 3 0 -25 0 load 4 -25 -25 -25 load 5 -25 0 -25 load 6 -25 -25 0 load 7 0 0 0 load 8 -25 0 0 }
> 
> analyze 10000
> 
> loadConst
> 
> set vDisp [nodeDisp 5 3] set lvalues [list 1 [expr 1+$devDisp/$vDisp] [expr 1+$devDisp/$vDisp]] set ts "{Series -time {1 2 1000} -values {$lvalues} -factor 1}"
> 
> eval "pattern Plain 2 $ts { sp 5 3 $vDisp sp 2 3 $vDisp sp 4 3 $vDisp sp 1 3 $vDisp }"
> 
> integrator LoadControl 0.0001 analyze 10000
> 
> puts "Finish analysis" set endT [clock seconds]
> 
> wipe

Hi!

Thank you for reaching out. Please explain your problem through email (jaabell@uandes.cl) to talk about this. Thanks!

**Comment by MekPAME** [comment]
Ok, I am going to do it! 💯

**Comment by fmckenna** [comment]
@jaabell was that fix i pulled in earlier today to resolve this issue?

**Comment by jaabell** [comment]
Yes. I've been talking to this user via email. This was their issue.
