### ISSUE TITLE
Why no show up?

### ISSUE THREAD

**Issue by huisky2000** [OpenSees/OpenSees#1352]
Hi,

I've downloaded the OpenSees3.6.0-x64.exe.zip and unzip to C:\ProgramData\OpenSees3.6.0. It seems to be working in the beginning. However, recently, it has suddenly stopped working. Not sure what happened, or how to diagnose it, as I see no output. Does anyone have the same problem? Wondering if it can be due to security issues?

Regards,
Huiksy2000

**Comment by fmckenna** [comment]
run OpenSees from a DOS terminal to see what the error is.

**Comment by huisky2000** [comment]
Hi,
Yes, the following error shows up. I google and tried to install the C++ redistribution under Win 11, but it doesn't solve the problem.
Any hints?
![OpenSees_error](https://github.com/OpenSees/OpenSees/assets/8373688/cebd28b1-a589-412c-9985-726c15637d06)

**Comment by fmckenna** [comment]
i have placed the vc redistributable package in the OpenSees .zip folder. Download the app again. if it fails again, double click on the vc_redist.x64 application in the bin folder
