### ISSUE TITLE
SURFACE LOAD ELEMENTS

### ISSUE THREAD

**Issue by MekPAME** [OpenSees/OpenSees#1359]
Hi!
Is there a way to add the command "SurfaceLoad element" of OpenSees? 
It's not possible that in this software is so hard to apply a uniform load pressure. When I want to apply a load to a surface if the mesh is not uniform the pressure is not uniform!!!!!!

All the other problem types have this feature, should be normal to apply a uniform pressure regardless the mesh.

Please!

**Comment by mhscott** [comment]
Thank you for the feature request and feedback.

There is a SurfaceLoad element by McGann that does what you describe. It's indirect, but general. Give it a try.

**Comment by MekPAME** [comment]
Thanks a lot! Actually this is a problem of GID+OpenSees software not OpenSees.

**Comment by mhscott** [comment]
Then you should post the issues on the GiD+OpenSees website or contact the developers.

The issues on this repo are for issues in the OpenSees source code, not issues with third party applications.

**Comment by MekPAME** [comment]
Yes, I know, sorry @mhscott.
