### ISSUE TITLE
ADVICES FOR Gravity analysis failed to converge!

### ISSUE THREAD

**Issue by MekPAME** [OpenSees/OpenSees#1362]
Hi OpenSees Community. I am running the following Gravity analysis with the SANISAND04 costitutive law. 
The analysis has the following parameters:
system BandGeneral
numberer RCM
constraints Transformation
integrator LoadControl 0.25
test NormDispIncr 1e-06 100 0
algorithm Newton
analysis Static

analyze 4

updateMaterialStage -material 366 -stage 1

But when I run it I've got the following message:

WARNING: CTestNormDispIncr::test() - failed to converge
after: 100 iterations  current Norm: 5.31012e-05 (max: 1e-06, Norm deltaR: 1.16921)
NewtonRaphson::solveCurrentStep() -the ConvergenceTest object failed in test()
StaticAnalysis::analyze() - the Algorithm failed at step: 0 with domain at load factor 0.25
OpenSees > analyze failed, returned: -3 error flag

The model is working cause I've tried to run it before with an Elastic costitutive law and it works!
How can I improve it to make it better?
Any ideas or raccomendations?
For example I did not use any substepping, could be useful?

Thank you very much!

**Comment by silviamazzoni** [comment]
The issues on this repo are for issues in the OpenSees source code, not a user-support forum.

**Comment by MekPAME** [comment]
Alright! I am really sorry for that @silviamazzoni 
Could I post the issue on the following website?
https://www.silviasbrainery.com/opensees-forum
