### ISSUE TITLE
Database + Restore command issue

### ISSUE THREAD

**Issue by MekPAME** [OpenSees/OpenSees#1365]
Hi! Good morning OpenSees Community, in particular D.Eng @mhscott 

As you've adviced on the Portwood Digital, I contact you for an error that I get when I run the command "restore".
I show in this post the Code and the Error I am getting in order to better understand.
The database+save command it works, but the restore does not.

I think maybe there are some updates to this commands I must download and apply. 
Could you explain me the way?
The files are saved and stored in the folder as I wanted, but I can not restore them.

Thanks a lot in advance!

Code:

OpenSees > source  13thM_Model_Mesh_definition.tcl
ManzariDafalias nDmaterial - Written: A.Ghofrani, P.Arduino, U.Washington
SSPbrick element - Written: C.McGann, P.Arduino, P.Mackenzie-Helnwein, U.Washington
SurfaceLoad element - Written: C.McGann, P.Arduino, P.Mackenzie-Helnwein, U.Washington
Geotechnical Model MESH uploading done!...Pame Mek!
OpenSees > source  13thM_Recorders.tcl
Starting analysis Gravity Analysis...Pame Mek!
OpenSees > source  13thM_Gravity_Analysis.tcl
Running Gravity Analysis Pame!
First run analysis done. Gravity applied! Pame Right Now!

OpenSees > #After defining the model and performing the first analysis (A),
OpenSees > #create a File database (in the code below I added a subfolder db/
OpenSees > #to the database name because I don’t want a bunch of files in my current working directory)
OpenSees >
OpenSees > #database $type $dbName
OpenSees >
OpenSees > database File db/Gravity_step
OpenSees >
OpenSees > #Save the model
OpenSees >
OpenSees > save 23
OpenSees >
OpenSees > wipe
OpenSees >
OpenSees >OpenSees > #database $type $dbName
OpenSees >
OpenSees > database File db/Gravity_step
OpenSees >
OpenSees > # restore the Gravity step
OpenSees >
OpenSees > restore 23
FEM_ObjectBrokerAllClasses::getNewElement -  - no Element type exists for class tag 116
Domain::recv - cannot create element with classTag 116
FE_Datastore::restoreState - domain failed to recvSelf
WARNING - database failed to restoreState

**Comment by mhscott** [comment]
Thanks, looks like an issue with SurfaceLoad elements

**Comment by MekPAME** [comment]
@mhscott Thanks Professor @mhscott 
Yeah, I've used them in order to apply a uniform surface load in the Gravity step. This is the way I've given the lateral overload pressure.
Just let me know how I could figure it out.
It's really important for me this command.

**Comment by mhscott** [comment]
Should be fixed with this PR: https://github.com/OpenSees/OpenSees/pull/1366

**Comment by MekPAME** [comment]
@mhscott Wonderful!
Sorry, just a question. I am unskilled about coding (at least now, my first experience with OpenSees). 
What shoud I do now to add your improvements in my OpenSees installed?
Thanks a lot in advance Professor.

**Comment by MekPAME** [comment]
@mhscott Happy Spring Season Professor.
I've written and run the following code, but does not restore the files yet!
Could you give more instructions please?

# Define variables
set repository_url "https://github.com/OpenSees/OpenSees"
set pull_request_number 1366
set branch_name "update_from_pr_${pull_request_number}"
set files_changed {
    "SRC/actor/objectBroker/FEM_ObjectBrokerAllClasses.cpp"
    "SRC/element/surfaceLoad/SurfaceLoad.cpp"
    "SRC/element/surfaceLoad/SurfaceLoad.h"
    "SRC/element/surfaceLoad/TriSurfaceLoad.cpp"
    "SRC/element/surfaceLoad/TriSurfaceLoad.cpp"
}

# Clone the repository
exec git clone $repository_url
cd OpenSees

# Create a new branch for the update
exec git checkout -b $branch_name

# Fetch the pull request changes
exec git fetch origin pull/$pull_request_number/head:update_from_pr

# Merge the changes into the new branch
exec git merge $branch_name

# Check out the changed files
foreach file $files_changed {
    exec git checkout origin/master -- $file
}

# Commit the changes
exec git add .
exec git commit -m "Update with changes from pull request $pull_request_number"

# Push the changes to your repository
exec git push origin $branch_name

# Clean up - delete the temporary branch
exec git checkout master
exec git branch -D $branch_name

puts "OpenSees has been updated with changes from pull request $pull_request_number."

**Comment by mhscott** [comment]
This thread is not the best place to discuss basic use of GitHub and compiling OpenSees. Please look for resources online, e.g., YouTube, then reach out directly if you have questions.

**Comment by MekPAME** [comment]
I agree Professor.
I am going to to build  (compile) OpenSees with your modifications. 
Just let me know if there is a version of VisualStudio I must use or any other raccomandations.
Thanks a lot!

**Comment by MekPAME** [comment]
@mhscott Good morning Professor.
I've been able to build a new OpenSees.exe with the PR:1366 but when I use the command restore I get this message:
OpenSees > restore 23
FileDatastore::recvVector() - failed
WARNING SurfaceLoad::recvSelf() - failed to receive Vector
Domain::recv - Ele with dbTag 41146 failed in recvSelf()
FE_Datastore::restoreState - domain failed to recvSelf
WARNING - database failed to restoreState

**Comment by mhscott** [comment]
This minimal script should work with the latest code from the `master` branch of OpenSees

```python
ops.wipe()
ops.model('basic','-ndm',3,'-ndf',3)

ops.node(1,0,0,0); ops.fix(1,1,1,1)
ops.node(2,1,0,0); ops.fix(2,1,1,1)
ops.node(3,1,1,0); ops.fix(3,1,1,1)
ops.node(4,0,1,0); ops.fix(4,1,1,1)

p = 0.5

ops.element('SurfaceLoad',1,1,2,3,4,p)

ops.database('File','/tmp/surfaceLoad')
ops.save(1)

ops.wipe()

ops.database('File','/tmp/surfaceLoad')
ops.restore(1)
```

**Comment by MekPAME** [comment]
@mhscott Thanks a lot Professor for your support. I'll let you know if it works :)
I am getting doubts with the next .exe I've compiled, indeed now the analysis running time is much higher than your last release.
I am not able neither to conclude the Gravity analysis, might be something on VisualStudio like some settings?

_
