### ISSUE TITLE
stessStrain recorder output is blank

### ISSUE THREAD

**Issue by BFF-LEI-Lei** [OpenSees/OpenSees#1369]
Hi，
I used a custom script to record the fiber stress-strain results for a zero-length section element like：
"recorder Element -file Stress-Strain.txt –time -ele 35 section 26 fiber 13.5 0.0 11 stressStrain".

However, it didn't work and the Stress-Strain.txt was blank.

I also tried with 
"recorder Element -file Stress-Strain.txt –time -ele 35 section fiber 13.5 0.0 11 stressStrain"
and "recorder Element -file Stress-Strain.txt –time -ele 35 section fiber 13.5 0.0 stressStrain"
and "recorder Element -file Stress-Strain.txt -ele 35 section 26 fiber 13.5 0.0 11 stressStrain".

All the efforts were in vain.

Anybody help?

**Comment by mhscott** [comment]
It looks like you have a long dash before `time`. Replace with a short dash -

https://portwooddigital.com/2023/10/29/beware-the-em-dash/
