### ISSUE TITLE
Database Restore command Code issue

### ISSUE THREAD

**Issue by MekPAME** [OpenSees/OpenSees#1378]
Hiii :)

I post the following code to notice the failure of the command "restore", in this case seems to be the LoadPattern section.
I hope that it will become a new PR to improve the master repos.

OpenSees > restore 230
FileDatastore::recvVector() - failed
PathTimeSeries::recvSelf() - channel failed to receive the Path Vector
LoadPattern::recvSelf - the TimeSeries failed to recv
Domain::recv - LoadPattern with dbTag 46564 failed in recvSelf
FE_Datastore::restoreState - domain failed to recvSelf
WARNING - database failed to restoreState

<<< Database command failure >>>

**Comment by mhscott** [comment]
Please post a minimal example from which the issue can be reproduced, something like this: https://github.com/OpenSees/OpenSees/issues/1365#issuecomment-2013305235

**Comment by MekPAME** [comment]
Well, one moment, maybe I've got new essential info. This is the piece of the script I am working on. After restoring the gravity step, with the surface load elements (which now thanks to the PR1366 works), when I define a new load pattern says: "invalid command name "pattern"". 

OpenSees > database File db/Gravity_step
OpenSees >
OpenSees >
OpenSees > restore 23
OpenSees >
OpenSees >

OpenSees > pattern Plain 2 {Series -time {1 2 10000} -values {0 1 1} -factor 1} {
    load      1        0        0    -47.4        0        0        0
}
invalid command name "pattern"
OpenSees >

in order to figure out this problem I added just this command bar:

model BasicBuilder -ndm 3 -ndf 3

and so I could define a new pattern with no problem, BUT most likely this step is the one which takes to the ERROR I've opened this issue.

infact if you run this simple script:

wipe

model BasicBuilder -ndm 3 -ndf 3

node      1            0            1            1
node      2            0            0            1
node      3            0            1            0
node      4            1            1            1
node      5            1            0            1
node      6            1            1            0
node      7            0            0            0
node      8            1            0            0

fix      1   1   0   0   
fix      2   1   1   0   
fix      3   1   0   1   
fix      4   0   0   0   
fix      5   0   1   0   
fix      6   0   0   1   
fix      7   1   1   1    
fix      8   0   1   1   

nDMaterial ElasticIsotropic 328 100000 0.25 1

element SSPbrick    1      5      4      6      8      2      1      3      7    328

element SurfaceLoad 2  1  4  5  2  -3.24

pattern Plain 1 {Series -time {0 1 10000} -values {0 1 1} -factor 1} {
eleLoad  -ele 2  -type  -surfaceLoad

# Record initial state of model

record

# Analysis options

system BandGeneral
numberer RCM
constraints Transformation
integrator LoadControl 1
test NormDispIncr 1e-04 100 1
algorithm Newton
analysis Static

analyze 1

loadConst
wipeAnalysis

database File db/Gravity_step_proof

save 1

wipe

database File db/Gravity_step_proof

restore 1

pattern Plain 2 {Series -time {1 2 10000} -values {0 1 1} -factor 1} {
    load      1        0        0    -47.4                        
} 

The invalid command name "pattern" does not appear.

So the question is why restoring my model I get that message when I define a new load pattern after restoring???

**Comment by MekPAME** [comment]
@mhscott Thanks Professor for your advice. I am conducting deeper investigations.

**Comment by MekPAME** [comment]
Out! Here it is @mhscott. If you run the following code the error subject of the issue will appear.

wipe

model BasicBuilder -ndm 3 -ndf 3

# node $NodeTag $XCoord $Ycoord $Zcoord

node      1            0            1            1
node      2            0            0            1
node      3            0            1            0
node      4            1            1            1
node      5            1            0            1
node      6            1            1            0
node      7            0            0            0
node      8            1            0            0

fix      1   1   0   0   
fix      2   1   1   0   
fix      3   1   0   1   
fix      4   0   0   0   
fix      5   0   1   0   
fix      6   0   0   1   
fix      7   1   1   1    
fix      8   0   1   1   

set e 0.67
nDMaterial ManzariDafalias   328   355  0.05   $e    1.51  0.515  0.0145    0.902    1    100 0.01 4.05 1.25  0.40  0.87  1.73    4    600  0

element SSPbrick    1      7      8      6      3      2      5      4      1    328  0  0  0

element SurfaceLoad 2  2  5  4  1  -3.24

pattern Plain 1 {Series -time {0 1 10000} -values {0 1 1} -factor 1} {
eleLoad  -ele 2  -type  -surfaceLoad
}

system BandGeneral
numberer RCM
constraints Transformation
integrator LoadControl 1
test NormDispIncr 1e-04 100 1
algorithm Newton
analysis Static

analyze 1

loadConst
wipeAnalysis

database File db/Gravity_step_proof

save 1

wipe

database File db/Gravity_step_proof

restore 1

pattern Plain 2 {Series -time {1 2 10000} -values {0 1 1} -factor 1} {
    load      1        0        0    -47.4                               
}

system BandGeneral
numberer RCM
constraints Penalty 1.0e08 1.0e08
integrator LoadControl 1
test NormDispIncr 1e-03 100 1
algorithm Newton
analysis Static

analyze 1

loadConst
wipeAnalysis

database File db/Load_step_proof

save 2

wipe

database File db/Load_step_proof

restore 2

**Comment by MekPAME** [comment]
Sorry, I did not understand why the issue has been closed.
@mhscott May you indicate me the if now the problem is solved and with which PR?
Many thanks!

**Comment by mhscott** [comment]
The issue was not closed and is under review.

**Comment by MekPAME** [comment]
Alright dear Professor.
Thanks a lot for your support!

**Comment by MekPAME** [comment]
Good morning and 1st of May! @mhscott 
Any news about Professor?

**Comment by mhscott** [comment]
I found something, but need to talk it over with @fmckenna next week.

**Comment by MekPAME** [comment]
@mhscott This message is just a memento for the issue #1378.

**Comment by mhscott** [comment]
@MekPAME Should be fixed now: https://github.com/OpenSees/OpenSees/pull/1412

**Comment by MekPAME** [comment]
Thanks a lot @mhscott.
I am going to compile and I'll let you know.

Warm regards

Marcello De Vivo
