### ISSUE TITLE
Different results for the same model in a loop

### ISSUE THREAD

**Issue by JavierCC05** [OpenSees/OpenSees#1379]
Hello everyone,

A model of a single-degree-of-freedom system using the SAWS material model running inside a loop does not produce consistent results from analysis to analysis. The real response is repeated most frequently; however, a certain number of results are different from the expected response. There is no clear pattern of when or why the different results appear. Sometimes the error could be as frequent as 30 over 100 iterations or as infrequent as 0 over 100 iterations. If using other materials such as Steel02, the results are always the same. This error was originally found in OpenSEESPy for either dynamic or static analysis but was also replicated using TCL. In TCL, minimizing discrepancies can be achieved by calling the TCL file within an external loop where each iteration opens and closes a new Command Prompt (cmd). This approach significantly reduces discrepancies, yielding approximately 10 errors out of 10,000 iterations. The following Python example is one of the simplest and consists of a ZeroLength element subjected n times in a loop to a displacement control pattern. It plots the hysteresis result on the first iteration, the i+1 hysteresis when the result of the “i+1” iteration is different from the “i” iteration, and a final graph with 1 when the result of the “i+1” iteration is different from the “i” iteration. The Steel02 material is in the script with the tag=2; therefore, you can also run the model using that material. What could be the problem? We have a more detailed document containing all the options we tried to solve this and other dynamic and static models in TCL and Python. I can email them to you in case you are interested. 

Thanks.
 
#==============================================================================
    # Displacement Control
    #==============================================================================
    
    #Import libraries
    #==============================================================================
    import openseespy.opensees as op
    import os
    import numpy as np
    import time
    import matplotlib.pyplot as plt
    
    
    #Input variables
    #==============================================================================
    n = 100         # Number of times to run the code
    SF = 1.0        # Scaling factor for the displacement pattern
    
    #Displacement Pattern
    deform = [0.1, -0.1, 0.5, -1., 1., -2., 2., -4., -4., 5., -5., 6, -6 ]
    
    #Loop
    #==============================================================================
    
    for i in range(n):
        start_time = time.time()
        
        #Model
        #==============================================================================
        op.wipe() 
        op.wipeAnalysis()
        op.model('basic', '-ndm', 2)
        
        #Geometry
        #------------------------------------------------------------------------------
        op.node(1, 0, 0)
        op.node(2, 0, 0)
        
        op.fix(1, 1, 1, 1)
        op.fix(2, 0, 1, 1)  
        
        #Materials
        #------------------------------------------------------------------------------  
        #SAWS
        matTag = 1
        S0 = 5.0                  #[kip/in]
        F0 = 8.760                #[kip]
        FI = 1.5                  #[kip]
        R1 = 0.05                 #[-]
        R2 = -0.15                #[-]
        R3 = 0.8                  #[-]
        R4 = 0.05                 #[-]
        DU = 3.25                 #[in]
        alpha = 0.75              #[-]
        beta = 1.02               #[-]
        op.uniaxialMaterial('SAWS', matTag, F0, FI, DU, S0, R1, R2, R3, R4, alpha, beta)
        
        #Steel02
        matTag = 2
        Py = 5.0
        Dy = 1.5		 
        E0 = Py/Dy		
        b = 0.005
        params = [30, 0.959, 0.5]		
        a1 = 0.097
        a2 = 1.0
        a3 = a1
        a4 = a2
        op.uniaxialMaterial('Steel02', matTag, Py, E0, b, *params, a1, a2, a3, a4)
        
        # Elements 
        #------------------------------------------------------------------------------
        op.geomTransf('Linear', 1) 
        op.element('zeroLength', 100, 1, 2, '-mat', 1 , '-dir', 1)
        
        # Recorders
        #------------------------------------------------------------------------------
        ResDir = 'Res_DispControl'   
        if not os.path.exists(ResDir):
            os.mkdir(ResDir)
            
        op.recorder('Node', '-file',    ResDir +'/'+'Displacement_'+str(i+1)+'.out','-time','-node',*[2],'-dof',1,'disp')
        op.recorder('Element', '-file', ResDir+'/'+'Forces_'+str(i+1)+'.out', '-time', '-ele', *[100], 'force')
    
        #Analysis
        #------------------------------------------------------------------------------
        #Load Pattern
        op.timeSeries('Linear', 1) 
        op.pattern('Plain', 1, 1)
        
        #1. Constraint Handler
        op.constraints('Plain')
        #2. DOF_Numberer
        op.numberer('Plain')
        #3. System of equations/Solver
        op.system('FullGeneral')
        #4.Test
        op.test('EnergyIncr', 1.0e-8, 300, 0)
        #5. SolutionAlgorithm
        op.algorithm('Newton')
        
        #Start Analysis
        act_disp = 0.0
        
        for DincrDef in deform:
            DincrDef= DincrDef*SF
            
            Dincr = 0.01*DincrDef/abs(DincrDef)
            
            #6. Integrator
            op.integrator('DisplacementControl', 2, 1, Dincr)
            
            #7. Analysis
            op.analysis('Static')
            
            if Dincr>0:
                op.load(2, 1, 0, 0)
                Dmax = DincrDef
                ok = 0
                while ok==0 and act_disp<Dmax:
                    ok=op.analyze(1)            
                    if ok==0:    
                        act_disp=op.nodeDisp(2 ,1)
         
            elif Dincr<0:
                op.load(2, -1, 0, 0)
                Dmax = DincrDef
                ok = 0
                while ok==0 and act_disp>Dmax:
                    ok=op.analyze(1)           
                    if ok==0:    
                        act_disp=op.nodeDisp(2, 1)
        
        if ok!=0:
            print('Error at t = ' + str(act_disp))
        else:
            print('\nAnalysis '+str(i)+' Complete')
            end_time = time.time()
            elapsed_time = round(end_time - start_time,2)
            print(f"Elapsed time: {elapsed_time} seconds")
        
        op.remove('recorders')
        op.wipe() 
        op.wipeAnalysis()    
    
    
    # Plotting Errors
    #==============================================================================
    
    X = np.loadtxt(f"{ResDir}/Displacement_{1}.out")[:, 1]
    Y = np.loadtxt(ResDir+'/Forces_'+str(1)+'.out',skiprows=0)[:,4]
    plt.plot(X,Y)
    plt.show()
    
    diff = []
    err = []
    cont = 0
    i = 1
    
    while i<n:
        Y = np.loadtxt(ResDir+'/Forces_'+str(i)+'.out',skiprows=0)[:,4]
        Y2 = np.loadtxt(ResDir+'/Forces_'+str(i+1)+'.out',skiprows=0)[:,4]
        
        if len(Y2) != len(Y):
            # When the different response appears, there is a different size in the
            # response
            err.append(1)
            diff.append(i)
            X = np.loadtxt(f"{ResDir}/Displacement_{i}.out")[:, 1]
            X2 = np.loadtxt(f"{ResDir}/Displacement_{i+1}.out")[:, 1]
            plt.plot(X,Y)
            plt.show()
            plt.plot(X2, Y2)
            plt.show()
            i+=2
            cont = cont+1
            continue
        else: 
            d = sum(abs((Y2 - Y)))
            if d > 0:
                err.append(1)
                diff.append(i)
                X = np.loadtxt(f"{ResDir}/Displacement_{i}.out")[:, 1]
                X2 = np.loadtxt(f"{ResDir}/Displacement_{i+1}.out")[:, 1]
                plt.plot(X,Y)
                plt.show()
                plt.plot(X2, Y2)
                plt.show()
                i+=2
                cont = cont+1
                continue
                
            else:
                err.append(0)
                i+=1
     
    fig= plt.subplots(dpi=200)   
    plt.scatter(range(1,len(err)+1), err)
    plt.xlabel('Iteration n [-]')
    plt.ylabel('Difference between i and i+1 [-]')
    plt.title("n = "+ str(n)+" - n_error = "+str(cont))

**Comment by mhscott** [comment]
Thanks for describing the issue and providing an example.

`valgrind` showed uninitialized variables, which would explain the variable results. Should be fixed now: https://github.com/OpenSees/OpenSees/pull/1380

Scary this material has been used and generated published results since 2009....

**Comment by JavierCC05** [comment]
Thank you, Dr. Scott.

**Comment by mhscott** [comment]
Thank you, @JavierCC05! The updated code will be compiled into the next pip release of OpenSeesPy and in the next release of OpenSees.exe (Tcl).
