### ISSUE TITLE
Which Makefile.def?

### ISSUE THREAD

**Issue by ashkanbj** [OpenSees/OpenSees#138]
Hello,

I am trying to build OpenSees on an HPC. I do not know which Makefile.def I should use. I was wondering if anyone can help me with this problem.
I don't know what are the properties of the HPC I am working on, but I can ask for any information. So please tell me if I need to provide more information.

Thanks,
Ashkan

**Comment by ashkanbj** [comment]
> That is a mixture of compiler, hardware, and actual OpenSees model .. it is all due to round-off (though presence of bug is always possible). If the compilers produced the exact same set of instructions that were run in the same sequence on the processor the results would be the same .. they do not .. depending on the CPU, optimization levels, hardware (cache sizes), they reorder the instructions a bit to make them go fast for that particular setup .. i.e. C = A + B + D might on one machine C = (A + B) + D, on another C = A + (B + D) .. this is fine if computers had no roundoff and numbers culd be represented exactly, but they do .. as a consequence the number C may be slightly different .. for FE models that are ill or poorly conditioned, round-off can play havoc on the results (especially for transient analysis were if results srart drifting different they can become very different and large models) .. try use solvers that do pivoting to help.

Thank you, Dr. McKenna. What are these solvers that use pivoting?

**Comment by thatoneddrguy** [comment]
Hello,

I have a similar question regarding which makefile.def to use. I've noticed that all of the guides on compiling OpenSeesMP are for Linux, but I can't seem to find anything about compiling OpenSeesMP on Windows. Is it possible to build OpenSeesMP using the Visual Studio solution files? Or is there some other process for building OpenSeesMP on Windows?

**Comment by mhscott** [comment]
Closing issue. The last comment was slightly off topic. We are working to compile OpenSeesMP on Windows.
