### ISSUE TITLE
Implementation of OpenSees 3.6.0 on the computing Grid SCoPE

### ISSUE THREAD

**Issue by marcogaetanidaragona** [OpenSees/OpenSees#1384]
Dear all,
I beg your help while implementing OpenSees 3.6.0 on the parallel computing grid SCoPE. I asked the administrators to implement this new version, but they faced some issues related to the installation environment (also evidencing that no indication about the compiler version adopted is provided). This is their reply to my request:

"After several attempts at configuration and compilation, we note that Release 3.6.0 of Open Sees is not compilable with the operating environment of our computing infrastructure (see, for example, the excerpt from the following compilation log from which it is evident that the call to the abs function does not occur in a compatible manner with the available compiler versions - we also note that the compilation instructions do not provide indications on the compiler versions to be used).
[ 23%] Built target OPS_Actor
[ 23%] Built target OPS_Renderer
[ 25%] Built target OPS_ConvergenceTest
[ 25%] Built target OPS_Utilities
Scanning dependencies of target OPS_Element
[ 25%] Building CXX object CMakeFiles/OPS_Element.dir/SRC/element/PML/PML2D_3.cpp.o
/opt/exp_soft/unina.it/CentOS7/OpenSees-3.6.0/SRC/element/PML/PML2D_3.cpp: In member function ‘void PML2D_3::ComputeK(double*, double*, double, double, double, double, double, double, double, double, double)’:
/opt/exp_soft/unina.it/CentOS7/OpenSees-3.6.0/SRC/element/PML/PML2D_3.cpp:707:45: error: call of overloaded ‘abs(double)’ is ambiguous
     a = std::abs(XYelement[6] - XYelement[0]);
                                             ^
/opt/exp_soft/unina.it/CentOS7/OpenSees-3.6.0/SRC/element/PML/PML2D_3.cpp:707:45: note: candidates are:
In file included from /opt/exp_soft/unina.it/CentOS7/OpenSees-3.6.0/SRC/element/PML/PML2D_3.h:32:0,
                 from /opt/exp_soft/unina.it/CentOS7/OpenSees-3.6.0/SRC/element/PML/PML2D_3.cpp:26:
/usr/include/stdlib.h:770:12: note: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;

I hope you can help me to solve these problems. 

Best regards,
Marco

**Comment by mhscott** [comment]
Looks like the administrators should pull the latest source code from GitHub: https://github.com/OpenSees/OpenSees/commit/cf56a221cfe87ce3e9ac4c9a4a12aec84dc11834

**Comment by fmckenna** [comment]
any update?
