### ISSUE TITLE
Activate Beam3dPartialUniformLoad function for 3d ForceBeamColumn element

### ISSUE THREAD

**Issue by tpanagiotakos** [OpenSees/OpenSees#1406]
To activate the function Beam3dPartialUniformLoad and allow the user to specify partial load in 3d ForceBeamColumn elements, the following changes need to be made to the source code of the 'create pattern' command (openseespatterncommands.cpp):
1. Add:
  #include <Beam3dPartialUniformLoad.h>
2. Modify:
...
else if (ndm == 3) {
// wy, wz, wx, aL, bL
double data[5] = { 0.0, 0.0, 0.0, 0.0, 0.0 };
int numdata = OPS_GetNumRemainingInputArgs();
if (numdata < 2) {
	opserr << "WARNING eleLoad - beamUniform want Wy Wz <Wx>\n";
	return -1;
}
if (numdata > 5) numdata = 5;
if (OPS_GetDoubleInput(&numdata, data) < 0) {
	opserr << "WARNING eleLoad - invalid value for beamUniform\n";
	return -1;
}
for (int i = 0; i < theEleTags.Size(); i++) {
	if (numdata > 3)
		theLoad = new Beam3dPartialUniformLoad(eleLoadTag, data[0], data[1], data[2], data[3], data[4], theEleTags(i));
	else
			  theLoad = new Beam3dUniformLoad(eleLoadTag, data[0], data[1], data[2], theEleTags(i));
	if (theLoad == 0) {
		opserr << "WARNING eleLoad - out of memory creating load of type " << type;
		return -1;
	}
// get the current pattern tag if no tag given in i/p
int loadPatternTag = theActiveLoadPattern->getTag();
// add the load to the domain
if (theDomain->addElementalLoad(theLoad, loadPatternTag) == false) {
		  opserr << "WARNING eleLoad - could not add following load to domain:\n ";
		  opserr << theLoad;
		  delete theLoad;
		  return -1;
}
eleLoadTag++;
	  }
	  return 0;
}

**Comment by mhscott** [comment]
Thank you. Please modify the source code and make a pull request.
