### ISSUE TITLE
The order of matrix elements returned by the GimmeMCK command has been modified

### ISSUE THREAD

**Issue by whispers1104** [OpenSees/OpenSees#1419]
I need to use the GimmeMCK command to obtain the mass and stiffness matrices of the structure, but I found that the order of the nodes in the obtained stiffness matrix seems to be automatically rearranged by the domain, even if I use the plain numbering device. Is there a way to disable the renumbering, or how should I number so that the node arrangement order in the obtained matrix is ​​the same as when it was defined? Thank you!

**Comment by mhscott** [comment]
If you think this is a bug, you'll have to provide a small example that demonstrates the issue. Could be multi-point constraints, e.g., if using rigid diaphragms, causing the DOFs to be renumbered.

**Comment by mhscott** [comment]
Nice plot, but I don't understand what you're demonstrating. Too confusing with inconsistent node numbers.
Anyway, try using the `Plain` constraint handler instead of `Transformation`

**Comment by whispers1104** [comment]
Let me clarify the numbering rules. The number of each node represents the node number in the XYZ direction. For example, 112 represents the first node in the X direction, the first node in the Y direction, and the second node in the Z direction. In this case, if we check the order of node definition and look at the stiffness matrix, the grids should correspond to 112, 212, 312, etc., which are defined in the X direction. But node 112 is connected to node 212 but not to node 312, so theoretically there should be no value in the third grid of the first row. This is why I judge that opensees has rearranged the order of the nodes internally.
![Stiffness Matrix](https://github.com/OpenSees/OpenSees/assets/102704871/50a053e1-c164-4e17-98a6-e9f0b3b4ffe4)

**Comment by whispers1104** [comment]
Next, I did another experiment, adjusting the numbering to natural number order, and keeping the other settings unchanged. The resulting stiffness matrix was like this. It can be found that this time the stiffness matrix does seem to arrange the degrees of freedom in the order defined. I also checked the OpenSees documentation on plain numberer, which mentioned: This command is used to construct a Plain degree-of-freedom numbering object to provide the mapping between the degrees-of-freedom at the nodes and the equation numbers. A Plain numberer just takes whatever order the domain gives it nodes and numbers them, this ordering is both dependent on node numbering and size of the model. This indicates that the difference may indeed be caused by the numbering problem. But what confuses me is what size of volume or numbering will cause this problem, and how does the OpenSees internal numberer determine it? This is very important to me.
![Stiffness Matrix2](https://github.com/OpenSees/OpenSees/assets/102704871/3f3fbcaf-0594-4009-9221-82003d70f164)

**Comment by fmckenna** [comment]
use the following to see what the mapping is between the nodal dof and the equation numbers .. note the mapping is 0 througn n-1, not 1 through n .. https://openseespydoc.readthedocs.io/en/latest/src/nodeDOFs.html

**Comment by whispers1104** [comment]
@fmckenna Thank you for your reply! I tried the nodeDOFs command and found that opensees numberer seems to map degrees of freedom to equation numbers in order of numbering from smallest to largest, which solved my problem to a large extent!

**Comment by whispers1104** [comment]
By the way, is there a command to get the stiffness and mass matrices without constraint processing?

**Comment by mhscott** [comment]
No, but you can define your model with no boundary conditions, then remove rows and columns manually when post-processing
