### ISSUE TITLE
missing recorder data 

### ISSUE THREAD

**Issue by arsalan3731** [OpenSees/OpenSees#1426]
I have an issue with file that opensees Recorders saved Data...
after completing an analyze some of recorders lost Data recorded from several last step of analyze for example:
a push over analyze done properly with 1200 steps and roofDisp recorder saved all the 1200 steps But element Recorder just saved 500 step analyze Data!!!!!
how can I fix this problem?

**Comment by arsalan3731** [comment]
> this is not an OpenSees issue, it's a user issue. you need to use the wipe command at the end to close the recorders.

thank you for your time silvia.
just to be sure:
simply "wipe" command at the end of analyze code is enough?

**Comment by silviamazzoni** [comment]
please refer to the documentation, as the format is interpreter-dependent. If this doesn't resolve your issue, please debug your input.
Again, this is not a user-support page.

**Comment by mhscott** [comment]
If you are using the latest version of OpenSees.exe (3.6.0) or OpenSeesPy, you should not have to use the `wipe` command to flush the recorders. Please make sure you are using the most up-to-date version.
