### ISSUE TITLE
sectionLocation do not return all locations!

### ISSUE THREAD

**Issue by BijanSeif** [OpenSees/OpenSees#1429]
Hi,

As it is shown in the following line, secnum is optional and if we do not enter any value foe secnum all sections location will be return as output.

https://github.com/OpenSees/OpenSees/blob/205b5c91e6a385074771ac205777c507beeb309c/SRC/interpreter/OpenSeesOutputCommands.cpp#L2856

But the question is that why in the tcl commands (As shown in the following) user is obliged to enter at least 3 parameters and user is forced to enter the section number, so this command only returns one location! (Location of the entered section number)

https://github.com/OpenSees/OpenSees/blob/205b5c91e6a385074771ac205777c507beeb309c/SRC/tcl/commands.cpp#L8188
https://github.com/OpenSees/OpenSees/blob/205b5c91e6a385074771ac205777c507beeb309c/SRC/tcl/commands.cpp#L8191

Let me know if there is another way to get all sections location. Thanks

**Comment by mhscott** [comment]
That's going to take a little bit of work to fix. For now, can you build the list manually?

```tcl
set locs ""
for {set i 1} {$i <= $Np} {incr i} {
   lappend $locs [sectionLocation $eleTag $i]
}
```

**Comment by BijanSeif** [comment]
Thanks Prof. @mhscott for response. 

The main problem is the `$Np` in `{$i <= $Np}`. That's for drawing purposes, and it is not possible to ask for `$Np` from users, and it should be exported from domain automatically. I understand fixing it in source code needs time. If there is currently no way to find `$Np` there is NP.

I think if `sectionTag `command for TCL become activate it will be handled however it needs time also!

**Comment by mhscott** [comment]
@BijanSeif Fixing this issue is planned, you can re-open the issue so we don't forget!

**Comment by BijanSeif** [comment]
Really thanks Prof. @mhscott.

**Comment by mhscott** [comment]
@BijanSeif Should be fixed now: https://github.com/OpenSees/OpenSees/pull/1451
