### ISSUE TITLE
SAVE + RESTORE command SANISAND-MS

### ISSUE THREAD

**Issue by MekPAME** [OpenSees/OpenSees#1453]
Hi OpenSees community!

@mhscott 
@jaabell ¡Hola!

I open this issue because using the commands Save+Restore  with the costitutive model SANISAND-MS it does not work. 
Indeed It's not yet implemented as suggested by the message that appears just trying to save the gravity analysis.

SAniSandMS::sendSelf - not yet implemented! Contact https://github.com/jaabell

Could you make this implementation please?

It will be useful for all the community!

Warm regards

Marcello De Vivo

**Comment by mhscott** [comment]
Looks like @jaabell is the person who has claimed responsibility for this implementation.

**Comment by MekPAME** [comment]
@mhscott Yeah, he is, as it is written by OpenSees.
I mentioned you Professor because you've done the same command implementation for ManzariDafalias SANISAND04 through the pull requests number #1378 & #1412. 
So I suppose would be just necessary to copy them into the SANISAND-MS.
When the modifications  will be done on SANISAND-MS as well, I'll compile again and I'll you know if it works for both the costitutive models.

Warm regards!

Thanks for your support!

**Comment by mhscott** [comment]
@MekPAME No, the issue and PR you reference were for the PathTimeSeries. Please work with @jaabell to resolve the issues with `sendSelf` and `recvSelf` for the soil constitutive models.

**Comment by mhscott** [comment]
Any updates?

**Comment by MekPAME** [comment]
Hi Professor!
Not yet, @jaabell will fix it soon, I am going to contact him again.
Thanks a lot for the reminder.
Warm regards

**Comment by jaabell** [comment]
Hi @MekPAME . Can you provide a minimal example that might be of your interest, so I can do the changes and test? I'll try to get it done this week.

**Comment by MekPAME** [comment]
!Hola! @jaabell Nice!
Here it comes!

wipe

model BasicBuilder -ndm 3 -ndf 3

# --------------------------------------------------------------------------------------------------------------
# N O D E S
# --------------------------------------------------------------------------------------------------------------

# node $NodeTag $XCoord $Ycoord $Zcoord

node      1            0            1            1
node      2            0            0            1
node      3            0            1            0
node      4            1            1            1
node      5            1            0            1
node      6            1            1            0
node      7            0            0            0
node      8            1            0            0

# --------------------------------------------------------------------------------------------------------------
# R E S T R A I N T S
# --------------------------------------------------------------------------------------------------------------

# fix $NodeTag x-transl y-transl z-transl

fix      1   1   0   0   
fix      2   1   1   0   
fix      3   1   0   1   
fix      4   0   0   0   
fix      5   0   1   0   
fix      6   0   0   1   
fix      7   1   1   1    
fix      8   0   1   1   

#nDMaterial ManzariDafalias   328   355  0.05   $e    1.51  0.515  0.0145    0.902    1    100 0.01 4.05 1.25  0.40  0.87  1.73    4    600  0
#nDMaterial ElasticIsotropic 328 100000 0.25

#Definition of the parameters of the adopted costitutive soil law

set G0        98  ; # [Adimensional]
set nu        0.2  ; # [Adimensional]
set e_init    0.70  ; # [Adimensional]
set Mc        1.46  ; # [Adimensional]
set c         0.70 ; # [Adimensional]
set lambda_c  0.023 ; # [Adimensional]
set e0        0.958 ; # [Adimensional]
set ksi       0.305  ; # [Adimensional]
set P_atm     100 ; # [kPa]
set m         0.005  ; # [Adimensional]
set h0        1.046  ; # [Adimensional]
set ch        0.950  ; # [Adimensional]
set nb        2.0   ; # [Adimensional]
set A0        0.84  ; # [Adimensional]
set nd        3.5  ; # [Adimensional]
set mu0       260     ; # For SAniSand [Adimensional]
set zeta      0.0005     ; # For SAniSand [Adimensional]
set beta      1     ; # For SAniSand [Adimensional]
set Den       0     ; # [Mg/m^3]
set intScheme 3     ; # Corresponds to Modified-Euler integration scheme
set TanType   1     ; # 0: elastic stiffness, 1: continuum elastoplastic stiffness
set JacoType  1     ; # Not used in explicit methods
set TolF      1.0e-6; # Tolerances, not used in explicit
set TolR      1.0e-6; # Tolerances, not used in explicit

# nDMaterial Definition used by SSPbrick Elements

nDMaterial SAniSandMS  328 $G0 $nu $e_init $Mc $c $lambda_c $e0 $ksi $P_atm $m $h0 $ch $nb $A0 $nd $zeta $mu0 $beta $Den $intScheme $TanType $JacoType $TolF $TolR

# Create element

element SSPbrick    1      7      8      6      3      2      5      4      1    328  0  0  0

element SurfaceLoad 2  2  5  4  1  -3.24


pattern Plain 1 {Series -time {0 1 10000} -values {0 1 1} -factor 1} {
eleLoad  -ele 2  -type  -surfaceLoad
}
# Record initial state of model

record

# Analysis options

system Umfpack
numberer RCM
constraints Transformation
integrator LoadControl 1
test NormDispIncr 1e-04 100 1
algorithm Newton
analysis Static

#Analyze model

analyze 1

# all previously defined patterns are constant for so on.
loadConst
wipeAnalysis

#database $type $dbName 

database File db/Gravity_step_proof

#Save the model

save 1

wipe

#database $type $dbName 

database File db/Gravity_step_proof

# restore the Gravity step

restore 1

# Loads - Plain Pattern

pattern Plain 2 {Series -time {1 2 10000} -values {0 1 1} -factor 1} {
    load      1        0        0    -47.4                               
}

# Analysis options

system BandGeneral
numberer RCM
constraints Penalty 1.0e08 1.0e08
integrator LoadControl 1
test NormDispIncr 1e-03 100 1
algorithm Newton
analysis Static

analyze 1

# all previously defined patterns are constant for so on.
loadConst
wipeAnalysis

#database $type $dbName 

database File db/Load_step_proof

#Save the model

save 2

wipe

#database $type $dbName 

database File db/Load_step_proof

# restore the Gravity step

restore 2
# --------------------------------------------------------------------------------------------------------------

**Comment by jaabell** [comment]
PR #1532 implements the functionality and contains a test based on your test case.
