### ISSUE TITLE
build guide for MacOS (M series chips) needs improvements

### ISSUE THREAD

**Issue by eweca-d** [OpenSees/OpenSees#1458]
In the [official guide](https://opensees.github.io/OpenSeesDocumentation/developer/build.html#obtaining-the-source-code) to build this application on MacOS. It requires `conan install .. --build missing` without any note for installing `conan`. It is confusing. According to the guide for Windows, it is better to add `pip install conan==1.59.0` before it.

`conanfile.py` should be updated. The guide asks to build missing by conan, but the setup script does not support Arm arch. I tried to modify the line 10 to be `settings = {"os": None, "build_type": None, "compiler": None, "arch": ["x86_64", "armv8"]}`. It works well.

The `SuperLU_5.1.1` cannot be compiled correctly on mac due to more strict constrait for the return type annotation `OpenSees3.6.0/opensees/OTHER/SuperLU_5.1.1/SRC/dutil.c:464:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]`. I added `int` explicitly for the function `print_double_vec`. Now it works well.

Same story for  `METIS` with error `/opensees/OTHER/METIS/minitpart.c:250:17: error: call to undeclared function 'SelectQueueOneWay'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]`. I added `int SelectQueueOneWay(int ncon, float *npwgts, float *tpwgts, int from, PQueueType queues[MAXNCON][2]);` in `minitpart.h`.

It is better to improve them to help others to compile OpenSees on MacOS.

**Comment by z-ichinohe** [comment]
Thank you for your information and raising this issue. I created two pull requests regarding this issue.
1. In OpenSees/OpenSeesDocumentation#151, `conan install .. --build missing` is removed. To build on Mac, you don't need to use conan because all dependencies to build can be installed via Homebrew.
2. I agree with your proposal.
3. I can't reproduce the error about METIS on M1 Mac and Github Action workflows. Even though `minitpart.c` and `int SelectQueueOneWay` exist, `minitpart.h` doesn't. Could you tell me more information to reproduce the problem mentioned above or make a pull request by yourself?

**Comment by eweca-d** [comment]
> Thank you for your information and raising this issue. I created two pull requests regarding this issue.
> 
> 1. In [Building manual compatible with Github Actions workflows. OpenSeesDocumentation#151](https://github.com/OpenSees/OpenSeesDocumentation/pull/151), `conan install .. --build missing` is removed. To build on Mac, you don't need to use conan because all dependencies to build can be installed via Homebrew.
> 2. I agree with your proposal.
> 3. I can't reproduce the error about METIS on M1 Mac and Github Action workflows. Even though `minitpart.c` and `int SelectQueueOneWay` exist, `minitpart.h` doesn't. Could you tell me more information to reproduce the problem mentioned above or make a pull request by yourself?

1. Yes. We can install hdf, eigen, and tcl via Homebrew. However, I believe canon is a better choice for the consistency since the conan is required by both Windows and Ubuntu so far.
2. Thank you for your effort!
3. The problem occurs when I tried to compiling OpenSeesMP. My bad. I added `int SelectQueueOneWay(int ncon, float *npwgts, float *tpwgts, int from, PQueueType queues[MAXNCON][2]);` in `metis.h`. But it also work if added in `minipart.c`.

**Comment by nemaarpit** [comment]
I have created the pull request for the compile errors here: #1499 , since I saw those errors on linux as well.
