### ISSUE TITLE
Possible memory leak when using fiber sections

### ISSUE THREAD

**Issue by mclpascua** [OpenSees/OpenSees#1459]
Hi all,

I think I may have found a memory leak in the fibre section. I found the problem while conducting time history analyses on a supercomputer facility and my code is using a lot memory, proportional to the length of the ground motion records. 

I made a MWE which is a single bay, single storey 3D steel frame. I used Prof Michael Scott's suggestion on how to find a memory leak using psutil. https://openseesdigital.com/2023/12/27/a-better-way-to-find-memory-leaks-in-opensees/

- The beams and the columns start as elasticBeamColumn elements. There is no memory leak, as shown in the plot below. (Note: Vertical axis shows memory leak in MB.)
![image](https://github.com/OpenSees/OpenSees/assets/70562179/c95ef914-732a-4bcf-a581-34631dc75ff6)

- I change the columns to a dispBeamColumn element defined with a fiber section to show the memory leak. I used three different materials for the fiber section (elastic, steel01, steel02). The memory usage is smaller when the material is elastic but the leak is still there.

(elastic material)
![image](https://github.com/OpenSees/OpenSees/assets/70562179/334a3fd0-2238-4f5f-8653-1705b2918ad3) 

(Steel01 material)
![image](https://github.com/OpenSees/OpenSees/assets/70562179/142ff991-4190-4d54-934f-d5a95d889ef3) 

(Steel02 material)
![image](https://github.com/OpenSees/OpenSees/assets/70562179/493a758f-637f-4d0b-8808-05dd688acb09) 

- I have also tried changing the fiber integration type from Lobatto to Legendre and it makes no difference to the memory usage. 

Below is my MWE

`

    # -*- coding: utf-8 -*-
    """
    Created on Sat Jun 29 16:40:19 2024
    
    @author: Claire Pascua (mpas592@aucklanduni.ac.nz)
    """
     #     122____________222
     #       /|          /|
     #      / |1003     / |1004
     #     /  |121     /  |221
     # 112/___________/212
     #    |           |
     #    |1001       |1002
     #    |           |
     #   111         211

    import os
    import matplotlib.pyplot as plt
    import numpy as np
    import openseespy.opensees as ops
    import psutil
    
    pid = os.getpid()
    thisprocess = psutil.Process(pid)
    
    Nruns = 2000
    mem = [0]*Nruns
    MB = 1024**2 # Megabytes
    
    for i in range(Nruns):
        ops.wipe()
        ops.model('basic','-ndm',3,'-ndf',6)
    
        # ============================
        # %% DEFINE UNITS
        # ============================
        mm = 1e-3
        m = 1
        kN = 1e3
        kPa = 1e3
        MPa = 1e6
    
        Lx = 7500*mm
        Ly = 7500*mm
        H = 4000*mm
    
        # ============================
        # %% DEFINE NODES
        # ============================
        ops.node(111, 0 , 0, 0);
        ops.node(211, Lx, 0, 0);
        ops.node(121, 0 , Ly, 0);
        ops.node(221, Lx, Ly, 0);
    
        ops.node(112, 0 , 0, H);
        ops.node(212, Lx, 0, H);
        ops.node(122, 0 , Ly, H);
        ops.node(222, Lx, Ly, H);
    
        ops.node(332, 0.5*Lx, 0.5*Ly, H)
    
        # ============================
        # %% DEFINE BOUNDARY CONDITIONS
        # ============================
        ops.fix(111,1,1,1,1,1,1)
        ops.fix(211,1,1,1,1,1,1)
        ops.fix(121,1,1,1,1,1,1)
        ops.fix(221,1,1,1,1,1,1)
    
        ops.fix(332, 0, 0, 1, 1, 1, 0)
        ops.rigidDiaphragm(3, 332, *[112, 212, 122, 222])
    
        # ============================
        # %% DEFINE MATERIALS
        # ============================
        fc1 = 40 * MPa
        Ec1 = 4700*np.sqrt(fc1/MPa) * MPa
        Gc1 = 0.4*Ec1 # See Table10-5 of ASCE41-17
    
        fy300 = 354.60 * MPa
        epy300 = 0.001921
        E300 = fy300/epy300
        Esh300 = 1132 * MPa                    # Tangent at initial strain hardening
        b300 = Esh300/E300
        steel_mattag = 1
    
        # ops.uniaxialMaterial('Elastic', steel_mattag, E300)
        # ops.uniaxialMaterial('Steel01', steel_mattag, fy300, E300, b300)
        ops.uniaxialMaterial('Steel02', steel_mattag, fy300, E300, b300, 15, 0.925, 0.15)
    
        # ============================
        # %% DEFINE SECTIONS
        # ============================
        b = 400*mm # mm
        d = 400*mm # mm
        A = b*d
        Iy = b*d**3/12
        Iz = d*b**3/12
        Jxx = b*d/12*(b**2 + d**2)
    
        steel_sectag = 1
        ops.section('Fiber', steel_sectag, '-GJ', E300)
        ops.patch('circ', steel_mattag, 30, 3, 0, 0, 300*mm, 0, 360)
        nip = 2
        integrationType = 'Lobatto'
        steel_integrationtag = 1
        ops.beamIntegration(integrationType, steel_integrationtag, steel_sectag, nip)
    
        # Define geometrc transformation
        ops.geomTransf('Linear', 1, 1, 0, 0)
        ops.geomTransf('Linear', 2, 0, 1, 0)
        ops.geomTransf('Linear', 3, 0, 1, 1)
    
        # ============================
        # %% DEFINE ELEMENTS
        # ============================
        # Elastic Columns (no to minimal memory leak)
        # ops.element('elasticBeamColumn', 1001, 111, 112, A, Ec1, Gc1, Jxx, Iy, Iz, 2)
        # ops.element('elasticBeamColumn', 1002, 211, 212, A, Ec1, Gc1, Jxx, Iy, Iz, 2)
        # ops.element('elasticBeamColumn', 1003, 121, 122, A, Ec1, Gc1, Jxx, Iy, Iz, 2)
        # ops.element('elasticBeamColumn', 1004, 221, 222, A, Ec1, Gc1, Jxx, Iy, Iz, 2)
    
        # Fibre Columns (memory leak)    
        ops.element('dispBeamColumn', 1001, 111, 112, 3, steel_integrationtag)
        ops.element('dispBeamColumn', 1002, 211, 212, 3, steel_integrationtag)
        ops.element('dispBeamColumn', 1003, 121, 122, 3, steel_integrationtag)
        ops.element('dispBeamColumn', 1004, 221, 222, 3, steel_integrationtag)
    
        # # Beams (X)
        ops.element('elasticBeamColumn', 2001, 112, 212, A, Ec1, Gc1, Jxx, Iy, Iz, 2)
        ops.element('elasticBeamColumn', 2002, 122, 222, A, Ec1, Gc1, Jxx, Iy, Iz, 2)
        # # Beams (Y)
        ops.element('elasticBeamColumn', 2003, 112, 122, A, Ec1, Gc1, Jxx, Iy, Iz, 3)
        ops.element('elasticBeamColumn', 2004, 212, 222, A, Ec1, Gc1, Jxx, Iy, Iz, 3)
    
        # ============================
        # %% APPLY LOADS
        # ============================
        P = 300*kN
        ops.timeSeries('Linear', 1)
        ops.pattern('Plain', 1, 1)
        ops.load(112, 0, 0, 0.25*P, 0, 0, 0)
        ops.load(212, 0, 0, 0.25*P, 0, 0, 0)
        ops.load(122, 0, 0, 0.25*P, 0, 0, 0)
        ops.load(222, 0, 0, 0.25*P, 0, 0, 0)
        ops.load(332, 0.10*P, 0, 0, 0, 0, 0)
    
        # ============================
        # %% DEFINE ANALYSIS
        # ============================
        ops.constraints("Transformation")
        ops.numberer("Plain")
        ops.test("NormDispIncr", 1.0e-12, 10000, 0)
        ops.algorithm('Newton', '-initial')
        ops.system('BandGeneral')
    
    
        # ============================
        # %% PERFORM ANALYSIS
        # ============================
        ops.integrator("LoadControl", 1)
        ops.analysis("Static")
        ops.analyze(1)
        ops.loadConst('-time', 0.0)
        ops.wipeAnalysis()
    
        ops.wipe()
        if i == 0: # First run
            mem0 = thisprocess.memory_info()[0]
        mem[i] = (thisprocess.memory_info()[0] - mem0)/MB
    
    plt.plot(mem, '-k')

`

Many thanks, 
Claire

**Comment by mhscott** [comment]
Thank you for providing an example. What version of openseespy are you using?

**Comment by mclpascua** [comment]
Hi Prof Scott,

I was using version 3.4. I have updated to 3.6 and as far as I can tell, there's no more memory leak. My apologies for not checking that before posting.

Thanks,
Claire
