### ISSUE TITLE
Followed instructions for compiling. what to do now?

### ISSUE THREAD

**Issue by erikemondt** [OpenSees/OpenSees#146]
I am currently facing a problem while compiling OpenSeesPy on my mac. As a student, I am completely new to compiling software and I feel like I am missing some knowledge. I followed the instructions available on OpenSeesPyDoc, which were of great help. But I am not sure how to proceed now. How can I now actually make use of the OpenSees software on my Mac? i.e, How do i access the OpenSees library from my Python environment (Anaconda3)? Below you can find a description of all details that might be relevant in italic.

I also wonder why OpenSeesPy is not available for Mac, but compiling is only possible on a Mac. Is this correct?

OS Version: 10.14.6
QT version: 5.12.1
QTC Version: 4.10.0

Directories added in OpenSeesPy.pro file:
 
macx: {
LIBS += -L/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/ -lpython3.7
INCLUDEPATH += /usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m \
               /usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/internal
DEPENDPATH += /usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include
}

The Opensees.dylib and OpenSees.so files where added to:
Users⁩ ▸ ⁨erikemondt⁩ ▸ ⁨anaconda3⁩ ▸ ⁨lib⁩ ▸ ⁨python3.7⁩ ▸ ⁨site-packages⁩ ▸ ⁨openseespy⁩ ▸ ⁨opensees⁩

**Comment by mhscott** [comment]
Hello @erikemondt, The Mac version of OpenSeesPy has always been difficult to compile.  @zhuminjie may be able to help.

**Comment by ahartloper** [comment]
@erikemondt To answer one of your questions, there is a Windows version of OpenSeesPy. You can simply `pip install openseespy`  on Windows.

**Comment by erikemondt** [comment]
Many thanks. I Also use OpenSees on Mac, but on https://openseespydoc.readthedocs.io/en/latest/src/compile.html, 
it is stated that "Currently, only building in OS X is supported".

The reason I need to compile is to include a new material (dll) in OpenSees. Is there another way to do so?

**Comment by mhscott** [comment]
Why a dll?  Why not compile the .cpp file directly with everything else in OpenSees/ ?

I don't know if it will make a difference in your compiling issues, but fundamentally, why a dll?

**Comment by erikemondt** [comment]
The material has been provided by an external party in .dll format, and i can not edit the source code of the dll. I am not sure how to include this dll in OpenSees, I thought compiling on my mac was the only option, are there alternatives?

Kind regards

**Comment by ahartloper** [comment]
A few questions:
1) Do you have an OpenSees material .dll (i.e., the material was compiled for use in OpenSees), or was it compiled for another program and you are trying to integrate it into OpenSees?
2) Do you have the .dylib or just the .dll?

If you only have the .dll I'm not sure how much luck you will have using the material on MacOS in any case.

**Comment by erikemondt** [comment]
It was compiled for another program and I am trying to integrate it in OpenSees. I have .dll and .lib files. In the user manual, it states the following about compiling:

"If Intel Fortran is available, the easiest way to include the DLL models in the source
code is to use the intrinsic ATTRIBUTES DLLIMPORT functionality and reference the
relevant library file (.lib) when compiling the calling program (the simulation
software). This loads the InterfaceFoundation subroutine from the DLL, which can
then be called in the main program as if it was any other locally defined subroutine.
Specifically, the following line should be included in the source code:
!DEC$ ATTRIBUTES DLLIMPORT :: InterfaceFoundation "

As I am new to compiling, do you have any advice on how to approach it? And would it be better to do it on windows (which i prefer)?

Many thanks for you time

**Comment by ahartloper** [comment]
Yes I think it will be better to do it on windows using Visual Studio.

Is this a uniaxial material, or multiaxial? I believe you will have to write some sort of adapter material that adapts the interface provided by your "InterfaceFoundation" library to the interface of either the UniaxialMaterial or NDMaterial in OpenSees. This will constitute a new set of C++ .cpp and .h files. These files are then added to the OpenSees project (I would recommend using the standard .tcl interpreter), and compile an OpenSees with the new material.

**Comment by erikemondt** [comment]
thank you for your advice. It is a multi-axial material, and I should indeed write some interface code. I'm currently using the Python interpreter, do you expect that will give problems?

**Comment by ahartloper** [comment]
I don't have much experience beyond a few simple examples with the Python3 interpreter, but I imagine it should be fine.

**Comment by mhscott** [comment]
The Python module shouldn't give problems.  You'll write an OPS_XYZmaterial function that works with both the Tcl and Python interpreters.

**Comment by erikemondt** [comment]
Many thanks for your help!

**Comment by mhscott** [comment]
Closing old issues.  If there are further problems, please start a new thread.
