### ISSUE TITLE
ShellDKGT Element: Not being able to use parameters

### ISSUE THREAD

**Issue by felipecordero** [OpenSees/OpenSees#1465]
Hello everyone.

I'm trying to use **`ops.parameter`** on **ShellDKGT** element, but I got errors. 

The code I'm using is:

### The section
ops.section('ElasticMembranePlateSection', sectionTag, E, nu, tickness)

### The element
`
ops.element('ShellDKGT', eleTag, node1, node2, node3, sectionTag)
`

### The parameter (none of the following two lines are working:
`
ops.parameter(1, 'element', eleTag, 'section', sectionTag, 'E')
`
`
ops.parameter(1, 'element', eleTag, 'E')
`

From the previous two line, I got:

`Parameter::addComponent 1 — no objects were able to identify parameter`

Is this not implemented for **ShellDKGT**?

Thanks in advance.

**Comment by mhscott** [comment]
The second option `ops.parameter(1'element',eleTag,'E')` should work now: https://github.com/OpenSees/OpenSees/pull/1467

**Comment by felipecordero** [comment]
Thank you very much
