### ISSUE TITLE
Bug in FiberSection3dThermal?

### ISSUE THREAD

**Issue by johnnyontheweb** [OpenSees/OpenSees#1468]
It seems that, in SRC/material/section/FiberSection3dThermal.cpp, the line 660:
`if (theCopy->Fiber_TMax == 0 || theCopy->Fiber_TMax) {`
should be:
`if (theCopy->Fiber_TMax == 0 || theCopy->Fiber_T == 0 ) {`

SInce I'm not confident with this code (and cannot find any sample model to try with), I'm trying to build one and I'm wondering if this is a bug or not. I got error in initialization of a tcl deck like this:
```
model BasicBuilder -ndm 3 -ndf 6
node 1 0e0 0e0 0e0
node 2 2e0 0e0 0e0
# elements
geomTransf Linear 1 0 -1 0
uniaxialMaterial SteelECThermal 2 EC3 355000 210000000
section FiberThermal 3 -GJ 26923 {
patch quad 2 2 2 0.1 -0.1 0.1 0.1 -0.1 0.1 -0.1 -0.1
}
element dispBeamColumnThermal 1 1 2 5 3 1
...
```

Thanks in advance

ps.
as far as you may know, are FiberSection3dThermal and dispBeamColumnThermal(3D) code only a draft? I know that they're inherited from OpenSees for Fire, but I'm guessing why I can find only 2D samples.

EDIT: I noticed that Steel01Thermal behaves different from the binary of OpenSeesForFire. It seems the code can handle only thermal loads (`analyze failed, returned: -3 error flag.`, while OpenSeesForFire is not giving such error). Actually mechanical loading is not treated as an error but there's no effect on material strain.

**Comment by mhscott** [comment]
The maintainers of the OpenSeesForFire repo have not updated the thermal code in the main OpenSees (this repo), and likely never will. You are better off to keep using OpenSeesForFire.

**Comment by johnnyontheweb** [comment]
I knew that there were support for thermal analyses thanks to your blog post (https://portwooddigital.com/2020/11/30/opensees-fire-v2-0/) =D 
thanks for it, it's very useful to understand the starting point.
Anyway, I think the one reported is a bug - the cantilever simple model in the OS for Fire site (attached) works in OSforFire but it's not working in OS.
I compared the code for:
- Steel01Thermal, Steel02Thermal and SteelECThermal : no relevant differences
- dispBeamColumnThermal : no relevant differences

I believe there's some bug in the FiberThermalSection3D - will investigate further.

[cantilever.txt](https://github.com/user-attachments/files/16321277/cantilever.txt)

**Comment by mhscott** [comment]
I see. Can you try this example in 3D?

http://portwooddigital.com/2024/01/24/minimal-thermal-example/

**Comment by johnnyontheweb** [comment]
Thanks, I tried with the previous sample adapted to yours (using forceBeamColumnThermal), but thermal load is not handled properly:
`ForceBeamColumn3d::addLoad -- load type unknown for element with tag: 1`

In the code, I see ForceBeamColumn2dThermal.cpp but not the 3D counterpart - I'm guessing why the element is still recognized if it's not implemented. Then, there's no LOAD_TAG_Beam3dThermalAction handling in forceBeamColumns3d.

[cantilever2.txt](https://github.com/user-attachments/files/16325833/cantilever2.txt)

ps.
I got also `ForceBeamColumn3d::ForceBeamColumn3d -- no torsion detected in sections, continuing with element torsional stiffness GJ/L = 1e+10` but the section already has  the `-GJ` flag.

ps2.
in TclModelbuilder, line 3090, I find the reading of input line for beam 3d thermal load:
```
	else if (argc - count == 4) {

		if (Tcl_GetDouble(interp, argv[count], &t1) != TCL_OK) {
			opserr << "WARNING eleLoad - invalid T1 " << argv[count] << " for -beamThermal\n";
			return TCL_ERROR;
		}
		if (Tcl_GetDouble(interp, argv[count + 1], &locY1) != TCL_OK) {
			opserr << "WARNING eleLoad - invalid LocY1 " << argv[count + 1] << " for -beamThermal\n";
			return TCL_ERROR;
		}
		if (Tcl_GetDouble(interp, argv[count + 2], &t5) != TCL_OK) {
			opserr << "WARNING eleLoad - invalid T5 " << argv[count] << " for -beamThermal\n";
			return TCL_ERROR;
		}
		if (Tcl_GetDouble(interp, argv[count + 3], &locY5) != TCL_OK) {
			opserr << "WARNING eleLoad - invalid LocY5 " << argv[count + 1] << " for -beamThermal\n";
			return TCL_ERROR;
		}

		locY2 = locY1 + (locY5 - locY1) / 4;
		locY3 = locY1 + (locY5 - locY1) / 2;
		locY4 = locY1 + 3 * (locY5 - locY1) / 4;
		t2 = t1 + (t5 - t1) / 4;
		t3 = t1 + (t5 - t1) / 2;
		t4 = t1 + 3 * (t5 - t1) / 4;
		locZ1 = locZ2 = locZ3 = locZ4 = locZ5 = 0;
		t6 = t7 = t8 = t9 = t10 = 0;
		t11 = t12 = t13 = t14 = t15 = 0;
...
```

I corrected T5 and LocY5 in messages, they are typos (I suppose they were just copied from the lines above).  
What I cannot understand is in the last lines: why Z-temperature gradient is zeroed? 
Setting gradient in Y direction is enough for all fibers in section? If so, does it means that Z gradient is _added_ to the Y one?
I cannot figure out how interpolation works in the code.

**Comment by mhscott** [comment]
In _TclForceBeamColumn.cpp_, a `ForceBeamColumn3d` will be created by default because the `ForceBeamColumn3dThermal` is not available. So, those error messages are misleading.

It also appears that `FiberSection3dThermal` reads the torsion in the OPS_ function but doesn't pass the torsion to the constructor, thus the `-GJ` warning.

I'm not sure the intent with the section temperature interpolation.

**Comment by johnnyontheweb** [comment]
I'm trying to complete the code of FiberSection3dThermal for torsion support and to add ForceBeamColumn3dThermal, I'll keep you posted.

To further clarify my previous guesses, I found that the interpolation of fiber temperature is done in `FiberSection3dThermal::determineFiberTemperature`: there's no bidimensional interpolation, since temps. in Z section local direction are used only when we're at locY1 (lower definition point for Y temp.) and locY5 (higher point). 
Also, I'll see if I can add 2d interpolation; it seems this has been designed for double-T sections only.

**Comment by johnnyontheweb** [comment]
Thanks for revising merge - another PR will follow with a new command for bilinear interpolation of temperatures in a fiber section and the shell tria thermal element.

**Comment by johnnyontheweb** [comment]
Many thanks for your work in merging revision!
