### ISSUE TITLE
WARNING-no torsion specified for 3D fiber section, use -GJ or -torsion

### ISSUE THREAD

**Issue by HaoxinGuo** [OpenSees/OpenSees#147]
# My question
When I use the software Opensees3.0.3 that **compiled by myself**, I  have encountered this problem。 
The software prompts me to have this error：**“WARNING-no torsion specified for 3D fiber section, use -GJ or -torsion”**. 
![error](https://user-images.githubusercontent.com/41227936/66307205-672cb600-e936-11e9-8436-f40af6d61926.png)
And I can find the **error code** ocuured in this file ```TclModelBuilderSectionCommand.cpp``` ,the function is
 ```
int TclCommand_addFiberSectionThermal(ClientData clientData, Tcl_Interp *interp, int argc, TCL_Char **argv, TclModelBuilder *theTclModelBuilder)
```
# My Source tcl File
[source_tcl_code.zip](https://github.com/OpenSees/OpenSees/files/3696857/source_tcl_code.zip)
Hope to get your help,thanks a lot.

**Comment by mhscott** [comment]
Gaoxin,
The FiberSection3d was recently changed #142 .  You have to either use -GJ
section Fiber 1 -GJ $GJ {

}
or use the new -torsion option
uniaxialMaterial Elastic 3 $GJ
section Fiber 1 -torsion 3 {

}

**Comment by HaoxinGuo** [comment]
Thanks a lot. It worked. You have solved my problem today, thank you for your contribution to OpenSees. Have a good day.

**Comment by mhscott** [comment]
[Here](https://portwooddigital.com/2019/10/06/torsion-with-fiber-sections/) is more detail on the change

**Comment by HaoxinGuo** [comment]
Thanks a lot.
And I want to share with you some other questions I have encountered. I hope it can help us to build this project more perfect.
## An error in debug mode
An error occurred while  running the following code
```tcl
set xDamp 0.05;
set nEigenI 1;
set nEigenJ 2;
set lambdaN [eigen [expr $nEigenJ]]; # the error happend
set lambdaI [lindex $lambdaN [expr $nEigenI-1]];
set lambdaJ [lindex $lambdaN [expr $nEigenJ-1]];
``` 
And the error is shown in this figure 
![error](https://user-images.githubusercontent.com/41227936/66312667-ab728300-e943-11e9-9aab-75c9555ca947.png)
However **it's going well in release mode.**
## reason
**in debug mode ArpackSolver (default eigensolver) got error** 
use release version 
work me fine
Have a good day.

**Comment by mhscott** [comment]
Please start a new issue for a new topic.
