### ISSUE TITLE
Convergence Issues with CFSWSWP and CFSSSWP Materials in Provided Example Script

### ISSUE THREAD

**Issue by LMChina** [OpenSees/OpenSees#1470]
Hello,

I am encountering convergence issues with the uniaxial materials CFSWSWP and CFSSSWP in OpenSees. Specifically, the example scripts provided by Opensees wiki. 

Materials: CFSWSWP and CFSSSWP
Example Script: https://opensees.berkeley.edu/wiki/index.php?title=Cold-Formed_Steel_Wood_Sheathed_Shear_Wall_Panel_examples
Issue: Convergence failure during the analysis
Opensees version: 3.6.0 x64.

Could you please provide guidance on how to resolve these convergence issues? Any insights or recommendations would be greatly appreciated.

Thank you for your assistance.

Best regards,

Mao Li

**Comment by mhscott** [comment]
These models are VERY buggy. For random input, the state determination enters an infinite loop in some cases.

The models were removed from the interpreters in a recent PR (after the version 3.6.0 you are using was compiled).

I recommend you switch to HystereticSM

**Comment by LMChina** [comment]
> These models are VERY buggy. For random input, the state determination enters an infinite loop in some cases.
> 
> The models were removed from the interpreters in a recent PR (after the version 3.6.0 you are using was compiled).
> 
> I recommend you switch to HystereticSM

Thanks for your reply and meaningful suggestions, Prof. Scott.
