### ISSUE TITLE
wipe() does not work on elemental damping

### ISSUE THREAD

**Issue by rempre63** [OpenSees/OpenSees#1480]
Hi All,

I have noticed that wipe() does not work on elemental damping

https://opensees.github.io/OpenSeesDocumentation/user/manual/model/damping/elementalDamping.html

Regards

**Comment by mhscott** [comment]
Do you mean if you define an elemental damping with tag X, then wipe, the define a new damping with tag X there is an error?

**Comment by rempre63** [comment]
Yes, exactly.

**Comment by fmckenna** [comment]
thanks yuleee. i accepted the pull request. https://github.com/OpenSees/OpenSees/pull/1488
