### ISSUE TITLE
Problems with PFEMSolver_Mumps and PFEMCompressibleSolver_Mumps

### ISSUE THREAD

**Issue by nlhpcaguajardo** [OpenSees/OpenSees#1484]
Hi
When I compile the version 3.7.0 in the 95% It shows me the following error:

OpenSees-3.7.0/SRC/tcl/commands.cpp(3123): error: identifier "PFEMSolver_Mumps" is undefined
  	  PFEMSolver_Mumps* theSolver = new PFEMSolver_Mumps(relax,0,0,0);
  	  ^

OpenSees-3.7.0/SRC/tcl/commands.cpp(3123): error: identifier "theSolver" is undefined
  	  PFEMSolver_Mumps* theSolver = new PFEMSolver_Mumps(relax,0,0,0);
  	                    ^

OpenSees-3.7.0/SRC/tcl/commands.cpp(3123): error: expected a type specifier
  	  PFEMSolver_Mumps* theSolver = new PFEMSolver_Mumps(relax,0,0,0);
  	                                    ^

OpenSees-3.7.0/SRC/tcl/commands.cpp(3135): error: incomplete type is not allowed
  	  PFEMCompressibleSolver_Mumps* theSolver = new PFEMCompressibleSolver_Mumps(relax,0,0);
  	                                                ^

OpenSees-3.7.0/SRC/tcl/commands.cpp(3136): error: no instance of constructor "PFEMCompressibleLinSOE::PFEMCompressibleLinSOE" matches the argument list
            argument types are: (PFEMCompressibleSolver_Mumps)
            theSOE = new PFEMCompressibleLinSOE(*theSolver);
                                               ^
OpenSees-3.7.0/SRC/system_of_eqn/linearSOE/sparseGEN/PFEMCompressibleLinSOE.h(44): note: this candidate was rejected because arguments do not match
  class PFEMCompressibleLinSOE : public PFEMLinSOE
        ^
OpenSees-3.7.0/SRC/system_of_eqn/linearSOE/sparseGEN/PFEMCompressibleLinSOE.h(48): note: this candidate was rejected because mismatch in count of arguments
      PFEMCompressibleLinSOE();        
      ^
OpenSees-3.7.0/SRC/system_of_eqn/linearSOE/sparseGEN/PFEMCompressibleLinSOE.h(47): note: this candidate was rejected because arguments do not match
      PFEMCompressibleLinSOE(PFEMCompressibleSolver &theSolver, bool exp=false);        
      ^

compilation aborted for OpenSees-3.7.0/SRC/tcl/commands.cpp (code 2)
gmake[3]: *** [CMakeFiles/OpenSeesMP.dir/build.make:104: CMakeFiles/OpenSeesMP.dir/SRC/tcl/commands.cpp.o] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:4748: CMakeFiles/OpenSeesMP.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:4755: CMakeFiles/OpenSeesMP.dir/rule] Error 2
gmake: *** [Makefile:586: OpenSeesMP] Error 2

Is there anyone who has or has had this error?

Thanks in advance

**Comment by mhscott** [comment]
You may need to define PFEM in your Makefile.def

**Comment by fmckenna** [comment]
we have updated commands.cpp .. it should compile now
