### ISSUE TITLE
Help needed: A simple truss model using displacement control is giving an error. Can anyone explain?

### ISSUE THREAD

**Issue by CR-317** [OpenSees/OpenSees#1486]
model BasicBuilder -ndm 2 -ndf 2

node 1 0.0 0.0
node 2 144.0 0.0

fix 1 1 1
fix 2 0 1

uniaxialMaterial Elastic 1 3000

element Truss 1 1 2 10 1

pattern Plain 1 {
    load 2 1.0 0.0
}

recorder Node -file node2_disp.out -time -node 2 -dof 1 disp

constraints Plain
numberer Plain
system BandGeneral
test NormDispIncr 1.0e-6 10
algorithm Newton
integrator DisplacementControl 2 1 0.01
analysis Static

analyze 100

puts "Node 2 displacement: [nodeDisp 2 1]"

wipe

The error message is as follows:

load 2 1.0 0.0
WARNING unknown Series type load -  valid types: Linear, Rectangular, Path, Constant, Trig, Sine, Ramp
WARNING - problem creating TimeSeries for LoadPattern 1
expected integer but got "
    load 2 1.0 0.0
"
    while executing
"pattern Plain 1 {
    load 2 1.0 0.0
}"
    (file "wykz.tcl" line 19)

**Comment by mhscott** [comment]
The error is in your load pattern definition. Please check the canonical OpenSees truss example:
https://opensees.berkeley.edu/wiki/index.php/Basic_Truss_Example

**Comment by CR-317** [comment]
&nbsp; Thank you for your letter.
&nbsp; The example you provided is load control, where the linear loading is completed in one step.My example is displacement control. Even after I made the following changes to the code, the error still occurs.






The original code：
pattern Plain 1 {
&nbsp; &nbsp; load 2 1.0 0.0
}



The modified code：
timeSeries Linear 1
pattern Plain 1 1{
&nbsp; &nbsp; load 2 1.0 0.0
}



The error message is as follows:


1{
WARNING unknown Series type 1{ -&nbsp; valid types: Linear, Rectangular, Path, Constant, Trig, Sine, Ramp
WARNING - problem creating TimeSeries for LoadPattern 1
expected integer but got "1{"
&nbsp; &nbsp; while executing
"pattern Plain 1 1{"
&nbsp; &nbsp; (file "wykz.tcl" line 20)



Could you analyze where the error might be? Thank you very much.


寻难而进，行胜于言
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenSees/OpenSees"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenSees/OpenSees] Help needed: A simple truss model using displacement control is giving an error. Can anyone explain? (Issue #1486)





 
The error is in your load pattern definition. Please check the canonical OpenSees truss example:
 https://opensees.berkeley.edu/wiki/index.php/Basic_Truss_Example

**Comment by mhscott** [comment]
Put a space between `1` and `{`. The error message tells you type `1{` is not recognized.

**Comment by CR-317** [comment]
Yes, it was my oversight; I didn't add the spaces, and the problem is resolved now. Thank you very much.




寻难而进，行胜于言
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenSees/OpenSees"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenSees/OpenSees] Help needed: A simple truss model using displacement control is giving an error. Can anyone explain? (Issue #1486)





 
Put a space between 1 and {. The error message tells you type 1{ is not recognized.

**Comment by CR-317** [comment]
#&nbsp; &nbsp;&nbsp;
#&nbsp; &nbsp; &nbsp; 5&nbsp; &nbsp; &nbsp;_______ 10
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp;
#&nbsp; &nbsp; &nbsp;4&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 9
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|
#&nbsp; &nbsp; &nbsp;3&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 8&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|
#&nbsp; &nbsp; &nbsp;2&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 7
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|&nbsp; &nbsp; &nbsp;
#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1&nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 6




&nbsp; &nbsp; The above diagram shows a schematic of a double-column pier subjected to cyclic loading.

Gravity loads were applied to nodes 5 and 10 using load control, and this step was completed.

Cyclic loading was applied to nodes 5 and 10 using displacement control, with displacement values sourced from an external file, but an error occurred during this step.&nbsp;

The code is as follows:


timeSeries Path 1 -dt 1.0&nbsp; -filePath node5-1.txt
timeSeries Path 2 -dt 1.0&nbsp; -filePath node10-1.txt


pattern Plain 2 1 {&nbsp; &nbsp; &nbsp;&nbsp;
	sp 5 1 1
}


pattern Plain 3 2 {&nbsp; &nbsp; &nbsp;
	sp 10 1 1
}


puts "analysis disp"
system BandGeneral ;
constraints Penalty 1.0e20 1.0e20
test NormDispIncr 1.0e-6 1000
algorithm KrylovNewton
analysis Static
analyze 18600&nbsp; &nbsp;;#The two files have 18,600 lines.



The error message is as follows:
analysis disp
WARNING PlainHandler::handle() -&nbsp; non-homogeneos constraint for node 5 homogeneous constraint assumed
WARNING PlainHandler::handle() -&nbsp; non-homogeneos constraint for node 10 homogeneous constraint assumed



Could you please explain the reason for this?
Your help in resolving this matter would be very much appreciated.




寻难而进，行胜于言
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenSees/OpenSees"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenSees/OpenSees] Help needed: A simple truss model using displacement control is giving an error. Can anyone explain? (Issue #1486)





 
The error is in your load pattern definition. Please check the canonical OpenSees truss example:
 https://opensees.berkeley.edu/wiki/index.php/Basic_Truss_Example

**Comment by mhscott** [comment]
Please search online for answers and consider posting basic modeling questions on the OpenSees Facebook group: https://www.facebook.com/groups/opensees/. There you will find suggestions on getting started with OpenSees. GitHub issues are for reporting bugs or requesting features in the code.

**Comment by CR-317** [comment]
Okay, thank you for your help.




寻难而进，行胜于言
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenSees/OpenSees"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenSees/OpenSees] Help needed: A simple truss model using displacement control is giving an error. Can anyone explain? (Issue #1486)





 
Please search online for answers and consider posting basic modeling questions on the OpenSees Facebook group: https://www.facebook.com/groups/opensees/. There you will find suggestions on getting started with OpenSees. GitHub issues are for reporting bugs or requesting features in the code.
