### ISSUE TITLE
Modelling zero compression steel elements

### ISSUE THREAD

**Issue by rbagel** [OpenSees/OpenSees#1491]
Hi all,
I am modelling steel components of a bridge structure subjected to a pushover to replicate experimental data. The set up of the structure means these elements have zero compressive resistance, so I am trying to model these elements having fairly standard tensile behaviour but no compressive strength. 

I have tried the Steel4 and Hysteretic uniaxial materials but both of these materials have caused issues in my model when the strength parameters for compression are set to zero, or close to zero. 

Any ideas on how to implement this? Thanks in advance. 

![bar response exp](https://github.com/user-attachments/assets/fd46ce5c-2731-4ce1-96e0-f03076a554fa)

**Comment by mhscott** [comment]
The issues here are for reporting bugs and requesting features. Please ask modeling questions elsewhere on the OpenSees message board or Facebook group.
