### ISSUE TITLE
ConcreteCM number of required arguments

### ISSUE THREAD

**Issue by zwaezi84** [OpenSees/OpenSees#1508]
ConcreteCM needs the following arguments:
// Parse the script for material parameters
  if (numArgs != 10 && numArgs !=  11 && numArgs != 12) {
    opserr << "Incorrect # args Want: uniaxialMaterial ConcreteCM tag? fpcc? epcc? Ec? rc? xcrn? ft? et? rt? xcrp? <-GapClose gap?>" << endln;
    return 0;
  }

But since mon is also a parameter needed after xcrp, the total number of parameters can be 13, not 12!

**Comment by mhscott** [comment]
But would you have `mon` and `gap` in the same instance of _ConcreteCM_?

**Comment by zwaezi84** [comment]
Yeah. You are right. Sorry.

**Comment by mhscott** [comment]
No problem. Based on your inquiry, I was able to clean up the ConcreteCM constructor (https://github.com/OpenSees/OpenSees/pull/1510), which is a good thing, so thanks!
