### ISSUE TITLE
import opennesspy on Mac M1 with segmentation fault  python

### ISSUE THREAD

**Issue by ma-wenqian** [OpenSees/OpenSees#1519]

**Comment by ma-wenqian** [comment]
I successfully compiled the openseespy on my Mac M1. The python 3.11 env is management by Conda. The commend used are from `./github/workflow`.  conda python platform: `platform : osx-arm64`
But i can't import it in python with an error `zsh: segmentation fault  python`. I am sure the python version is same between compilation and import process by checking the cmake out put.

can anyone help me?

**Comment by morgankmcbain** [comment]
Hi - I'm no expert at this, but my friend saw your post and knew I had notes on compiling openseespy on Mac M1. I'm not sure exactly what could be causing the segmentation fault, but the attached pdf has a description of the overall process that worked for me back in Spring 2023 on a Mac M1 w/ Monterey 12. Please note the following suggested change to the procedure (safer method) which mhscott provided on the opensees message board: https://opensees.berkeley.edu/community/viewtopic.php?p=126222&hilit=compiling+on+M1#p126222

[Process for compiling OpenseesPy on Mac with Monterey 12.pdf](https://github.com/user-attachments/files/17119037/Process.for.compiling.OpenseesPy.on.Mac.with.Monterey.12.pdf)

**Comment by mhscott** [comment]
Closing. Please re-open if needed.
