### ISSUE TITLE
I got different results after upgrading to OpenSees 3.7.0 and OpenSeesPy 3.7.0.4

### ISSUE THREAD

**Issue by cyt222** [OpenSees/OpenSees#1520]
Hello,
I have an identical model that uses MVLEM-3D for dynamic time history analysis in both tcl and py formats.
Recently, I upgraded OpenSees to 3.7.0 and OpenSeesPy to 3.7.0.4, and I reran these files.
Then, I received results that differed from those from OpenSeesPy 3.5.1.12 and OpenSees 3.6.0.
<img width="454" alt="OpenSees" src="https://github.com/user-attachments/assets/4dbb8b65-1a4d-4b23-95c2-24f510aac69e">

**Comment by mhscott** [comment]
Please share a *simple* model that demonstrates the difference between versions.

**Comment by cyt222** [comment]
@mhscott 
The last time I used OpenSees and OpenSeesPy was in May. 
At the time, I was using OpenSees 3.6.0 and OpenSeesPy 3.5.1.12.
Recently, I wanted to conduct an analysis using a different damping ratio, but I discovered that it takes more time to complete.
In addition, the results are not as I expected.
So I tried to run the same script that I used in May with several versions of OpenSees and OpenSeePy.
The results are displayed in the previous post. Rections are the sum of reaction forces, and the inertial force is computed from the acceleration output.
Now I wonder if something changes in the latest OpenSees (3.7.0) and OpenSeesPy (3.6.0.3 and 3.7.0.4).
Later, I will try a simple model to test this.

**Comment by mhscott** [comment]
Thanks for the information. Not much we can do without a simple example that demonstrates the issue.

**Comment by mhscott** [comment]
Please provide an update and if you have it, a minimal example.

**Comment by mhscott** [comment]
Did you figure out the issue? Haven't heard anything. Closing. Re-open if you develop a minimal example.
