### ISSUE TITLE
Allow for beta = 0.0, gamma = 0.0, and dt = 0.0 for Newmark when A form is used

### ISSUE THREAD

**Issue by gaaraujo** [OpenSees/OpenSees#1529]
Hi, I want to modify Newmark to allow for $\beta = 0.0$, $\gamma = 0.0$, and $\Delta t = 0.0$ when the `-form A` is used (i.e. `displ = 3`). It should be an easy fix, but I noticed that some of the sensitivity commands involve several divisions by $\gamma$ and $\beta$, and I don't want to mess them up. 

In particular, I found the following check in the `Newmark::formEleResidual()` method: 
https://github.com/OpenSees/OpenSees/blob/bb0c99e0ef96621998d736ef4a9f2557956543bc/SRC/analysis/integrator/Newmark.cpp#L594-L597
However, other sensitivity commands do not seem to have similar checks. Should I replicate this check in the other sensitivity analysis commands to prevent potential divisions by zero when $\gamma = \beta = 0.0$, or does the check in `Newmark::formEleResidual()` handle these scenarios for all sensitivity-related operations?

Any feedback is appreciated!

**Comment by mhscott** [comment]
@gaaraujo You can make that if statement on line 594 `return 0;` after printing the ERROR message. Then do similar things in the other sensitivity methods.
