### ISSUE TITLE
Compile problems with source code with VS2010

### ISSUE THREAD

**Issue by losusca** [OpenSees/OpenSees#154]
When I compile the source code of OpenSees2.5.0+TCL8.5 with VS2010, there are always errors, can't open some .lib files, such as DoddRestrepo.lib, drain.lib, etc., then I copied these files from OpenSees3.0.3 source code to the lib of OpenSees 2.5.0. These errors are not present, but a new fatal error LNK1104 has occurred, couldn't open the input file libdecimal.lib. I found libdecimal.lib in my computer, I tried the above copy method again, it didn't work, then I tried adding libdecimal.lib to VS2010\ VC\lib, the same does not work, what should I do?

**Comment by ahartloper** [comment]
Did you include the libdecimal.lib or the containing directory somewhere in the OpenSees project?

**Comment by losusca** [comment]
Thank you very much for your reply. I added libdecimal.lib into the Opensees project properties - Include directories and Library directories, but this error message still appear.

**Comment by losusca** [comment]
@ahartloper   Thank you very much for your reply. I added libdecimal.lib to the Opensees project properties - Include directories and Library directories, but this error message will still appear.

**Comment by ahartloper** [comment]
Did you add the directory under Properties > Linker > General > Additional Library Directories? Also did you do this for the correct configuration?

**Comment by charles-see** [comment]
I  got the same problem like you,but my environment is vs2019,it is so difficult to compile

**Comment by mhscott** [comment]
Thread is old, save for recent comment, which is addressed here: https://youtu.be/BLcY1w7a5Ec

If problems with VS 2010 still remain, please start a new issue.
