### ISSUE TITLE
Limit on Number of Recorder Files in OpenSeesPy on Windows

### ISSUE THREAD

**Issue by LMChina** [OpenSees/OpenSees#1544]
Dear OpenSees developers,

I am using OpenSeesPy in a Windows 10 environment and encountered a limitation with the maximum number of recorder files that can be generated. Specifically, when trying to record node or element responses with multiple output files (file type: .out), I found that the maximum number of files that can be generated is 509. Beyond this number, additional recorders are not created, and there are no errors or warnings indicating the issue.

To reduce the number of output files, I attempted to use multiple result types within a single recorder command, like this:

`ops.recorder('Element', '-file', f'example.out', '-ele', 1, 'force', 'deformation')
`

However, I noticed that only the first result type (force) is recorded, while the second (deformation) is ignored. When I separate the recorders into two distinct commands, the responses are recorded correctly in the respective files.

It would be helpful to understand:

1. If this limitation on file numbers is specific to Windows or OpenSeesPy.
2. Whether there is a way to record multiple response types in a single file to bypass this limit.

Thank you for your time, and I look forward to any guidance or suggestions you might have.

Best regards,

Mao Li

**Comment by mhscott** [comment]
This is an operating system issue, not an OpenSees issue.

You can create your own files via Python and output response via commands like `ops.nodeDisp()` and `ops.eleResponse()`
