### ISSUE TITLE
ColoumbDamperMaterial not found in prebuilt OpenSees executables. 

### ISSUE THREAD

**Issue by mallentino** [OpenSees/OpenSees#1546]
Recently, I had to use the CoulombDamperMaterial to replicate the behaviour of my extperimental sub-structure numerically. 
Upom using the latest precompiled version of OpenSees-3.7.0, it was not able to recognise the material denition. Following is the error message

WARNING could not create uniaxialMaterial CoulombDamperMaterial

After trying trying all the builds till the time it was first added in version 3.5.0, I faced the same issue. On compiling ver 3.7.0, I found that  most of the missing callouts for this material were fixed since its release in version 3.5.0. However, the TclModelBuilderUniaxialMaterialCommand.cpp file is still missing its reference. After adding the correct callouts I was able to build the executable file without the above error. 

Following are the lines I added to TclModelBuilderUniaxialMaterialCommand.cpp:
extern void *OPS_CoulombDamperMaterial(void);

	if ((strcmp(argv[1],"CoulombDamperMaterial") == 0)) {
      void *theMat = OPS_CoulombDamperMaterial();
      if (theMat != 0) 
	theMaterial = (UniaxialMaterial *)theMat;
      else 
	return TCL_ERROR;

    }

Could you please fix it in the final build and update it.

**Comment by mhscott** [comment]
Thanks, should be in the next release of OpenSees.exe
https://github.com/OpenSees/OpenSees/commit/40d991a4d934f57ffa5e7a481ef9442569a152b9
