### ISSUE TITLE
Issue in OpenSees MP caused by Mumps Solver

### ISSUE THREAD

**Issue by Venkataraman16** [OpenSees/OpenSees#1553]
I am trying to run dynamic analysis in parallel in OpenSees MP but noticed the displacements from all the GMs had the same values (average response). Further, when I try to run the GMs for different number of steps, the program gets stuck when one processor finish running. This does not happen when I used some other solver instead of Mumps. Here is an example code to check this issue.   
[Simple Model.zip](https://github.com/user-attachments/files/18027319/Simple.Model.zip)

**Comment by silviamazzoni** [comment]
@fmckenna have a quick look, I have been working with Venkat on this one. Let's discuss this tomorrow.
@mhscott this is the one i had mentioned to you.

**Comment by mhscott** [comment]
Can you make a simple model in a single script? Not gonna look at a zip file.

**Comment by fmckenna** [comment]
Mumps cannot be used in OpenSeesMP for this situation .. it is a parallel solver, takes contributions from all the processes and solves the equations every time a solve is requested .. when running MP for this type of analysis you want a sequential solver so each process is dealing with it's local system of equations.

**Comment by silviamazzoni** [comment]
Frank, your comment is consistent with my observation of the issue Venkat has run into.
So are you saying that the Mumps solver works for what I'd call distributed computing in OpenSeesMP -- when you do domain decomposition -- but NOT when you are doing multi-processing parallel independent analyses?

**Comment by fmckenna** [comment]
yes.
