### ISSUE TITLE
Compiling OpenSees with Visual Studio 2019 & Creating DLL files

### ISSUE THREAD

**Issue by patricioparedes** [OpenSees/OpenSees#156]
Hi all!
I have reviewed the Issues in this section and found somehow similar problems without being able to solve them.  I have created a new element (inside the elastomeric bearing group). I have tried two things to run OpenSees with the new element:

1) Creating a DLL (I'm working on Windows) using the "Add new code..." slides/instructions. I was able to create the file after some issues, however, even when I put the script, OpenSees.exe file and .dll file in the same folder, the new element is not recognized. I tried setting the system environmental path as suggested in a previous Issue without solving the problem. 

2) I tried compiling the whole code using Visual Studio 2019. However, the following .lib files are missing: actor.lib, analysis.lib, cblas.lib, convergence.lib, cssparse.lib, damage.lib, database.lib, domain.lib, drain.lib, element.lib, glu32.lib, graph.lib, handler.lib, ifconsol.lib, libifcoremt.lib, libmmt.lib, material.lib, matrix.lib, modelbuilder.lib, opengl32.lib, optimization.lib, recorder.lib, reliability.lib, renderer.lib, superLU.lib, system.lib, tagged.lib, tcl.lib, utility.lib, wsock32.lib. 
I guess I don't need all of them (realiability.lib, for instance). However, how do I know? Not all the .lib names are that obvious. 

Thanks in advance for your help. 

Patricio.

**Comment by mhscott** [comment]
Check your library path in the Visual Studio project settings and make sure OpenSees/Win64/lib is there.

**Comment by ahartloper** [comment]
@patricioparedes I would check mhscott's comment first. If this doesn't fix things: Do you have the Intel fortran compiler on your computer?

Most of the libraries you mention are built as a part of OpenSees, however, ifconsol and libifcoremt are part intel fortran. My best guess is that the OpenSees libraries can't be built because the intel fortran environment is not set-up, thus you get errors that all the libraries are missing.

**Comment by patricioparedes** [comment]
Problem solved! I was able to compile OS. Thank your so much for your help. 

(I'm just curious about the .dll approach. Should that have worked too? or the slides are out of date?)

**Comment by mhscott** [comment]
I'm guessing the slides are out of date :)
