### ISSUE TITLE
Unable to build OpenSeesPy in VS 2019

### ISSUE THREAD

**Issue by thatoneddrguy** [OpenSees/OpenSees#157]
I am having issues building OpenSeesPy in Visual Studio 2019 on a Windows 10 64-bit computer. As shown in the screenshots below, I have included the paths to Python 3.7 but I am getting an issue in node.h. Has anyone else encountered a similar issue when building OpenSeesPy in Visual Studio? Are there other environment variables or settings that need to be set?
![2019-11-03 20_44_48](https://user-images.githubusercontent.com/10858202/68101002-3d58a780-fe80-11e9-9457-e71fdb080bc0.png)
![2019-11-03 20_44_16](https://user-images.githubusercontent.com/10858202/68101006-40539800-fe80-11e9-94df-1c3dcac573a3.png)

**Comment by zhuminjie** [comment]
Can you moving the python include path to the end of the list in the  first picture? Also the include path is not needed in the library directories in the second picture.

**Comment by thatoneddrguy** [comment]
@zhuminjie Thanks for the suggestion to move the python include path to the end of the list, it resolved the original issue. However, I'm coming across a new "LNK2019 unresolved external symbol" error and I was wondering if you might have any insight on what might be causing this error. Looking up the error online seems to suggest that there is a library file that I need to include in the project, and the information from the error list suggests that it has something to do with "OPS_Explicitdifference", "OPS_Integrator", "PythonRV" and "OPS_RandomVariable".

![2019-11-16 11_05_36](https://user-images.githubusercontent.com/10858202/68997972-46bf1800-0861-11ea-9c31-930a479c6eea.png)

![2019-11-16 11_06_13](https://user-images.githubusercontent.com/10858202/68997975-4cb4f900-0861-11ea-97d7-2867b733edfe.png)

Any insight on how to resolve this error is greatly appreciated.

**Comment by zhuminjie** [comment]
Do you update with the latest source? These libraries have been added.

**Comment by thatoneddrguy** [comment]
@zhuminjie Updating to the latest source fixed the issue and I was able to build OpenSeesPy. Thanks for all your help!
