### ISSUE TITLE
v2.5 compilation error on centos in superLU function

### ISSUE THREAD

**Issue by shahram10715** [OpenSees/OpenSees#164]
Hi everyone:
While compiling on centoOS I encounter the following error:

    SuperLU.cpp: In member function ‘virtual int SuperLU::solve()’:
    SuperLU.cpp:238:67: error: cannot convert ‘GlobalLU_t*’ to ‘SuperLUStat_t*’ for argument ‘12’ to ‘void dgstrf(superlu_options_t*, SuperMatrix*, int, int, int*, void*, int, int*, int*, SuperMatrix*, SuperMatrix*, SuperLUStat_t*, int*)’
         etree, NULL, 0, perm_c, perm_r, &L, &U, &Glu, &stat, &info);
                                                                   ^

any idea?

**Comment by shahram10715** [comment]
Very intresting because I have no problem compiling v2.4.6 or v3.0

**Comment by ahartloper** [comment]
I would say that probably 562ad325 fixed this issue (Feb 24 2016).

**Comment by shahram10715** [comment]
yes thanks a lot, 562ad3259b347da1b6f25577a8d9216833407b91 worked for me. And sorry for my late response. I think I should close this issue.
