### ISSUE TITLE
How to create a OpenSees.exe file using Visual Studio for OpenSees material adding?

### ISSUE THREAD

**Issue by benjaminsoraghi** [OpenSees/OpenSees#168]
Hello
I started working on developing a material in OpenSees. I followed the [OpenSees tutorial provided by Dr. Frank McKenna](http://opensees.berkeley.edu/OpenSees/workshops/OpenSeesDays2012/B3_AddingYourCode.pdf)  and as I implement all steps in Visual Studio 2010 I got errors on missing files of _<SectionForceDeformation.h>_ and _<bool.h>_ files. I, however, was able to find those files on the [Github]( https://github.com/OpenSees/OpenSees), but still, I am not able to compile the _ElasticPPcpp_ file. Then I changed my Visual Studio to 2017/2019, but I still have issues with compiling as I try to implement the same step of the tutorial in the VS 2017, although VS 2017 it is slightly different.
My question is that is there anyone that can help me with a step by step procedure to compile the _ElasticPPccp_ file and make the ._dll_ file in VS 2010 or 2017 to be able to run the _example1_ (also provided in the tutorial)?
I can also share the errors I get from VS 2010 and 2017.
I do appreciate your help

Benjamin Soraghi

**Comment by ahartloper** [comment]
Hi Benjamin,

Is there any particular reason for wanting the .dll, or are you OK with an OpenSees.exe that has the material incorporated?

If you are OK with the .exe, I would clone the most recent OpenSees repo from github, then try to compile OpenSees 64 bit using Visual Studio 2019 without any modifications. Once you get OpenSees to compile without your added code, then you can work on adding the new material.

**Comment by benjaminsoraghi** [comment]
Thank you for your quick response. Oh well, I thought when we compile the ElasticPPcpp file it generates a .dll file :)
So no, if there is no need to create the .dll file then that is fine. I just need to learn to compile the ElasticPPcpp file without getting an error.

**Comment by ahartloper** [comment]
A very brief guide to get you started:

1. Get visual studio community 2019
2. Clone the opensees repo: `git clone git@github.com:OpenSees/OpenSees.git`
3. Build the Win64 solution (compile OpenSees)

When you hit 3. there could be a few errors that need to be worked through. Once you have the OpenSees.exe built, then you can add the new material and recompile. If you are still stuck at this point let me know.

**Comment by benjaminsoraghi** [comment]
@ahartloper That is very kind of you to help me through that.
I did all 3 steps and yes, I got errors (more than a few LOL). After Building the Win64 folder (compiling OpenSees), I got 136 Errors and 940 Warnings. The errors description is "Cannot open include file: 'tcl.h': No such file or directory" with the Code of C1083. 
Here I attached a screenshot of the Error List window
![Error List](https://user-images.githubusercontent.com/57687730/68965398-b4a80880-07a9-11ea-9822-b14c0bf6e639.PNG)

Side question: could you please suggest some reading material regarding "**building an OpenSees.exe**"?

**Comment by fmckenna** [comment]
tcl needs to be installed in C:/Program Files/Tcl .. which is not the default .. uninstall and reinstall or go edit all the project settings to include tha path you installed tcl in.

**Comment by ahartloper** [comment]
@benjaminsoraghi In this context OpenSees builds and runs the model, and you can use .dll's to define additional materials that are not defined in OpenSees. Alternatively, you can just add the material definition to OpenSees so the extra .dll is not necessary (the route I suggested).

**Comment by Nigel-7** [comment]
Hello Benjamin,

Thank you for sharing your experience. Recently I also met the same problem as you. I tried to add the example ElasticPPccp material to opensees using Visual Studio 2017. Likewise, I tried to follow every step illustrated by Frank McKenna. But still could not work it out. The error I got is shown in the screenshot. I am not sure if the problem lies in the version of Visual Studio or somewhere else. Any instruction would be gratefully appreciated.
<img width="704" alt="Errors" src="https://user-images.githubusercontent.com/59978531/72584619-c3e62800-38b8-11ea-864f-e14dfd03e47c.png">

**Comment by ahartloper** [comment]
How did you obtain the source code, and you have the latest version?

**Comment by Nigel-7** [comment]
> How did you obtain the source code, and you have the latest version?

Hi,

I got all the source code on this pape(https://github.com/OpenSees/OpenSees), including the DEVELOPER file and all the source code of OpenSees. I guess these are the latest version. Please let me know if anything wrong. Thank you.

**Comment by Nigel-7** [comment]
> A very brief guide to get you started:
> 
> 1. Get visual studio community 2019
> 2. Clone the opensees repo: `git clone git@github.com:OpenSees/OpenSees.git`
> 3. Build the Win64 solution (compile OpenSees)
> 
> When you hit 3. there could be a few errors that need to be worked through. Once you have the OpenSees.exe built, then you can add the new material and recompile. If you are still stuck at this point let me know.

Hello,

I tried as your instructed, with the only difference that I used Visual Studio 2017. The error list is shown in the scrrenshot. Any clue about what the problem is? Thank you so much!
<img width="1010" alt="Errors2" src="https://user-images.githubusercontent.com/59978531/72656302-4da0fe80-3968-11ea-85b3-a510e30f262c.png">

**Comment by ahartloper** [comment]
You need to switch the platform toolset you are using. The opensees project is set to v142 (Visual Studio 2019), you can set it to the one corresponding to VS2017, or use VS2019 (see: https://docs.microsoft.com/en-us/cpp/build/working-with-project-properties?view=vs-2019).

**Comment by Nigel-7** [comment]
> Thank you for your quick response. Oh well, I thought when we compile the ElasticPPcpp file it generates a .dll file :)
> So no, if there is no need to create the .dll file then that is fine. I just need to learn to compile the ElasticPPcpp file without getting an error.

Hi Benjamin,

I think I am having the same problem as you. Have you worked it out? Could you please share with me how you fixed it? And which version of Visual studio you used. Really thank you.

Best
Chen

**Comment by mhscott** [comment]
Closing old issues. Was this resolved? This video may help: https://youtu.be/BLcY1w7a5Ec

**Comment by AHT74** [comment]
Has anyone tried to do this in Ubuntu?
