### ISSUE TITLE
Compiling OpenSees for MacOS Catalina 10.15

### ISSUE THREAD

**Issue by gferman** [OpenSees/OpenSees#172]
Dear OpenSees Community,

I would like to ask your support to solve the following issue. I'm trying to compile from source in my Macbook Pro with MacOS Catalina. After forking the source, and cloning to my computer, I faced the following problems:

1. The OpenSees folder was located in /Users/MyUserName/Documents/Github/OpenSees after cloning. From this location, I received several error messages, which I attribute to the fact that Makefile.def is pointing the source to /Users/MyUserName/OpenSees. I don't know if I can compile anywhere else in my directory. To circumvent this problem, I moved the source to /Users/MyUserName/OpenSees.

2. Then, I received the error that folder /Users/MyUserName/OpenSees/OTHER/SuperLU_4.1/ is missing. Indeed, this folder is not present in the version I forked from GitHub. So, I modified the Makefile.def file as follows:

`SUPERLU_DISTdir   = $(HOME)/OpenSees/OTHER/SuperLU_DIST_2.5/SRC`

3. Now, I receive one fatal error message related to SuperLU and other missing files

`clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/zeroLength/TclZeroLength.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/forceBeamColumn/TclForceBeamColumnCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/coordTransformation/TclGeomTransfCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/joint/TclJoint2dCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/joint/TclJoint3dCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/joint/TclBeamColumnJointCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/updatedLagrangianBeamColumn/TclElement2dYS.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/updatedLagrangianBeamColumn/TclElement2dGNL.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/updatedLagrangianBeamColumn/TclCyclicModelCommands.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/damage/TclModelBuilderDamageModelCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/UP-ucsd/TclFourNodeQuadUPCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/TclElementCommands.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/dispBeamColumnInt/TclDispBeamColumnIntCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/elasticBeamColumn/TclElasticBeamCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/fourNodeQuad/TclFourNodeQuadCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/brick/TclTwenty_Node_BrickCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/brick/TclBrickCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/feap/TclFeapElementCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/beamWithHinges/TclBeamWithHingesBuilder.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/frictionBearing/frictionModel/TclModelBuilderFrictionModelCommand.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/element/PFEMElement/TclModelBuilder_addPFEMElement.o'
clang: error: no such file or directory: '/Users/gferman/OpenSees/SRC/api/elementAPI_TCL.o'
clang: error: no such file or directory: '/Users/gferman/lib/libOpenSees.a'
clang: error: no such file or directory: '/Users/gferman/lib/libArpack.a'
clang: error: no such file or directory: '/Users/gferman/lib/libSuperLU.a'
clang: error: no such file or directory: '/Users/gferman/lib/libUmfpack.a'
clang: error: no such file or directory: '/Users/gferman/lib/libAMD.a'
clang: error: no such file or directory: '/Users/gferman/lib/libItpack.a'
clang: error: no such file or directory: '/Users/gferman/lib/libLapack.a'
clang: error: no such file or directory: '/Users/gferman/lib/libCSparse.a'
clang: error: no such file or directory: '/Users/gferman/lib/libBlas.a'
clang: error: no such file or directory: '/Users/gferman/lib/libCBlas.a'
clang: error: no such file or directory: '/usr/local/lib/libgfortran.a'`

I used Makefile.def.MacOS10.8 as a template, and made the modifications described above. Attached you can find the terminal output for reference. 
[terminal-output.txt](https://github.com/OpenSees/OpenSees/files/3860378/terminal-output.txt)

Thanks,

-Gaston

**Comment by gferman** [comment]
Unfortunately, I was not able to solve this issue. Now I'm working on the latest release of MacOS, so I do not longer need to fix this problem. Thanks anyway!

**Comment by Omar-A-M** [comment]
Hey @gferman, I am trying now to compile opensees on MacOS Sonoma and I am facing a lot of errors can you please share your experience? And if there is steps to follow?

**Comment by gferman** [comment]
Hey @Omar-A-M. Unfortunately, I didn't continue working on this topic since I used pre-compiled versions of OpenSees, particularly OpenSeesPy.
