### ISSUE TITLE
create LimitState material 

### ISSUE THREAD

**Issue by Alaaldeen14** [OpenSees/OpenSees#174]
Hi 

I successfully created my own uniaxial materials in Opensees by modifying some of the original materials. 
Now, I am trying to modify the Limit state material. I created the DLL file and when I run I get a message that The modified limit state material did not find the limit curve. 
The function " theCurve = OPS_getLimitCurve(curveData[0]) " seems not to be working.  this function is in  LimitCurve class.

I did not make any modifications to the materials yet, I only tried to create a DLL file with changing the name of the material.  Can you please advise me?

**Comment by benjaminsoraghi** [comment]
@Alaaldeen14 Sorry I don't know the answer to your question, but could you please tell me what kind of material you developed?

**Comment by Alaaldeen14** [comment]
@benjaminsoraghi  Thanks for your reply. the behavior of my material should be controlled by the force and deformation of a different element. Like the limit state materials in Opensess.
