### ISSUE TITLE
Modal damping

### ISSUE THREAD

**Issue by JoseBaena** [OpenSees/OpenSees#178]
Dear OpenSEES team,

I have read in some documents that modal damping model is already available in openSEES,  but I have been looking for it for days in internet and I can not find the line of code or an example to use it. It doesn't appear in the wiki page of OpenSEES. Would you mind to share with me more information about how to use it in OpenSEES
(the modal damping model was developed by Wilson and Penzien, and it also appears in a recent research of Chopra and McKenna, 2015).

Many thanks, 

Jose Fdo Baena

**Comment by mhscott** [comment]
Hello Jose,
It's a couple lines of code.  See the comments section of this post: https://wp.me/pbejzW-3
Then read this post: https://wp.me/pbejzW-1T
Michael

**Comment by JoseBaena** [comment]
Dear Michael,

Thank you so much for your reply! I am having problems to find information about modal damping on OpenSees, although I have recently studied many papers where this approach has been used and compared. I would like to do the same for a couple of structures I am analysing.

However, I still did not find the command to code it in TCL, do you know how to do it, by chance? Thanks again, and also for your contributions to earthquake engineering simulation.

Best, Jose

**Comment by mhscott** [comment]
Jose,
I added a Tcl script for modal damping at the bottom of this post

https://wp.me/pbejzW-3

Let me know if you have any questions.
Michael

**Comment by JoseBaena** [comment]
Hello Michael,

This is extremely useful for me, many thanks!

Jose
