### ISSUE TITLE
not getting output

### ISSUE THREAD

**Issue by ksonauce** [OpenSees/OpenSees#181]
I am very new to OpenSees. When I run my model I get the following message in the dialog box and I am not getting any output when I load the results.
![image](https://user-images.githubusercontent.com/6945211/69902107-06729600-1347-11ea-8370-bbd6493a72d2.png)

**Comment by barischrooneyj** [comment]
You're going to have to share the model file, at least relating to those lines:)

**Comment by zgz115** [comment]
how to solve it?I encountered the same problem.

**Comment by strings4rings** [comment]
Get the tcltk files downloaded and extracted from the following website;

http://www.tcl.tk/software/tcltk/download.html (I used tcl8610-src.zip)
Paste the extracted files at the location where it is saying not found in the error message ( I mean C:/.......)

Done..!
