### ISSUE TITLE
Issue on compiling OpenSeesSP on Ubuntu

### ISSUE THREAD

**Issue by jf-huang** [OpenSees/OpenSees#183]
Hi everyone,

I have downloaded the latest source code from Github and tried to compile OpenSeesSP on Ubuntu. Right now, I have finished compiling the **requisite packages including tcl8.6, BLAS-3.8.0, lapack-3.9.0, scalapack-2.1.0, mpich2-1.5rc3, metis-5.1.0, parmetis-4.0.3, scotch-6.0.9, petsc-2.2.1, MUMPS-5.1.2**. Besides, I have also modified the Makefile.def of OpenSees according to the install location of the packages on my computer and set PROGRAMMING_MODE to PARALLEL in order to compile OpenSeesSP. However, I have run into some compilation errors that I could not resolve. Specifically, the errors are as follows:

**Try1. When set HAVEPETSC = YES in the Makefile.def**:
PetscSOE.cpp: In member function ‘virtual int PetscSOE::setSize(Graph&)’:
PetscSOE.cpp:252:42: error: invalid conversion from ‘_p_Mat**’ to ‘PetscInt {aka int}’ [-fpermissive]
       ierr = MatCreate(PETSC_COMM_WORLD, &A); CHKERRQ(ierr);
PetscSOE.cpp:252:44: error: too few arguments to function ‘PetscErrorCode MatCreate(MPI_Comm, PetscInt, PetscInt, PetscInt, PetscInt, _p_Mat**)’
       ierr = MatCreate(PETSC_COMM_WORLD, &A); CHKERRQ(ierr);    
c++: error: /home/jfhuang/lib/libOpenSees.a: No such file or directory
c++: error: /home/jfhuang/OpenSees/SRC/system_of_eqn/linearSOE/petsc/PetscSOE.o: No such file or directory
c++: error: /home/jfhuang/OpenSees/SRC/system_of_eqn/linearSOE/petsc/PetscSolver.o: No such file or directory
c++: error: /home/jfhuang/OpenSees/SRC/system_of_eqn/linearSOE/petsc/PetscSparseSeqSolver.o: No such file or directory
Makefile:35: recipe for target 'tcl' failed
make[1]: *** [tcl] Error 1
make[1]: Leaving directory '/home/jfhuang/OpenSees/SRC/modelbuilder/tcl'
Makefile:45: recipe for target 'all' failed
make: *** [all] Error 2

**Try2. When set HAVEPETSC = NO in the Makefile.def**:  
/usr/bin/ld: cannot find -lpesslsmp
/usr/bin/ld: cannot find -lblacssmp
/usr/bin/ld: cannot find -lg2c
collect2: error: ld returned 1 exit status
Makefile:35: recipe for target 'tcl' failed
make[1]: *** [tcl] Error 1
make[1]: Leaving directory '/home/jfhuang/OpenSees/SRC/modelbuilder/tcl'
Makefile:45: recipe for target 'all' failed
make: *** [all] Error 2

The errors from Try1 seem to relate to the incompatible interface between OpenSees and the petsc package I installed. I have tried to use the latest version of  petsc, but it still didn't work. The errors from Try2 seem to indicate that I still have some libraries missing but I am not sure which to install. I am new to compilation of OpenSees and Ubuntu so there are probably some points I have missed during the process.  I have attached the Makefile.def I used for your kind reference. 
[Makefile.txt](https://github.com/OpenSees/OpenSees/files/3948587/Makefile.txt)

**Any input on this will be greatly appreciated!**

Regards,
Junfei

**Comment by vijaypolimeru** [comment]
Go thorugh the following steps provided in the [Link](https://www.researchgate.net/post/How_to_install_opensees_in_UBUNTU) by Mr. Farbood Panahi. It worked for me

**Comment by jf-huang** [comment]
Thank you Vijay! I have also referred to this page and it has helped me compile the sequential version. However, when I tried to compile OpenSeesaSP, these errors showed up. It turned out that I still have to change the MACHINE_SPECIFIC_LIBS  in Makefile.def of OpenSees and copy some required dependent libs to the target directory. Now it works well!
