### ISSUE TITLE
eigen -fullGenLapack does not return mass orthonormal eigenvectors

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#184]
The eigen command with the -fullGenLapack option does return eigenvectors that are scaled to be mass orthonormal.

**Comment by mhscott** [comment]
Paging @fmckenna

**Comment by mhscott** [comment]
@fmckenna, do you want me to fix it?

**Comment by sewkokot** [comment]
@fmckenna, @mhscott, I noticed that indeed there is a difference in the normalization of eigenvectors obtained from 'eigen -SOLVER'. For example, for a 3-dof system I get the following eigenvectors (first column - first mode shape, etc.):

using '-genBandArpack':
```
[[ 0.106 -0.076]
 [ 0.13  -0.158]
 [ 0.135  0.121]]
```

and using '-fullGenLapack':
```
[[ 0.786  0.479]
 [ 0.964  1.   ]
 [ 1.    -0.768]]
```

So the '-fullGenLapack' solver normalizes the maximum absolute value in an eigenvector to 1.0.

The corresponding stiffness and mass matrices are as follows:
```
K:
[[ 45000. -20000. -15000.]
 [-20000.  45000. -25000.]
 [-15000. -25000.  40000.]]
```
```
M:
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
```

By the way, in a parametric study, calculating the eigenvalue problem of a cantilever beam (27 dofs) x 1000 times, I got that '-fullGenLapack' solver took 4.5 seconds to complete the task while surprisingly the '-genBandArpack' one took 14.2 seconds. I thought that the default '-genBandArpack' is faster, but it can depend on the number of degrees of freedom and the number of times the eigen command is repeated.

**Comment by mhscott** [comment]
Thanks for the information @sewkokot!  I'll remind @fmckenna about this when our weekly PR meetings resume in January.  Do you have any large models available where you can compare fullGenLapack and genBandArpack times?

**Comment by sewkokot** [comment]
@mhscott, A quick test on a 800-dof quad model shows that 'eigen -genBandArpack' takes 0.1s, and 'eigen -fullGenLapack' 4.5s. So in this case the default solver is faster.

I'll do more performance tests after the Christmas holidays. Merry Christmas :)

**Comment by mhscott** [comment]
@sewkokot Thanks for checking that!  Don't worry about doing more tests, I just wanted to see which was faster for one eigenvalue analysis on a larger model.  Have a good Christmas holiday!

**Comment by sa-jalali** [comment]
@mhscott
please add this issue to the problems of the eigenSolver :
The tag numbers assigned to the nodes dramatically affect the analysis time when using the default solver.
For example when we have three nodes and assign 10001, 10002 and 10003 to them, the analysis takes around 5 times longer than when we use 1, 2 and 3 as the tags.

Thanks

**Comment by mhscott** [comment]
@sa-jalali Is this for small three DOF models, or does the issue scale up to larger systems?

**Comment by sa-jalali** [comment]
@mhscott 
Yes, the problem scales up with increase of the model size.
What we have checked is a 3-d multi-story frame model with masses lumped at the story master nodes to which other story nodes are constrained using RigidDiaphragm.
So, the number of nodes in the model and the number of stiffness DOf's are medium to large, but the number of mass DOf's are around 10-50.

**Comment by p-ranchal** [comment]
> @mhscott, A quick test on a 800-dof quad model shows that 'eigen -genBandArpack' takes 0.1s, and 'eigen -fullGenLapack' 4.5s. So in this case the default solver is faster.
> 
> I'll do more performance tests after the Christmas holidays. Merry Christmas :)

Confirming this using a 1000 DOF, 3D 4-story steel moment frame model including floors modeled using shell elements. 
`-genBandArpack` option is almost instantaneous but `-fullGenLapack` takes on the order of 18 seconds.

**Comment by johnnyontheweb** [comment]
Other errors for me, with the current version of repo I'm getting this:
```
OpenSees > system ProfileSPD
OpenSees > eigen 3
forrtl: severe (408): fort: (19): Dummy character variable 'WHICH' has length 2 which is greater than actual variable length -3689348814741910324
```
Call stack reports dsaupd.f at line 517 (see https://github.com/opencollab/arpack-ng/blob/master/SRC/dsaupd.f )
It's a frame model with 635 nodes and 765 elements, unfortunately I cannot share because it's made with custom elements - I'll try to build a shareable model. Smaller models work fine.
With `-fullGenLapack` option, the solver stucks into \SRC\system_of_eqn\eigenSOE\FullGenEigenSolver.cpp, line 168, in calling DGGEV.

**Comment by mhscott** [comment]
Thank, please let us know if you can reproduce the error with standard elements.

**Comment by johnnyontheweb** [comment]
Please find attached the file (more elements than previously told). I notice the error as told earlier just launching debug.
```
         OpenSees -- Open System For Earthquake Engineering Simulation
                 Pacific Earthquake Engineering Research Center
                        Version 3.3.0 64-Bit

      (c) Copyright 1999-2016 The Regents of the University of California
                              All Rights Reserved
  (Copyright and Disclaimer @ http://www.berkeley.edu/OpenSees/copyright.html)


forrtl: severe (408): fort: (19): Dummy character variable 'WHICH' has length 2 which is greater than actual variable length -3689348814741910324

Image              PC                Routine            Line        Source
OpenSees.exe       00000001400A078D  Unknown               Unknown  Unknown
OpenSees.exe       00000001400012D1  DSAUPD                    516  dsaupd.f
OpenSees.exe       00000001416EBEB8  Unknown               Unknown  Unknown
OpenSees.exe       00000001416EB289  Unknown               Unknown  Unknown
OpenSees.exe       0000000140300844  Unknown               Unknown  Unknown
OpenSees.exe       00000001401E6D18  Unknown               Unknown  Unknown
tcl86t.dll         00007FFC0FAE62E8  Unknown               Unknown  Unknown
tcl86t.dll         00007FFC0FAE8373  Unknown               Unknown  Unknown
tcl86t.dll         00007FFC0FAE9B3D  Unknown               Unknown  Unknown
tcl86t.dll         00007FFC0FB88313  Unknown               Unknown  Unknown
tcl86t.dll         00007FFC0FB863AE  Unknown               Unknown  Unknown
OpenSees.exe       00000001401D6DFE  Unknown               Unknown  Unknown
OpenSees.exe       00000001401D68D1  Unknown               Unknown  Unknown
OpenSees.exe       00000001416FAD24  Unknown               Unknown  Unknown
OpenSees.exe       00000001416FAC37  Unknown               Unknown  Unknown
OpenSees.exe       00000001416FAAFE  Unknown               Unknown  Unknown
OpenSees.exe       00000001416FAD39  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFC4FDD7034  Unknown               Unknown  Unknown
ntdll.dll          00007FFC51D42651  Unknown               Unknown  Unknown
```
[RCbuilding_fiberEigen-modal.zip](https://github.com/OpenSees/OpenSees/files/6082440/RCbuilding_fiberEigen-modal.zip)

**Comment by johnnyontheweb** [comment]
I noticed that there were errors in material settings, that must always account for tension response (eg concrete 01 does not).
Anyway, I'm still wondering why I get that error during debug (memory issues from C to Fortran function?), but I'm principally worried about the different results reported in this issue, rather than performance. Thanks

**Comment by mhscott** [comment]
Closing. Please start new issues if any errors persist.
https://github.com/OpenSees/OpenSees/commit/5ab9f277b2b50b327fbb8d8e6b958517422cdb7c

**Comment by Yahya-bit** [comment]
hello every one 
i have large model and i have problem with the eigenvalue analysis more than 5 hours and not finish

**Comment by mhscott** [comment]
Bringing this to everyone's attention re slow compute times for fullGenLapack
https://github.com/OpenSees/OpenSees/issues/804

**Comment by mhscott** [comment]
> Other errors for me, with the current version of repo I'm getting this:
> 
> ```
> OpenSees > system ProfileSPD
> OpenSees > eigen 3
> forrtl: severe (408): fort: (19): Dummy character variable 'WHICH' has length 2 which is greater than actual variable length -3689348814741910324
> ```
> 
> Call stack reports dsaupd.f at line 517 (see https://github.com/opencollab/arpack-ng/blob/master/SRC/dsaupd.f ) It's a frame model with 635 nodes and 765 elements, unfortunately I cannot share because it's made with custom elements - I'll try to build a shareable model. Smaller models work fine. With `-fullGenLapack` option, the solver stucks into \SRC\system_of_eqn\eigenSOE\FullGenEigenSolver.cpp, line 168, in calling DGGEV.

Can you remove 'static' from your local compiled version then see if the issue goes away?
https://github.com/OpenSees/OpenSees/blob/master/SRC/system_of_eqn/eigenSOE/ArpackSolver.cpp#L192

**Comment by johnnyontheweb** [comment]
@mhscott 
Usually I collect all Fortran libs from the local installation of Fortran compiler, but to try to solve the error posted here #771 by using the libs you collected [here](https://www.dropbox.com/sh/ko0fuigt4e68vcf/AADjLbW5255iSp6dzGauUXVea?dl=0)
After a clean compilation the issue does not appear anymore (I don't know why - different version of the libs?) and everything reverted to work properly.

**Comment by mhscott** [comment]
Alright, thanks for checking. Start a new issue if the problem reappears
