### ISSUE TITLE
"section Fiber" doesn't work for "-ndm 3 -ndf 6" in OpenSees 3.1.0

### ISSUE THREAD

**Issue by StephenLuby** [OpenSees/OpenSees#186]
Hi, everyone! 
I could not run my model built by an earlier version and I found that there might be some bugs about the command "section Fiber" in OpenSees3.1.0. Here is the simplified code. The answer should be "============================", but it has no output and does not report any error.

`model BasicBuilder -ndm 3 -ndf 6`
`set C35confined 1`
`uniaxialMaterial Concrete01 $C35confined -38.04e3 -3.0e-3 -26.0e3 -1.0e-2`
`set Rec 1`
`section Fiber $Rec  {`
`patch rect $C35confined     13      4  -0.930000  -2.680000   0.930000   2.680000`
`}`
`puts "============================"`

But it works if I change the first line to 

`model BasicBuilder -ndm 2 -ndf 3`

I hope I have clarified the issue.

**Comment by sa-jalali** [comment]
Hi.
In new version you have to explicitely determine the $GJ value after the $secTag argument. The default GJ value is not further used perhaps because of its dependance on model's system of units.

**Comment by mhscott** [comment]
It might be related to a recent change in the input for 3D fiber sections:

https://wp.me/pbejzW-9X

**Comment by StephenLuby** [comment]
Thanks for your help!
