### ISSUE TITLE
Fortran DLL compilation error

### ISSUE THREAD

**Issue by erikemondt** [OpenSees/OpenSees#196]
Hi everyone,

I am trying to compile an externally provided material in OpenSees. This material has been written in Fortran, and it's preferred to keep it that way.  In order compile it to the dll, first I need to compile the material example provided here https://github.com/OpenSees/OpenSees/tree/master/DEVELOPER/material/fortran
Then i can implement the new material based on an existing (and working) file.  

Thing is, the source code provided does not seem to be working. As I am new to both Fortran and compiling the issue may be easily solved. I suspect, that after solving this error, it will compile without problems. I am experiencing the same error as described here https://github.com/OpenSees/OpenSees/issues/65 but here the issue was not solved.

What i did in order to compile:
	1) Downloaded the latest version of the source code of OpenSees
	2) Created a new DLL Project in visual studio 2015 for fortran
	3) Added 3 fortran files from (https://github.com/OpenSees/OpenSees/tree/master/DEVELOPER/material/fortran) to the source files
	4) Also added all lib files from /Win64/lib/debug to the source files

It gives the following errors:
error LNK2019: unresolved external symbol OPS_GETINTINPUT referenced in function ELASTICPPF   (file:elasticPPf.obj)
error LNK2019: unresolved external symbol OPS_GETDOUBLEINPUT referenced in function ELASTICPPF	(file:elasticPPf.obj)	
error LNK2019: unresolved external symbol OPS_ALLOCATEMATERIAL referenced in function ELASTICPPF   (file:elasticPPf.obj)	
error LNK2019: unresolved external symbol OPS_ERROR referenced in function LOCALINIT  (file:elasticPPf.obj)	
fatal error LNK1120: 4 unresolved externals   (file:x64\Debug\ElasticPPf.dll)

It appears to compile the .obj files successfully, but fails to link them. I suspect additional .obj or .lib files are required, or that i should add additional linker directories. I already tried adding the ...\core directory to the additional include directories (properties>Fortran>General) but it does not help.

I am not sure how to proceed from here, so I hope someone can help. Thanks in advance.

**Comment by ahartloper** [comment]
Have you looked at the documentation here for .dll's: https://opensees.berkeley.edu/AddingYourCode.pdf ? These steps have worked for me in the past.

**Comment by erikemondt** [comment]
I did follow the steps as described there. Adding the \core folder to Additional Include directories, and its files to the source files does not make a difference however. I figured I do not need these two steps for compiling Fortran, is that correct?
Would you recommend writing the adapter in C++, instead of having everything in Fortran? If so, why? I have no experience in both languages and I'm open to learning both.

**Comment by ahartloper** [comment]
Hmm not sure about the error you are running into. Possibly the symbols for OPS_GETINTINPUT etc., need to be provided, and not just defined as externals through INTERFACE.

I would recommend using C++, imo the main benefit of using C++ is that the steps for creating a new material are well established.

**Comment by mhscott** [comment]
Closing. Re-open if it's still an issue.
