### ISSUE TITLE
"Segmentation fault: 11" in macOS Catalina

### ISSUE THREAD

**Issue by mtsonicc** [OpenSees/OpenSees#197]
Hello,

I'm experiencing a problem while using Joint2D in macOS Catalina.

Joint2D element requires input parameters as shown below: 
`element Joint2D $eleTag $Nd1 $Nd2 $Nd3 $Nd4 $NdC <$Mat1 $Mat2 $Mat3 $Mat4> $MatC $LrgDspTag`

If I set "$Mat1 $Mat2 $Mat3 $Mat4" to zero, OpenSees returns "segmentation fault: 11" in macOS Catalina.

an example line is shown below:
`element Joint2D 10100 10101 10102 10103 10104 10100 10101 10102 0 10104 10100 0;`

The exact same code works fine in Windows 10 (version 1903).

If I don't use zeros in "<$Mat1 $Mat2 $Mat3 $Mat4>", "segmentation fault: 11" does not happen.

example code is provided below::
[test_Joint2D.tcl.zip](https://github.com/OpenSees/OpenSees/files/4058615/test_Joint2D.tcl.zip)

Thank you for your help!

**Comment by mtsonicc** [comment]
I think the error is caused by Line 253 in "TclJoint2dCommand.cpp".

[Line 253]::
```
    theJoint2D = new Joint2D( Joint2DId,
			      iNode,jNode,kNode,lNode,CenterNodeTag,
			      *MatI,*MatJ,*MatK,*MatL,*PanelMaterial,
			      theTclDomain,
			      LargeDisp);
```


if zero value is used as input of MatI, MatI becomes NULL.
example lines are shown below, when zero value input is used:
```
if ( MatI == NULL )
	    {
	      opserr << "WARNING material not found\n";
	      opserr << "Material: " << MatIid;
	      opserr << "\nJoint2D element: " << Joint2DId << endln;
	      return TCL_ERROR;
	    }
	} else MatI = NULL;
```

**Comment by ahartloper** [comment]
You can check explicitly by compiling OpenSees in debug mode and then using visual studio to find what causes the segfault. Maybe here is a good link to get started: https://stackoverflow.com/questions/15097610/debugging-an-executable-in-visual-studio/15100480.

**Comment by mtsonicc** [comment]
Thanks for reply.

Windows version of OpenSees works fine.

The problem occurs in macOS version of OpenSees.
Either publicly distributed OpenSees for macOS (which can be downloaded from https://opensees.berkeley.edu/OpenSees/user/download.php) and compiled version of OpenSees crash when "element Joint2D" command with zero material tag is used.
I don't understand why this is happening...

**Comment by mtsonicc** [comment]
> You can check explicitly by compiling OpenSees in debug mode and then using visual studio to find what causes the segfault. Maybe here is a good link to get started: https://stackoverflow.com/questions/15097610/debugging-an-executable-in-visual-studio/15100480.

Thanks for reply.
Windows version of OpenSees works fine.

The problem occurs in macOS version of OpenSees.
Either publicly distributed OpenSees for macOS (which can be downloaded from https://opensees.berkeley.edu/OpenSees/user/download.php) and compiled version of OpenSees crash when "element Joint2D" command with zero material tag is used.
I don't understand why this is happening...

**Comment by ahartloper** [comment]
Ah OK, you could checkout gdb or maybe xcode has some tools. Otherwise you can isolate the line with "print" debugging ;)

**Comment by mtsonicc** [comment]
> 
> 
> Ah OK, you could checkout gdb or maybe xcode has some tools. Otherwise you can isolate the line with "print" debugging ;)

Thank yo for your reply. I haven't try debugging C++. Is gdb some sort of debugging tool for Makefile? 

Line 253 in "TclJoint2dCommand.cpp" is clearly the one causing segmentation fault error in macOS version of OpenSees. If I put print "aaaaa" and "bbbbb" before and after Line 253, respectively, 
```
opserr << "aaaaa\n" << endln;
    theJoint2D = new Joint2D( Joint2DId,
			      iNode,jNode,kNode,lNode,CenterNodeTag,
			      *MatI,*MatJ,*MatK,*MatL,*PanelMaterial,
			      theTclDomain,
			      LargeDisp);
opserr << "bbbb\n" << endln;
```

This is what I get.
```
aaaaa
segmentation fault: 11
```
I think I would have to understand what gdb is...
thanks for your help, though.

**Comment by ahartloper** [comment]
OK I believe I understand the bug now. As you say MatI is assigned as a null pointer, then when the constructor is called 
```
 theJoint2D = new Joint2D( Joint2DId,
			      iNode,jNode,kNode,lNode,CenterNodeTag,
			      *MatI,*MatJ,*MatK,*MatL,*PanelMaterial,
			      theTclDomain,
			      LargeDisp);
```
the pointer MatI is deferenced, causing undefined behavior. Not sure why it doesn't crash when compiled in visual studio.

Possibly an easy fix is to re-write the constructor with the material integer tags as arguments instead of the pointer to the materials. Then get the material from inside the constructor using `OPS_getUniaxialMaterial(matID)`.

**Comment by mtsonicc** [comment]
Thank you very much for your help.
As I understand, you are suggesting that I would have to change "MatI = NULL" in the following code ( part of "TclJoint2dCommand.cpp") to something other than NULL.

```
if ( MatI == NULL )
	    {
	      opserr << "WARNING material not found\n";
	      opserr << "Material: " << MatIid;
	      opserr << "\nJoint2D element: " << Joint2DId << endln;
	      return TCL_ERROR;
	    }
	} else MatI = NULL;
```

I'll try to re-write "TclJoint2dCommand.cpp" as you have suggested.

thanks again for your help.

**Comment by ahartloper** [comment]
I suggest re-writing `Joint2D::Joint2D( ... )` to take the `integer` tags instead of `UniaxialMaterials`. Then get the materials from within `Joint2D::Joint2D` instead using `OPS_getUniaxialMaterial`.

Thinking again, maybe an easier fix is just to pass the pointer and not dereference. Then check if the pointers are null in `Joint2D::Joint2D`.

**Comment by mtsonicc** [comment]
ok.. it looks like things are getting a little bit more complicated than I thought. I'll do my best to resolve this problem as you suggested. But first of all, I would have to understand what constructor, destructor, pointer and deference are... because I know very little about C++ language.

Do you mind if I ask you one more question? Why is early part of "Joint2D.cpp" is very similar to those written in "TclJoint2dCommand.cpp"? For example, line 53 to 541 of "Joint2D.cpp":
```
void* OPS_Joint2D()
{
    Domain* theDomain = OPS_GetDomain();
    if (theDomain == 0) return 0;
... (omitted) ...
	if ( numdata == 8  )
	{
	    int PanelMatId;
	    num = 1;
	    if (OPS_GetIntInput(&num, &PanelMatId) < 0) {
		opserr << "WARNING invalid matID\n";
		opserr << "Joint2D element: " << Joint2DId << endln;
		return 0;
	    }
... (omitted) ...
```
The lines I pasted above in "Joint2D.cpp" is nearly identical to those in "TclJoint2dCommand.cpp". As I understand, these lines in "Joint2D.cpp" have no effect on OpenSees. I tried adding some lines for debugging purpose, such as, 
`opserr << "aaaaa\n" << endln;`
but OpenSees printed nothing. (modifications made after line 541 of "Joint2D.cpp" had effect.)
However, modifying similar lines in "TclJoint2dCommand.cpp" affected OpenSees.

I'm very much appreciated for your kind instructions.

**Comment by ahartloper** [comment]
Typically functions starting with `OPS_` are called by the interpreter, for example in your .tcl file when you write
```
element Joint2D ...
```
TCL would typically use the function `OPS_Joint2D`. However, in this case, the `TclModelBuilder_addJoint2D` function is called instead (I'm not sure why in this case, but let's live with it for now).

I would start by fixing the `TclModelBuilder_addJoint2D` function and the `Joint2D::Joint2D` constructor. I would comment out the entire `OPS_Joint2D` function and forget about it for now. It can probably be removed later to cut down on redundant code.

**Comment by mtsonicc** [comment]
I really appreciate your kind explanations.
I would post here again if I have any progress.
Thank you.

**Comment by ahartloper** [comment]
No problem, you can post here if you have any other questions.

**Comment by ahartloper** [comment]
@mtsonicc were you able to work out this issue?

**Comment by mtsonicc** [comment]
@ahartloper hi. I appreciate for your attention. Unfortunately, I couldn't solve this problem yet. I recently bought a book for c++ and I'm trying to understand about pointer, destructor, deference, NULL, etc.
I think it is going to take a little bit longer than I have expected...

**Comment by mtsonicc** [comment]
I think I found a temporal solution to this problem.
I have modified the following lines in `Joint2D.cpp` starting from line 671.

```
  // make copy of the uniaxial materials for the element
UniaxialMaterial * ww = NULL;printf("&ww = %p\n",&ww);
  if ( &spring1 == ww ) { fixedEnd[0] = 1;  theSprings[0] = NULL; } else { fixedEnd[0] = 0; theSprings[0] = spring1.getCopy(); }
  if ( &spring2 == ww ) { fixedEnd[1] = 1;  theSprings[1] = NULL; } else { fixedEnd[1] = 0; theSprings[1] = spring2.getCopy(); }
  if ( &spring3 == ww ) { fixedEnd[2] = 1;  theSprings[2] = NULL; } else { fixedEnd[2] = 0; theSprings[2] = spring3.getCopy(); }
  if ( &spring4 == ww ) { fixedEnd[3] = 1;  theSprings[3] = NULL; } else { fixedEnd[3] = 0; theSprings[3] = spring4.getCopy(); }
  if ( &springC == ww ) { opserr << "ERROR Joint2D::Joint2D(): The central node does not exist "; exit(-1); } else { fixedEnd[4] = 0; theSprings[4] = springC.getCopy(); }
```

These modifications solves the problem.
It should be noted that `printf("&ww = %p\n",&ww);` is necessary.
without `printf("&ww = %p\n",&ww);`, segfault error occurs.
I think this is related to memory allocation in macOS.

I will post again if i find a better solution.

**Comment by ahartloper** [comment]
OK I'll take a look at it later this week, there must be undefined behavior still given what you say about the print statement.

**Comment by mtsonicc** [comment]
@ahartloper 
Thank you very much for your help! I'll post again if I make any progression.

**Comment by ahartloper** [comment]
@mtsonicc Can you double check that I fixed the issue? I pushed the changes to my fork under the `fix_joint2d` branch.

https://github.com/ahartloper/OpenSees/tree/fix_joint2d

**Comment by mtsonicc** [comment]
@ahartloper Thank you very much for your help.
The segmentation fault error is no longer happening.
I truly appreciate for your help.
