### ISSUE TITLE
Update request of Makefile.def for macOS Catalina

### ISSUE THREAD

**Issue by mtsonicc** [OpenSees/OpenSees#198]
Hello,

A few days ago, I posted this in OpenSees BBS.
https://opensees.berkeley.edu/community/viewtopic.php?f=2&t=66484

And after a few hours of struggle, I finally managed to compile OpenSees in macOS Catalina.
Here is my "Makefile.def" used for compiling OpenSees.
[Makefile.def.zip](https://github.com/OpenSees/OpenSees/files/4058625/Makefile.def.zip)

In the file, "-D_HTTPS" flag has been removed due to following problem:
`#"HTTP.cpp:965:39: error: use of undeclared identifier 'SSLv2_client_method'; did you mean 'SSLv23_client_method'?"`
I reckon HTTP.cpp is somewhat related to "-tcp" flag in Node Recorder command.
`recorder Node <-file $fileName> <-xml $fileName> <-binary $fileName> <-tcp $inetAddress $port> <-precision $nSD> <-timeSeries $tsTag> <-time> <-dT $deltaT> <-closeOnWrite> <-node $node1 $node2 ...> <-nodeRange $startNode $endNode> <-region $regionTag> -dof ($dof1 $dof2 ...) $respType'`

There was also another example of similar problem:
https://opensees.berkeley.edu/community/viewtopic.php?f=4&t=62945&p=105080&hilit=sslv2#p105080

**Comment by gferman** [comment]
Thanks @mtsonicc , I have the same issue as you do. Would be wonderful if we can fix this issue and allow macOS users to build OpenSees from source.

**Comment by fmckenna** [comment]
we have migrated to cmake
https://opensees.github.io/OpenSeesDocumentation/developer/build.html
