### ISSUE TITLE
opensees.so import error after compiling

### ISSUE THREAD

**Issue by u-anurag** [OpenSees/OpenSees#203]
I compiled OpenSees on WSL Ubuntu 18 without any errors. It created OpenSees (Tcl) in the "bin" folder and opensees.so in "OpenSees/SRC/interpreter" folder. The Makefile.def.EC2-UBUNTU says that it should create opensees.so in "bin" folder but that is not the case. When I tried to import opensees.so in python, I got the following error. Did I miss something?

![image](https://user-images.githubusercontent.com/35711550/73006017-26fb2180-3dc7-11ea-9b69-df3a6c85acc3.png)

**Comment by mhscott** [comment]
Hello Anurag,

Do you have RELIABILITY defined in OpenSees/Makefile.def?

RELIABILITY = YES_RELIABILITY

Michael

**Comment by u-anurag** [comment]
RELIABILITY = NO_RELIABILITY

**Comment by mhscott** [comment]
Anurag,

OK, set it to YES_RELIABILITY, then ‘make wipe’ and ‘make’.  Let me know if you still have problems with it.

Michael

**Comment by u-anurag** [comment]
I did:
- RELIABILITY = YES_RELIABILITY
- make wipe && make
- cd SRC/interpreter && make
(got opensees.so in this folder)
Tried "import opensees" in python and still got the same error.

**Comment by zhuminjie** [comment]
The error shows that there was an error in compiling. Although opensees.so is still created, some functions are missing because they were not created in the compiling. Check your compiling outputs to see which files failed.

**Comment by u-anurag** [comment]
You are right Minjie. It did not compile files OpenSeesCommandsPython.o, OpenSeesCommandsTcl.o, PythonAnalysisBuilder.o, PythonInterpreter.o, PythonModelBuilder.o, TclInterpreter.o, and TclWrapper.o in the folder SRC/interpreter. I found some warnings of unknown target,

make[1]: Entering directory '/home/anurag/OpenSees/OTHER/SuperLU_5.1.1/SRC'
Makefile:133: warning: overriding recipe for target '.c.o'

make[3]: Entering directory '/home/anurag/OpenSees/SRC/material/uniaxial'
Unknown target KinematicHardening.o, try:  make help
Unknown target TclNewUnixialMaterial.o, try:  make help
Unknown target PenaltyMaterial.o, try:  make help
Unknown target WrappedMaterial.o, try:  make help
Unknown target SecantMaterial.o, try:  make help
Unknown target ConfinedConcrete02.o, try:  make help

make[3]: Entering directory '/home/anurag/OpenSees/SRC/element/forceBeamColumn'
Unknown target GaussQBeamIntegration.o, try:  make help
Unknown target d1mach.o, try:  make help

Any guidance on how to figure it out?

**Comment by zhuminjie** [comment]
The warnings are not the problem. There must be a file failed to compile. Check all outputs to find "error"

**Comment by u-anurag** [comment]
No errors found. It never showed any error while compiling.  

[Compile.txt](https://github.com/OpenSees/OpenSees/files/4106149/Compile.txt)
[CompilePython.txt](https://github.com/OpenSees/OpenSees/files/4106148/CompilePython.txt)

**Comment by zhuminjie** [comment]
The file is too large. I can't open it. I have checked the missing file is in the makefile. I can't think of other reasons why it's not there. Can you run the OpenSees Tcl binary?

**Comment by u-anurag** [comment]
Yes, the compiled OpenSees Tcl binary is running just fine with my added new recorder command. Also, I guess you can download these two .txt files and open them with any text editor. I couldn't find any errors in the compilation output.

**Comment by zhuminjie** [comment]
Did you solve it?

**Comment by u-anurag** [comment]
No. I could not solve it. I'll close the issue for now.

**Comment by ccaprani** [comment]
@u-anurag I'd like to re-open this issue as I also have it, and have done extensive work to try track down the culprit to no avail. It initiated as https://github.com/zhuminjie/OpenSeesPy/issues/69 but it's more appropriate here.

It appears regardless of whether `RELIABILITY` is compiled with either `YES_RELIABILITY` or `NO_RELIABILITY`.  It is similar to [this SO question](https://stackoverflow.com/questions/11643666/python-importerror-undefined-symbol-for-custom-c-module) suggesting the order offered to the linker is not right, or some other `#include` problem.

Using `nm -u /path/to/opensees.so`,  the undefined symbols in the `opensees.so` file all seem to stem from `TclReliabilityBuilder.o`:

```bash
                 U _ZN10RayleighRVC1EiRK6Vector
                 U _ZN11ChiSquareRVC1Eidd
                 U _ZN11ChiSquareRVC1EiRK6Vector
                 U _ZN11LognormalRVC1Eidd
                 U _ZN11LognormalRVC1EiRK6Vector
                 U _ZN13ExponentialRVC1Eidd
                 U _ZN13ExponentialRVC1EiRK6Vector
                 U _ZN17ReliabilityDomain18getRandomVariablesEv
                 U _ZN17ReliabilityDomain20getRandomVariablePtrEi
                 U _ZN17ReliabilityDomain22getRandomVariableIndexEi
                 U _ZN17ReliabilityDomain26getNumberOfRandomVariablesEv
                 U _ZN17ReliabilityDomain34getNumberOfCorrelationCoefficientsEv
                 U _ZN17ReliabilityDomain8clearAllEv
                 U _ZN17ReliabilityDomainC1EP6Domain
                 U _ZN17ShiftedRayleighRVC1Eidd
                 U _ZN17ShiftedRayleighRVC1EiRK6Vector
                 U _ZN19Type1LargestValueRVC1Eidd
                 U _ZN19Type1LargestValueRVC1EiRK6Vector
                 U _ZN19Type2LargestValueRVC1Eidd
                 U _ZN19Type2LargestValueRVC1EiRK6Vector
                 U _ZN20ShiftedExponentialRVC1Eidd
                 U _ZN20ShiftedExponentialRVC1EiRK6Vector
                 U _ZN20Type1SmallestValueRVC1Eidd
                 U _ZN20Type1SmallestValueRVC1EiRK6Vector
                 U _ZN20Type3SmallestValueRVC1EiRK6Vector
                 U _ZN22CorrelationCoefficientC1Eiiid
                 U _ZN28AllIndependentTransformationC1EP17ReliabilityDomaini
                 U _ZN30NatafProbabilityTransformationC1EP17ReliabilityDomaini
                 U _ZN6BetaRVC1EiRK6Vector
                 U _ZN7GammaRVC1Eidd
                 U _ZN7GammaRVC1EiRK6Vector
                 U _ZN8GumbelRVC1Eidd
                 U _ZN8GumbelRVC1EiRK6Vector
                 U _ZN8NormalRVC1Eidd
                 U _ZN8NormalRVC1EiRK6Vector
                 U _ZN8ParetoRVC1EiRK6Vector
                 U _ZN9LaplaceRVC1Eidd
                 U _ZN9LaplaceRVC1EiRK6Vector
                 U _ZN9UniformRVC1Eidd
                 U _ZN9UniformRVC1EiRK6Vector
                 U _ZN9WeibullRVC1Eidd
                 U _ZN9WeibullRVC1EiRK6Vector
```

 but `TclReliabilityBuilder` appears linked and built throughout. 

The only commonality is that the undefined references in `commands.cpp`, `TclSeriesCommand.cpp` and `TclParameterCommans.cpp` are all within the `#ifdef _RELIABILITY` preprocessor directives; but this is set (as confirmed by adding pp directive `#error` within the block); and even setting `#define _RELIABILITY` in the cpp files makes no difference bizarrely.

After several days on this another set of eyes is warranted. I've double checked through the includes and makefiles; and even checked git blame; but nothing obvious jumps out. Comparison with other makedefs (including carefully checking linker ordering) says it *should* work - I am beginning to think it's a bug with the latest Ubuntu toolchain.

I'm running Ubuntu 21.04 with:
- g++/gcc: gcc version 9.3.0 (crosstool-NG 1.24.0.133_b0863d8_dirty) 
- gfortran: gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1)
- ld: GNU ld (GNU Binutils) 2.35.1

For reference, the errors are below. 

```
GNU ld (GNU Binutils for Ubuntu) 2.36.1
/usr/bin/ld: /home/ccaprani/projects/opensees/OpenSees/SRC/tcl/commands.o: in function `reliability(void*, Tcl_Interp*, int, char const**)':
commands.cpp:(.text+0x1bba): undefined reference to `TclReliabilityBuilder::TclReliabilityBuilder(Domain&, Tcl_Interp*)'
/usr/bin/ld: /home/ccaprani/projects/opensees/OpenSees/SRC/tcl/commands.o: in function `wipeReliability(void*, Tcl_Interp*, int, char const**)':
commands.cpp:(.text+0x1c33): undefined reference to `TclReliabilityBuilder::~TclReliabilityBuilder()'
/usr/bin/ld: /home/ccaprani/projects/opensees/OpenSees/SRC/tcl/commands.o: in function `sensitivityAlgorithm(void*, Tcl_Interp*, int, char const**)':
commands.cpp:(.text+0x1f33): undefined reference to `TclReliabilityBuilder::getReliabilityDomain()'
/usr/bin/ld: /home/ccaprani/projects/opensees/OpenSees/SRC/tcl/commands.o: in function `removeObject(void*, Tcl_Interp*, int, char const**)':
commands.cpp:(.text+0x11934): undefined reference to `TclReliabilityBuilder::getReliabilityDomain()'
/usr/bin/ld: commands.cpp:(.text+0x11949): undefined reference to `ReliabilityDomain::removeRandomVariable(int)'
/usr/bin/ld: commands.cpp:(.text+0x119e6): undefined reference to `TclReliabilityBuilder::getReliabilityDomain()'
/usr/bin/ld: commands.cpp:(.text+0x11a01): undefined reference to `ReliabilityDomain::removeLimitStateFunction(int)'
/usr/bin/ld: commands.cpp:(.text+0x11a9e): undefined reference to `TclReliabilityBuilder::getReliabilityDomain()'
/usr/bin/ld: commands.cpp:(.text+0x11ab9): undefined reference to `ReliabilityDomain::removeCutset(int)'
/usr/bin/ld: /home/ccaprani/projects/opensees/OpenSees/SRC/domain/pattern/TclSeriesCommand.o: in function `TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*)':
TclSeriesCommand.cpp:(.text+0x1d5a): undefined reference to `theReliabilityDomain'
/usr/bin/ld: TclSeriesCommand.cpp:(.text+0x1d6d): undefined reference to `ReliabilityDomain::getModulatingFunction(int)'
/usr/bin/ld: TclSeriesCommand.cpp:(.text+0x1eba): undefined reference to `DiscretizedRandomProcessSeries::DiscretizedRandomProcessSeries(int, int, ModulatingFunction**, double, double)'
/usr/bin/ld: TclSeriesCommand.cpp:(.text+0x206e): undefined reference to `theRandomNumberGenerator'
/usr/bin/ld: TclSeriesCommand.cpp:(.text+0x20d8): undefined reference to `theReliabilityDomain'
/usr/bin/ld: TclSeriesCommand.cpp:(.text+0x20eb): undefined reference to `ReliabilityDomain::getSpectrum(int)'
/usr/bin/ld: TclSeriesCommand.cpp:(.text+0x2176): undefined reference to `theRandomNumberGenerator'
/usr/bin/ld: TclSeriesCommand.cpp:(.text+0x21a2): undefined reference to `SimulatedRandomProcessSeries::SimulatedRandomProcessSeries(int, RandomNumberGenerator*, Spectrum*, int, double)'
/usr/bin/ld: /home/ccaprani/projects/opensees/OpenSees/SRC/domain/component/TclParameterCommands.o: in function `TclModelBuilderParameterCommand(void*, Tcl_Interp*, int, char const**, Domain*, TclModelBuilder*)':
TclParameterCommands.cpp:(.text+0x72d): undefined reference to `theReliabilityDomain'
/usr/bin/ld: TclParameterCommands.cpp:(.text+0x7b5): undefined reference to `theReliabilityDomain'
/usr/bin/ld: TclParameterCommands.cpp:(.text+0x7c8): undefined reference to `ReliabilityDomain::getRandomVariablePtr(int)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:14: tcl] Error 1
make[1]: Leaving directory '/home/ccaprani/projects/opensees/OpenSees/SRC/modelbuilder/tcl'
make: *** [Makefile:51: all] Error 2
```

**Comment by u-anurag** [comment]
@ccaprani thanks for looking into it. Since the visualization commands I was trying to implement were external, I did not dig deeper into this error. I am glad you did.

**Comment by sewkokot** [comment]
@ccaprani Can you show us your Makefile.def which causes the missing functions?

**Comment by ccaprani** [comment]
Thanks @sewkokot : Yes, those library files are created in that folder; and yes, they are added in the `MACHINE_NUMERICAL_LIBS` list, and even in the order you have there too.

`Makefile.def` is attached (just remove `*.txt` extension needed for github upload) - should have done this already - thanks

[Makefile.def.txt](https://github.com/OpenSees/OpenSees/files/7293746/Makefile.def.txt)

Hopefully it is something silly and I can get on with contributing! Thanks for any help.

**Comment by ccaprani** [comment]
@mhscott @sewkokot I upgraded to 21.10 today and ran again...same problem. If you get a chance to look over the makefile, I'd really appreciate it. It's going to be something to do with the order of the libraries as passed to the linker, and how linkers `ld` > 2.35 changed something that could mean that the includes order in the makefiles that worked previously no longer work.

**Comment by fmckenna** [comment]
see build instructions on extra steps needed to get openseespy working 

https://opensees.github.io/OpenSeesDocumentation/developer/build.html

**Comment by ccaprani** [comment]
Thanks @fmckenna ! It mostly built ok; the CMake build is great. 

A few minor suggestions for the docs made here https://github.com/OpenSees/OpenSeesDocumentation/pull/65

Errors in the build (not for docs repo) are for MP and SP versions. I'm running Ubuntu 22.04, output is below.

After issuing `cmake --build . --config Release --target OpenSeesMP`
```bash
...
[ 95%] Building CXX object CMakeFiles/OpenSeesMP.dir/SRC/tcl/commands.cpp.o
In file included from /home/ccaprani/projects/opensees/OpenSees/SRC/tcl/commands.cpp:308:
/home/ccaprani/projects/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/PFEMSolver_Mumps.h:32:10: fatal error: dmumps_c.h: No such file or directory
   32 | #include <dmumps_c.h>
      |          ^~~~~~~~~~~~
compilation terminated.
gmake[3]: *** [CMakeFiles/OpenSeesMP.dir/build.make:104: CMakeFiles/OpenSeesMP.dir/SRC/tcl/commands.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:4607: CMakeFiles/OpenSeesMP.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:4614: CMakeFiles/OpenSeesMP.dir/rule] Error 2
gmake: *** [Makefile:586: OpenSeesMP] Error 2
```
and after issuing `cmake --build . --config Release --target OpenSeesSP`
```bash
[ 95%] Building CXX object CMakeFiles/OpenSeesSP.dir/SRC/tcl/commands.cpp.o
In file included from /home/ccaprani/projects/opensees/OpenSees/SRC/tcl/commands.cpp:308:
/home/ccaprani/projects/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/PFEMSolver_Mumps.h:32:10: fatal error: dmumps_c.h: No such file or directory
   32 | #include <dmumps_c.h>
      |          ^~~~~~~~~~~~
compilation terminated.
gmake[3]: *** [CMakeFiles/OpenSeesSP.dir/build.make:104: CMakeFiles/OpenSeesSP.dir/SRC/tcl/commands.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:4519: CMakeFiles/OpenSeesSP.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:4526: CMakeFiles/OpenSeesSP.dir/rule] Error 2
gmake: *** [Makefile:573: OpenSeesSP] Error 2
```
