### ISSUE TITLE
Compiling OpenSees in Windows 10 Version 1909

### ISSUE THREAD

**Issue by mtsonicc** [OpenSees/OpenSees#209]
Dear anyone who had trouble compiling OpenSees,

I had some trouble compiling OpenSees in Windows 10 Version 1909.
But after a few days of struggle, I finally compiled OpenSees in Windows 10.
I believe there are some people experiencing similar problem as mine, and I would like to be of some help.
A brief summary of my system: Windows 10 Version 1909 / Intel 9th generation CPU.

(1)     Download **ActiveTcl** from (https://www.activestate.com/products/tcl/downloads/) (I used **ActiveTcl-8.6.9.8609.2**) and install it in `C:\Program files\Tcl`

(2)     Download and install **Intel Parallel Studio XE** (https://software.intel.com/en-us/parallel-studio-xe/choose-download)
(2.1)    I used **parallel_studio_xe_2020_cluster_edition_online_setup.exe**.
(2.2)    Make sure to install **64-bit Intel Fortran compiler** and **MKL library**.

(3)     Install **Python**. I used **Miniconda 3.7** (https://docs.conda.io/en/latest/miniconda.html)

(4)     Clone opensees (`git clone https://github.com/OpenSees/OpenSees`)

(5)     Open `~/OpenSees/Win64/OpenSees.sln` with Visual Studio (I used **Microsoft Visual Studio Community 2019**).

(6)     Select **Release** and **x64** in **Solution Configurations** drop-down lists. For my case, default selection was **Debug.Dll**. (**Solution Configurations** menu is right next to the undo and redo icon at the top)

(7)     Things to be done in the **Solution Explorer**:
(7.1)    Select **OpenSees - right click - Properties** (or simply select OpenSees and _Alt+Enter_).
(7.1.1)  A new window named as **OpenSees Property Pages** will appear.
(7.1.2)  On the left panel, select **Linker - General**.
(7.1.3)  select **Additional Library Directories** and add `$(ICPP_COMPILER20)\compiler\lib\Intel64_win`.

(7.2)    Select **OpenSeesTK - right click - Properties** (or simply select and hit _Alt+Enter_)
(7.2.1)  A new window named as **OpenSeesTK Property Pages** will appear.
(7.2.2)  Do the same process instructed in (7.1.2) to (7.1.3).

(7.3)    Select **OpenSeesPy - right click - Properties** (or simply select and _Alt+Enter_).
(7.3.1)  A new window named as **OpenSeesPy Property Pages** will appear.
(7.3.2)  On the left panel, select **Linker - General**.
(7.3.3)  On the right panel,  select **Additional Library Directories**.
(7.3.4)  add `$(ICPP_COMPILER20)\compiler\lib\Intel64_win`
(7.3.5)  replace `c:\Program Files\Python36\libs` to `%UserProfile%\Miniconda3\libs`
(7.3.6)  On the left panel, select **C/C++**.
(7.3.7)  select **Additional Include Directories**.
(7.3.8)  replace `c:\Program Files\Python36\include` to `%UserProfile%\Miniconda3\include`

(7.4)    Select **OpenSeesPy36 - right click - Properties** (or simply select and _Alt+Enter_).
(7.4.1)  A new window named as **OpenSeesPy36 Property Pages** will appear.
(7.4.2)  Do the same process instructed in (7.3.2) to (7.3.8).
(7.4.3)  On the left panel, select **Linker - Input**.
(7.4.4)  On the right panel, select **Additional Dependencies**
(7.4.5)  replace `python36.lib` to `python37.lib`.

(8)     Build the entire OpenSees solution.

**Comment by Mengsen-W** [comment]
Hi mtsonicc, How to create a OpenSees.exe when Builded the entire OpenSees solution.

**Comment by Mengsen-W** [comment]
Hi
How to run the example1 in Visual Studio, or how to run cpp files in opensees directly?

**Comment by prafulla-malla** [comment]
![image](https://user-images.githubusercontent.com/34392453/95845315-bdaeaa80-0d69-11eb-8139-3f1bf06e24db.png)
How can I solve this problem while creating  .dll file using VS 2019

**Comment by mhscott** [comment]
Try to compile with cmake
https://opensees.github.io/OpenSeesDocumentation/developer/build.html#building-the-opensees-applications
