### ISSUE TITLE
Problem loading "ElasticPPcpp.so" in Ubuntu 19.10

### ISSUE THREAD

**Issue by mtsonicc** [OpenSees/OpenSees#227]
Hello,
I'm having problem loading `ElasticPPcpp.so` in Ubuntu 19.10.
(Ths .so file was compiled from **ElasticPPcpp.cpp** located in "**~/OpenSees/DEVELOPER/material/cpp**")

Here are list of things I've tried: (current directory: **~/OpenSees/DEVELOPER/material/cpp**; Version of OpenSees: 3.1.0)
(1) `export LD_LIBRARY_PATH=.` then run `~/bin/OpenSees example1.tcl`. -> This did not work.
(2) `export LD_LIBRARY_PATH=./` then run `~/bin/OpenSees example1.tcl`. -> This did not work.
(3) I also tried putting `OpenSees` and **ElasticPPcpp.so** in the same directory (**~/OpenSees/DEVELOPER/material/cpp**) -> This did not work either.

I found this post from https://opensees.berkeley.edu/community/viewtopic.php?f=4&t=63954&p=108263&hilit=localLibName#p108263 and added a line of code `opserr << "Could not find file: " << localLibName << endln;` in **packages.cpp** as instructed in the post.
This is what I get from adding the code: `Could not find file: ElasticPPcpp.so`

Note that there was no error importing `ElasticPPcpp.dll` in Windows 10 and `ElasticPPcpp.dylib` in macOS Catalina.

Any help or advise would be greatly appreciated.
Thanks for your attention.
Regards.

**Comment by erikemondt** [comment]
Dear mtsonicc,

could you please contact me regarding the creation of the DLL? I have some questions but i don't want to hijack this thread. You can reach me on erik.emondt@nov.com. Many thanks in advance.

**Comment by mtsonicc** [comment]
Dear erikemondt,

Hi, you can create .DLL by following the procedure instructed in https://opensees.berkeley.edu/wiki/index.php/Adding_your_own_Code


> Dear mtsonicc,
> 
> could you please contact me regarding the creation of the DLL? I have some questions but i don't want to hijack this thread. You can reach me on [erik.emondt@nov.com](mailto:erik.emondt@nov.com). Many thanks in advance.

**Comment by erikemondt** [comment]
I followed the instructions provided, but they were not sufficient. In order to compile succesfully I had to perform the additional steps as described in: https://github.com/OpenSees/OpenSees/issues/236#issue-566332170
Could you perhaps send your project? It would be greatly appreciated.

**Comment by erikemondt** [comment]
I followed the instructions provided, but they were not sufficient. In order to compile succesfully I had to perform the additional steps as described in: https://github.com/OpenSees/OpenSees/issues/236#issue-566332170
Could you perhaps send your project? It would be greatly appreciated.

> Dear erikemondt,
> 
> Hi, you can create .DLL by following the procedure instructed in https://opensees.berkeley.edu/wiki/index.php/Adding_your_own_Code
> 
> > Dear mtsonicc,
> > could you please contact me regarding the creation of the DLL? I have some questions but i don't want to hijack this thread. You can reach me on [erik.emondt@nov.com](mailto:erik.emondt@nov.com). Many thanks in advance.

**Comment by mtsonicc** [comment]
posting lists of things I've tried.

**1. in ununtu terminal, I typed** 
```
export LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH"
~/bin/OpenSees example1.tcl
```

-> this did not work


**2. in ununtu terminal, I typed** 
```
cp ./ElasticPPcpp.so ~/lib
export LD_LIBRARY_PATH="$HOME/lib:$LD_LIBRARY_PATH"
cd ~/lib
~/bin/OpenSees example1.tcl
```

-> this did not work either.

**3. I also took a look inside of "/SRC/api/packages.cpp" and modified following lines to see what was causing the problem.**

(starting from **line 289 of packages.cpp**)

  ```
*libHandle = dlopen (localLibName, RTLD_NOW);
  opserr << "localLibName: "<<localLibName << endln;
  
  if (*libHandle == NULL)  {
    opserr << "no lib exists" << endln;
    delete [] localLibName;
    return -1; // no lib exists
  }
```

and here is the result
```
OpenSees -- Open System For Earthquake Engineering Simulation
                 Pacific Earthquake Engineering Research Center
                        Version 3.2.0 64-Bit

      (c) Copyright 1999-2016 The Regents of the University of California
                              All Rights Reserved
  (Copyright and Disclaimer @ http://www.berkeley.edu/OpenSees/copyright.html)


localLibName: ElasticPPcpp.so
no lib exists
localLibName: ElasticPPcpp.so
no lib exists
WARNING could not create uniaxialMaterial ElasticPPcpp

    while executing
"uniaxialMaterial ElasticPPcpp 1 3000 0.001"
    (file "example1.tcl" line 22)
```

OpenSees successfully located "localLibName", but failed to run dlopen command.

Any help or advise would be greatly appreciated.
Regards.

**Comment by mtsonicc** [comment]
updates:
I tried adding `fprintf(stderr, "dlopen failed: %s\n", dlerror());exit(EXIT_FAILURE);` after `*libHandle = dlopen (localLibName, RTLD_NOW);`.

and this is what i get:
`dlopen failed: /home/myaccount/OpenSees/DEVELOPER/material/cpp/ElasticPPcpp.so: undefined symbol: _ZN16UniaxialMaterial11setResponseEPPKciR10OPS_Stream`

I'm not sure what "undefined symbol" means..

I also tried "ldd ElasticPPcpp.so":
```     linux-vdso.so.1 (0x00007fffc56f1000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f01bc050000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f01bbc50000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f01bba30000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f01bb690000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f01bc600000)
```

**Comment by fmckenna** [comment]
you are missing a symbol .. you need a demangler to see which one .. if
luck you have c++-filt on your system

**Comment by mtsonicc** [comment]
@fmckenna thank you very much for your response.

I tried "`c++filt _ZN16UniaxialMaterial11setResponseEPPKciR10OPS_Stream`"
and this is what I get:
`UniaxialMaterial::setResponse(char const**, int, OPS_Stream&)`

**Comment by mtsonicc** [comment]
update:

I found `-Wl,-undefined,suppress` in compile command for macOS.
 
I tried adding `--unresolved-symbols=ignore-all` in MakeFile (~/OpenSees/DEVELOPER/material/cpp/Makefile; Line 10)
`$(CC++) -shared -Wl,--unresolved-symbols=ignore-all,-soname,$(LIBRARY) -o $(LIBRARY) $(OBJS) -lc`

But this didn't work either...

**Comment by fmckenna** [comment]
we no longer suggest this method for adding elements/materials or anything else  .. use cmake and add to the CMAkE process .. the dll's have given us too much pain over the years
