### ISSUE TITLE
Compiling OpenSeesMP in Windows

### ISSUE THREAD

**Issue by thatoneddrguy** [OpenSees/OpenSees#228]
Hello,

I am having trouble compiling OpenSeesMP in Windows using Visual Studio 2019. I have tried adding 'openseesMP.vcproj' to the OpenSees solution, but this results in C2894 and C2733 errors that I am not sure how to resolve. I am able to build the regular OpenSees and OpenSeesPy, but not OpenSeesMP. Has anyone had luck compiling OpenSeesMP in Visual Studio 2019?

**Comment by ahartloper** [comment]
Which files / lines raise the errors?

**Comment by thatoneddrguy** [comment]
![2020-02-10 16_44_33](https://user-images.githubusercontent.com/10858202/74263912-983a4000-4cb4-11ea-903c-cfe162a9bc53.png)
Here is the list of errors that I'm getting.

**Comment by ahartloper** [comment]
This is the standard C++ library string? Maybe when it's included the #include definition is wrapped by an extern "C".

**Comment by mhscott** [comment]
Which Windows MPI libraries are you using?

**Comment by fmckenna** [comment]
have a look at latest build instructions https://opensees.github.io/OpenSeesDocumentation/developer/build.html
