### ISSUE TITLE
how to compile Python opensees.so

### ISSUE THREAD

**Issue by sewkokot** [OpenSees/OpenSees#243]
Before some recent changes I had compiled opensees.so with the following steps:
```
cd SRC/interpreter
make 
```
however now it does work. What is current recommended way to get opensees.so?

**Comment by ahartloper** [comment]
- What operating system are you using?
- What are the errors?
- Which commit are you using (what is the SHA)?

**Comment by sewkokot** [comment]
I'm using Linux and the up-to-date OpenSees git sources. 
In the meantime I found that now opensees.so can be built directly from the main OpenSees directory with:
`make python`
and I get brand new opensees.so in ./SRC/interpreter/ directory :)
