### ISSUE TITLE
twoNodeLink + MultiLinear bug

### ISSUE THREAD

**Issue by ArchDH** [OpenSees/OpenSees#244]
I encountered this bug while using OpenSeesPy library while ago, but I did not try it on the real OpenSees. Today I finally executed these two sets of codes actually and found the same error on OpenSees 3.1.0

*OS : Window 8.1 64bit 
-------------------------------------------------------------------------
[Code 1 - twoNodeLink + MultiLinear material]
-------------------------------------------------------------------------
wipe
model basic -ndm 2 -ndf 3
node 1 0.0 0.0
node 2 0.0 1.0
mass 2 1.0 1.0 0.0
fix 1 1 1 1
fix 2 0 1 1
uniaxialMaterial MultiLinear 1 0.1 100. 0.5 150. 1.0 175.
element twoNodeLink 1 1 2 -mat 1 1 1 -dir 1 2 3

recorder Node -file Node2.txt -time -node 2 -dof 1 2 3 disp
recorder Element -file Element1.txt -time -ele 1 -dof 1 2 3 force

pattern Plain 1 Linear {
load 2 1.0 0.0 0.0
}
system UmfPack
numberer RCM
constraints Plain
algorithm Newton
integrator DisplacementControl 2 1 0.1
analysis Static
analyze 20

[Result]
![fig 1](https://user-images.githubusercontent.com/22149162/74934083-bcbab880-5428-11ea-9bcb-59867cf2dd63.png)

-------------------------------------------------------------------------
[Code 2 - zeroLength + MultiLinear material]
-------------------------------------------------------------------------
wipe
model basic -ndm 2 -ndf 3
node 1 0.0 0.0
node 2 0.0 1.0
mass 2 1.0 1.0 0.0
fix 1 1 1 1
fix 2 0 1 1
uniaxialMaterial MultiLinear 1 0.1 100. 0.5 150. 1.0 175.
element zeroLength 1 1 2 -mat 1 1 1 -dir 1 2 3

recorder Node -file Node2.txt -time -node 2 -dof 1 2 3 disp
recorder Element -file Element1.txt -time -ele 1 -dof 1 2 3 force

pattern Plain 1 Linear {
load 2 1.0 0.0 0.0
}
system UmfPack
numberer RCM
constraints Plain
algorithm Newton
integrator DisplacementControl 2 1 0.1
analysis Static
analyze 20

[Result]
![fig 2](https://user-images.githubusercontent.com/22149162/74934180-f4c1fb80-5428-11ea-8164-eb2d86f641e1.png)
-------------------------------------------------------------------------

**Comment by mhscott** [comment]
Thanks for posting the error.  Are you using the latest source code from GitHub?  I changed something with the input recently PR #220, but I don't think that will affect anything.

Also, please capitalize OpenSees, no CAPS lock: https://wp.me/pbejzW-1T

**Comment by ArchDH** [comment]
> Thanks for posting the error. Are you using the latest source code from GitHub? I changed something with the input recently PR #220, but I don't think that will affect anything.
> 
> Also, please capitalize OpenSees, no CAPS lock: https://wp.me/pbejzW-1T

**Comment by ArchDH** [comment]
> Thanks for posting the error. Are you using the latest source code from GitHub? I changed something with the input recently PR #220, but I don't think that will affect anything.
> 
> Also, please capitalize OpenSees, no CAPS lock: https://wp.me/pbejzW-1T

Thanks for answering. I used the latest source but I guess it's an internal bug among the codes.
