### ISSUE TITLE
mpi.h not found while compiling on Debian

### ISSUE THREAD

**Issue by shahram10715** [OpenSees/OpenSees#249]
if I used the provided makefile.def of debian, there are the following links to download which doesn't work:
```
wget http://www.netlib.org/scalapack/scalapack.tgz
wget http://www.netlib.org/blacs/mpiblacs.tgz
```
 and if I comment these two lines I will encounter:
`fatal error: mpi.h: No such file or directory`
and even if I supply the complete path to mpi.h still doesn't work.
But if I use the Ubuntu makefile.def everything goes well.
By the way I wrote a bash script which can be used to compile both on Debian and Ubuntu, here is the link to my script:
https://github.com/shahram10715/myPasteBeeens/blob/master/opensees.sh

**Comment by mhscott** [comment]
Thank you for the information.
