### ISSUE TITLE
Using C++11 fatures

### ISSUE THREAD

**Issue by MassimoPetracca** [OpenSees/OpenSees#256]
Dear all,

I was wondering whether it is allowed in OpenSees to use **C++11** features. I couldn't find any tips or guidelines about this in OpenSees, so I'm not using C++11 (even if I would like to...).

However I found that in the VTK_Recorder.cpp file there is usage of the "auto" keyword which is a C++11 feature.

Thus the question, can we use C++11 features such as "auto" keyword, "lambda" functions and std::shared_ptr?

**Comment by fmckenna** [comment]
yes .. all the compilers we now use to release the code are 11 compliant.

**Comment by MassimoPetracca** [comment]
@fmckenna Thanks!
