### ISSUE TITLE
Trubles with new OpenSees version

### ISSUE THREAD

**Issue by xantis85** [OpenSees/OpenSees#257]
Hello to everyone!
I'm experiencing some problems with OpenSees 3.1.0. In particular, I got some problems when trying to construct a Reinforced concrete section with fibers, by using "pach quadr" and "layer straigth". After the definition of the first fiber section, the software crashes. The identical script works with version 3.0.3 without any problem.
Any possibility to fix this bug?

**Comment by mhscott** [comment]
Check the closed issue #147 

https://github.com/OpenSees/OpenSees/issues/147

**Comment by xantis85** [comment]
Thank you very much professor Scott.
