### ISSUE TITLE
Is PSUMAT available ?

### ISSUE THREAD

**Issue by vpapanik** [OpenSees/OpenSees#268]
I compiled the latest source code in VS2019 and the program works with PSUMAT. However, the source is not available. Which precompiled file is the code linked to ?

**Comment by fmckenna** [comment]
it is hidden away in 1 of the lib files built using the intel fortran compiler and made available. you do not need the source code as you can link to it. Linux and Mac developers are not so fortunate, as I don't include it in any prebuilt lib for those systems.
