### ISSUE TITLE
opensees by make at GitHub cannot work well with PlaneStressUserMaterial

### ISSUE THREAD

**Issue by Mengsen-W** [OpenSees/OpenSees#269]
I tested some command at the Ubuntu 18 and centos 7, all of those cannot work well . So, try to building  a stabilization OpenSees in the Linux certainly needed.

**Comment by mhscott** [comment]
Please be more specific and provide examples.

**Comment by mhscott** [comment]
Sorry, your issue is with PSUMat?  The source code for that is not available.

**Comment by u-anurag** [comment]
I guess the issue is that PSUMAT works with the OpenSees windows executable (downloaded from the website) but does not work with when compiled on a Linux machine. I tried to regenerate the error. See the image below, OpenSees 3.1 Windows executable (top) and OpenSees 3.1 compiled on Linux (bottom). 

![image](https://user-images.githubusercontent.com/35711550/76776578-8d1f7780-676c-11ea-8431-5032b4f55e8b.png)

**Comment by mhscott** [comment]
Thanks, Anurag!

Despite taking advantage of the OpenSees framework and publishing several papers with PSUMAT, the authors have decided to restrict the source code....

________________________________

**Comment by Mengsen-W** [comment]
authors have decided to restrict the source code... Is there any other solution with PSUMat...

**Comment by u-anurag** [comment]
You could use an nD-material (Drucker Prager, J2 Plasticity etc.) and convert it to plane stress material. This combination is to replace PSUMat in your code. The output will not be the same of course.

**Comment by Mengsen-W** [comment]
Thanks, Anurag!
Despite all this, I hope the author can provide some help or support on Linux.

**Comment by fmckenna** [comment]
the code is avail in application available for everyone to run at TACC through designsafe https://www.designsafe-ci.org/ .. PSUMAT is one of several pieces of code not available to developers .. if you need to run on your desktop you might consider running it through a VM on windows or mac os.

**Comment by fmckenna** [comment]
it is avail to windows developers as the code is included in one of the precompiled windows libs. if you actually need it in a development version you will have to use windows (use a vm, windows 10, you will also need visual studio and an the intel compilers (C++, C, and Fortran))
