### ISSUE TITLE
OpenSeesMP and OpenSeesSP

### ISSUE THREAD

**Issue by AhmetAlperParker** [OpenSees/OpenSees#279]
OpenSeesMP is in general for parametric studies. SP version is for very large models. Is it possible to make parametric studies on very large models with one of them, or even better should there be a OpenSeesMPSP or something similar? Let's say I have ida analysis of very large models to be run on distributed machines with OpenMP and MPI type analysis.
Regards
Ahmet Alper Parker

**Comment by zhuminjie** [comment]
That's exactly what OpenSeesPy, a Python interpreter for OpenSees, shoots for. We are working on it.
