### ISSUE TITLE
Intel Compilers

### ISSUE THREAD

**Issue by AhmetAlperParker** [OpenSees/OpenSees#284]
Hi,
Most of the time, OpenSees is compiled with Visual Studio. Is there an effort to provide Intel Compiler compiled versions?

**Comment by ahartloper** [comment]
You mean with the Intel C++ compiler on Windows OS? It should be possible by switching from the Microsoft build tools to Intel C++. That said I haven't tried since many versions ago.

**Comment by AhmetAlperParker** [comment]
Yes, Windows OS. Is there a compiled version accessible now in anyone? I compiled one with gcc on Linux and compare its results with a later version (so similar) on Windows, some runs do not converge on Linux, but converge on Windows.

**Comment by ahartloper** [comment]
Hmm strange. See attached, I compiled with Intel C++ 19.0.
[OpenSees-Intel19_0.zip](https://github.com/OpenSees/OpenSees/files/4403199/OpenSees-Intel19_0.zip)

**Comment by AhmetAlperParker** [comment]
Same convergence behavior. Thanks for the file
