### ISSUE TITLE
Request for CMake implementation

### ISSUE THREAD

**Issue by johnnyontheweb** [OpenSees/OpenSees#286]
It is clear that, at this point, OpenSees needs a CMake project definitions to ease compilation over different platforms.
This will simplify a lot the projects generation, even in VS, since in most cases there are lots of paths to be changed (e.g. lib folders, etc.).
It will be difficult at this stage of the project but IMHO necessary  - ready to collaborate.

**Comment by mhscott** [comment]
@fmckenna has talked about doing this, but I think he is overloaded with other duties.  Do you have experience with CMake?  What would the basic structure look like for OpenSees?

**Comment by johnnyontheweb** [comment]
I have a limited experience in writing CMake files. Anyway, we can write a CMakeLists.txt in the project root folder, containing all the definitions for all the architectures (Windows, Linux, Mac OS, etc.) and calling a Cmakelists.txt for each project (actor, analysis, etc. ...)
There are many samples over the internet:
`cmake_minimum_required (VERSION 2.8.7)

project (OpenSees CXX C)
...`

We can ask the user the folders to be used for dependencies for compilation and linking (eg. C:\program files\tcl, or C:\tcl, or C:\activeTcl ...) by using Cmake options (for instance, by using "find_library" cmake command).

`set (TCL_DIR CACHE PATH "Manual Tcl directory")

if (TCL_DIR)
           find_library (TCL_LIB tcl DOC "Tcl library" PATH "${TCL_DIR}/lib")
           include_directories ("${TCL_DIR}")
    else ()
              find_library (TCL_LIB tcl DOC "TCL library")
    endif ()
    if (${TCL_LIB} STREQUAL "TCL_LIB-NOTFOUND")
             message (FATAL_ERROR "Tcl not found")
    endif ()
 `

By running cmake in every different platform will lead to the automatic compilation of project files and solutions, ready for the different compilers (Visual studio, MinGW, etc.) and systems.
In addition, we'll have a cleaner solution by eliminating pre-configured vcxproj files (and folders Win32 and Win64 too).

**Comment by Mengsen-W** [comment]
Adding CMAKE support is absolutely necessary, as it ensures a full platform compilation process. I can be of some help if needed
