### ISSUE TITLE
A note about OpenSees and RAM

### ISSUE THREAD

**Issue by vpapanik** [OpenSees/OpenSees#288]
Just dropping a note to describe a uncomfortable experience with a 35k node model I am working on in the past month. I used the UmfPack solver. The model used to run the previous day. I made some small changes in material properties and the next day it failed to run; reverted back to the previous version and it still refused to run.

The analysis didn't crash; I just had a 'failed to solve()' message at iteration 0, nothing else, so I thought that it had to do some bad geometry, materials, sections etc. but could not find the solution.

Today I run it on a different computer and all of the sudden the same model run without problems.

Verdict : The solver has to include a message that says : '**Out of memory !**' :)

**Comment by mhscott** [comment]
Do you get the same behavior with a different solver, e.g. SparseGeneral?

On a related note, I suspect UmfPack is leaking memory.  When an analysis with UmfPack is put in a Monte Carlo loop, the process eventually runs out of memory.

**Comment by vpapanik** [comment]
Yes I tried SPARSEGEN and I saw something that looked like a memory issue, so I ran the model on another computer with UmfPack and worked.

It is probably a leak after all. Thank you for your consideration !

**Comment by u-anurag** [comment]
Generally, if you run on Linux, at least it shows *Core Dump* when there is a memory leak. I faced it once with a model with 5.5k nodes on a computer with Linux and 4GB RAM. Windows does not show such a message. Is there a big difference in RAM in both the computers you used? Just for comparison.

**Comment by vpapanik** [comment]
My model had 35k LayeredShell elements. On the 16GB laptop it was running fine for a couple of times, crashed later. On the 32GB desktop, no problems whatsoever. Looks like a leak to me.

**Comment by mhscott** [comment]
Could also be a leak in the element, section, and/or material models.
