### ISSUE TITLE
tiny bug

### ISSUE THREAD

**Issue by vpapanik** [OpenSees/OpenSees#295]
This is minor, but in NDMaterial.cpp, line 295:

theResponse =  new MaterialResponse(this, 2, this->getStress());

should be

theResponse =  new MaterialResponse(this, 2, this->**getStrain**());

**Comment by mhscott** [comment]
Thanks for noticing that, will change it in a future PR.  Not really a bug though :)

**Comment by vpapanik** [comment]
that's why I said tiny :D Thanks !
