### ISSUE TITLE
Bug in J2Plasticity material - corrected

### ISSUE THREAD

**Issue by vpapanik** [OpenSees/OpenSees#304]
I tried to build a composite section (LayeredShell) using concrete (PSUMAT in PlateFromPlaneStress) and steel plate (J2Plasticity in PlateFiber). The response was not good so I tried to test the J2Plasticity material using a representative volume element (ShellMITC4) with LayeredShell section of unit thickness i.e. constitutive driver (attached).

[J2MaterialDriver.tcl.txt](https://github.com/OpenSees/OpenSees/files/4458911/J2MaterialDriver.tcl.txt)

The single-element model worked in the elastic region but stopped unexpectedly at the very start of the 6th step. The same behavior has been also reported here a long time ago:

https://opensees.berkeley.edu/community/viewtopic.php?f=2&t=63859&p=107946&hilit=j2plasticity#p107946

The problem was found in J2Plasticity :: plastic_integrator method for the plastic region (J2Plasticity.cpp lines 519-568). Specifically, variables _resid_ and _tang_ depend on timestep **dt**, no matter if eta is zero (usual case of rate-independent response).

When a new load step starts, the _ops_Dt_ variable, assigned to **dt**, is zero. This causes a division by zero and assigns **nan** values to _resid_, _tang_ and eventually _gamma_, which causes chaos.

On line 444, setting:

const double dt = ops_Dt+**1e-8**

completely eliminates the problem. This issue may still be present on other models using ops_Dt in a denominator.

**Comment by mhscott** [comment]
Good catch!  It would probably be better to make the eta/dt term conditional instead of artificially small.

**Comment by mhscott** [comment]
Resolved #314
