### ISSUE TITLE
nDMaterial   PlateFromPlaneStress

### ISSUE THREAD

**Issue by mohammem** [OpenSees/OpenSees#31]
Hi All,
I am trying to use (nDMaterial PlateFromPlaneStress) material with the latest release of OpenSees (2.5.0 6536). I am getting an error when I run my model with this material. However, my model with the same material works normally with the OpenSees release (2.5.0 6477).

Thanks,
Mohammed

**Comment by mhscott** [comment]
Mohammed,

Do you have an input file that we can use to test the problem?

Michael

**Comment by mohammem** [comment]
Hi Dr. Scott,
I have attached an input file with this email. Please let me know if you
have any questions.

Thanks,
Mohammed

**Comment by mhscott** [comment]
Mohammed,

Are you running this on Windows?  You may have a compiled version without _HAVE_PSU defined whereas the previous version had this defined.  Are you able to recompile on Windows?  If using Linux, the PlaneStressUserMaterial will not work.

Michael

**Comment by mohammem** [comment]
Hi Dr. Scott,
Yes I am using Windows. I will try to compile a new version on my computer. 

Thanks,
Mohammed
