### ISSUE TITLE
plasticDeformation and basicForce element recorder question

### ISSUE THREAD

**Issue by krim71** [OpenSees/OpenSees#317]
Hi,

I was wondering what each column in the output file of plasticDeformation and basicForce element recorders refer to in a 2D, 3DoF model? I couldn't find it anywhere in OpenSees documentation.

Thanks.

**Comment by mhscott** [comment]
The first column should be axial deformation/force and the second and third columns are rotation relative to the chord/bending moment at I and J, respectively.

**Comment by krim71** [comment]
Prof. Scott,

Thank you!
