### ISSUE TITLE
tcl8.6/clock.tcl

### ISSUE THREAD

**Issue by Xing90** [OpenSees/OpenSees#318]
I got a problem when using OpenSees Navigator P-code. I was unable to get results for running analysis. It said,"
**couldn't read file "OpenSees3.2.0-x64.exe/lib/tcl8.6/clock.tcl": no such file or directory while executing
"source -encoding utf-8 [file join $TclLibDir clock.tcl]" 
    (procedure "::tcl::clock::format" line 3) 
    invoked from within 
"clock format $systemTime -format "%d-%b-%Y %H:%M:%S"" 
    invoked from within 
"puts "Starting OpenSees analysis: [clock format $systemTime -format "%d-%b-%Y %H:%M:%S"]" " 
    (file "model3.tcl" line 8)**
Anyone could help me please? Thank you very much!

**Comment by vpapanik** [comment]
Yes, install the full ActiveTcl 8.6 in order to fix that and keep OpenSees.exe only.

**Comment by Xing90** [comment]
> Yes, install the full ActiveTcl 8.6 in order to fix that and keep OpenSees.exe only

**Comment by Xing90** [comment]
> Yes, install the full ActiveTcl 8.6 in order to fix that and keep OpenSees.exe only.

Thank you very much!
