### ISSUE TITLE
Record absolute accelerations and ground accelerations

### ISSUE THREAD

**Issue by gabrielegranello** [OpenSees/OpenSees#330]
Hi OPpy community,
I am struggling to extract the absolute acceleration from OPpy. In the TCL version, it was possible by using the recorder command. However, when I am using nodeAccel command I get the relative one.

In the same manner, I would like to extract the ground motion acceleration. The reason is that I am discretizing the time step in case the analysis fails, and therefore I would like to have the input with the same time step of the output. I am trying the getLoadFactor command but it only returns me a series of 0. 

Am I perhaps missing something? Thanks for helping!

Best,
Gabriele

**Comment by mhscott** [comment]
What is OPpy?

Did you try using the recorder command in OpenSeesPy like you did in the Tcl version?

**Comment by gabrielegranello** [comment]
Dear Prof. Scott,
sorry I was meant to write OpenseesPy as an abbreviation. Thanks, yes I ended up using the recorder object and it does return the absolute acceleration. To your knowledge, is there any way to save the results of the recorder object directly into a Python string?
Thanks for helping.

Best,
Gabriele

**Comment by ambaker1** [comment]
I ran into this same issue. getLoadFactor works with a Plain time-series, but not with UniformExcitation
Here's some example code:

# getLoadFactor does not work UniformExcitation

# Define simple truss
model BasicBuilder -ndm 1 -ndf 1
uniaxialMaterial Elastic 1 100.0
node 1 0 0
node 2 1 0 -mass 1.0
fix 1 1
element truss 1 1 2 10.0 1

# Add arbitrary path time-series
set acc {0.001 -0.02 0.005 0.04 0.056 0.02 -0.003 0.0052 0.0068 0.0159}
set dt 0.1
timeSeries Path 1 -dt $dt -values $acc -prependZero

# Add Plain pattern
pattern Plain 1 1 {load 2 1.0}
# Add UniformExcitation pattern
pattern UniformExcitation 2 1 -accel 1

# Define analysis settings
constraints Plain
system BandGeneral
numberer RCM
algorithm Newton
test EnergyIncr 1e-9 10
integrator Newmark 0.5 0.25
analysis Transient

# Run static analysis, put the loadFactor
puts "Time\t\tPlain Load Pattern\tUniformExcitation Load Pattern"
puts [join [join [list [getTime] [getLoadFactor 1] [getLoadFactor 2]]] \t]
for {set i 0} {$i < [llength $acc]} {incr i} {
    analyze 1 $dt
    puts [join [join [list [getTime] [getLoadFactor 1] [getLoadFactor 2]]] \t]
}

**Comment by mhscott** [comment]
The UniformExcitation class doesn't implement getLoadFactor, so the default 0 is returned.  Should be an easy thing to add.

**Comment by ambaker1** [comment]
That would be great if that was a feature. Just curious though-why doesn’t getLoadFactor work with time series instead of load patterns? Some load patterns take input from multiple time series. It seems like it would make more sense to be tied to time-series.

**Comment by annehulsey** [comment]
@mhscott  What was the conclusion of this thread - is there a way to extract the input acceleration at each time step? Specifically, how could I modify the script in the [SDOF example](https://openseespydoc.readthedocs.io/en/latest/src/exampleNamedSpacedNonlinearSDOF.html) to get the absolute accelerations?

**Comment by mhscott** [comment]
@annehulsey Sorry, the thread is a loose end! For now you'll have to read it from the ground acceleration file and add it to the relative acceleration from the analysis.

**Comment by annehulsey** [comment]
@mhscott Thanks for the response! Does opensees just use simple linear interpolation to go from the acceleration dt to the analysis dt?

**Comment by mhscott** [comment]
Yes, linear interpolation if the time step is smaller than the ground motion interval.

**Comment by asaaed** [comment]
@mhscott 

> Yes, linear interpolation if the time step is smaller than the ground motion interval.

What about the opposite, i mean what if time step is larger than the ground motion interval?

**Comment by mhscott** [comment]
That should be easy to figure out.

**Comment by ambaker1** [comment]
@asaaed it’s linear interpolation. So, if the analysis time happens to be on the points of the time-series path, it will use the exact values. If it is between points, it interpolates. The size of the analysis dt is irrelevant.

**Comment by asaaed** [comment]
> @asaaed it’s linear interpolation. So, if the analysis time happens to be on the points of the time-series path, it will use the exact values. If it is between points, it interpolates. The size of the analysis dt is irrelevant.

Thanks, so if integration steps are 5.5 times of record steps, just 5th and 6th step of record are involved in interpolation and the middle points (2nd to 4th) are omitted?

**Comment by ambaker1** [comment]
@asaaed I believe so! That's why you should pick an analysis dt that is smaller than your record dt.

**Comment by mhscott** [comment]
It's all linear interpolation.
Closing this issue as it has gone way off the original topic.
