### ISSUE TITLE
Potential bug about Node recorder using OpenSeeSP

### ISSUE THREAD

**Issue by jf-huang** [OpenSees/OpenSees#332]
Hello,

Hope everyone is doing well! Recently I have come across a problem with using the Node recorder in OpenSeesSP. The OpenSeesSP was compiled on ubuntu 18.04 with the latest code from the Github repo. However, when I used this recorder to get the nodal displacements the order of the nodal results in the xml file seem not correct, as follows:

**Command:** recorder Node -xml floorDisp.xml -time -region 7 -dof 1 disp
**Excerpt of the result xml file:** 
![image](https://user-images.githubusercontent.com/44045796/80785820-6360bb00-8b36-11ea-9aa1-3a391f716b40.png)

As can be seen, the second NodeOutput label starts while the first NodeOutput label has not been not completed yet and as a result I am not sure which column of data corresponds to which node. **After some trial and error, I found that this error is related to how many cores I specify for analysis. When I specify less than 4 cores (np<=3), the result xml file will be correct** , as shown below:
![image](https://user-images.githubusercontent.com/44045796/80786049-3e207c80-8b37-11ea-8621-57975328d454.png)

**Besides, this problem seems model-specific in some way. I have used the Node recorder in other models with the same compiled OpenSeesSP (record 21 nodes, run with 10 cores) and it worked out fine.**

Is this a bug or have I missed something? I have attached the model (steel moment frame) and it would be great if anyone can try it out (run the main.tcl file). Any input is appreciated. Thanks in advance!

Regards,
Junfei
[OpenSeesModel.zip](https://github.com/OpenSees/OpenSees/files/4562706/OpenSeesModel.zip)

**Comment by jf-huang** [comment]
I have tried to use the Node recorder to record the node responses to separate files and the results did not agree with the one I obtained when recording to the same file. So I suppose this is a bug?

**Comment by mhscott** [comment]
Perhaps.  But you'll have to provide more information and a minimum working example for anyone to investigate.

________________________________

**Comment by jf-huang** [comment]
Hi Prof. Scott,

Thanks for your reply! I have attached the model I used in the initial thread. It is a 40-story moment resisting frame and I am recording the floor nodes to get the time histories. In the attached scripts only 2 nodes are recorded but it can be changed to other number of nodes. The results would remain the same.

Regards,
Junfei

**Comment by mhscott** [comment]
Junfei,

Thank you.  Can you provide a smaller example (one story, one input file) where the issue occurs?

Michael

________________________________

**Comment by jf-huang** [comment]
Prof. Scott,

Attached is a simplified 1-story 1-bay frame model (12 elements, 13 nodes). This issue will occur when 7 cores are used and the header of the result xml file is shown as follows:
![image](https://user-images.githubusercontent.com/44045796/80892830-f65a3c00-8c81-11ea-90ce-0e7d7489e60c.png)

Please note that this issue will not occur when only 2 nodes are recorded (7 cores used):
![image](https://user-images.githubusercontent.com/44045796/80893191-0c1d3080-8c85-11ea-9fad-20d316a34605.png)

Besides, OpenSeesSP would complain "WARNING AnalysisMode::getGroupGraph  - 0 vertices, has the Domain been populated?" if more than 7 cores (np>7) are used for this model. Does it mean that OpenSeesSP cannot do the graph partition for this small model for more than 7 cores? However, I think this is not related to the issue I am having as it does not happen for the 40-story model.

Thank you for your kind help!

Regards,
Junfei
[1story1bay.zip](https://github.com/OpenSees/OpenSees/files/4569076/1story1bay.zip)

**Comment by JX-Deng** [comment]
Hi Junfei,

May I ask you how you successfully compile the parallel version of OpenSees, I really struggle with it facing many problems.  Many thanks for any instructions or related reference.

Regards,

**Comment by jf-huang** [comment]
Hi, 

I have built OpenSeesSP on ubuntu and [here](https://hub.docker.com/r/jfhuang19/opensees_sp/dockerfile) is the Dockerfile that shows the steps I take to build it. Hope it helps.

Regards,
Junfei

**Comment by mhscott** [comment]
Can you use the regular node recorder with -file instead of XML?  The XML doesn't work properly with OpenSeesSP but the -file option should work.
