### ISSUE TITLE
How does FiberSection2dThermal calculate moment?

### ISSUE THREAD

**Issue by mcoar** [OpenSees/OpenSees#334]
Good morning, 
I am curious about the moment calculation that is used by the FiberSection2dThermal section. I have pasted a section from Elhami Khorasani et al 2015 about how the OpenSees Thermal module calculates moment, and the "double-counting" of modulus reduction for thermal fibers at elevated temperatures in the equations for Fth and zbar. The results from my validation suggest that the current OpenSees version 3.2.0 uses the _effective_ centroid zbar = \sum{Ar*Er*zr}/\sum{Ar*Er}, when my understanding is that it should use the _geometric centroid_ zbar = \sum{Ar*zr}/\sum{Ar} for calculating thermal moment. 

I am not quite familiar enough with C++ to understand from the code itself how these values are calculated. Any support in whether this change has been implemented, or if not, why not, would be appreciated. Thank you!

![image](https://user-images.githubusercontent.com/53275798/80817829-27fad680-8ba0-11ea-999a-dec50c46697d.png)
![image](https://user-images.githubusercontent.com/53275798/80817858-347f2f00-8ba0-11ea-93dc-8a7fb3ad1c8a.png)
[Khorasani, Garlock, Quiel - 2015 - Modeling steel structures in OpenSees Enhancements for fire and multi-hazard probabilistic analyses.pdf](https://github.com/OpenSees/OpenSees/files/4564998/Khorasani.Garlock.Quiel.-.2015.-.Modeling.steel.structures.in.OpenSees.Enhancements.for.fire.and.multi-hazard.probabilistic.analyses.pdf)

**Comment by mhscott** [comment]
Have you tried contacting the authors?

Khorasani - U Buffalo
Quiel - Lehigh
Garlock - Princeton

________________________________

**Comment by mcoar** [comment]
Good morning, 

Thank you for your response. I have contacted the authors about this - Garlock is my advisor, and Elhami Khorasani was a Ph.D. student of hers before becoming a professor at UBuffalo. Quiel was also a student of hers. 

The paper I shared suggested changes to two files - Steel01Thermal and FiberSection2dThermal. I see from the source file for Steel01Thermal that the suggested changes have been implemented in the current version of Opensees 3.2.0. However, I don't see the changes to FiberSection2dThermal implemented in the current version. I suppose I'm really asking why one change was implemented and not the other.

**Comment by mcoar** [comment]
Good afternoon, it seems as though there were actually changes to both the files I referenced. I was using the OpenSees for Fire version 3.0.0, which only has changes to the section, not the material. While I'm still not getting the results I expect, this is not the issue. Thanks for your feedback, I'm closing this issue.
