### ISSUE TITLE
Failed to import openseespy (3.2.0)

### ISSUE THREAD

**Issue by mnadhro** [OpenSees/OpenSees#337]
Hi,
after upgrading to the latest version 3.2.0, failed to import opensees,
It is in both linux and web based DesignSafe Jupyter, there is no problem for windows

![Screenshot at 2020-05-04 11-36-17](https://user-images.githubusercontent.com/61713112/80973461-13c90a80-8e28-11ea-8960-e448bd68b332.png)

**Comment by mhscott** [comment]
If this is still an issue, please post it here: https://github.com/zhuminjie/openseespy/issues
