### ISSUE TITLE
EqualDOF and rigidDiaphragm Slaving. 

### ISSUE THREAD

**Issue by nicclemett** [OpenSees/OpenSees#338]
Hi All,

I am using OpenSeesPy and I am having some troubles using the `equalDOF()` and `rigidDiaphragm() ` commands to create a rigid diaphragm in my model, when double nodes are specified at each coordinate.
The issue I am encountering is that if I try and use the `equalDOF()` and `rigidDiaphragm()` commands sequentially all of constraints do not appear to be applied to the model.

I have a simple 3D model as shown below and described in the attached input file.

image

I have modelled two nodes at each BCJ location so that at a later stage I can add a zeroLength spring to represent the BCJ flexibility. In the meantime I would like to slave the two nodes so that they have the same displacements in all 6 DOF.

I have used the `rigidDiaphragm()` command to slave all of the L1 nodes to one of the nodes at the corner. The issue I am encountering is that if I specify the pairs of nodes to also have the same Z, Mx, and My, displacements using the command `equalDOF(master, slave, *[3, 4, 5])` then no constraint appears to be imposed as evidenced by the `nodeDOFs()` and eigenvalues printed out by my script.

![image](https://user-images.githubusercontent.com/62114051/81179804-734f2380-8faa-11ea-996e-9396061c3a0b.png)

Another interesting thing that I noticed was that if the `equalDOF()` command is placed before the `rigidDiaphragm()` then the node DOFs are quite different and the modeshapes no longer seem reasonable... N10 Dofs 3,4 are equal to N6 Dofs 1, 5 respectively.

![image](https://user-images.githubusercontent.com/62114051/81179908-9f6aa480-8faa-11ea-902b-5630774345b9.png)

It appears as if when one of the constraints (`equalDOF()` or `rigidDiaphragm()`) is already specified for a node then the next one is sort of ignored...

In addition I also tried to slave only node A at each location to the `rigidDiaphragm()` and then use `equalDOF(master, slave, *[1,2,3,4,5,6])` for node B but this also gave unrealistic modeshapes.

I can work around this problem by slaving all of the L1 nodes to the diaphragm and then placing a very stiff zeroLength element between the nodes. This gives the same displacements for each node in the pair as I would expect, however, I would prefer to avoid this and use slaving if possible.

I appreciate any help that you can provide regarding this...

Cheers,
Nic

[dbl_node_frame_with_node_masses.zip](https://github.com/OpenSees/OpenSees/files/4586868/dbl_node_frame_with_node_masses.zip)

**Comment by fmckenna** [comment]
this is not the forum for questions on using OpenSees.

you can only mix equalDOF and rigidConstraints if you use the penalty method to enforce the constraints. all others fail with gibberish results. you need approp. penalty factors to enforce your constraint and not mess up your eigenvalues if you use that route.

**Comment by mhscott** [comment]
@fmckenna, This is a forum for asking modeling questions related to OpenSees!  Tcl or Python.

**Comment by fmckenna** [comment]
@mhscott 

the place for questions on usage is here: 
https://opensees.berkeley.edu/community/index.php

github is for developers having issues with the code. otherwise we will be swamped answering 
questions for which many answers already exist.

e.g. similar posts to board
https://opensees.berkeley.edu/community/viewtopic.php?f=2&t=63492&p=106846&hilit=equalDOF+rigidDiaphragm#p106846

https://opensees.berkeley.edu/community/viewtopic.php?f=2&t=63550&p=107063&hilit=equalDOF+rigidDiaphragm#p107063

**Comment by nicclemett** [comment]
@fmckenna My apologies. Thank you for the links. I will uses this community for any future queries.
