### ISSUE TITLE
How to request old versions of OpenSees?

### ISSUE THREAD

**Issue by mcoar** [OpenSees/OpenSees#339]
Good afternoon, 
In the readme file of this repository, it states that older versions of the code are available upon request. I would like to request an older version to compare results but I'm not sure the best place to do so or who to contact. Any help is appreciated. 
Note: I'm looking for versions around November 2018. The file history says that a change was made to Steel01Thermal on Nov 5th, and I'm curious about versions just before and just after this change was made. Thank you1

**Comment by ahartloper** [comment]
You can check-out an old commit and compile that code. If you have the commit hash:
```
git checkout <hash>
```
then compile

**Comment by mcoar** [comment]
@ahartloper Got it,  thank you! I haven't compiled the program before but I should be able to figure it out.
