### ISSUE TITLE
Bug on Normal Distribution?

### ISSUE THREAD

**Issue by talledodiego** [OpenSees/OpenSees#340]
Dear @fmckenna @mhscott ,
I suspect I have found a bug in NormalRV.cpp. 
The pdf is evaluated as following:
```
double
NormalRV::getPDFvalue(double rvValue)
{
	//static const double pi = std::acos(-1.0);
	static const double oneOverRootTwoPi = 1.0/sqrt(2.0*pi);
	
	//return 1 / sqrt ( 2.0 * pi ) * exp ( - 0.5 * pow ( ( ( rvValue - mu ) / sigma ), 2.0 ) );
	return oneOverRootTwoPi * exp ( - 0.5 * pow ( ( ( rvValue - mu ) / sigma ), 2.0 ) );
}
```
isn't missing a sigma in the first term? I think it should be 1.0/(sigma*sqrt(2.0*pi))
Or am I wrong?
I attach a comparison of the normal pdf with mean 34 and stdv 8.5 obtained by OpenSees and by Octave.

![OpenSees_N_34_8 5](https://user-images.githubusercontent.com/38036285/81392897-a36c0300-911f-11ea-9a1e-3eb75268fa37.jpg)

![Octave_N_34_8 5](https://user-images.githubusercontent.com/38036285/81392899-a4049980-911f-11ea-90f7-5e0c798b629e.jpg)

**Comment by mhscott** [comment]
Closing the issue, fixed a while back #342
