### ISSUE TITLE
Zerolengthcontact2D

### ISSUE THREAD

**Issue by sepugua** [OpenSees/OpenSees#349]
Hello to all. I hope you are good and healthy. I'm trying to model a soil-structure interaction with the particular element zeroLengthContact2D $eleTag $sNode $mNode $Kn $Kt $mu -normal $Nx $Ny. The variables $Kn and $Kt are the penalty in the normal and tangential direction. However I do not know what value assign to those variables. If someone can help me, I would appreciate it.

https://opensees.berkeley.edu/wiki/index.php/ZeroLengthContact_Element

**Comment by mhscott** [comment]
This question would be better suited for the message board
https://opensees.berkeley.edu/community
