### ISSUE TITLE
Bug in moment release code

### ISSUE THREAD

**Issue by sewkokot** [OpenSees/OpenSees#358]
Dear Michael (@mhscott ),

The recent introduction of moment releases for elastic beams is very useful, however there must be a bug in the code. The issue is that, for example, for a portal frame, when the left end of a girder has moment release, there is non-zero bending moment for the top of the left column. For comparison I tested the moment-release example with an alternative model using equalDof solution and the later gives correct results.

The model is a portal frame with horizontal force at top left column and element uniform load on the girder (el. 2). I don't know if this is related with the element load of the element with moment-release. Also the same issue happens when -beamPoint load is present and moment-releases are at both element ends. Below I attach the two OpenSeesPy scripts and resulting section forces for comparison. In particular look at the column-girder corner for bending moments. Shear and axial forces shapes are similar but the values differ between 'release 1' and 'equalDOF' options.

Model with moment-relase:
```python
import openseespy.opensees as ops

ops.model('basic', '-ndm', 2, '-ndf', 3)  # frame 2D

H, L = 4., 6.
A, Iz = 0.09, 0.000675
E = 25.0e6

ops.node(1, 0.0, 0.0)
ops.node(2, 0.0, H)
ops.node(3, L, H)
ops.node(4, L, 0.0)

ops.fix(1, 1, 1, 1)
ops.fix(4, 1, 1, 1)

ops.geomTransf('Linear', 1)

ops.element('elasticBeamColumn', 1, 1, 2, A, E, Iz, 1)
# left end moment release
ops.element('elasticBeamColumn', 2, 2, 3, A, E, Iz, 1, '-release', 1)
ops.element('elasticBeamColumn', 3, 3, 4, A, E, Iz, 1)

ops.timeSeries('Constant', 1)
ops.pattern('Plain', 1, 1)

# element (girder) transverse load
ops.eleLoad('-ele', 2, '-type', '-beamUniform', -2., 0.)
# horizontal load
ops.load(2, 1.e1, 0., 0.)

ops.constraints('Transformation')
ops.numberer('RCM')
ops.system('BandGeneral')
ops.test('NormDispIncr', 1.0e-6, 6, 2)
ops.algorithm('Linear')
ops.integrator('LoadControl', 1)
ops.analysis('Static')
ops.analyze(1)

ops.printModel()

M2_col_top = ops.eleResponse(1, 'localForces')[5]
M2_gir_left = ops.eleResponse(2, 'localForces')[2]

print('\n - forces at left column-girder corner:')
print(f'M2_col_top: {M2_col_top}')
print(f'M2_gir_left: {M2_gir_left}')
```

equalDof model:
```python
import openseespy.opensees as ops

ops.model('basic', '-ndm', 2, '-ndf', 3)  # frame 2D

H, L = 4., 6.
A, Iz = 0.09, 0.000675
E = 25.0e6

ops.node(1, 0.0, 0.0)
ops.node(2, 0.0, H)
ops.node(22, 0.0, H)
ops.node(3, L, H)
ops.node(4, L, 0.0)

ops.equalDOF(2, 22, 1, 2)

ops.fix(1, 1, 1, 1)
ops.fix(4, 1, 1, 1)

ops.geomTransf('Linear', 1)

ops.element('elasticBeamColumn', 1, 1, 2, A, E, Iz, 1)
# left end moment release
# ops.element('elasticBeamColumn', 2, 2, 3, A, E, Iz, 1, '-release', 1)
ops.element('elasticBeamColumn', 2, 22, 3, A, E, Iz, 1)
ops.element('elasticBeamColumn', 3, 3, 4, A, E, Iz, 1)

ops.timeSeries('Constant', 1)
ops.pattern('Plain', 1, 1)

# element (girder) transverse load
ops.eleLoad('-ele', 2, '-type', '-beamUniform', -2., 0.)
# horizontal load
ops.load(2, 1.e1, 0., 0.)

ops.constraints('Transformation')
ops.numberer('RCM')
ops.system('BandGeneral')
ops.test('NormDispIncr', 1.0e-6, 6, 2)
ops.algorithm('Linear')
ops.integrator('LoadControl', 1)
ops.analysis('Static')
ops.analyze(1)

ops.printModel()

M2_col_top = ops.eleResponse(1, 'localForces')[5]
M2_gir_left = ops.eleResponse(2, 'localForces')[2]

print('\n - forces at left column-girder corner:')
print(f'M2_col_top: {M2_col_top}')
print(f'M2_gir_left: {M2_gir_left}')
```
The set of wrong section forces diagrams for moment-release feature 
![portal_frame_1_release_M](https://user-images.githubusercontent.com/12695169/84141109-ee48a580-aa52-11ea-8d34-b0419eb2c3fe.png)
![portal_frame_1_release_T](https://user-images.githubusercontent.com/12695169/84141298-41225d00-aa53-11ea-9e70-d62493b0f34b.png)
![portal_frame_1_release_N](https://user-images.githubusercontent.com/12695169/84141309-45e71100-aa53-11ea-9682-0502c1d872b1.png)

The set of correct section forces diagrams using equalDof feature
![portal_frame_1_equalDof_M](https://user-images.githubusercontent.com/12695169/84141125-f3a5f000-aa52-11ea-8231-bb693116b82a.png)
![portal_frame_1_equalDof_T](https://user-images.githubusercontent.com/12695169/84141321-4c758880-aa53-11ea-95a3-1d71651006f6.png)
![portal_frame_1_equalDof_N](https://user-images.githubusercontent.com/12695169/84141328-50090f80-aa53-11ea-9bf5-6b6f49cde6f9.png)

**Comment by mhscott** [comment]
Hello Seweryn,

Thanks for looking into this and providing a straightforward example.

It appears I didn't implement the 'localForce' option in getResponse to include releases.

Michael
________________________________

**Comment by sewkokot** [comment]
I observed that the same issue occurs when using 'globalForce' option in eleResponse. Moreover, the global displacement (U) vector is different in both cases. Below you can find the stiffness matrices and output from 'printModel()' for nodes. It is interesting that when using '-release' option we don't get two distinct rotations at node 2, which is the case when using 'equalDOF' (nodes 2 and 22). Therefore the sizes of matrices are also different 7x7 vs 6x6.

- model with 'equalDOF'
```
K:
[[ 378164.062       0.       6328.125 -375000.          0.          0.          0.   ]
 [      0.     563437.5         0.          0.       -937.5      2812.5      2812.5  ]
 [   6328.125       0.      16875.          0.          0.          0.          0.   ]
 [-375000.          0.          0.     378164.062       0.       6328.125       0.   ]
 [      0.       -937.5         0.          0.     563437.5     -2812.5     -2812.5  ]
 [      0.       2812.5         0.       6328.125   -2812.5     28125.       5625.   ]
 [      0.       2812.5         0.          0.      -2812.5      5625.      11250.   ]]

 Node: 1
	Coordinates  : 0 0
	Disps: 0 0 0
	 unbalanced Load: 0 0 0
	ID : -1 -1 -1

 Node: 2
	Coordinates  : 0 4
	Disps: 0.00328014 -6.85326e-06 -0.00123005
	 unbalanced Load: 10 0 0
	ID : 0 1 2

 Node: 3
	Coordinates  : 6 4
	Disps: 0.00326039 -1.44801e-05 -0.000459966
	 unbalanced Load: 0 0 0
	ID : 3 4 5

 Node: 4
	Coordinates  : 6 0
	Disps: 0 0 0
	 unbalanced Load: 0 0 0
	ID : -1 -1 -1

 Node: 22
	Coordinates  : 0 4
	Disps: 0.00328014 -6.85326e-06 -0.000305257
	 unbalanced Load: 0 0 0
	ID : 0 1 6
```

* model with '-release 1'
```
[[ 378164.062       0.       6328.125 -375000.          0.          0.   ]
 [      0.     563671.875    4218.75        0.      -1171.875    2812.5  ]
 [   6328.125    4218.75    33750.          0.      -4218.75     8437.5  ]
 [-375000.          0.          0.     378164.062       0.       6328.125]
 [      0.      -1171.875   -4218.75        0.     563671.875   -2812.5  ]
 [      0.       2812.5      8437.5      6328.125   -2812.5     25312.5  ]]

 Node: 1
	Coordinates  : 0 0
	Disps: 0 0 0
	 unbalanced Load: 0 0 0
	ID : -1 -1 -1

 Node: 2
	Coordinates  : 0 4
	Disps: 0.00196654 -5.21344e-06 -0.000367401
	 unbalanced Load: 10 0 0
	ID : 0 1 2

 Node: 3
	Coordinates  : 6 4
	Disps: 0.00195027 -1.61199e-05 -1.07561e-05
	 unbalanced Load: 0 0 0
	ID : 3 4 5

 Node: 4
	Coordinates  : 6 0
	Disps: 0 0 0
	 unbalanced Load: 0 0 0
	ID : -1 -1 -1
```

**Comment by mhscott** [comment]
Thanks for pointing out the error.  It was an issue with static matrices.  #376
