### ISSUE TITLE
TwoNodeLink: nodes have differing dof at ends for the element

### ISSUE THREAD

**Issue by Xing90** [OpenSees/OpenSees#377]
Hi,
I am trying to use TwoNodeLink element to connect a node with dof=2 and another node with dof=3 in 2D model. However, I can't get the analysis result because it shows that nodes have differing dof at ends for the element as shown below.

“TwoNodeLink: setDomain(): nodes 7 and 5 have differing dof at ends for element: 5”

Could anyone help me to solve this problem? Thank you very much!

**Comment by mhscott** [comment]
The TwoNodeLink element works only for two nodes with the same DOF, like a zero length element, but with length.

You will need to look into using contact elements for connecting nodes with different DOFs.

Michael

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
o: 1-541-737-6996
OpenSees blog: www.portwooddigital.com<https://outlook.office.com/mail/options/mail/messageContent/www.portwooddigital.com>
________________________________
