### ISSUE TITLE
DegradingPinchedBW is missing

### ISSUE THREAD

**Issue by vpapanik** [OpenSees/OpenSees#379]
When trying to compile the latest code, a linker error appears because DegradingPinchedBW material is missing.

Commenting out DegradingPinchedBW material in TclModelBuilderUniaxialMaterialCommand.cpp resolves the issue.

**Comment by mhscott** [comment]
This is on Windows, correct?  Until the project files are updated, you can add the DegradingPinchedBW material to the Visual Studio workspace.

The model should be included in the Makefiles for Linux.

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
o: 1-541-737-6996
OpenSees blog: www.portwooddigital.com<https://outlook.office.com/mail/options/mail/messageContent/www.portwooddigital.com>
________________________________

**Comment by vpapanik** [comment]
Yes, Windows it is. I added DegradingPinchedBW.h and .cpp to material/uniaxial and it worked. Thanks a lot !
