### ISSUE TITLE
reset command and Fatigue material

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#384]
Invoking the reset command on a model with the Fatigue material will cause the element with Fatigue to fail. This makes the reset command useless for models using Fatigue.
`# Define model
model BasicBuilder -ndm 2 -ndf 3

# Create nodes
node 1 0 0
node 2 1 0
fix 1 1 1 1
fix 2 0 1 1

# Define materials
uniaxialMaterial Elastic 1 100.0
uniaxialMaterial Fatigue 2 1

# Create element
element truss 1 1 2 10.0 2

# Define analysis
constraints Plain
numberer Plain
system BandGeneral
test EnergyIncr 1.e-8 100
algorithm Newton
integrator LoadControl 0.1
analysis Static

# Run analysis
puts "Analyzing once"
analyze 1
puts "Resetting"
reset
puts "Analyzing again"
analyze 1
`

**Comment by mhscott** [comment]
Thanks for bringing this up.  The revertToStart method in FatigueMaterial was resetting some parameters to zero that it should not have been.  Fixed now #385

**Comment by mhscott** [comment]
Also, thank you for providing an easy minimum working example :)

**Comment by ambaker1** [comment]
Glad this could finally be fixed! I tried reporting it before on the forums and the support tab on the OpenSees website, but no response. Thank you for your prompt reply.
