### ISSUE TITLE
ASDShell

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#386]
What's so bad about just using double X[4]?  The more non-standard items you use, the more difficult it is for others to compile.  #frustrating 

@MassimoPetracca 

I have -std=c++11 in my Makefile.def

ASDShellQ4.cpp: At global scope:
ASDShellQ4.cpp:257:56: error: array must be initialized with a brace-enclosed initializer
         std::array<double, 4> X = { 0.0, 0.0, 0.0, 0.0 };
                                                        ^
ASDShellQ4.cpp:257:56: error: too many initializers for ‘std::array<double, 4ul>’
ASDShellQ4.cpp:258:56: error: array must be initialized with a brace-enclosed initializer
         std::array<double, 4> Y = { 0.0, 0.0, 0.0, 0.0 };
                                                        ^
ASDShellQ4.cpp:258:56: error: too many initializers for ‘std::array<double, 4ul>’
ASDShellQ4.cpp:259:56: error: array must be initialized with a brace-enclosed initializer
         std::array<double, 4> b = { 0.0, 0.0, 0.0, 0.0 };
                                                        ^
ASDShellQ4.cpp:259:56: error: too many initializers for ‘std::array<double, 4ul>’
ASDShellQ4.cpp:260:56: error: array must be initialized with a brace-enclosed initializer
         std::array<double, 4> c = { 0.0, 0.0, 0.0, 0.0 };
                                                        ^
ASDShellQ4.cpp:260:56: error: too many initializers for ‘std::array<double, 4ul>’
ASDShellQ4.cpp:265:56: error: array must be initialized with a brace-enclosed initializer
         std::array<double, 4> g = { 0.0, 0.0, 0.0, 0.0 };
                                                        ^
ASDShellQ4.cpp:265:56: error: too many initializers for ‘std::array<double, 4ul>’
ASDShellQ4.cpp: In member function ‘int ASDShellQ4::calculateAll(Matrix&, Vector&, int)’:

**Comment by MassimoPetracca** [comment]
Dear Prof.

**Comment by mhscott** [comment]
Thanks for finding the issue.  I will submit a PR to incorporate the workaround.
