### ISSUE TITLE
Wiki documentation

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#391]
I’m not sure if this is the right place for this - but the OpenSees wiki’s LaTeX math engine is not working, which makes it very difficult to read the documentation.

**Comment by mhscott** [comment]
The documentation will be moved to a new platform by the end of summer.  The math will probably be removed or ported to Markdown.

https://opensees.github.io/OpenSeesDocumentation/index.html

**Comment by ambaker1** [comment]
Awesome! Thanks for the info.
