### ISSUE TITLE
Output Commands for Fibre/Section Information

### ISSUE THREAD

**Issue by cslotboom** [OpenSees/OpenSees#392]
Hey Team, 

Thanks for all your hard work!

I'm following up a community thread about getting fibre/section information.
In the thread, asked about about getting fibre information with an output command, something like:
i.e. sectionFiber(eleTag, secNum) = [fibre_x, fibre_y, fibre_z]

I was also following up about getting element element information, something like area, depth, width, etc for non-fibre sections. It sounded like that was more difficult.

Being able to output section/fiber information would be helpful to better visualize what is internally going on in fiber sections, as well make "thickened" visualizations of models.

**Comment by mhscott** [comment]
There is a "fiberData" option in the fiber section setResponse that will return the fiber area, location, stress, and strain.

**Comment by cslotboom** [comment]
Hey - thanks.
For some reason I didn't realize you could use the "eleResponse" command in this way.
i.e. 
`
out = op.eleResponse(1, 'section', '1', "fiberData" )
`
This will work perfectly for my purposes.
