### ISSUE TITLE
Linking errors in Visual Studio

### ISSUE THREAD

**Issue by MassimoPetracca** [OpenSees/OpenSees#393]
Dear all, 
@fmckenna @mhscott , currently the visual studio projects does not compile due to some linking errors about:

- DegradingPinchingBW
- ElementRecorderRMS
- NodeRecorderRMS

Their source are missing in the VS projects, but the OPS_*** methods are called, thus the link error. Should those OPS_*** methods be removed, or should their source code be added to VS project files?

**Comment by ahartloper** [comment]
Thanks for the heads-up for these. I assume some new functionality was added, but not to the VS project.
