### ISSUE TITLE
Segmentation fault at opensees command "analyse 1"

### ISSUE THREAD

**Issue by sewkokot** [OpenSees/OpenSees#41]
I found a bug which has been caused by commit 9b208dba 
"fmk - adding gitignore, bug fix force beam columns if rho, moving load from addInertia load to getResistingForce for line elements". Just the previous commit  90fda164 "Update README" from Fri Sep 14 14:53:48 2018 -0700 works with the same tcl model file.

As you can see in the gdb debugging messages the problem is related to using forceBeamColumn2d, addVector etc. In my opensees model I use forceBeamColumn 2d elements and fiber sections. If needed I can create a small example to reproduce the problem. The problem happens when OpenSees is compiled both by gnu or intel compilers.

$ gdb openseesX13 model22.tcl
...
(gdb) run
...
Program received signal SIGSEGV, Segmentation fault.
0x0000555555968765 in Vector::addVector(double, Vector const&, double) ()
(gdb) bt full
#0  0x0000555555968765 in Vector::addVector(double, Vector const&, double) ()
No symbol table info available.
#1  0x00005555563de27f in ForceBeamColumn2d::getResistingForce() ()
No symbol table info available.
#2  0x00005555562f971e in FE_Element::addRtoResidual(double) ()
No symbol table info available.
#3  0x00005555565ca094 in StaticIntegrator::formEleResidual(FE_Element*) ()
No symbol table info available.
#4  0x000055555629f2ad in LoadControl::formEleResidual(FE_Element*) ()
No symbol table info available.
#5  0x00005555562f950d in FE_Element::getResidual(Integrator*) ()
No symbol table info available.
#6  0x00005555565c92c4 in IncrementalIntegrator::formElementResidual() ()
No symbol table info available.
#7  0x00005555565c8d3c in IncrementalIntegrator::formUnbalance() ()
No symbol table info available.
#8  0x000055555628a7c1 in NewtonRaphson::solveCurrentStep() ()
No symbol table info available.
#9  0x0000555556286f7d in StaticAnalysis::analyze(int) ()
No symbol table info available.
#10 0x00005555558cf3fc in analyzeModel(void*, Tcl_Interp*, int, char const**) ()
No symbol table info available.
#11 0x00007ffff79c2689 in TclInvokeStringCommand ()
   from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#12 0x00007ffff79c4a96 in TclNRRunCallbacks () from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
No symbol table info available.
#13 0x00007ffff79c564a in ?? () from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
No symbol table info available.
#14 0x00007ffff7a7f438 in Tcl_FSEvalFileEx () from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
No symbol table info available.
#15 0x00007ffff7a7dcc7 in Tcl_EvalFile () from /usr/lib/x86_64-linux-gnu/libtcl8.6.so
No symbol table info available.
#16 0x00005555558ce740 in g3TclMain(int, char**, int (*)(Tcl_Interp*), int, int) ()
No symbol table info available.
#17 0x00005555558c2158 in main ()
No symbol table info available.

**Comment by mhscott** [comment]
Hi Seweryn, can you upload a simple example that reproduces the error?  Thanks!

**Comment by mhscott** [comment]
Seweryn, I found the issue.  The size of the 'load' vector (recently added by @fmckenna) was not initialized in the element constructor.  I've updated it and will make a pull request.

**Comment by sewkokot** [comment]
Hi Michael, I confirm the issue is fixed in your Opensees fork. Thank you!
