### ISSUE TITLE
Memory error when calling sendSelf() for ForceBeamColumn2d

### ISSUE THREAD

**Issue by mckee107** [OpenSees/OpenSees#410]
When invoking sendSelf() on ForceBeamColumn2d with the save command, there is a memory allocation error. Running in the release version (3.2.0), the program crashes and exits. Running in debug mode shows that when creating the vector dData for sendSelf() (line 1828), there is an exception thrown in malloc_base.cpp.

I have attached an input script that demonstrates the issue. 
[TestSaveState1.zip](https://github.com/OpenSees/OpenSees/files/4984103/TestSaveState1.zip)

```
# Codi McKee
# Texas A&M University
# 27-Jul-2020

# ----------------------
# Initialize
puts "\tInitialize..."; after 20;
wipe;	

file mkdir "Input";
file mkdir "Output";

# ----------------------
# Build model
#
puts "\tBuild Model..."; after 20;
model basic -ndm 2 -ndf 3;
geomTransf	Corotational 1;

node 1 [expr 0] [expr 0];
node 2 [expr 120] [expr 0];
node 3 [expr 240] [expr 0];

fix 1 1 1 0;
fix 3 0 1 0;

# ----------------------
# Materials
#
puts "\tMaterials..."; after 20;

uniaxialMaterial ReinforcingSteel 1 60 100 29000 15000 0.003 0.5

# uniaxialMaterial Concrete04 tag? fpc? epsc0? epscu? Ec0? <ft? etu? <beta?>> <-res rf? epscf?>
uniaxialMaterial Concrete04 2 -6.00 -0.004102 -0.008835 4511 

# ----------------------
# Sections
#
puts "\tSections..."; after 20;
section	Fiber 1	{ ;
#		Core
	patch rect 2 30 30 -8.500 -8.500 8.500 8.500 ;
#		Cover
	patch rect 2 10 30 -8.500  -11.00  8.500 -8.500  ;	# Left
	patch rect 2 10 30 -8.500   8.500   8.500  11.00 ;	# Right
	patch rect 2 10 10  8.500  -11.00  11.00 11.00 ;	# Top
	patch rect 2 10 10 -11.00 -11.00 -8.500  11.00 ;	# Bot
#		Steel
	layer straight 1 4 0.440 -8.500 -8.500 -8.500 8.500 ;
	layer straight 1 2 0.440 -2.83 -8.50 -2.83 8.50 ;
	layer straight 1 2 0.440  2.83 -8.50  2.83 8.50 ;
	layer straight 1 4 0.440  8.500 -8.500  8.500 8.500 ;
 };
 
# ----------------------
# Elements
#
puts "\tElements..."; after 20;

element forceBeamColumn 1 1 2 10 1 1
element forceBeamColumn 2 2 3 10 1 1
# element elasticBeamColumn 1 1 2 10 29000 1000 1;
# element elasticBeamColumn 2 2 3 10 29000 1000 1;

# ----------------------
# Loads
#
puts "\tLoads..."; after 20;
pattern Plain 1 Linear {
load 2 0 [expr 10]  0
}


# ----------------------
# Apply Loads
#
set maxDisp [expr -1.0];
set Nsteps 100;  
set Dsteps [expr (1.0*$maxDisp/$Nsteps)]; 	
set Tol 1.0e-6;	
set MaxIter 1000;
set TestType NormUnbalance ;
set AlgType Newton;
constraints Transformation;     		
numberer RCM;			
system BandGeneral 
test $TestType $Tol $MaxIter 5; 
algorithm Newton;			
integrator DisplacementControl  2 2 $Dsteps;
analysis Static;	

puts "\tApply Loads..."; after 20;	
analyze [expr int($Nsteps)];		

puts "\tSave State..."; after 20;	
set currentTime [getTime];
puts "\t\tCurrent time = $currentTime";
puts "\t\tMake database...";
database File "DB_1";
puts "\t\tSave...";
save 1;
puts "\tSaved..."; after 20;

wipe;
```

**Comment by mhscott** [comment]
Thanks for providing a pretty straightforward example!  Before trying it out, I just want to make sure that you're sure it's the ForceBeamColumn2d, i.e., if you use geomTransf Linear or section Elastic or uniaxialMaterial Elastic with the fiber section, do you *not* get a database error?

**Comment by mckee107** [comment]
Here's what happens when I try it with different options:

- **w/ geomTranf Linear:** Works fine
- **w/ section Elastic:** crashes creating Vector dData in ForceBeamColumn2d sendSelf(). Debugger shows _"Vector::Vector(int) - out of memory creating vector of size 38"_
- **w/ uniaxialMaterial Elastic:** works fine

I don't know enough about the inner workings of programs to know what else to test or any possible causes.

**Comment by mhscott** [comment]
Codi,
Thanks!  That helps a lot.
Michael
________________________________

**Comment by mhscott** [comment]
I ran the script on Ubuntu with the latest source code from GitHub and there was no problem.
Which operating system are you using and which version number of OpenSees?

**Comment by mckee107** [comment]
I am using Windows 10 with version 3.2.0 downloaded from the website. I also have the issue when I compile the source code in Visual Studio with the latest updates. The issue is consistent when using the model input I provided. I have not tested on a different computer, but I can do that and let you know.

**Comment by mckee107** [comment]
Okay apparently it's just an issue on my laptop. I ran the code on my desktop, and it worked fine.

**Comment by mhscott** [comment]
It's probably a memory leak in the code, perhaps somewhere else.  That's usually the case with machine-dependent errors like this.

**Comment by mckee107** [comment]
How is a memory leak like this fixed?

**Comment by mhscott** [comment]
There are utilities to check for memory leaks.  I only know a couple linux tools like valgrind and electric fence (efence).
The model you sent is small enough to make some sense out of what valgrind reports, so I'll give that a try.

**Comment by jaabell** [comment]
Was this fixed? Need help?

**Comment by mhscott** [comment]
Nothing definitive from valgrind.  I suspect it's those static pointers vsSubdivide, etc. allocated as 'new' in the constructor that are causing problems with databases.  I'll do a PR and @mckee107 can try it out to see if there's still an issue.

**Comment by mhscott** [comment]
Give it a try now @mckee107 #415

**Comment by mckee107** [comment]
That appears to have fixed this problem, using the elastic section. If I use a fiber section with the ReinforcingSteel material, there is a similar issue with line 753:   res = theChannel.sendVector(this->getDbTag(), cTag, data);. 
I tried with Steel02, and it worked fine. 

Thanks!

**Comment by mhscott** [comment]
That might have been an error in ReinforcingSteel::send/recvSelf.  I just updated it, give it a try.

**Comment by mckee107** [comment]
That did the trick. Thank you!

**Comment by mhscott** [comment]
Cool!  I'll update the 3D and other versions that do the same thing with the static variables.
