### ISSUE TITLE
PSUMAT link error

### ISSUE THREAD

**Issue by johnnyontheweb** [OpenSees/OpenSees#419]
Hello, 
is PSUMAT routine available to all? Can it be found anywhere?
It's a call to an external routine in PlaneStressUserMaterial.cpp, I have to disable the preprocessor symbol _HAVE_PSUMAT to compile.

**Comment by u-anurag** [comment]
See this discussion here #269.

**Comment by johnnyontheweb** [comment]
Thanks, I read this - in the last post, FMK tells that it is avaialble for windows, but no place to retrieve the lib.
If it is include, which is the lib containing the code?

If not, IMHO this material has to be removed. There are other ways to use external material, see DEVELOPER folder.

**Comment by mhscott** [comment]
Search for PSUMAT in DoddRestrepo.lib, it should be in there
