### ISSUE TITLE
Query of mass for elements with mass density

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#424]
The command nodeMass allows the user to query the mass assigned to a node. However, if mass is assigned to an element, there is no way to query it.

Example: 

```
model BasicBuilder -ndm 2
node 1 0 0
node 2 1 0
geomTransf Linear 1
element elasticBeamColumn 1 1 2 10.0 1000.0 100.0 1 -mass 1.0
fix 1 1 1 1
puts [eigen -fullGenLapack 1]
puts [nodeMass 1 1]
puts [nodeMass 1 2]
puts [nodeMass 1 3]
puts [nodeMass 2 1]
puts [nodeMass 2 2]
puts [nodeMass 2 3]
```

All the nodeMass queries return 0.0, even though mass clearly exists, as an eigen analysis works.

**Comment by mhscott** [comment]
Alex,

I suppose you could get the full mass matrix using the MCK integrator (https://wp.me/pbejzW-FH), then subtract off the nodal masses to get the element contributions to the mass matrix 🙂

Michael
________________________________

**Comment by mhscott** [comment]
The nodes only store nodal mass and element mass is assembled during the analysis.

**Comment by ambaker1** [comment]
Ok, but how do I know which nodes/dofs the rows/columns correspond to?
```
model BasicBuilder -ndm 2
node 1 0 0
node 2 1 0
geomTransf Linear 1
element elasticBeamColumn 1 1 2 10.0 1000.0 100.0 1 -mass 1.0
fix 1 1 1 1
puts [eigen 1]
system FullGeneral
integrator GimmeMCK 1 0 0
analyze 1 0.0
puts [printA]
puts [nodeMass 2 1]
puts [nodeMass 2 2]
puts [nodeMass 2 3]
```
In this situation, it returns a 3x3 matrix, even though there are two 3-dof nodes. I am assuming in this case that it is removing the fixed DOFs, but for a large model, how can I know which DOFs are which?

**Comment by mhscott** [comment]
ops.nodeDOFs(nodeTag) returns the equation numbers for the node.

________________________________

**Comment by ambaker1** [comment]
I am using OpenSees 3.2.2, Tcl version, Windows 10, and it does not recognize the command.

**Comment by mhscott** [comment]
I see.  It's only been added to the Python interpreter.  A lot of these utiliity commands have duplicate code in SRC/tcl/commands.cpp and SRC/interpreter/OpenSeesOutputCommands.cpp, so we need to figure out a better way to handle these functions.

If it's urgent, i can add the nodeDOFs command to Tcl.  Just let me know.

________________________________

**Comment by ambaker1** [comment]
I wouldn't say it is urgent, I think for now I can just use the nodeMass command to get my mass matrix - since the models I am currently using don't use element mass. But if it could be added in the next version, that'd be great!
-Alex

**Comment by mhscott** [comment]
I added the nodeDOFs command to Tcl just now.  It should be in the next version, or now if you're compiling from source code.

**Comment by fmckenna** [comment]
remember the mass matrix should come from the element, the nodal mass matrix approach with the gimmeMK is only going to work for the lumped mass matrix approach, i.e. you are missing the off block diagonal terms.

**Comment by mhscott** [comment]
The GimmeMCK is an integrator that assembles mass just like Newmark and other integrators, so the element mass should be there.

________________________________

**Comment by ambaker1** [comment]
Thank you for all the clarification and for fixing the nodeDOFs command for the future :)
