### ISSUE TITLE
Compiling issues in VS2019 

### ISSUE THREAD

**Issue by csasj** [OpenSees/OpenSees#428]
I’m having troubles compiling OpenSees in VS2019 after following the instructions [How to compile the OpenSeesPy for windows in VS2019 zhuminjie/OpenSeesPyDoc#167](https://github.com/zhuminjie/OpenSeesPyDoc/issues/167) . I’m working with the source code of the last commit on 15/08/2020.  

The error messages displayed are in the screenshot below. 

![issue](https://user-images.githubusercontent.com/69809839/90514128-0af30f00-e161-11ea-838d-e5999626a63a.PNG)

The LINK error related to ‘matrix.lib’ doesn’t seem to be a path problem. I’ve already manually added the **ifconsol.lib** as well as the others and  also checked that the libraries path were correctly included in the project. 

Thank in you in advance for your support.

**Comment by mhscott** [comment]
The ID::fill method was not returning a value.  Linux compiler allows this, but not VS.  I updated the code to return 0, should compile now.
