### ISSUE TITLE
section Aggregator command to add the Shear force-deformation

### ISSUE THREAD

**Issue by gooddaytogo** [OpenSees/OpenSees#430]
Hi, everybody,

I am using the section Aggregator command to add the Shear force-deformation to the existing fiber section, but I am confused about how to define the Shear force-deformation relation by using the uniaxialMaterial.

As described, uniaxialMaterial represents uniaxial stress-strain (or force-deformation) relationships, I am confused when using the uniaxialMaterial, should we use stress-strain relation of the material or force-deformation relation of the section and how OpenSees handles it? Thanks.

**Comment by mhscott** [comment]
Please post modeling questions to the OpenSees message board: opensees.berkeley.edu/community

The issues for this GitHub repo are for compiling and development of OpenSees.
