### ISSUE TITLE
Different result from 2D & 3D model

### ISSUE THREAD

**Issue by Xing90** [OpenSees/OpenSees#434]
Hi everyone,
I am trying to do a pushover analysis for a single-bay single-floor steel frame. I have tried a 2D model and got good results. However, when I build the same model in 3D （it's still a 2D frame but in 3D model）, the results were completely different. I'm wondering why the results of a 2D frame in 3D model were wrong. Could anyone help me to relieve my confusion？Thank you very much！

**Comment by mhscott** [comment]
Please post modeling questions on the OpenSees message board: http://opensees.berkeley.edu/community
