### ISSUE TITLE
E013 class "Element" has no member "getRayleigh

### ISSUE THREAD

**Issue by csasj** [OpenSees/OpenSees#446]
I changed my computer and now I've got this error (see figure below) and I can't compile OpenSees. In my old machine I've never got this error and I could work with my own compiled version (last commit was on 14 Sep). 

![error_getRay](https://user-images.githubusercontent.com/69809839/93664593-7e45b480-fa70-11ea-860b-ccb2bc2a1d68.PNG)

For some reason now it doesn't recognize the function but the Element.h and Element.cpp files haven't changed. 

![image](https://user-images.githubusercontent.com/69809839/93664836-16906900-fa72-11ea-925b-871d12f05fb2.png)

Thank you in advance for your support.

**Comment by mhscott** [comment]
Make sure _DLL is not defined in your project preprocesser settings.


--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
o: 1-541-737-6996
OpenSees blog: www.portwooddigital.com<https://outlook.office.com/mail/options/mail/messageContent/www.portwooddigital.com>
________________________________

**Comment by csasj** [comment]
Thanks. The issue is solved.
