### ISSUE TITLE
Issue with OpenSees installation Tcl library files

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#451]
The OpenSees installation for Tcl only includes the init.tcl file in the tcl8.6 folder. Shouldn't it contain all the main Tcl library files?
Without all the main Tcl library files, some functionalities are missing, such as the ability to load in packages with the "package require" command.
I downloaded the source for Tcl 8.6.10 and moved the library files over to the tcl8.6 folder, and this fixed the missing functionality.

**Comment by fmckenna** [comment]
They are .. but 99.9% of users don’t need the missing functions .. the
knowledgeable ones do install their own tack and remove the lib for
altogether

**Comment by ambaker1** [comment]
Ok, just wanted to bring it to attention.
