### ISSUE TITLE
Steel4 in parallel analysis

### ISSUE THREAD

**Issue by basharhariri** [OpenSees/OpenSees#464]
I would like to report that OpenSeesSP does not accept the Steel4 material to run if the number of processors selected for the analysis exceeds 1. 

     FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 87
     WARNING Truss::recvSelf() - 10000102 failed to get a blank Material of type 87
     10000102 failed to send its Material
     WARNING Truss::sendSelf() - 10000112 failed to send its Material

**Comment by mhscott** [comment]
It looks like Steel4 was not included in SRC/actor/FEMObjectBrokerAllClasses.cpp.  Not uncommon :)

**Comment by mhscott** [comment]
Fixed #465.  Let us know if you run into any more of these.

**Comment by mhscott** [comment]
Note: Steel4 still needs sendSelf/recvSelf to be implemented

**Comment by basharhariri** [comment]
This means the Steel4 material needs also be updated to work in OpenSeesSP. I wonder whether this can be done from your end, or we need to contact Zsarnóczay.
Thank you

**Comment by mhscott** [comment]
We can do it.  It's pretty straightforward.

**Comment by basharhariri** [comment]
Perfect :)

**Comment by basharhariri** [comment]
I would like to report that the problem still exists!

**Comment by mhscott** [comment]
Because we haven't implemented sendSelf/recvSelf yet 😄 

There's a lot of data in this model, so it won't be so straightforward.
