### ISSUE TITLE
Error compiling OPS Release 3.2.0 on arm64 machine

### ISSUE THREAD

**Issue by gferman** [OpenSees/OpenSees#468]
Hello everyone!

I'm trying to compile OpenSees Release 3.2.0 on a RaspBerry Pi 4B 8GB (arm64) with Ubuntu 20.10. I use the `Makefile.def.EC2-UBUNTU` makefile with the modifications expained by [Vijay Polimeru](https://vijaypolimeru.github.io/research/opensees/programming/ubuntu/2020/02/02/compile-opensees-ubuntu.html).

Everything worked fine until compiling the ARPACK library. The following error message appears:

```
make[1]: Entering directory '/home/gferman/OpenSees/OTHER/ARPACK'
Making dgetv0.o from dgetv0.f
/usr/bin/gfortran -Wall -O -c dgetv0.f -o dgetv0.o
dgetv0.f:404:32:

  367 |           call dvout (logfil, 1, rnorm0, ndigit,
      |                                 2
......
  404 |          call dvout (logfil, n, resid, ndigit,
      |                                1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
make[1]: *** [../../Makefile.def:252: dgetv0.o] Error 1
make[1]: Leaving directory '/home/gferman/OpenSees/OTHER/ARPACK'
```

Can someone point me out what could be wrong and how to fix it? Thanks!

-Gaston

**Comment by jaabell** [comment]
Apparently, there was a gfortran compiler warning that got upgraded to a compiler error in gcc 10.x.x and beyond. You can circumvent the error by using the compiler flag `-fallow-argument-mismatch`. To do this, append the `-fallow-argument-mismatch` to the `FFLAGS` variable in both definitions of the `ifdef` block. 

![Screenshot from 2020-11-30 15-57-15](https://user-images.githubusercontent.com/5404696/100651809-ca408f80-3324-11eb-8761-95c4eeb3679f.png)

I'm not sure whether this issue will bring problems to the implementation, but I'll close the issue for now. If at all, you will get errors when using ARPACK, which is only used in eigenvalue problems. So if you find any issues with modal analysis let us know!! 

@fmckenna 
@mhscott
