### ISSUE TITLE
Bug for stresses recorder in FourNodesTetrahedron

### ISSUE THREAD

**Issue by johnnyontheweb** [OpenSees/OpenSees#469]
In FourNodeTetrahedron::getResponse, the first line:
`static Vector stresses(48);`

should be:
`static Vector stresses(6);`

to avoid heap corruption writing the recorder.

**Comment by mhscott** [comment]
Agreed, thanks for pointing that out.  Fixed now: https://github.com/OpenSees/OpenSees/commit/ea22e5372def4c69c12ce4afa54db3606c4baef3
