### ISSUE TITLE
Error compling 3.2.2 and 3.2.0 opensees in cmd, only in my pc other pcs it did work

### ISSUE THREAD

**Issue by MohamedOrafi** [OpenSees/OpenSees#470]
I get erroneous results as compared to the same code run in other pcs, even though the opensees version is the exact same. What could be the reason?

**Comment by mhscott** [comment]
Can you provide more details?  Is it a compiling issue or is it an issue with versions of OpenSees that you did not compile?

**Comment by mhscott** [comment]
Closing. Will assume the issue was resolved due to non-response.
