### ISSUE TITLE
PlateFiber Recorder

### ISSUE THREAD

**Issue by alfonsogdr** [OpenSees/OpenSees#472]
Good morning to all OpenSees Community.

Following the topic on https://opensees.berkeley.edu/community/viewtopic.php?f=2&t=67876, when modeling PlateFiber sections, if we use the recorders for stress and strains in each gauss point for each layer:

recorder Element -file file_name -time -ele elem_number material gauss_point fiber layer stress/strain

we obtain S11,S22,S12,S23,S31 for stresses and Epsilon11, Epsilon22, Epsilon12, Epsilon23, Epsilon31 for strains. In layered sections we asume Plane Stress in each layer so the value of S33 will be zero but the value of Epsilon33 is not zero. I was wondering if the recording of this value could be implemented.

Thank you very much.

**Comment by mhscott** [comment]
So that I don't change the current recording functionality, would it be OK to have a separate option like strain33?

recorder Element -file file_name -time -ele elem_number material gauss_point fiber layer **strain33**

**Comment by mhscott** [comment]
Any updates on this? Closing, but re-open if this functionality is still required
