### ISSUE TITLE
Problem with definition of a new element

### ISSUE THREAD

**Issue by ehsantafakori** [OpenSees/OpenSees#483]
Hello everyone,
We studied the Structure- Soil- Structure Interaction (SSSI) effects on seismic response of structures. For this purpose, we used Opensees software to perform nonlinear time history analysis, while the stiffness matrix of soil- foundation and foundation- soil- foundation systems were obtained through static analysis of exact plain strain finite element models in Abaqus. In this method, we need to assemble the stiffness matrix to global stiffness matrix of structure's models in Opensees framework. While there is no suitable element for this purpose, we developed a new element, named ElasticSuperElement, in C language and used it to apply SSSI effects in the structure models in Opensees. In fact, a matrix as stiffness matrix and node tags are introduced in this element and the element assembles the matrix in rows and columns of the global stiffness matrix related to degree of freedoms of desired nodes. Based on necessity, we developed this element for certain numbers of nodes (20 nodes). For this propose node pointer is declared like this:
Node *theNodes[20]
We want to modify this element, in the way which can be used for n numbers of nodes. In this case node point was declared in C ++ like this:
Int NumberOfNode;
Node* theNodes = new Node{ NumberOfNode };
The code was built but encountered an error in debug step. We want to ask if this is possible to modify the element for n nodes and if it’s possible, how is the node pointer declared and how do we solve the error?

**Comment by lcpt** [comment]
Hello.

I think it's better if you use [backticks](https://www.markdownguide.org/basic-syntax#code) or indentation to denote a word or phrase as code. On the other hand, if you use curly braces `{}` instead of square brackets you are using [`{} initialization`](https://www.modernescpp.com/index.php/initialization); so, for example:

    #include <iostream>

    double *a= new double{4};

    int main(void)
      {
        std::cout << *a << std::endl;
        return 0;
      }

Will print 4 on your terminal (`a` doesn't contain four doubles, but a single double with a `4` inside).

**Comment by mhscott** [comment]
This will give you an array of Node pointers.  You don't want your element to keep its own nodes, just pointers to the nodes
`Node **theNodes = new Node*[NumberOfNode]`
For every 'new' you need a 'delete'
`delete [] theNodes`

Also, this is not an OpenSees issue, but a general programming issue, so I am closing the issue.

**Comment by ehsantafakori** [comment]
Hello Mr.Michael H. Scott
Thank you for your response. It solved my problem.

**Comment by ehsantafakori** [comment]
Hello Mr.Michael H. Scott
Thank you for your response. It solved my problem.
