### ISSUE TITLE
$a1, $a3 of SteelMPF Material doesn't work

### ISSUE THREAD

**Issue by WUDDD** [OpenSees/OpenSees#490]
for SteelMPF Material, when $a1($a3) < 0, the SteelMPF Material wouldn't be softening, but just keep same as  $a1($a3) = 0. But, when $a1($a3) > 0, the SteelMPF Material would be hardening.

**Comment by WUDDD** [comment]
when $a3 = -0.2:
![Steel_a3_Steel_-00 2000](https://user-images.githubusercontent.com/55080638/103846865-0ad8b900-50da-11eb-92fe-19273242ea91.jpg)

when $a3 = 0:
![Steel_a3_Steel_000 0000](https://user-images.githubusercontent.com/55080638/103846878-10360380-50da-11eb-9ead-c99c735c0f1a.jpg)

when $a3 = 0.2:
![Steel_a3_Steel_000 2000](https://user-images.githubusercontent.com/55080638/103846891-1926d500-50da-11eb-8491-bd012127e062.jpg)

**Comment by WUDDD** [comment]
#
![As_a3_Steel_-00 0800](https://user-images.githubusercontent.com/55080638/103846935-3065c280-50da-11eb-9b8e-baa7036d6103.jpg)

**Comment by mhscott** [comment]
Are you referring to Steel02 or SteelMPF?

**Comment by WUDDD** [comment]
> Are you referring to Steel02 or SteelMPF?
SteelMPF has problems. When $a1($a3) < 0, SteelMPF cann't be softening.
The $a1 and $a3 of Steel02 work well. Steel02 can be hardening or softening according to the value of $a1 and $a3.

**Comment by mhscott** [comment]
Can you show me the command you are inputting?  The documentation says there should be four a1--a4

https://openseespydoc.readthedocs.io/en/latest/src/SteelMPF.html

But the parsing command is trying to read six a1--a6.  If it can't find six, it just reads two: a1 and a2.

**Comment by WUDDD** [comment]
# a1=-0.05
uniaxialMaterial SteelMPF 3 358.0 358.0 203000 0.001 0.001 20 0.925 0.15 0 1 0 1
uniaxialMaterial SteelMPF 4 311.5 311.5 199000 0.001 0.001 20 0.925 0.15 -0.05 1 0 1
# a1=0
uniaxialMaterial SteelMPF 3 358.0 358.0 203000 0.001 0.001 20 0.925 0.15 0 1 0 1
uniaxialMaterial SteelMPF 4 311.5 311.5 199000 0.001 0.001 20 0.925 0.15 0 1 0 1
# a1=0.05
uniaxialMaterial SteelMPF 3 358.0 358.0 203000 0.001 0.001 20 0.925 0.15 0 1 0 1
uniaxialMaterial SteelMPF 4 311.5 311.5 199000 0.001 0.001 20 0.925 0.15 0.05 1 0 1

Here is the command I am inputting. I am simulating SRC columns in OpenSees, using material 3 for steel bars and  material 4 for i-shaped steel.
I just know the four parameters a1-- a4  from documentation of OpenSees. Can you show me the information about the six a1--a6 ?

**Comment by kkolozvari** [comment]
Per [SteelMPF user documentation](https://opensees.berkeley.edu/wiki/index.php/SteelMPF_-_Menegotto_and_Pinto_(1973)_Model_Extended_by_Filippou_et_al._(1983)) and peer Menegotto-Pinto-Filippou model formulation, parameters a1, a2, a3, a4 are for **Isotropic Strain Hardening**, not **Softening**. You shouldn't be using negative values of the parameters.
