### ISSUE TITLE
Request to add sensitivity analysis method to Concrete07 and Reinforcing Steel uniaxialmaterials

### ISSUE THREAD

**Issue by Borislav-Todorov** [OpenSees/OpenSees#494]
Concrete07.cpp and reinforcingsteel.cpp among other uniaxial materials do not have setParameter and updateParameter options available for sensitivity analysis, could this please be implemented? I do not have much experience in C++ but can contribute if necessary to expedite this

**Comment by mhscott** [comment]
It's pretty easy to do. I'll probably make a video on how to do it so that you (and others) can see the process.

**Comment by jamalT1996** [comment]
> It's pretty easy to do. I'll make a video on how to do it so that you (and others) can see the process.

Hello,
I also would like to know how to add sensitivity to plasticdamageconcrete3d.cpp. Please let me know if you made the video.
Sincerely.

**Comment by mhscott** [comment]
I haven't made a video, so I recommend looking at other materials with an implementation of setParameter and updateParameter
