### ISSUE TITLE
Compiling errors in VS2019

### ISSUE THREAD

**Issue by Slopezre** [OpenSees/OpenSees#495]
Hello, OpenSees community!

I am experiencing difficulties compiling OpenSees.exe in Visual Studio 2019. I am using Github's original files. I am obtaining errors 2039, 2065, 2355, 2660, and 3861 (see attached screenshots). Can you please explain how to fix it? 

Thank you

![image](https://user-images.githubusercontent.com/77215077/104111233-948cb000-52ad-11eb-8133-797af8e0f291.png)

**Comment by mhscott** [comment]
The issue with getRayleighDampingForces is addressed at about 20:00 in this video: https://youtu.be/BLcY1w7a5Ec

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
o: 1-541-737-6996
OpenSees blog: www.portwooddigital.com<https://outlook.office.com/mail/options/mail/messageContent/www.portwooddigital.com>
________________________________

**Comment by Slopezre** [comment]
Thank you, Professor Scott. Problem solved!
