### ISSUE TITLE
Steady-state response to harmonic load (quasi-static problem)

### ISSUE THREAD

**Issue by sewkokot** [OpenSees/OpenSees#498]
I'm interested in solving the steady-state harmonic response due to
the steady-state harmonic load for an undamped model.

The load is as follows
F(t) = F0 * sin(p * t)
where 'p' is a circular frequency (rad/s) of the harmonic load, and F0 is a global amplitude vector
of nodal loads.

Therefore starting from the following equation of motion

M a(t) + K u(t) = F0 * sin(p * t)

this equation can be simplified to the system of algebraic equations

Since the response is harmonic
u(t) = u0 * sin(p * t) and
a(t) = -p^2 * u0 * sin(p * t)

the steady-state response comes from the following
quasi-static equation

(K - p^2 M) u0 = F0   or simply written as  
Kmod * u = F0        (as in statics Ku = F)

The F0 amplitude load distribution can be taken from the
loadPattern/load/eleLoad commands (timeSeries can be neglected here), 
only the excitation frequency 'p' should be specified somewhere.

Is there an easy way to implement it? Any hints on what classes
(integrator?) should be modified or a new command should be added similar to 'eigen'?

Thank you in advance for any help.

**Comment by mhscott** [comment]
Hello Seweryn,

You can solve the original equation of motion M a(t) + K u(t) = F0 * sin(p * t) with a 'Sine' timeSeries and nodal load on an SDF system, or with a uniformExcitation.

Michael

**Comment by sewkokot** [comment]
Thank you, Michael, however I need the steady-state response of a MDOF system and I want to avoid the transient analysis. I have a test example using the 'Trig/Sine' timeSeries with rayleigh damping to get rid of the transient phase, but it's time consuming. I need to do thousands of repetitions for various parameters so the direct quasi-static solution would be optimal.

A workaround would be to use your GimmeMCK integrator commands to get the K and M matrices and finally solve for the amplitudes using numpy's solve function:
u0 = np.linalg.solve(K - (p*p)*M, F0)

It seems that the standalone 'steadyStateResponse' command can be implemented natively in OpenSees, similarly to responseSpectrum from the following PR
https://github.com/OpenSees/OpenSees/pull/485

I will look at the responseSpectrum implementation to figure out the solution for the steady-state response. Any hints on how to implement it in OpenSees would be appreciated :)

**Comment by mhscott** [comment]
Can you make a subclass of StaticIntegrator, similar to LoadControl, that adds factors for M,C,K like GimmeMCK does? I can help out if you have questions. @fmckenna gave some insights, I think we know how to do it.

**Comment by sewkokot** [comment]
@mhscott, @fmckenna thank you a lot! Your last response helped me to solve the task with minimal effort. 

I created a new HarmonicSteadyState subclass as you wrote, then added what follows to HarmonicSteadyState.cpp file and it magically worked :) I didn't expect it to be that simple.
```
int
HarmonicSteadyState::formEleTangent(FE_Element *theEle)
{
    theEle->zeroTangent();
    theEle->addKtToTang();
    theEle->addMtoTang(-loadCircFreq*loadCircFreq);
    return 0;
}
```

**Comment by mhscott** [comment]
Great!  The loadCircFreq is private data set in the constructor?

**Comment by sewkokot** [comment]
Yes, indeed, the loadCircFreq (p - circular frequency of excitation rad/s as shown the formulas above) is a private variable in the constructor and is defined by user as an argument in the integrator command:
```
p = 300.  # circular frequency of excitation in rad/s
ops.integrator('HarmonicSteadyState', 1.0, 1, 1, 1, p) 
```
For my quick and dirty implementation I just appended the new argument to the existing ones in the LoadControl integrator and I was interested in the solution for an undamped linear elastic conditions (e.g. a verification example in Sap2000 based on Structural Dynamics textbook by Paz).

**Comment by mhscott** [comment]
Seems like it's working, so going to close the issue.

**Comment by tmsmendez** [comment]
Hello @mhscott, @sewkokot:

I am interested in performing this type of steady state harmonic analysis. Any chance this functionality could be added to the next version of OpenSees?

Best regards,

**Comment by sewkokot** [comment]
@tmsmendez, thanks to @fmckenna  and @mhscott , it's basically an additional StaticIntegrator subclass.I will do some code cleanup, rebase it to current main branch and prepare a PR.

**Comment by sewkokot** [comment]
@tmsmendez, @fmckenna and @mhscott, I have created the PR https://github.com/OpenSees/OpenSees/pull/723
