### ISSUE TITLE
WARNING could not create uniaxialMaterial

### ISSUE THREAD

**Issue by essi87** [OpenSees/OpenSees#50]
Hello everyone, 
I am trying to add new material in opensees using  windows. I was able to create .dll file. When I run an example it gives me this error: WARNING could not create uniaxialMaterial ...... 
Does anyone knows what the problem is? 

Thanks,

**Comment by talledodiego** [comment]
The path should be find by your opensees.exe so the problem should be that one. your dll file could be in the same folder of opnsees.exe or in the same folder of your tcl files or in any folder you want, providing you add that folder to the system PATH variable.

Then it should work.

Diego

**Comment by essi87** [comment]
Could you clarify further on adding the folder to the system Path variable?

Thanks,
Ehsan

**Comment by talledodiego** [comment]
https://stackoverflow.com/questions/9546324/adding-directory-to-path-environment-variable-in-windows

**Comment by sj138** [comment]
@essi87 How did you solve this problem? Even I am having this problem.

**Comment by sa-jalali** [comment]
The best way for adding a new material to OpenSees is to add it to the source code and build a new OpenSees.exe file. The dll method occasionally encounters problems like what you just mentioned. Working with the "material" project in OpenSees source is quite easy; you just need to add your .h and .cpp files to it. However, you also need to manipulate the "TclModelBuilderUniaxialMaterialCommand.cpp" file located in the same project so that your new material command can be identified by OpenSees.

**Comment by imeg** [comment]
@essi87  if you are c# or Matlab programmer you can try this 
[Implementation of new element and material for OpenSees in .NET environment (C# and MATLAB)
](http://opensees.net/blog/Implementation-of-new-element-and-material-for-OpenSees-in-.NET-environment-(Csharp-and-MATLAB))

https://www.youtube.com/watch?v=rEDNtXR9RwY

**Comment by erikemondt** [comment]
for me this solved the issue (on windows):

In "ElasticPPcpp.cpp" , change

#ifdef _USRDLL
#define OPS_Export extern "C" _declspec(dllexport)
#elif _MACOSX
#define OPS_Export extern "C" attribute((visibility("default")))
#else
#define OPS_Export extern "C"
#endif

into:

#define OPS_Export extern "C" _declspec(dllexport)

**Comment by mhscott** [comment]
We are going to remove the DLL stuff and will make videos on how to add elements and material to OpenSees without DLLs, which cause too many problems.
