### ISSUE TITLE
Return values for printA, printB commands

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#500]
A limitation of the printA and printB commands is that they either print to file or to screen. It would be helpful if they could also return the matrix or vector. It appears this is only an issue for Tcl, since OpenSeesPy seems to not have this limitation (https://github.com/volkanozsarac/ModalAnalysis-OpenSeespy/blob/master/ModalAnalysis.py)

**Comment by mhscott** [comment]
The Python command returns a list, which you then have to convert to a matrix (or vector). Can linalg in Tcl take a list and convert to matrix/vector?

**Comment by ambaker1** [comment]
Yes, if it returns a list with newlines delineating rows, you can split by newline to get a matrix.

**Comment by mhscott** [comment]
Might be best to do in your scripts using a loop with Nequations from systemSize

**Comment by ambaker1** [comment]
Couldn't it just redirect what would go to a file or screen, and return the value instead? I know when it prints to file, it prints the rows on separate lines. If that is too much of a hassle though, just a list would be fine as it could be reshaped into a matrix.

**Comment by mhscott** [comment]
Is this resolved now?
