### ISSUE TITLE
ElasticPPGap initial tangent

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#510]
The ElasticPPGap material is well suited for post-tensioning rods and strands, but does not currently work with the InitStressMaterial wrapper. This is because when the ElasticPPGap material is created, it does not initialize the "trialTangent" value, which is queried by the InitiStressMaterial. Here's a MWE to replicate the issue.

```
model BasicBuilder -ndm 2
uniaxialMaterial ElasticPPGap 1 29000.0 50.0 0.0
uniaxialMaterial InitStressMaterial 2 1 10.0
```

**Comment by mhscott** [comment]
Probably needs a little bit of logic to set initial tangent in the constructor, right? Something like set initial tangent to E if there is no gap, otherwise set initial tangent to zero?

**Comment by ambaker1** [comment]
All I did in the pull request is make it so that initializing the material (or reverting to start) calls the "setTrialStrain" function, which initializes the trialTangent as you mention.

**Comment by mhscott** [comment]
OK, I will close this issue and head over to the PR
