### ISSUE TITLE
Cannot open "PML.lib" when compiling Win64 Visual Studio project

### ISSUE THREAD

**Issue by mckee107** [OpenSees/OpenSees#514]
I am getting this linker error when compiling the debug version of the Win64 project. It compiles fine with the release version. Is this PML.lib located somewhere in the repo, so that I can link the location?

**Comment by mhscott** [comment]
Find where PML.lib is located in the release project settings (Linker tab), then copy over to the debug settings

**Comment by mckee107** [comment]
The only thing I can find with PML is that it's listed as an "additional library", but doesn't have a location. I found the "PML.lib" file located in the ../../lib/release/ folder though. Was this library manually placed in that folder by the contributor? Or am I missing something. I did find that there is a preprocessor definition listed for the element project called "_HAVE_PML_", is this something that can be used to avoid dealing with the pml library?

**Comment by mhscott** [comment]
@parduino Does PML.lib need to be compiled and added to lib/debug?

**Comment by parduino** [comment]
> 
> 
> The only thing I can find with PML is that it's listed as an "additional library", but doesn't have a location. I found the "PML.lib" file located in the ../../lib/release/ folder though. Was this library manually placed in that folder by the contributor? Or am I missing something. I did find that there is a preprocessor definition listed for the element project called "_HAVE_PML_", is this something that can be used to avoid dealing with the pml library?

The PML.lib has been created for the WIN64 release version and not yet the debug version.
You are correct in relation to the _HAVE_PML. It can be used to completely bypass PML in Windows. 
This is not a problem for the Linux distribution

**Comment by mhscott** [comment]
Were you able to get this compiled in Debug mode, @mckee107, with the _HAVE_PML undefined?

**Comment by mckee107** [comment]
No, removing the _HAVE_PML preprocessor definition from the element project did not work. The linker is still looking for the PML.lib. Either I'm doing something wrong, or the _HAVE_PML definition isn't properly implemented.

**Comment by parduino** [comment]
Hi Mike

   I did not compile it yet for debug.
Setting the _HAVE_PML  in BS should be enough.
I will check.

Pedro

**Comment by parduino** [comment]
Correct. Let me compile the library for debug too.

Pedro

**Comment by mckee107** [comment]
It compiles fine now, with the pml.lib copied from the ../lib/release folder to ../lib/debug. I'll keep an eye out for commits related to this, but I suppose it's resolved for now...

**Comment by parduino** [comment]
Great, but, I expect that if you try to use the PML element using your windows debug version it will not work.
Have you try compiling the release version??

**Comment by mckee107** [comment]
@parduino The release version compiles fine. If you can give me an example script, I can see if there are issues running the program with the PML element in the debug mode.

**Comment by fmckenna** [comment]
it will work fine .. you just won't be able to debug it

**Comment by parduino** [comment]
Frank,

  I did not know you can still link.
But it makes sense.

Pedro
