### ISSUE TITLE
Issue with compiling in visual studio 2019

### ISSUE THREAD

**Issue by harshmistry96** [OpenSees/OpenSees#518]
Hi, 

I am trying to add new material in Opensees. Just for starter, I tried to build the ElasticPP material example following the steps provided on the website. Following is the error:
------------------------------------------------------------------------------------------------------------------------------------
1>Generating Code...
1>   Creating library C:\Users\harsh\source\repos\OpenSees\DEVELOPER\material\ElasticPP\x64\Debug\ElasticPP.lib and object C:\Users\harsh\source\repos\OpenSees\DEVELOPER\material\ElasticPP\x64\Debug\ElasticPP.exp
1>Domain.obj : error LNK2019: unresolved external symbol "void __cdecl OPS_printSectionForceDeformation(class OPS_Stream &,int)" (?OPS_printSectionForceDeformation@@YAXAEAVOPS_Stream@@H@Z) referenced in function "public: virtual void __cdecl Domain::Print(class OPS_Stream &,int)" (?Print@Domain@@UEAAXAEAVOPS_Stream@@H@Z)
1>Domain.obj : error LNK2019: unresolved external symbol "void __cdecl OPS_printCrdTransf(class OPS_Stream &,int)" (?OPS_printCrdTransf@@YAXAEAVOPS_Stream@@H@Z) referenced in function "public: virtual void __cdecl Domain::Print(class OPS_Stream &,int)" (?Print@Domain@@UEAAXAEAVOPS_Stream@@H@Z)
1>C:\Users\harsh\source\repos\OpenSees\DEVELOPER\material\ElasticPP\x64\Debug\ElasticPP.dll : fatal error LNK1120: 2 unresolved externals
1>Done building project "ElasticPP.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
--------------------------------------------------------------------------------------------------------------------------------------

Could someone please help with dealing this error?

Kind Regards,
Harsh Mistry

**Comment by mhscott** [comment]
I haven't seen those types of errors before. Try to compile following these videos

https://youtube.com/playlist?list=PL8NMUJpRHALHg9gkeYUUc2r8GTnr9dINf

**Comment by harshmistry96** [comment]
Okay i will try and let you know. 
Thank you

**Comment by harshmistry96** [comment]
Hi, 
@mhscott  I tried the steps shown in the video but still I'm getting following error:

Build started...
1>------ Build started: Project: OpenSees, Configuration: Debug x64 ------
1>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/FORCE' specification
1>   Creating library .\..\..\bin\OpenSees.lib and object .\..\..\bin\OpenSees.exp
1>actor.lib(FEM_ObjectBrokerAllClasses.obj) : error LNK2019: unresolved external symbol "public: __cdecl RockingBC::RockingBC(void)" (??0RockingBC@@QEAA@XZ) referenced in function "public: virtual class Element * __cdecl FEM_ObjectBrokerAllClasses::getNewElement(int)" (?getNewElement@FEM_ObjectBrokerAllClasses@@UEAAPEAVElement@@H@Z)
1>element.lib(TclElementCommands.obj) : error LNK2019: unresolved external symbol "void * __cdecl OPS_RockingBC(void)" (?OPS_RockingBC@@YAPEAXXZ) referenced in function "int __cdecl TclModelBuilderElementCommand(void *,struct Tcl_Interp *,int,char const * *,class Domain *,class TclModelBuilder *)" (?TclModelBuilderElementCommand@@YAHPEAXPEAUTcl_Interp@@HPEAPEBDPEAVDomain@@PEAVTclModelBuilder@@@Z)
1>.\..\..\bin\OpenSees.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "OpenSees.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 24 up-to-date, 0 skipped ==========

Thank you for the help in advance!

**Comment by mhscott** [comment]
RockingBC is a recent addition, so it may not be in the VS project. You can add it manually.

**Comment by harshmistry96** [comment]
Hi,
@mhscott Thank you, it finally worked.

**Comment by mhscott** [comment]
Good to hear!
