### ISSUE TITLE
Suggestion for the alpha values while using Penalty Constraint in Openseespy

### ISSUE THREAD

**Issue by harshmistry96** [OpenSees/OpenSees#520]
Hi,

I am trying to modify the effective site response analysis example (opensees) and was wondering as to which criteria should be considered while providing the "alphaS" and "alphaM" value. The elastic gravity analysis works perfectly, but when i update the material to stage 1, then the plastic gravity analysis take very long time execute just a single iteration. 

Can someone please help with this issue.

Kind Regards,
Harsh Mistry

**Comment by mhscott** [comment]
Please post modeling questions like this either on the OpenSees message board (opensees.berkeley.edu/community) or the Facebook group.
