### ISSUE TITLE
DisplacementControl integrator not working for opposite sign loads and disp increments

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#524]
Here's a MWE that works in release 3.2.2 but not in current master branch:
```
# Different signs on loads and disp control don't work in current version
# Feb 5th, 2021 
# Alex Baker

model BasicBuilder -ndm 2

# Vars
set L 1.0
set A 100.0
set E 10000.0
set I 1000.0

# Nodes
node 1 0 0
node 2 0 $L
fix 1 1 1 1

# Element
geomTransf Linear 1
element elasticBeamColumn 1 1 2 $A $E $I 1

# Loads
pattern Plain 1 Linear {
    load 2 1.0 0 0
}

puts "Should have [expr {3*$E*$I/$L**3}] .."

# Analysis settings
wipeAnalysis
constraints Plain
numberer RCM
system FullGeneral
test EnergyIncr 1.0e-8 10
integrator DisplacementControl 2 1 -0.01
algorithm Newton
analysis Static
puts "[getTime] [nodeDisp 2 1]"
for {set i 0} {$i < 100} {incr i} {
    analyze 1
    puts "[getTime] [nodeDisp 2 1]"
}
```

**Comment by ambaker1** [comment]
Or should I say MNWE, minimum not working example...

**Comment by imeg** [comment]
check this file
https://github.com/OpenSees/OpenSees/blob/master/SRC/analysis/integrator/EQPath.cpp
syntax
integrator EQPath $arc_length $type
opserr << "WARNING integrator $arc_length $type \n";
			opserr << "$type = 1 Minimum Residual Displacement \n";
			opserr << "$type = 2 Normal Plain \n";
			opserr << "$type = 3 Update Normal Plain \n";
			opserr << "$type = 4 Cylindrical Arc-Length \n";

**Comment by sewkokot** [comment]
Bisecting gives me this commit: 5520366a
and the getFactor method:
```
 LinearSeries::getFactor(double pseudoTime)
 {
-  return cFactor*pseudoTime;
+  if (pseudoTime < tStart)
+    return 0.0;
+  else
+    return cFactor*(pseudoTime-tStart);
```
Just keeping only the last 'return' line fixes the problem for tStart=0, but I didn't test it with tStart!=0

**Comment by mhscott** [comment]
Thanks @sewkokot!  This was my doing, @ambaker1.  I added a time offset to the linear series, which is messing with the initial post-tensioning in your model.

**Comment by ambaker1** [comment]
Ah, I remember seeing your pull request for the linear series. Are you just going to revert that change then? It makes cyclic pushovers impossible. 
I don't know what you mean about initial post-tensioning, my post-tensioning doesn't use the linear time-series, just initial strain on my material.

**Comment by mhscott** [comment]
Yeah, I meant whatever you were doing for the initial state of your model, prior to pushover.
I'll revert the change and create a new time series. I didn't realize the change would have such effects.

**Comment by ambaker1** [comment]
Ah, I see. Sounds good, glad we could catch it and find the issue!

**Comment by mhscott** [comment]
I could just make the default start time -BIGNUMBER instead of 0.0

**Comment by ambaker1** [comment]
That wouldn't work though. Then at t= 0.0, with cFactor of 1.0, you would get load factor of BIGNUMBER

**Comment by mhscott** [comment]
Oh yeah, duh!

**Comment by ambaker1** [comment]
You almost need an "Elastic-No-Tension" style time-series to get what you were trying to add.

**Comment by mhscott** [comment]
I think I can make it return -factor*time when time < 0, otherwise use the start time when time > 0
That should solve both issues.

**Comment by ambaker1** [comment]
That's kind-of confusing, don't you think? I think Linear time series should just be that - linear. You could specify a start-time, but it should still be a single straight line in my opinion.

**Comment by mhscott** [comment]
Yeah, I'll just make a new time series.
Try it now after revert #526

**Comment by ambaker1** [comment]
Yup, works now!
