### ISSUE TITLE
SteelMPF isotropic hardening not the same as Steel02

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#540]
The uniaxial material _SteelMPF_ was supposedly created as an improvement upon _Steel02_. The main differences were fixing a load-memory issue with _Steel02_, and incorporating asymmetric yield stress and kinematic hardening ratios. However, the isotropic hardening was not mentioned as something that was changed (Kolozvari 2015). This difference is not likely to be caught if using the recommended parameters a1 = 0.01, a2 = 7.0, a3 = 0.01, and a4 = 7.0, since these isotropic hardening values create little to no effect. Using larger values, such as a1 = 0.1, a2 = 1.0, a3 = 0.1, and a4 = 1.0, the effects become clear.

I created two materials, using effectively the same properties, but the hysteresis are different. Without isotropic hardening, they are identical.
```
set fy 42.0
set E 29000.0
set b 0.005
set R 25
set cR1 0.90
set cR2 0.15
set a1 0.1
set a2 1
set a3 0.1
set a4 1
uniaxialMaterial Steel02 1 $fy $E $b $R $cR1 $cR2 $a1 $a2 $a3 $a4
uniaxialMaterial SteelMPF 2 $fy $fy $E $b $b $R $cR1 $cR2 $a1 $a2 $a3 $a4
```
![Steel02vsSteelMPF](https://user-images.githubusercontent.com/48138840/108394506-c5340380-71e2-11eb-8daf-3949d186667a.png)

Kolozvari, K., Orakcal, K., & Wallace, J. (2015). Shear-flexure interaction modeling for reinforced concrete structural walls and columns under reversed cyclic loading. Pacific Earthquake Engineering Research Center, University of California, Berkeley, PEER Report, 2015/12.

**Comment by mhscott** [comment]
@kkolozvari Can you take a look?

**Comment by ambaker1** [comment]
Looking at the source-code, it seems that SteelMPF more closely follows Filippou 1983:
![image](https://user-images.githubusercontent.com/48138840/108410013-e3a2fa80-71f4-11eb-800a-57fa8123ea31.png)
Here's the line: https://github.com/OpenSees/OpenSees/blob/bf462919e5cc959e31dfcff39f442c75b3f9adf3/SRC/material/uniaxial/SteelMPF.cpp#L564
On the other-hand, the Steel02 source code does something totally different:
![image](https://user-images.githubusercontent.com/48138840/108410076-f61d3400-71f4-11eb-8d09-5c8f979c5b07.png)
Here's the line: https://github.com/OpenSees/OpenSees/blob/bf462919e5cc959e31dfcff39f442c75b3f9adf3/SRC/material/uniaxial/Steel02.cpp#L345

**Comment by kkolozvari** [comment]
Hello, I am not familiar with Steel02 implementation, so I cannot say. We have implemented SteelMPF from scratch and we tried to follow the Filippou paper the best we could. One important difference is that SteelMPF overcomes issue with stress overshooting upon partial unloading as demonstrated in the figure below (Improved=SteelMPF vs Original=Steel02). For this, we had to implement additional history variables. 

![image](https://user-images.githubusercontent.com/53920372/108410981-eeea2c00-71dc-11eb-9f8a-125ed4d65ff6.png)

**Comment by ambaker1** [comment]
Hello, thanks for your reply. Your fix on the load-reversal error is one of the main reasons I want to use your material. I am modeling BRBs and looking for general asymmetric steel model. Yours appeared to be the simplest without going to rough bilinear models. I just want to make sure I understand the implementation of isotropic strain hardening, and the difference from the more widely used Steel02 was of concern for me. I see now that your model is more true to the Filippou 1983 paper. Now I am just curious where the equation in the Steel02 code came from.

**Comment by kkolozvari** [comment]
Great! I am glad you find it useful. Please note that SteelMPF has another unique feature, which is degradation of R parameter depending on the load history in the **elastic** range. Filippou paper is not specific on this (if I recall correctly), and this was our interpretation. We have noticed that sometimes this provides better results, sometimes not. If you have many cycles in the elastic range, the radius of the transition curve becomes too large. Let me know if this is an issue for you down the road. I have been meaning to implement a switch for this, but never found the time. This could motivate me to finally do it. Let me know. Thanks

**Comment by ambaker1** [comment]
Yeah, I don't think that'll be an issue - shouldn't the degradation of R be fixed within whatever strain range you are in? If you had fixed cycles, wouldn't R remain the same? R is related to the strain difference of the excursion, as can be seen in this figure from Filippou 1983:
![image](https://user-images.githubusercontent.com/48138840/108450379-1d92f180-7233-11eb-830b-71e6b012561f.png)
I was doing some testing, and your model seems to match Filippou's paper exactly. Here was the load history shown in Filippou that I was trying to match:
![image](https://user-images.githubusercontent.com/48138840/108450514-5b901580-7233-11eb-8335-1be3204db06e.png)
Here's how Steel02 and SteelMPF compare:
![image](https://user-images.githubusercontent.com/48138840/108451332-a0687c00-7234-11eb-9595-7ac98e378397.png)
Perhaps the issue should be the application of isotropic hardening in Steel02! Also Steel01, I checked and it uses the same equation as Steel02. I have not been able to find any documentation or publication explaining the different equation.
