### ISSUE TITLE
Get modelstate dt in WrapperElement

### ISSUE THREAD

**Issue by johnnyontheweb** [OpenSees/OpenSees#547]
In WrapperElement.c there's this code:
```
    // get the current load factor
    Domain *theDomain=this->getDomain();
    double time = theDomain->getCurrentTime();
    double dt = theDomain->getCurrentTime() - time;

    theModelState.time = time;
    theModelState.dt = dt;
```

_dt_ is always 0. How to get the current _dt_ from _Domain_? It should be corrected in all functions of WrapperElement.
thanks in advance

**Comment by johnnyontheweb** [comment]
Hello, please find attached the diff files for get _dt_ into WrapperElement, hope this will be merged in OS master branch.
In addition, some messages for debugging purposes, active only when _DEBUG directive is present.

[patchWrElem.zip](https://github.com/OpenSees/OpenSees/files/6069380/patchWrElem.zip)

**Comment by mhscott** [comment]
Please submit the changes as a pull request.

________________________________

**Comment by johnnyontheweb** [comment]
I can't, I have only a local copy of repo - please consider importing from diff files.

**Comment by mhscott** [comment]
I dot not understand why that is the case. We only accept code through PRs and will do our best to fix the issue ourselves.

**Comment by mhscott** [comment]
Actually, @fmckenna fixed it yesterday.
https://github.com/OpenSees/OpenSees/commit/1f8c29feab4ae0d64f5bfd9186789c0386cf926b
Please merge your local repo and verify it works.

**Comment by johnnyontheweb** [comment]
I didn't check the repo today - but why not to write here that the fix was already done ...

**Comment by mhscott** [comment]
Sorry, I checked the file and saw that it was modified yesterday. Noted in my previous comment.
