### ISSUE TITLE
Add "eleType" utility command

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#552]
This should be an easy implementation - add a command (I suggest the name "eleType") that returns a string of the element type. E.g. truss or elasticBeamColumn. Basically, exactly the same as is inputted in the element command. 
Different elements have different recorder queries, different number of nodes, and different number of degrees-of-freedom, so this command would help write scripts that are dependent on element type.
Example use (creating recorders for different element types):
```
foreach eleTag [getEleTags] {
    switch [eleType $eleTag] {
        truss {
            lappend trussTags $eleTag
        }
        elasticBeamColumn {
            lappend ebcTags $eleTag
        }
    }
}
recorder Element -file trussForce.out -ele {*}$trussTags axialForce
recorder Element -file ebcForces.out -ele {*}$ebcTags force
```

**Comment by mhscott** [comment]
Most elements implement getClassType, so should be easy to make a Tcl/Python function

https://github.com/OpenSees/OpenSees/blob/master/SRC/actor/actor/MovableObject.h

**Comment by ambaker1** [comment]
I created a pull request for this feature: #560
