### ISSUE TITLE
"testUniaxialMaterial" not available for Tcl interpreter

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#572]
The command "testUniaxialMaterial" currently does not work for the Tcl interpreter, despite being in "SRC/interpreter/OpenSeesCommandsTcl.cpp"

MWE:
```
model basic -ndm 1
uniaxialMaterial Elastic 1 29000.0
testUniaxialMaterial 1
```

As a side note, will "testUniaxialMaterial" replace the "UniaxialMaterialTest" model builder? And if so, will there be equivalent commands for the "PlaneStressMaterialTest" and "SectionForceDeformationTest" builders?

**Comment by mhscott** [comment]
It's a different model builder (testUniaxial):

https://github.com/OpenSees/OpenSees/blob/master/SRC/modelbuilder/tcl/myCommands.cpp

We'll sort out the testers as part of Python/Tcl cleanup

**Comment by ambaker1** [comment]
I am aware of the different test model builders, but the implementation in python is much better than creating a new model builder. Looking forward to the cleanup.
