### ISSUE TITLE
Algorithm ExpressNewton

### ISSUE THREAD

**Issue by Likuikui12** [OpenSees/OpenSees#599]
I have updated to 3.3.0, and the update log shows that a new algorithm has been updated: Algorithm ExpressNewton, but when I use it, it shows an unknown algorithm. Do you have such a situation? How can I solve it?

**Comment by mhscott** [comment]
Looks like the source code was added but the interpreter commands were not. We'll add those in for a future version.

**Comment by mhscott** [comment]
Just making sure, but you're talking about the Python interpreter, not Tcl, correct?

**Comment by mhscott** [comment]
https://github.com/OpenSees/OpenSees/pull/658

**Comment by Likuikui12** [comment]
yeah,so when we can ues Algorithm ExpressNewton in openseespy ,thanks






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael H. ***@***.***&gt;; 
发送时间: 2021年9月7日(星期二) 凌晨1:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OpenSees/OpenSees] Algorithm ExpressNewton (#599)





 
Just making sure, but you're talking about the Python interpreter, not Tcl, correct?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mhscott** [comment]
I added it to Python in PR https://github.com/OpenSees/OpenSees/pull/658. It should be in the next release.
