### ISSUE TITLE
OpenSees GPU solution

### ISSUE THREAD

**Issue by iLongStone** [OpenSees/OpenSees#605]
When I used an older version of OpenSees(v2.4.3), I was able to use the CUSP library and successfully implemented GPU-based accelerated solution.But when I use the new version of OpenSees(v3.0.3 or later), when I apply the _System CuSP_ command, the OpenSees will simply exit the operation with no error code or information.I see  the GPU calculation file of the new version has no change with that of the past version in the source code. Could you tell me why it is not possible to use GPU to solve the library CUSP? I  look forward to your reply sincerely!
My software environment is as follows: Windows 10 ,GPU GTX 1050, CUDA 11.2, OpenSees(v3.0.3 and later  versions).

**Comment by iLongStone** [comment]
![image](https://user-images.githubusercontent.com/66901108/123092188-cc06a780-d45c-11eb-8572-bb3a7ae816c2.png)

**Comment by mhscott** [comment]
Do you have CuSPSolver.dll installed on your computer? I can't help you further, but that might be the issue.

![image](https://user-images.githubusercontent.com/13142652/132252176-446bbc83-30e7-47e7-85ad-90ec89853d91.png)

**Comment by mhscott** [comment]
OpenSees.exe should now give a warning if the solver is unknown or not installed

https://github.com/OpenSees/OpenSees/commit/80b5220bfc0e79a46ebbda10333d58fb1d43479d
