### ISSUE TITLE
Eigenvalue analysis failed due to fortran error

### ISSUE THREAD

**Issue by wnduan** [OpenSees/OpenSees#63]
Hello everyone,

I've compiled OpenSees from commit ecbdf68. When I run verification scripts in `EXAMPLE/verification` everything works fine except those scripts with eigenvalue analysis, which leads to a `forrtl` error, like:

```bash
PortalFrame2d.tcl: Verification 2d Elastic Frame
  - eigenvalue and static pushover analysis
forrtl: severe (408): fort: (19): Dummy character variable 'WHICH' has length 2 which is greater than actual variable length -3689348814741910324

Image           PC                  Routine        Line        Source
OpenSees.exe    000000014083DC11    Unknown        Unknown    Unknown
OpenSees.exe    00000001407DF9E1    DSAUPD             516    dsaupd.f
...
```

I found that calling `eigen` command leads to the problem.

The compilation was taken with Visual Studio 2017 + Intal Fortran Compiler 19.0 + ActivTcl 18.6 on Windows 10 64bit system. This is the first time I try to compile an OpenSees executable on Windows, so I have no idea if I've miss configured some stuff or doing something bad during compilation. Does anyone have an idea about this issue?

#### Update:

The previous issue only happens when compiling a `Debug x64` version, since today I tried a `Release` compile and all the verification scripts are OK now. I still can't tell, however, what's going wrong in a `Debug` compile process. It might be the `Win64/lib/debug/arpack.lib` caused the problem here, I guess. 

Anyway, the problem is partially solved for me. I hope this would be helpful to someone else.

**Comment by TJhsl** [comment]
Do you know about the error ' fatal error C1083: Cannot open include file: “tk.h”: No such file or directory'? What do you mean about trying a Release compile? Win32? Please help me. I will appreciate baot that.

**Comment by TJhsl** [comment]
Have you solved the problem with Eigenvalue analysis?

**Comment by sa-jalali** [comment]
> Hello everyone,
> 
> I've compiled OpenSees from commit [ecbdf68](https://github.com/OpenSees/OpenSees/commit/ecbdf6850013a2552f17006c252d1c9252e7787d). When I run verification scripts in `EXAMPLE/verification` everything works fine except those scripts with eigenvalue analysis, which leads to a `forrtl` error, like:
> 
> ```shell
> PortalFrame2d.tcl: Verification 2d Elastic Frame
>   - eigenvalue and static pushover analysis
> forrtl: severe (408): fort: (19): Dummy character variable 'WHICH' has length 2 which is greater than actual variable length -3689348814741910324
> 
> Image           PC                  Routine        Line        Source
> OpenSees.exe    000000014083DC11    Unknown        Unknown    Unknown
> OpenSees.exe    00000001407DF9E1    DSAUPD             516    dsaupd.f
> ...
> ```
> 
> I found that calling `eigen` command leads to the problem.
> 
> The compilation was taken with Visual Studio 2017 + Intal Fortran Compiler 19.0 + ActivTcl 18.6 on Windows 10 64bit system. This is the first time I try to compile an OpenSees executable on Windows, so I have no idea if I've miss configured some stuff or doing something bad during compilation. Does anyone have an idea about this issue?
> 
> #### Update:
> The previous issue only happens when compiling a `Debug x64` version, since today I tried a `Release` compile and all the verification scripts are OK now. I still can't tell, however, what's going wrong in a `Debug` compile process. It might be the `Win64/lib/debug/arpack.lib` caused the problem here, I guess.
> 
> Anyway, the problem is partially solved for me. I hope this would be helpful to someone else.

Hi.
The issue is related to how the compiled code passes variables to the FORTRAN function being called. In debug version, VS has a problem (either in compiling or in run-time I'm not sure) that prevents proper passing of the variable.

**Comment by ehsantafakori** [comment]
Hello everyone,
I have same problem when I build opensees 3.03 and use eigen command  

forrtl: severe (408): fort: (19): Dummy character variable 'WHICH' has length 2 which is greater than actual variable length -3689348814741910324

Image              PC                Routine            Line        Source
OpenSees.exe       00000001400A3BDE  Unknown               Unknown  Unknown
OpenSees.exe       00000001400012D1  DSAUPD                    516  dsaupd.f
OpenSees.exe       00000001412A2CD8  Unknown               Unknown  Unknown
OpenSees.exe       00000001412A20A9  Unknown               Unknown  Unknown
OpenSees.exe       00000001402CDA04  Unknown               Unknown  Unknown
OpenSees.exe       00000001401C92D0  Unknown               Unknown  Unknown
tcl86t.dll         00007FF940606108  Unknown               Unknown  Unknown
tcl86t.dll         00007FF940608193  Unknown               Unknown  Unknown
tcl86t.dll         00007FF94060995D  Unknown               Unknown  Unknown
tcl86t.dll         00007FF9406DA2AB  Unknown               Unknown  Unknown
tcl86t.dll         00007FF9406094F5  Unknown               Unknown  Unknown
tcl86t.dll         00007FF9406A8F13  Unknown               Unknown  Unknown
tcl86t.dll         00007FF9406A6FFE  Unknown               Unknown  Unknown
OpenSees.exe       00000001401B93DB  Unknown               Unknown  Unknown
OpenSees.exe       00000001401B8E31  Unknown               Unknown  Unknown
OpenSees.exe       00000001412B1C44  Unknown               Unknown  Unknown
OpenSees.exe       00000001412B1B57  Unknown               Unknown  Unknown
OpenSees.exe       00000001412B1A1E  Unknown               Unknown  Unknown
OpenSees.exe       00000001412B1C59  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF970BE4034  Unknown               Unknown  Unknown
ntdll.dll          00007FF970D33691  Unknown               Unknown  Unknown

**Comment by ahartloper** [comment]
Are you building debug or release?

**Comment by erikemondt** [comment]
Check [https://github.com/OpenSees/OpenSees/issues/148](url) for steps on how to solve this, let me know if you have any more questions.

**Comment by erikemondt** [comment]
Don't follow the instructions you might find on the intel helpdesk when googling the error.

1) compile in release mode and check if the error occurs again. If not, you're lucky!  You can be 100% sure the mistake is due to a project setting that is different for the debug configuration. 

2) In system>project settings>c/c++>preprocessor>preprocessor definitions, debug configuration, delete "__WIN32". Compile, check if it worked.

3) If not, make sure the general project properties are correct, and the linker properties as well. 
If your release configuration was working, you can simply compare these.  Some differences are supposed to be there though, only make changes which are sensible, and write down your changes!!!!!

**Comment by mhscott** [comment]
We're cleaning up old issues.  If this problem still exists, please start a new issue.
