### ISSUE TITLE
Floating mass

### ISSUE THREAD

**Issue by dareoperatingsystem** [OpenSees/OpenSees#633]
Hi,
Is it possible for someone to apply large mass method in Ansys to OpenSees? For base excitation, you define a large mass and fix the to be restraint joints with constraints to the large mass joint. Then only apply earthquake acceleration to the large mass (large mass times ground acceleration in the only large mass degree of freedom). Is it possible for someone to make this available? It is very difficult for me to do since I do not know the source code and it is also in c++. This method is sometimes used in Ansys and it has theorthical value.
In normal, you apply minus whole mass matrix times base acceleration on the right hand side of dynamic equation.
In this one, you define a big mass and the right hand side is plus large mass times base excitation and all other degree of freedoms related to masses are zero.
For referance in example you can look
https://www.eng-tips.com/viewthread.cfm?qid=97815

**Comment by mhscott** [comment]
This sounds like more of a modeling question than an implementation issue.
Please post this question on the OpenSees message board: https://opensees.berkeley.edu/community/
Or the OpenSees Facebook group: https://www.facebook.com/groups/opensees
