### ISSUE TITLE
OpenSeesMP Error while testing ParallelModel Example

### ISSUE THREAD

**Issue by jaidip15** [OpenSees/OpenSees#641]
Hello All,
We are trying to run Parallel Model OpenSeesMP example located here - https://github.com/OpenSees/OpenSees/tree/master/EXAMPLES/ParallelModelMP

We were able to successfully compile Opensees Mp with MPI - mvapich2, GCC 11 on centos (RHEL7.7).
To test that OpenseesMP is correctly working or not. we simply tried the below command and it got failed.

FYI - OpenseesMP is working fine for this example - https://github.com/OpenSees/OpenSees/tree/master/EXAMPLES/SmallMP

Any suggestion what would be the cause of this error? or we are testing the example in the wrong way?

Command:
mpirun -np 3 OpenSeesMP exampleMP.tcl

Output:

OpenSees -- Open System For Earthquake Engineering Simulation
Pacific Earthquake Engineering Research Center
Version 3.3.0 64-Bit

(c) Copyright 1999-2016 The Regents of the University of California
All Rights Reserved
(Copyright and Disclaimer @ http://www.berkeley.edu/OpenSees/copyright.html)

[cli_2]: aborting job:
Fatal error in PMPI_Bcast:
Invalid communicator, error stack:
PMPI_Bcast(1645): MPI_Bcast(buf=0x3f21498, count=1, MPI_INTEGER, root=0, comm=0x0) failed
PMPI_Bcast(1546): Invalid communicator

[cli_0]: aborting job:
Fatal error in PMPI_Bcast:
Invalid communicator, error stack:
PMPI_Bcast(1645): MPI_Bcast(buf=0x37522c8, count=1, MPI_INTEGER, root=0, comm=0x0) failed
PMPI_Bcast(1546): Invalid communicator

[cli_1]: aborting job:
Fatal error in PMPI_Bcast:
Invalid communicator, error stack:
PMPI_Bcast(1645): MPI_Bcast(buf=0x50270c8, count=1, MPI_INTEGER, root=0, comm=0x0) failed
PMPI_Bcast(1546): Invalid communicator

Please, let me know any suggestions you may have on how to solve this problem!

Thank you

**Comment by mhscott** [comment]
Closing. Re-open if needed.
