### ISSUE TITLE
Fortran DLL compilation Error

### ISSUE THREAD

**Issue by mauropoliotti** [OpenSees/OpenSees#65]
Hi everyone, im struggling with the compilation of the uniaxial material written on Fortran that is on the developers folder as an example.
 
Im using VS2017, i defined a new fortran project of an empty dll and i included the 3 files elasticPPf, materialAPI, and material Type. Itried to compile the solution and i get :

Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error	error LNK2019: símbolo externo _OPS_Error sin resolver al que se hace referencia en la función _LOCALINIT	elasticPPf.obj	
Error	error LNK2019: símbolo externo _OPS_GetIntInput sin resolver al que se hace referencia en la función _ELASTICPPF	elasticPPf.obj	
Error	error LNK2019: símbolo externo _OPS_GetDoubleInput sin resolver al que se hace referencia en la función _ELASTICPPF	elasticPPf.obj	
Error	error LNK2019: símbolo externo _OPS_AllocateMaterial sin resolver al que se hace referencia en la función _ELASTICPPF	elasticPPf.obj	

In the compilation properties I tried different options, on the External Procedures window I tried to change the Name Case Interpretation to every posible option (Upper Case, Lower Case, As-is) but none of them worked.

Any ideas on whats going on??' Is there any path that I have to define??

Thanks

**Comment by erikemondt** [comment]
Dear mauropoliotti,

I am facing the exact same problem. Did you manage to solve it?

**Comment by mauropoliotti** [comment]
Dear erikmondt, I havent solved this problem. I migrated my code from Fortran to C++. It took  some time but at the end it worth the effort. Doing it directly in C++ will alow you to use objects like matrix or vectors with useful procedures for algebraic operations. 
Sorry i can't be of more help.
