### ISSUE TITLE
Compilation error with DistributedSuperLU

### ISSUE THREAD

**Issue by vuminhtue** [OpenSees/OpenSees#652]
Hello everyone, I am compiling OpenSees version 3.3.0 using Makefile.def.CentOS7.9 for our HPC running on CentOS8.2
I am very close to creating the OpenSeesMP. (Please note that there is no problem for OpenSees in sequential), where I face the final error:

```bash
g++: error: /software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSuperLU.o: No such file or directory
g++: error: /software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSparseGenColLinSOE.o: No such file or directory
```

I know that the output files were not created hence I went into the directory and tried to compile by myself:

```bash
cd /software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/
make
```

I then faced the following error:

```bash
In file included from /software/external/opensees/OpenSees/SRC/matrix/Vector.h:34,
                 from /software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/SparseGenColLinSOE.h:40,
                 from DistributedSuperLU.cpp:33:
/software/external/opensees/OpenSees/SRC/OPS_Globals.h:46:16: warning: unnecessary parentheses in declaration of ‘opserrPtr’ [-Wparentheses]
 #define opserr (*opserrPtr)
                ^
/software/external/opensees/OpenSees/SRC/matrix/f2c.h:95:8: note: in expansion of macro ‘opserr’
 { flag opserr;
        ^~~~~~
DistributedSuperLU.cpp:44:1: error: ‘superlu_options_t’ does not name a type; did you mean ‘superlu_scope_t’?
 superlu_options_t options;
 ^~~~~~~~~~~~~~~~~
 superlu_scope_t
DistributedSuperLU.cpp: In member function ‘virtual int DistributedSuperLU::solve()’:
DistributedSuperLU.cpp:146:10: error: ‘options’ was not declared in this scope
     if ((options.Fact == FACTORED) && (theSOE->factored == false)) {
          ^~~~~~~
DistributedSuperLU.cpp:155:23: error: ‘options’ was not declared in this scope
     pdgssvx_ABglobal(&options, &A, &ScalePermstruct, Xptr, ldb, nrhs, &grid,
                       ^~~~~~~
DistributedSuperLU.cpp: In member function ‘virtual int DistributedSuperLU::setSize()’:
DistributedSuperLU.cpp:237:21: error: invalid conversion from ‘LUstruct_t*’ to ‘int_t’ {aka ‘int’} [-fpermissive]
     LUstructInit(n, &LUstruct);
                     ^~~~~~~~~
DistributedSuperLU.cpp:237:30: error: too few arguments to function ‘void LUstructInit(int_t, int_t, LUstruct_t*)’
     LUstructInit(n, &LUstruct);
                              ^
In file included from DistributedSuperLU.cpp:40:
/software/external/opensees/OpenSees/SRC/../OTHER/SuperLU_DIST_2.0/SRC/superlu_ddefs.h:250:16: note: declared here
 extern void    LUstructInit(const int_t, const int_t, LUstruct_t *);
                ^~~~~~~~~~~~
DistributedSuperLU.cpp:244:29: error: ‘options’ was not declared in this scope
   set_default_options_dist(&options);
                             ^~~~~~~
DistributedSuperLU.cpp:244:3: error: ‘set_default_options_dist’ was not declared in this scope
   set_default_options_dist(&options);
   ^~~~~~~~~~~~~~~~~~~~~~~~
DistributedSuperLU.cpp:244:3: note: suggested alternative: ‘set_default_options_Distributed’
   set_default_options_dist(&options);
   ^~~~~~~~~~~~~~~~~~~~~~~~
   set_default_options_Distributed
make: *** [../../../../Makefile.def:305: DistributedSuperLU.o] Error 1
```

Please let me know if you have any solution or I would appreciate if you can send me the 2 missing files: DistributedSuperLU.o and DistributedSparseGenColLinSOE.o

**Comment by vishnusakethjella** [comment]
Please can anyone of you help with this issue? @fmckenna @mhscott @ambaker1 @MassimoPetracca

**Comment by mhscott** [comment]
https://github.com/OpenSees/OpenSees/issues/90

**Comment by vuminhtue** [comment]
Thank you @mhscott for quick turn around.
I took a look at the #90 before creating this question actually, as I am not really OpenSees expert, I really do not see the linkage between the two tickets.
In #90 , the error code relates to DistributedSuperLU.cpp(237):

```
error: argument of type "LUstruct_t *" is incompatible with parameter of type "int_t={int}"
      LUstructInit(n, &LUstruct);
```

In my version, the error code relates to DistributedSuperLU.cpp:44:1

```
DistributedSuperLU.cpp:44:1: error: ‘superlu_options_t’ does not name a type; did you mean ‘superlu_scope_t’?
 superlu_options_t options;
```

**Comment by jaidip15** [comment]
Hello,
Not sure what caused the issue.. but as i have read the error message above
**In file included from DistributedSuperLU.cpp:40:
/software/external/opensees/OpenSees/SRC/../OTHER/SuperLU_DIST_2.0/SRC/superlu_ddefs.h:250:16: note: declared here
 extern void    LUstructInit(const int_t, const int_t, LUstruct_t *);**
 
 it seems in your make file you are using SuperLU_DIST_2.0, can you try the listed below.
 
 AMDdir       = $(HOME)/OpenSees/OTHER/AMD
BLASdir      = $(HOME)/OpenSees/OTHER/BLAS
CBLASdir     = $(HOME)/OpenSees/OTHER/CBLAS
LAPACKdir    = $(HOME)/OpenSees/OTHER/LAPACK
SUPERLUdir   = $(HOME)/OpenSees/OTHER/SuperLU_5.1.1/SRC
SUPERLU_DISTdir   = $(HOME)/OpenSees/OTHER/SuperLU_DIST_4.3/SRC
ARPACKdir    = $(HOME)/OpenSees/OTHER/ARPACK
UMFPACKdir   = $(HOME)/OpenSees/OTHER/UMFPACK
METISdir     = $(HOME)/OpenSees/OTHER/METIS
CSPARSEdir   = $(HOME)/OpenSees/OTHER/CSPARSE
SRCdir       = $(HOME)/OpenSees/SRC

As there are newer versions of SuperLU available tried that out. Hopefully, it can solve the issue.

**Comment by vuminhtue** [comment]
Tks for the answer @jaidip15 .
However, I already set SUPERLU_DISTdir = $(HOME)/OpenSees/OTHER/SuperLU_DIST_4.3/SRC in the Makefile.def.
In fact, the error stems directly from other folder:
```
g++: error: /software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSuperLU.o: No such file or directory
g++: error: /software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSparseGenColLinSOE.o: No such file or directory
```

As a matter of fact that I go directly to the folder and run make file:+
```
/software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/
```
It throws the error related to file DistributedSuperLU.cpp:
```
DistributedSuperLU.cpp:44:1: error: ‘superlu_options_t’ does not name a type; did you mean ‘superlu_scope_t’?
 superlu_options_t options;

```

In which line 44 stating:
```
superlu_options_t options;
```

As I could not compile the sparseGEN directory, so I cannot get the **DistributedSuperLU.o** and **DistributedSparseGenColLinSOE.o**

**Comment by jaidip15** [comment]
Hello,
It will be difficult for me too, to really understand the issue as Opensees is a mix of a lot of dependencies and all other things to come good at the same time in order to compile SP and MP versions Successfully. Let's step back and understand what you are doing. 
For SP and MP, you have to install MUMPS/Petsc and in order to install MUMPS, you need other packages to install, Have you installed them if yes, and find any errors/problems during make?

Also, check with which GCC version you have build MPI. Sometimes it is possible that if more than one version of GCC is available in the system it may get conflict. e.x. If you have build MPI with GCC 10 and making opensees with GCC 4.5 or something, there will be a problem. 
FYI  - if your system default GCC is older (GCC4.5) there is a high chance you will be facing a problem.

As in your original error message above this error:

 /software/external/opensees/OpenSees/SRC/OPS_Globals.h:46:16: warning: unnecessary parentheses in declaration of ‘opserrPtr’ [-Wparentheses]
 #define opserr (*opserrPtr)

it is complaining about unnecessary parentheses -- a high chance that the compiler is not able to understand the definiation and failed to create .o file. Or maybe any missing flag needs to be added.

would it be possible for you to share the make file?

**Comment by mckee107** [comment]
When I built OpenSeesSP on our CentOS 7 HPC, I needed to correct a file. I'm not sure if this will help your problem or not, but it's worth a try. This is the patch file use for the EasyBuild system. Looks like you can probably manually change the line indicated in the file. 

```
Fix SuperLU_DIST options beeing renamed in 5.x.x version

author: Pavel Grochal (INUITS)

diff -rub --new-file OpenSees-3.2.0.after/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSuperLU.cpp OpenSees-3.2.0/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSuperLU.cpp
--- OpenSees-3.2.0.after/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSuperLU.cpp	2020-03-09 18:02:19.000000000 +0100
+++ OpenSees-3.2.0/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSuperLU.cpp	2020-11-12 15:08:44.344103344 +0100
@@ -41,7 +41,7 @@
 
-superlu_options_t options;
+superlu_dist_options_t options;
 SuperLUStat_t stat;
 SuperMatrix A;
 ScalePermstruct_t ScalePermstruct;
@@ -366,14 +366,3 @@
   opserr << "DistributedSuperLU::recvSelf(int cTag, Channel &theChannel) - END\n";
   return 0;
 }
```

**Comment by vuminhtue** [comment]
> Hello,
> It will be difficult for me too, to really understand the issue as Opensees is a mix of a lot of dependencies and all other things to come good at the same time in order to compile SP and MP versions Successfully. Let's step back and understand what you are doing.
> For SP and MP, you have to install MUMPS/Petsc and in order to install MUMPS, you need other packages to install, Have you installed them if yes, and find any errors/problems during make?
> 
> Also, check with which GCC version you have build MPI. Sometimes it is possible that if more than one version of GCC is available in the system it may get conflict. e.x. If you have build MPI with GCC 10 and making opensees with GCC 4.5 or something, there will be a problem.
> FYI - if your system default GCC is older (GCC4.5) there is a high chance you will be facing a problem.
> 
> As in your original error message above this error:
> 
> /software/external/opensees/OpenSees/SRC/OPS_Globals.h:46:16: warning: unnecessary parentheses in declaration of ‘opserrPtr’ [-Wparentheses]
> #define opserr (*opserrPtr)
> 
> it is complaining about unnecessary parentheses -- a high chance that the compiler is not able to understand the definiation and failed to create .o file. Or maybe any missing flag needs to be added.
> 
> would it be possible for you to share the make file?

[Makefile.def.txt](https://github.com/OpenSees/OpenSees/files/7129805/Makefile.def.txt)
Thanks @jaidip15 for looking into it. Pls find Makefile.def attached.
I do have mumps installed.
I used gcc/8.3.1, same version I used to install openmpi.
And I believe that it is not the error message, just warning:
```
 /software/external/opensees/OpenSees/SRC/OPS_Globals.h:46:16: warning: unnecessary parentheses in declaration of ‘opserrPtr’ [-Wparentheses]
```

My real error message is only this:
```
g++: error: /software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSuperLU.o: No such file or directory
g++: error: /software/external/opensees/OpenSees/SRC/system_of_eqn/linearSOE/sparseGEN/DistributedSparseGenColLinSOE.o: No such file or directory
```

**Comment by vuminhtue** [comment]
> superlu_dist_options_t options;

Thanks for the suggestion. 
However, after changing, that still not help.
Here is the error:
```
DistributedSuperLU.cpp:44:1: error: ‘superlu_dist_options_t’ does not name a type; did you mean ‘superlu_scope_t’?
 superlu_dist_options_t options;
```

**Comment by jaidip15** [comment]
Hello,
Thank you for sharing your Makefile.
on line 453 --  -I$(FE)/../OTHER/SuperLU_DIST_2.0/SRC \
this should not be there, please make change accordingly.
follow below document steps - it will help for sure.

https://apolo-docs.readthedocs.io/en/latest/software/applications/opensees/opensees-3.0.0/

use openmpi related stuff than intel libs.

Also, i am attaching my Makefile, may it can help.
FYI - I have followed above document to install MUMPS(5.1.0) and related dependencies with GCC 10.

   
[Makefile.def.txt](https://github.com/OpenSees/OpenSees/files/7130033/Makefile.def.txt)

All the best.

**Comment by vuminhtue** [comment]
Thanks @jaidip15 a lot for looking into it.
That solves the issue.
I did not recognize that is the line I need to change.
