### ISSUE TITLE
Conflict with OpenSees and Tcl command "load"

### ISSUE THREAD

**Issue by ambaker1** [OpenSees/OpenSees#656]
This is something that has bothered me for some time - the OpenSees load command overwrites the Tcl "load" command, which is used for loading in Tcl binary files (https://www.tcl.tk/man/tcl8.4/TclCmd/load.html). It would be nice if "load" was renamed to "nodeLoad" or something similar, in line with the "eleLoad" command. At the moment, this limitation can be worked around if you load in other Tcl packages before calling the "model" command.

**Comment by mhscott** [comment]
I think we're stuck with that. Instead, we'll define an "import" command that you can use instead after the "model" command.

**Comment by ambaker1** [comment]
How about oldload? It would be in line with oldputs, the unmodified Tcl command.
