### ISSUE TITLE
quadup elements and 9 node quadratic mesh problem

### ISSUE THREAD

**Issue by aligercek** [OpenSees/OpenSees#677]
i have an issue with the elements and meshes i mentioned at the title. i am a geotechnical masters student and i try to model gid+opensees example B2 which is plane frame on elastic soil. With lineer elastic surface materials model works just fine but when i try to change the quad element to quadup elements (i change the elastic material to multiyieldpressuredependet02 material also) and remesh the model with quadriteral9 elements program fails and says "analysis could not run". do you have any idea about this situation? i use free version of gid processor, is free version allows to analyze with these features i mentioned or is it just my mistake. if you have any examples with quadup elements, may you please share with me. thanks already for your answers.

**Comment by mhscott** [comment]
This sounds like a modeling issue and possibly a GiD issue, so you should contact the authors of GiD first, or post your modeling issue to the OpenSees message board or Facebook group. These GitHub issues are for issues with the code and it's not clear that this is a bug.
