### ISSUE TITLE
OpenSeesMP 3.3.0 Parallel code not working

### ISSUE THREAD

**Issue by vishnusakethjella** [OpenSees/OpenSees#679]
I tried to run the parallel model on OpenSeesMP 3.3.0 which was installed recently on HPC.

It is just running as sequential and showing me the below message in the output.

while executing
"system      Mumps"
    (file "A6_a5b50_1mX2.5m.tcl" line 200005)

Can anyone help me here to solve this issue?

P.S: The same model has run successfully on OpenSeesMP 2.5.0 last month. But it is not working on OpenSees 3.3.0 which was installed today on HPC.

**Comment by vishnusakethjella** [comment]
Please can anyone of you help with this issue? @fmckenna @mhscott @ambaker1 @MassimoPetracca @zhuminjie @aschellenberg74 @parduino @claudioperez

**Comment by mhscott** [comment]
Can you provide more details on this issue? How did you install? Did you build from source code?

**Comment by mhscott** [comment]
Any updates on this?
