### ISSUE TITLE
ShellDKGQ Element compare sap2000 thin shell 

### ISSUE THREAD

**Issue by mengdalian** [OpenSees/OpenSees#68]
a element with two nodes fixed 
apply node load to the other two nodes
The disp results are quite different
opensees result:
12.987 7.4026 -4.03626e-015 -1.23233e-018 2.773e-018 0.0137662
12.987 -7.4026 -4.03626e-015 1.23233e-018 2.773e-018 -0.0137662
sap2000 result:
6.18747  0.937351  0   0   0   0.000498
6.18747 -0.937351  0   0   0   -0.000498

this is my tcl and s2k
/**********begin tcl************************
wipe
puts "System"
model basic -ndm 3 -ndf 6
puts "restraint"
node 1 0.000E+000 0.000E+000 0.000E+000
node 2 3.000E+003 0.000E+000 0.000E+000
node 3 3.000E+003 3.000E+003 0.000E+000
node 4 0.000E+000 3.000E+003 0.000E+000
puts "node"
fix 1 1 1 1 1 1 1;
fix 4 1 1 1 1 1 1;
puts "material"
uniaxialMaterial Elastic 1 1.999E+005
############################################################################################################修改代码
nDMaterial ElasticIsotropic 2 30000 0.2    
uniaxialMaterial Elastic 3 1.999E+005
##S100 
nDMaterial PlateFiber 601 2
section PlateFiber 701 601 120.00
puts "transformation"
puts "element"
puts "shell element"
element ShellDKGQ 1 1 2 3 4 701
puts "recorder"
recorder Node -file node0.out -time -nodeRange 2 3 -dof 1 2 3 4 5 6 disp
############################################################################################################修改代码
puts "loading"
## Load Case = PUSH
pattern Plain 1 Linear {
load 2 11.25000E+006 0.000E+000 0.000E+000 0.000E+000 0.000E+000 0.000E+000
load 3 11.25000E+006 0.000E+000 0.000E+000 0.000E+000 0.000E+000 0.000E+000
}
puts "analysis"
constraints Plain
numberer Plain
system BandGeneral
test EnergyIncr 1.0e-6 200
algorithm Newton
integrator LoadControl 1.000E+000
analysis Static
analyze 1
print node 2
print node 3
/**********end tcl**************************

/**********begin sap2000**********
TABLE:  "PROGRAM CONTROL"
ProgramName=SAP2000 Version=15.1.0 ProgLevel=Ultimate LicenseOS=YES LicenseSC=YES LicenseBR=NO LicenseHT=NO CurrUnits="N,MM,C" SteelCode=AISC360-05/IBC2006 ConcCode="ACI 318-05/IBC2003" AlumCode="AA-ASD 2000" ColdCode=AISI-ASD96 BridgeCode="AASHTO LRFD 2007" RegenHinge=YES 
TABLE:  "ACTIVE DEGREES OF FREEDOM"
   UX=Yes   UY=Yes   UZ=Yes   RX=Yes   RY=Yes   RZ=Yes

TABLE:  "ANALYSIS OPTIONS"
   Solver=Advanced   SolverProc=Auto   Force32Bit=No   StiffCase=None   GeomMod=No

TABLE:  "COORDINATE SYSTEMS"
   Name=GLOBAL   Type=Cartesian   X=0   Y=0   Z=0   AboutZ=0   AboutY=0   AboutX=0

TABLE:  "MATERIAL PROPERTIES 01 - GENERAL"
Material=Mat1 Type=Concrete SymType=Isotropic TempDepend=No Color=16777215 Notes="3D3S" 

TABLE:  "MATERIAL PROPERTIES 02 - BASIC MECHANICAL PROPERTIES"
Material=Mat1 UnitWeight=2.49955e-05 UnitMass=2.549e-09 E1=30000 G12=12500 U12=0.2 A1=1e-05 

TABLE:  "FRAME SECTION PROPERTIES 01 - GENERAL"

TABLE:  "AREA SECTION PROPERTIES"
Section="1-Mat1" Material="Mat1" MatAngle=0 AreaType=Shell Type=Shell-Thin Thickness=120 BendThick=120 Color=7692654 Notes="3D3S" 

TABLE:  "JOINT COORDINATES"
Joint=6 CoordSys=GLOBAL CoordType=Cartesian XorR=0 Y=0 Z=0 SpecialJt=No GlobalX=0 GlobalY=0 GlobalZ=0 
Joint=7 CoordSys=GLOBAL CoordType=Cartesian XorR=3000 Y=0 Z=0 SpecialJt=No GlobalX=3000 GlobalY=0 GlobalZ=0 
Joint=8 CoordSys=GLOBAL CoordType=Cartesian XorR=3000 Y=3000 Z=0 SpecialJt=No GlobalX=3000 GlobalY=3000 GlobalZ=0 
Joint=9 CoordSys=GLOBAL CoordType=Cartesian XorR=0 Y=3000 Z=0 SpecialJt=No GlobalX=0 GlobalY=3000 GlobalZ=0 

TABLE:  "JOINT RESTRAINT ASSIGNMENTS"
Joint="6" U1=Yes U2=Yes U3=Yes R1=Yes R2=Yes R3=Yes 
Joint="9" U1=Yes U2=Yes U3=Yes R1=Yes R2=Yes R3=Yes 

TABLE:  "CONNECTIVITY - AREA"
Area="Area2" NumJoints=4 Joint1="6" Joint2="7" Joint3="8" Joint4="9"

TABLE:  "AREA SECTION ASSIGNMENTS"
Area="Area2" Section="1-Mat1" MatProp=Default 

TABLE:  "LOAD PATTERN DEFINITIONS"
LoadPat="Gk1" DesignType="LIVE" SelfWtMult=0 

TABLE:  "LOAD CASE DEFINITIONS"
Case="Gk1" Type="LinStatic" InitialCond="Zero" DesTypeOpt="Prog Det" DesignType="LIVE" AutoType=None RunCase=Yes 

TABLE:  "CASE - STATIC 1 - LOAD ASSIGNMENTS"
Case="Gk1" LoadType="Load pattern" LoadName="Gk1" LoadSF=1 

TABLE:  "JOINT LOADS - FORCE"
Joint="7" LoadPat="Gk1" CoordSys=GLOBAL F1=1.125e+07 F2=0 F3=0 M1=0 M2=0 M3=0 
Joint="8" LoadPat="Gk1" CoordSys=GLOBAL F1=1.125e+07 F2=0 F3=0 M1=0 M2=0 M3=0 

END TABLE DATA
/**********end sap2000*************

**Comment by mhscott** [comment]
Please post modeling issues to the OpenSees message board.
