### ISSUE TITLE
small issue in setResponse method of Shell sections

### ISSUE THREAD

**Issue by MassimoPetracca** [OpenSees/OpenSees#695]
Dear @mhscott ,  in a recent pull request #630 all sections are now calling their base class implementation to avoid duplicated code.
However, the base class opens the XML tags for the component labels (example: output.tag("ResponseType","Mz");) in a switch, assuming the components are those of a beam element.

This is not a major issue, it's only relevant for recorders with the -xml flag.
Now all components of shell sections are "Unknown".

**Comment by mhscott** [comment]
So, we just need to add more cases to the switch statement in the base SectionForceDeformation::setResponse implementation?

**Comment by MassimoPetracca** [comment]
@mhscott Yes, we need to add extra switch statements. But in order for it to work, we also need to:

1. Declare more SECTION_RESPONSE_XXX macros in SectionForceDeformation.h
```
// membrane forces
SECTION_RESPONSE_FXX
SECTION_RESPONSE_FYY
SECTION_RESPONSE_FXY
// bending moments
SECTION_RESPONSE_MXX
SECTION_RESPONSE_MYY
SECTION_RESPONSE_MXY
// transverse shear
SECTION_RESPONSE_VXZ
SECTION_RESPONSE_VYZ
```
2. In all shell sections (ElasticMembranePlateSection, MembranePlateFiberSection, LayeredShellFiberSeciton and their thermal couterparts) , Implement the SectionForceDeformation::getType() -> ID method, which should return an ID with the above mentioned codes.

If you agree, I can create a PR for this during the weekend

**Comment by mhscott** [comment]
Thanks, this looks good. Please make a PR when you are ready.

**Comment by MassimoPetracca** [comment]
Dear @mhscott I just created a PR #755
