### ISSUE TITLE
Questions about InertiaTruss 

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#707]
@Xiaodong-Ji-THU The recorder for axialForce does not return axial force, but instead the mass times the relative nodal acceleration in global directions
https://github.com/OpenSees/OpenSees/blob/master/SRC/element/truss/InertiaTruss.cpp#L911
Please let me know if I have misinterpreted the intent of the InertiaTruss::getResponse method.

**Comment by Xiaodong-Ji-THU** [comment]
Thank you for the suggestion. We have set the stiffness of this element to be zero in the updated code.(#716 )

**Comment by Xiaodong-Ji-THU** [comment]
Prof. Scott，thank you very much for pointing out this problem of the axialForce recorder. We have corrected it in the updated version of the code.(#716 )
