### ISSUE TITLE
InertiaTruss stiffness

### ISSUE THREAD

**Issue by mhscott** [OpenSees/OpenSees#708]
@Xiaodong-Ji-THU For the InertiaTruss element, a very small EA/L value (1e-10) is hardcoded in the element.
https://github.com/OpenSees/OpenSees/blob/master/SRC/element/truss/InertiaTruss.cpp#L459
From my personal experience, this is not a good idea, and it's generally better to let the user specify a stiffness in another element, or not.

**Comment by Xiaodong-Ji-THU** [comment]
Thank you for the suggestion. We have set the stiffness of this element to be zero in the updated code.(#716 )
