### ISSUE TITLE
Memory usage increase despite wipe wipeAnalysis

### ISSUE THREAD

**Issue by siddharthfcb** [OpenSees/OpenSees#709]
Hello
I am using openseespy for a parameteric study. I am running a large loop over 10,000 parameter values. As the code loops over the memory usage increases. i am not sure why this is happening. Since i am using wipe and wipe analysis the memory usage through out the loop should stay constant right?

Please see the link for the files. 
https://drive.google.com/file/d/1CdS8q-_S1F2NLyabu6eF61_RipJAGRgC/view?usp=sharing

**Comment by mhscott** [comment]
This is probably a memory leak from somewhere within OpenSees and may not be specific to Tcl or Python. Please reduce your model until you notice there is no memory loss, then re-add items to your model to see what causes leak.

**Comment by siddharthfcb** [comment]
Thank you Dr. Scott. I agree it doesn’t depend on if it is TCL or py. I saw similar thing in both. I will do as you suggested and update here. Thanks again. 

Siddharth

**Comment by mhscott** [comment]
Have you had a chance to look into the memory leaks in more detail?

**Comment by siddharthfcb** [comment]
Hello Dr. Scott 
Thank you for your email. I haven’t had a chance to look at it yet. 

Siddharth

**Comment by silviamazzoni** [comment]
I had this problem with "simple" inelastic SDOF response-spectrum analyses

**Comment by mhscott** [comment]
@silviamazzoni Can you send me a WME so I can see how you define the model and load patterns, etc.

**Comment by mhscott** [comment]
Can anyone provide a simple script that reproduces the memory leak?

**Comment by silviamazzoni** [comment]
if you watch the memory usage in your task manager, you see it creeping up, slowly.
you can reduce the number of analyses at first

**Comment by silviamazzoni** [comment]
actually, hold on!!!. maybe it's just creeping because of the data I am storing... I hate SWEs, they never really replicate big problems. :)

**Comment by mhscott** [comment]
Thank you, @silviamazzoni!
@siddharthfcb would you please share a simple example that demonstrates the issue you're having?

**Comment by mhscott** [comment]
@silviamazzoni Your script should be leak free now! https://github.com/OpenSees/OpenSees/commit/fe635f98ddd90fe4dd5893c509f6bb04b4aa3d8b

**Comment by silviamazzoni** [comment]
wow, thank you!!! That missing one line forced me to write soooo many lines of code....
Should I be updating OpenSees?
thank you!

**Comment by siddharthfcb** [comment]
@mhscott @silviamazzoni  Sorry for the late reply. however, this fixes it. Thanks.
