### ISSUE TITLE
Cannot download the source code

### ISSUE THREAD

**Issue by Yanxiaoyang96** [OpenSees/OpenSees#72]
I try to download the source code. But every time the downloading speed is very slow and after a while, the download was interrupted. What's the matter?

**Comment by zhuminjie** [comment]
How did you download it, through git or direct download?

**Comment by tiezheng1020** [comment]
Hi,
I successfully dowloaded the source code from Github (https://github.com/OpenSees/OpenSees/releases). You can have a try.
If it still does not work, probably it is due to the speed of your internet.
Tie

**Comment by tiezheng1020** [comment]
> I try to download the source code. But every time the downloading speed is very slow and after a while, the download was interrupted. What's the matter?

Hi,
I successfully dowloaded the source code from Github (https://github.com/OpenSees/OpenSees/releases). You can have a try.
If it still does not work, probably it is due to the speed of your internet.
Tie
