### ISSUE TITLE
DisplacementControl Integrator fails when cycling static analysis is used

### ISSUE THREAD

**Issue by zwaezi** [OpenSees/OpenSees#722]
I am using ver 3.3.0 and while testing a simple axial member with Concrete06 or ConcreteCM subjected to cyclic loading as the tensile unloading is completed and displacement=0.0 the analysis fails with this message 
Integer too large to represent

**Comment by mhscott** [comment]
Likely not a bug in the source code. Please check with other material models to see if you have the same issue.

**Comment by zwaezi** [comment]
The same thing happens with Concrete04 and Steel01 too!

**Comment by mhscott** [comment]
I still doubt this is a bug, but more of a modeling issue. Please post your issue on the message board or Facebook group.

**Comment by zwaezi** [comment]
Thanks.
