### ISSUE TITLE
Compilation error in OpenSees with Tcl8.6.10

### ISSUE THREAD

**Issue by fupu5414** [OpenSees/OpenSees#725]
My OpenSees source code's version is **3.3.0** and **Active Tcl 8.6.10**.The officical OpenSees works well,but the compiled fails showing **"Can't find a usable init.tcl in the following directories"** and **"version conflict for package "Tcl": have 8.6b1, need exactly 8.6.10"** .
![屏幕截图 2021-12-05 154241](https://user-images.githubusercontent.com/55308023/144738960-08a8b6c5-990b-4cfd-baa2-e2c98d68b1a5.png)

I just wonder if anyone has encountered the same problem. Or if you have the solution ,please let me knew ! Thanks a lot ! I had been struggling with this problem for days.

**Comment by fmckenna** [comment]
This is not a compilation issue, it is a running issue.

If you built it from scratch you included and linked against the Tcl you installed. That tcl distribution should have an init.tcl (if it does not you did not install all the necessary components). The error message should show you were the file is supposed to be. It seems to be finding one init.tcl (but the version is incompatable with the one you compiled it with) and hence your error.

**Comment by fupu5414** [comment]
Dear Prof. Frank：
Maybe there is a computer’s issue，and i ’ve changed PC then my compilation works fine !Thank you so much ! Have a good day!
