### ISSUE TITLE
Building Error in v3.4.0 (Visual Studio 2019)

### ISSUE THREAD

**Issue by iammix** [OpenSees/OpenSees#728]
Hello Community,
There is a compiling error in the latest version 3.4.0.

**FIX:** Add HarmonicSteadyState.h and HarmonicSteadyState.cpp files to the solution (analysis/integrator project).

**Comment by mhscott** [comment]
Thanks for the reminder! Fixed now.
https://github.com/OpenSees/OpenSees/pull/730
