### ISSUE TITLE
Getting Defined MaterialTags and ClasslTags

### ISSUE THREAD

**Issue by BijanSeif** [OpenSees/OpenSees#742]
Hi

In Opensees, As you know there are commands that give us list of the elements and nodes TAG. Is there any command that gives us the list of the generated Material TAGS and ClassTags? (Exactly like elements, with getEleTags we can get access to the list of defined element Tags and with getEleClassTags we can get access to the ClassTag of defined elements)

With Best Regards,
Bijan

**Comment by mhscott** [comment]
I don't believe there are such commands. Should be easy to add, similar to the geometric transformations.

**Comment by BijanSeif** [comment]
Thanks Prof @mhscott for the response
I try to add it similar to geometric transformations instruction.
