### ISSUE TITLE
EPPGapMaterial::EPPGapMaterial -- value of eta must be -1 <= eta <= 1, setting eta to 0

### ISSUE THREAD

**Issue by dimvoly** [OpenSees/OpenSees#743]
When using [EPP Gap Material](https://opensees.berkeley.edu/wiki/index.php/Elastic-Perfectly_Plastic_Gap_Material), for example defining it in this line:

`uniaxialMaterial ElasticPPGap 20 200000000000 300000000 0 1`

The value of $eta above is set to 1 in the .tcl file. However on running the .tcl file, the resulting error message suggests the bounds are:

`-1 <= eta <= 1`

The actual check and the error message should be made consistent.

As an aside, I'm not sure why $eta is constrained to be less than 1, in theory a material can get stiffer once it yields. But I don't deal with such materials.

**Comment by mhscott** [comment]
Yes, eta should be < 1 (not <=). If equal to 1, there will be a divide by zero error. I'm not sure why eta is allowed to be less than 0 though @kmackiegh

**Comment by kmackiegh** [comment]
It’s a softening material when eta is less than zero.

On Dec 25, 2021, at 11:00 PM, Michael H. Scott ***@***.******@***.***>> wrote:



Yes, eta should be < 1 (not <=). If equal to 1, there will be a divide by zero error. I'm not sure why eta is allowed to be less than 0 though @kmackiegh<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkmackiegh&data=04%7C01%7Ckevin.mackie%40ucf.edu%7C845b5459d12d47b40b4808d9c82c92bb%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637760916042364235%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mBZ1lDzQasylXtQGeK2IBFkylnH8Vns2VNTLw2B%2Bjcg%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenSees%2FOpenSees%2Fissues%2F743%23issuecomment-1001106800&data=04%7C01%7Ckevin.mackie%40ucf.edu%7C845b5459d12d47b40b4808d9c82c92bb%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637760916042364235%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=24TVD95w9JZVSHuKxG%2FpBY3VDZFBPngdcwAOYVw1X1g%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKWVBQBTC3JJ74QRSBCCNKDUS2ONDANCNFSM5KYORBUQ&data=04%7C01%7Ckevin.mackie%40ucf.edu%7C845b5459d12d47b40b4808d9c82c92bb%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637760916042364235%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GBXL9qJ63Rfjo9QuMpEhwafByTY62kaPP%2FUWYe%2F098I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckevin.mackie%40ucf.edu%7C845b5459d12d47b40b4808d9c82c92bb%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637760916042364235%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vZIYndwp8hj4mQQKB%2F4mSuPF8B3HvWeGycuAuscutTs%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckevin.mackie%40ucf.edu%7C845b5459d12d47b40b4808d9c82c92bb%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637760916042364235%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yxHqe7QIacTEHAvyp1CtNmW7GKkrpyN15%2FRYSGJccbs%3D&reserved=0>.

**Comment by mhscott** [comment]
Thanks @kmackiegh! Then should the eta value be bound by -1 or -infty?

**Comment by kmackiegh** [comment]
Theoretically -infnty, but I haven’t tested to see whether that causes other numerical issues. Probably any negative double is acceptable.

On Dec 26, 2021, at 9:06 AM, Michael H. Scott ***@***.******@***.***>> wrote:



Thanks @kmackiegh<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkmackiegh&data=04%7C01%7Ckevin.mackie%40ucf.edu%7Cb9b3c0c78a5c48bf827a08d9c881417c%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637761279760777322%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IC8t4nHK96u5Eiekg%2FjT0UB8BEl%2BsBdtZW0IxqYMvMU%3D&reserved=0>! Then should the eta value be bound by -1 or -infty?

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenSees%2FOpenSees%2Fissues%2F743%23issuecomment-1001197709&data=04%7C01%7Ckevin.mackie%40ucf.edu%7Cb9b3c0c78a5c48bf827a08d9c881417c%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637761279760777322%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PDMqiU%2FsYSLKyYiB5AY1kVLCY6f9jfl0OxBtxco%2BNh8%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKWVBQHO4BTVYE7Q4ZHG3ELUS4VOHANCNFSM5KYORBUQ&data=04%7C01%7Ckevin.mackie%40ucf.edu%7Cb9b3c0c78a5c48bf827a08d9c881417c%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637761279760777322%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=33TtfUydkiMzA4J%2FeGUNPNIGOPYk1gFauYnpG2nVQC8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckevin.mackie%40ucf.edu%7Cb9b3c0c78a5c48bf827a08d9c881417c%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637761279760777322%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h5mXP9CUPNDySnJjGnbX%2F1l%2BesMQPLwNZQVRdBEC1Bc%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckevin.mackie%40ucf.edu%7Cb9b3c0c78a5c48bf827a08d9c881417c%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C637761279760777322%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bjCoUFqFMU2zE97Duy8muGLxjn23W3x7WFLHp0un4sI%3D&reserved=0>.

**Comment by mhscott** [comment]
Code updated to allow eta < 1
