### ISSUE TITLE
Adding a method to timeSeries command

### ISSUE THREAD

**Issue by asaaed** [OpenSees/OpenSees#750]
Hi all,

I want to add a method to time series command which process the input motion based on two parameters. To clear I want to change the timeSeries Path command as follow:

`timeSeries Path $tag -dt $dt -filePath $filePath <-factor $cFactor> <-useLast> <-prependZero> <-startTime $tStart>`

change to:

`timeSeries Path $tag -dt $dt -filePath $filePath <-factor $cFactor> <-useLast> <-prependZero> <-startTime $tStart> <-newOption $parameter1 $parameter2>`

and my question is about the procedure to implement and the classes which should be used for this, is there any guideline available for this?

**Comment by mhscott** [comment]
It's not clear what you would like to implement, but if it's pre-processing, this should be done outside of OpenSees.

**Comment by asaaed** [comment]
Its a method that change the record and let us to use larger time steps with almost no accuracy loss, I want to add this method as an optional parameter to path Series, and to clarify its get the record which OpenSees read as input and change it to a smaller record and use it as the input for analysis.

**Comment by mhscott** [comment]
I think you should do this in pre-processing.
Path time series is a general object, not specific to ground motions.

**Comment by asaaed** [comment]
Thanks, but if i want to implement it into path command (something like <-factor $cFactor>) how i can do this, any guide or example?

**Comment by mhscott** [comment]
There is no guide or example, but you can look at the source code to see how the options are implemented.
