### ISSUE TITLE
Concrete07 error during the time history analysis

### ISSUE THREAD

**Issue by fupu5414** [OpenSees/OpenSees#752]
![Uploading QQ图片20211229170738.png…]()
## these are the parameters of my concrete07 material
uniaxialMaterial Concrete07 2 -29.40060576	-0.002516015	3.15e4	2.999159882	0.000190423	2	30	1.589735847	
uniaxialMaterial Concrete07 3 -27.25003878	-0.002336148	3.15e4	2.999159882	0.000190423	2	30	1.588063187	
uniaxialMaterial Concrete07 4 -27.24059629	-0.002335162	3.15e4	2.999159882	0.000190423	2	30	1.58813369

**Comment by mhscott** [comment]
The image did not upload. It's likely a model building issue, so try other concrete materials and static loading to see if you get similar errors.
Closing the issue. If you determine it's a program error, you can re-open or start a new issue. You can pursue modeling issues on the OpenSees Facebook group or the message board.
