### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by BijanSeif** [OpenSees/OpenSees#757]
Hi 

After I compile the opensees using Visualstudio The below Error appears for me!. Would you guide me the reason of this error and how solve it? (I'm using a 64bit windows and 2019 is the version of my visual studio) 

![image](https://user-images.githubusercontent.com/82403633/147837398-be1ca351-43f9-448c-85e9-a93821d36674.png)

![image](https://user-images.githubusercontent.com/82403633/147837391-040da7a6-5cc8-437c-98b7-a584179b93b8.png)

**Comment by mhscott** [comment]
There's a link to obtain the lib files in the description of this video: https://www.youtube.com/watch?v=BLcY1w7a5Ec

**Comment by BijanSeif** [comment]
Thanks Prof @mhscott for your great helps and guidance. Now it is compiled and working correctly.
