### ISSUE TITLE
Version dependent reliability issue

### ISSUE THREAD

**Issue by asaaed** [OpenSees/OpenSees#770]
Hi,

I have tried different versions of OpenSees for **reliability** analysis and the results were different on **same** models. The examples were obtained from [OpenSees](https://github.com/OpenSees/OpenSees/) repo's, and results for each example are as follow: 

> industrialFrame    
  
| Version | Example              | Result       |
| ------- | -------------------- | ------------ |
| 2.5.0   | industrialFrame      | beta = 4.891 |
| 3.2.2   | industrialFrame      | beta = 0.000 |
| 3.4.0   | industrialFrame      | beta = 0.000 |

> steelFrame

| Version | Example              | Result       |
| ------- | -------------------- | ------------ |
| 2.5.0   | steelFrame, nEle = 2 | beta=1.35918 |
| 3.2.2   | steelFrame, nEle = 2 | beta=3.63346 |
| 3.4.0   | steelFrame, nEle = 2 | beta=3.63346 |
| 2.5.0   | steelFrame, nEle = 4 | beta=1.45205 |
| 3.2.2   | steelFrame, nEle = 4 | beta=1.99697 |
| 3.4.0   | steelFrame, nEle = 4 | beta=1.99697 |
| 2.5.0   | steelFrame, nEle = 6 | beta=1.44943 |
| 3.2.2   | steelFrame, nEle = 6 | beta=1.56548 |
| 3.4.0   | steelFrame, nEle = 6 | beta=1.56548 |
| 2.5.0   | steelFrame, nEle = 8 | beta=1.44708 |
| 3.2.2   | steelFrame, nEle = 8 | beta=1.45493 |
| 3.4.0   | steelFrame, nEle = 8 | beta=1.45493 |

> portalframe          

| Version | Example              | Result       |
| ------- | -------------------- | ------------ |
| 2.5.0   | portalframe          | beta=2.44958 |
| 3.2.2   | portalframe          | beta=2.44958 |
| 3.4.0   | portalframe          | beta=2.44958 |

> truss                

| Version | Example              | Result       |
| ------- | -------------------- | ------------ |
| 2.5.0   | truss                | beta=0.28574 |
| 3.2.2   | truss                | beta=0.28574 |
| 3.4.0   | truss                | beta=0.28574 |

for *steelFrame* example i have checked the article entitled *"Shape sensitivities in the reliability analysis of nonlinear frame structures"* [doi:10.1016/j.compstruc.2006.02.014](https://dl.acm.org/doi/abs/10.1016/j.compstruc.2006.02.014) and none of results was same as the beta equal to **2.01** which explained in the [article](https://dl.acm.org/doi/abs/10.1016/j.compstruc.2006.02.014).

Based on these explanations I could not find out why:

- responses for same model are different in different versions of OpenSees
- responses for *truss* example (both truss and truss2) are exactly the same
- for *industrialFrame* example the new versions (3.2.2 and 3.4.0) calculate wrong response (beta = 0.0 and  gamma=0.00)
- for *portalframe* example each beam (column) has one element per member, and reliability results are exactly the same
- for  *steelFrame* example in new versions (3.2.2 and 3.4.0), changing the number of elements per member has a great impact on the reliability response 

> Number of elements per member in *steelFrame*

| Version | Example    | Number of elements | beta   |
| ------- | ---------- | ---- | ------ |
| 3.4.0   | steelFrame | 12   | 1.4474 |
| 3.4.0   | steelFrame | 11   | 1.444  |
| 3.4.0   | steelFrame | 10   | 1.4422 |
| 3.4.0   | steelFrame | 9    | 1.4442 |
| 3.4.0   | steelFrame | 8    | 1.4549 |
| 3.4.0   | steelFrame | 7    | 1.488  |
| 3.4.0   | steelFrame | 6    | 1.5655 |
| 3.4.0   | steelFrame | 5    | 1.7172 |
| 3.4.0   | steelFrame | 4    | 1.997  |
| 3.4.0   | steelFrame | 3    | 2.5384 |
| 3.4.0   | steelFrame | 2    | 3.6335 |

 > I perform analysis on Windows operating system (*.exe) with *tcl (Activetcl 8.6)* installed.

I would be glad if anyone could help with this issue and let me know which version is working properly and its reliability response is correct and reliable.

@mhscott , @fmckenna

**Comment by mhscott** [comment]
Thanks for running the different versions and reliability examples! Many things have changed since version 2.5.0.
Please use Monte Carlo simulation to determinate which reliability index, beta, is "correct" with version 3.4.0. That will help figure out the issues.

**Comment by asaaed** [comment]
Thanks, I'll try Monte Carlo simulation. What about the last table, are changes in the reliability index relative to changes in the number of elements make sense?

**Comment by mhscott** [comment]
Yes, plot the load-displacement relationships and you will see the effect of mesh refinement.

**Comment by asaaed** [comment]
Thanks, I have checked load-displacement relationships, and you are right. But in the mentioned article the reliability index for this example was 2.01, and its far from 1.4 or 3.5, i think the results should converge to **2.01**, not to 1.44 when the number of element per member are increased. Or may be the *steelFrame* example is **not exactly**, same as the article model simulation

**Comment by mhscott** [comment]
Please use Monte Carlo to determine the correct answer.

**Comment by mhscott** [comment]
Closing. If you have further comparisons and the issue persists, start a new conversation.
