### ISSUE TITLE
Eigen analysis error

### ISSUE THREAD

**Issue by johnnyontheweb** [OpenSees/OpenSees#771]
Hello all,
I get an error running eigen analysis on a simple shell model.
I suspect this is related to ShellMITC4 or due to the fact that no masses in Z are defined, but idk, please find a simple tcl model attached.

The error OS reports is `forrtl: severe (408): fort: (19): Dummy character variable 'WHICH' has length 2 which is greater than actual variable length -3689348814741910324`

can you help on this? thanks in advance

[shellModal.txt](https://github.com/OpenSees/OpenSees/files/8008868/shellModal.txt)

**Comment by mhscott** [comment]
Ran fine for me on Windows. Which operating system are you using?

![image](https://user-images.githubusercontent.com/13142652/152658209-7d583b02-74ec-4d68-abe3-3710058027b7.png)

**Comment by johnnyontheweb** [comment]
Hello, I'm using Windows 10, my repo is up-to-date. I have ActiveTCL 8.6.9.

**Comment by johnnyontheweb** [comment]
OpenSees compiles fine with no errors. AFAIK, I don't have any issue with Fortran libraries on my machine - I'm using the ones supplied by this repo. I'm using Intel oneAPI Fortran compiler with VS2019.

**Comment by johnnyontheweb** [comment]
As additional information, here you are the stack:
```
forrtl: severe (408): fort: (19): Dummy character variable 'WHICH' has length 2 which is greater than actual variable length -3689348814741910324

Image              PC                Routine            Line        Source
OpenSees.exe       000000014009996D  Unknown               Unknown  Unknown
OpenSees.exe       00000001400012D1  DSAUPD                    516  dsaupd.f
OpenSees.exe       00000001415FBCC8  Unknown               Unknown  Unknown
OpenSees.exe       00000001415FB099  Unknown               Unknown  Unknown
OpenSees.exe       0000000140307D44  Unknown               Unknown  Unknown
OpenSees.exe       00000001401E0F88  Unknown               Unknown  Unknown
tcl86t.dll         00007FFE129F62E8  Unknown               Unknown  Unknown
tcl86t.dll         00007FFE129F8373  Unknown               Unknown  Unknown
tcl86t.dll         00007FFE129F9B3D  Unknown               Unknown  Unknown
tcl86t.dll         00007FFE12A98313  Unknown               Unknown  Unknown
tcl86t.dll         00007FFE12A963AE  Unknown               Unknown  Unknown
OpenSees.exe       00000001401D0B49  Unknown               Unknown  Unknown
```

Line 518 in dsaupd.f is the first line in which `WHICH` was called (see for instance https://github.com/opencollab/arpack-ng/blob/master/SRC/dsaupd.f)

**Comment by johnnyontheweb** [comment]
Another update: I tried on 2 different windows systems, error happens more frequently (but not exclusively) with Debug executable. To be clearer, it happens always in Debug on both machines with the model I attached in 1st post. In Release, error happens only with larger models.
I suspect a memory problem - can someone provide instructions on debugging Fortran libs or how to investigate the problem?
of course sources should be provided - I have a doubt on which is the correct source, 'cause of the different line number of the error (see previous post).

**Comment by mhscott** [comment]
The issue is not memory in FORTRAN, it's the arguments passed from C to FORTRAN, e.g., with character arrays

**Comment by johnnyontheweb** [comment]
I agree, but by now debugging C gave no clue to me

**Comment by johnnyontheweb** [comment]
I simply have a copy of the official repo - anyway, thanks for your help and tests, I'll try to catch what went wrong on my side (and on both machines of mine).

**Comment by johnnyontheweb** [comment]
In release mode, the error is the one described here: https://www.facebook.com/groups/opensees/permalink/10158781334391492/
On the other hands, it happens only with ShellMITC4.
Issue reopened

**Comment by mhscott** [comment]
That post from Facebook does *not* describe your problem. Instead it shows that fullGenLapack is VERY slow for even moderately sized models. The long runtimes can easily be shown with other elements besides ShellMITC4. There is nothing in the post about runtime errors.
Please provide more examples that show the issue with and without ShellMITC4 as you claim.

**Comment by johnnyontheweb** [comment]
You stated "So there must be a memory allocation issue with -fullGenLapack", and that's exactly what I believe there is. 
I already provided a sample that causes error for me (and I understand it is unuseful for you). On my side, I tried to re-build several times, also from scratch, but nothing changes.
The main argument here is not about slowness of fullGenLapack, but about eventual memory leaks. I had the same situation descrided in the FB post with `Release` exe: I waited hrs, but no results. In `Debug`, the error described in previous msgs here. I suspect this is related some way to MITC4 shell elements, since in my experience I never experienced the same error with other models.

**Comment by mhscott** [comment]
I don't think it's memory allocation. The issue could be that -fullGenLapack attempts to computer eigenvalues/eigenvectors for all N modes of the system (thus VERY slow), but you may be running into issues because not all DOFs have mass. I'm just guessing, but it's likely not an issue isolated to ShellMITC4 elements.

**Comment by zhangping828** [comment]
HI:

Have u solved this issue??? I also encountered this problem. Could U show me some hints??
