### ISSUE TITLE
Compile  error ‘ReliabilityDomain’ was not declared in this scope

### ISSUE THREAD

**Issue by pletzer** [OpenSees/OpenSees#791]
Hi,

I'm getting the following error when building with GCC 9.2 on Linux

[ 61%] Building CXX object CMakeFiles/OPS_INTERPRETER.dir/SRC/interpreter/OpenSeesParameterCommands.cpp.o
/home/pletzera/OpenSees-pletzer/SRC/interpreter/OpenSeesParameterCommands.cpp: In function ‘int OPS_Parameter()’:
/home/pletzera/OpenSees-pletzer/SRC/interpreter/OpenSeesParameterCommands.cpp:51:3: error: ‘ReliabilityDomain’ was not declared in this scope
   51 |   ReliabilityDomain *theReliabilityDomain = OPS_GetReliabilityDomain();
      |   ^~~~~~~~~~~~~~~~~
/home/pletzera/OpenSees-pletzer/SRC/interpreter/OpenSeesParameterCommands.cpp:51:22: error: ‘theReliabilityDomain’ was not declared in this scope
   51 |   ReliabilityDomain *theReliabilityDomain = OPS_GetReliabilityDomain();
      |                      ^~~~~~~~~~~~~~~~~~~~
/home/pletzera/OpenSees-pletzer/SRC/interpreter/OpenSeesParameterCommands.cpp:51:45: error: ‘OPS_GetReliabilityDomain’ was not declared in this scope
   51 |   ReliabilityDomain *theReliabilityDomain = OPS_GetReliabilityDomain();
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/OPS_INTERPRETER.dir/SRC/interpreter/OpenSeesParameterCommands.cpp.o] Error 1

**Comment by mhscott** [comment]
Do you have RELIABILITY_FLAG set in your Makefile.def?

![image](https://user-images.githubusercontent.com/13142652/154566057-df66c903-e86a-4f91-aa07-d2ea52ed638a.png)

**Comment by mhscott** [comment]
Yeah, that include statement is already in the file if you have _RELIABILITY defined...

So, probably need to modify OpenSees/CMakeLists.txt instead

![image](https://user-images.githubusercontent.com/13142652/154567870-742c9750-d910-423a-8020-122c03d5e0bf.png)

**Comment by pletzer** [comment]
Do you want cmake .. -DRELIABILITY=ON and define _RELIABILITY? Or should _RELIABILITY be always defined?

**Comment by pletzer** [comment]
With the above fix I get

[ 90%] Building CXX object CMakeFiles/OpenSees.dir/SRC/api/packages.cpp.o
[ 90%] Linking CXX executable bin/OpenSees
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function reliability(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'TclReliabilityBuilder::TclReliabilityBuilder(Domain&, Tcl_Interp*)'
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function wipeReliability(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'TclReliabilityBuilder::~TclReliabilityBuilder()'
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function sensitivityAlgorithm(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'TclReliabilityBuilder::getReliabilityDomain()'
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function removeObject(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'TclReliabilityBuilder::getReliabilityDomain()'
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function removeObject(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'ReliabilityDomain::removeRandomVariable(int)'
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function removeObject(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'TclReliabilityBuilder::getReliabilityDomain()'
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function removeObject(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'ReliabilityDomain::removeLimitStateFunction(int)'
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function removeObject(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'TclReliabilityBuilder::getReliabilityDomain()'
lib/libOPS_InterpTcl.a(commands.cpp.o):commands.cpp:function removeObject(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'ReliabilityDomain::removeCutset(int)'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationBuilder::TclOptimizationBuilder(Domain&, Tcl_Interp*): error: undefined reference to 'OptimizationDomain::OptimizationDomain()'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addDesignVariable(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'DesignVariable::DesignVariable(int, char*, double, double, double, Tcl_Interp*, OptimizationDomain*, double)'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addDesignVariablePositioner(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'OptimizationDomain::getDesignVariablePtr(int)'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addDesignVariablePositioner(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'DesignVariablePositioner::DesignVariablePositioner(int, OptimizationDomain*, int, DomainComponent*, char const**, int)'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addDesignVariablePositioner(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'DesignVariablePositioner::DesignVariablePositioner(int, OptimizationDomain*, int, DomainComponent*, char const**, int)'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addDesignVariablePositioner(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'DesignVariablePositioner::DesignVariablePositioner(int, OptimizationDomain*, int, DomainComponent*, char const**, int)'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addDesignVariablePositioner(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'DesignVariablePositioner::DesignVariablePositioner(int, OptimizationDomain*, int, Parameter&)'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addObjectiveFunction(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'OptimizationDomain::getNumberOfDesignVariables()'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addObjectiveFunction(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'ObjectiveFunction::ObjectiveFunction(int, OptimizationDomain*, Tcl_Interp*, bool, Vector*, char*, char*, char*, double, double, double, double)'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addConstraintFunction(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'OptimizationDomain::getNumberOfDesignVariables()'
lib/libOPS_InterpTcl.a(TclOptimizationBuilder.cpp.o):TclOptimizationBuilder.cpp:function TclOptimizationModelBuilder_addConstraintFunction(void*, Tcl_Interp*, int, char const**): error: undefined reference to 'ConstraintFunction::ConstraintFunction(int, int, OptimizationDomain*, Tcl_Interp*, bool, Matrix*, char*, char*, char*, Vector*, Vector*, Vector*, Vector*)'
lib/libOPS_InterpTcl.a(TclParameterCommands.cpp.o):TclParameterCommands.cpp:function TclModelBuilderParameterCommand(void*, Tcl_Interp*, int, char const**, Domain*, TclModelBuilder*): error: undefined reference to 'theReliabilityDomain'
lib/libOPS_InterpTcl.a(TclParameterCommands.cpp.o):TclParameterCommands.cpp:function TclModelBuilderParameterCommand(void*, Tcl_Interp*, int, char const**, Domain*, TclModelBuilder*): error: undefined reference to 'theReliabilityDomain'
lib/libOPS_InterpTcl.a(TclParameterCommands.cpp.o):TclParameterCommands.cpp:function TclModelBuilderParameterCommand(void*, Tcl_Interp*, int, char const**, Domain*, TclModelBuilder*): error: undefined reference to 'ReliabilityDomain::getRandomVariablePtr(int)'
lib/libOPS_InterpTcl.a(TclSeriesCommand.cpp.o):TclSeriesCommand.cpp:function TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*): error: undefined reference to 'theReliabilityDomain'
lib/libOPS_InterpTcl.a(TclSeriesCommand.cpp.o):TclSeriesCommand.cpp:function TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*): error: undefined reference to 'ReliabilityDomain::getModulatingFunction(int)'
lib/libOPS_InterpTcl.a(TclSeriesCommand.cpp.o):TclSeriesCommand.cpp:function TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*): error: undefined reference to 'DiscretizedRandomProcessSeries::DiscretizedRandomProcessSeries(int, int, ModulatingFunction**, double, double)
 adding _RELIABILITY definition for Linux. Fixes a compile issue but there are still link issues
'
lib/libOPS_InterpTcl.a(TclSeriesCommand.cpp.o):TclSeriesCommand.cpp:function TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*): error: undefined reference to 'theRandomNumberGenerator'
lib/libOPS_InterpTcl.a(TclSeriesCommand.cpp.o):TclSeriesCommand.cpp:function TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*): error: undefined reference to 'theReliabilityDomain'
lib/libOPS_InterpTcl.a(TclSeriesCommand.cpp.o):TclSeriesCommand.cpp:function TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*): error: undefined reference to 'ReliabilityDomain::getSpectrum(int)'
lib/libOPS_InterpTcl.a(TclSeriesCommand.cpp.o):TclSeriesCommand.cpp:function TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*): error: undefined reference to 'theRandomNumberGenerator'
lib/libOPS_InterpTcl.a(TclSeriesCommand.cpp.o):TclSeriesCommand.cpp:function TclTimeSeriesCommand(void*, Tcl_Interp*, int, char const**, Domain*): error: undefined reference to 'SimulatedRandomProcessSeries::SimulatedRandomProcessSeries(int, RandomNumberGenerator*, Spectrum*, int, double)'
/home/pletzera/.conan/data/hdf5/1.12.0/_/_/package/34e8c2c611dcf40c183971c3d147509658867af0/lib/libhdf5.a(H5system.c.o):H5system.c:function Pflock: error: undefined reference to 'fcntl64'
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/OpenSees] Error 1
gmake[1]: *** [CMakeFiles/OpenSees.dir/all] Error 2
gmake: *** [all] Error 2
(

**Comment by mhscott** [comment]
Thanks, I get similar linker errors too. Cmake was configured with Reliability turned off and a few things were missed.

I'll talk with @fmckenna on Monday to discuss the best way to fix the issues.

**Comment by mhscott** [comment]
We'll work on removing the _RELIABILITY ifdefs

**Comment by mhscott** [comment]
This should have fixed the issue: https://github.com/OpenSees/OpenSees/commit/9071926b49990b2f7ef7adc362646b4a3bd78236
