### ISSUE TITLE
the eigenvalue analysis 

### ISSUE THREAD

**Issue by Yahya-bit** [OpenSees/OpenSees#804]
hello every one
i have large model and i have problem with the eigenvalue analysis more than 5 hours and not finish

**Comment by Yahya-bit** [comment]
i try different options  same  thing

**Comment by mhscott** [comment]
Use the default eigenvalue solver
[eigen $Nmodes]

**Comment by fmckenna** [comment]
If you have a large problem you never ever want to use the lapack eigen solvers (they are only there for toy problems for people who need all eigenvalues for a 5 story shear building for example as found in Prof. Chopra's book or homework problem) .. instead, as MHS has said, use the default one, i.e. do not use anything but "eigen $numModes" .. for large problems, as the eigen command uses whatever solver has been created or will us a ProfileSPD solver if no solver has yet been specified, create your transient analysis first with a sparse solver and then use the eigen command.

NOTE for what you may read online: no one in their right might would use a full gen lapack solver to get the eigen values in OpenSees, as it obtains ALL the eigenvalues which is a time consuming iterative process which gets longer with the more eigenvalues requested in it's computation and only returns the amount asked for in the command. The eigensolver is O(n^3) which is BRUTAL given solving a full matrix equation is O(N^2) and only an idiot would use a full gen matrix to solve an FEM problem ..  Any comparison you see online about the slowness of the eigen command in OpenSees versus other codes has been generated by a fool who knows nothing about how OpenSees works and so their advice on anything OpenSees related should be ignored.
