### ISSUE TITLE
static analysis

### ISSUE THREAD

**Issue by Yahya-bit** [OpenSees/OpenSees#820]
hello, i have a large model of soil-structure interaction with dashpots. it takes more than 7h to finish the static analysis.
can any one help me with that

**Comment by mhscott** [comment]
You will need to provide more information on the analysis and which element, materials, etc. you are using.
Until you determine there is an error in the core C++ code, you should post your issue on the message board or Facebook group. The issues here deal with coding, not with modeling issues.
