### ISSUE TITLE
From what repository can I get the latest releases of OpenSeesMP and OpenSeesSP?

### ISSUE THREAD

**Issue by cuellin** [OpenSees/OpenSees#824]
I'm trying to obtain them using:
 cvs -d :pserver:anonymous@opensees.berkeley.edu:/usr/local/cvs
but it returns a message of connection timed out. Is this cvs repository still online?

**Comment by fmckenna** [comment]
they are not in any repository .. we are trying to rebuild them with the CMakeLists.txt files in this github repo
