### ISSUE TITLE
Parallelizing issue

### ISSUE THREAD

**Issue by Milad-TB** [OpenSees/OpenSees#833]
Hi
I've been working on an optimization project which links MATLAB with OpenSees. Since the project is extremely time-consuming, I had to parallelize it. It works fine with static procedures but it doesn't work when I use dynamic analysis (time history analysis). The program functions well while utilizing only one core with both static and dynamic procedures. I guess the problem is caused by a bug in OpenSees itself but I'm not sure.  My model is a 3D power plant incorporating truss elements and the analysis type is linear. Please let me know if you need any more information. I would appreciate it if you could help me.

**Comment by mhscott** [comment]
Yeah, more information is required. Please make a minimal working example that demonstrates the issue. We cannot read your mind :)

**Comment by Milad-TB** [comment]
> Yeah, more information is required. Please make a minimal working example that demonstrates the issue. We cannot read your mind :)

I'm using the genetic algorithm (GA) to find the optimum sections for a power plant.  MATLAB does the optimization and OpenSees runs the structural analysis. MATLAB generates the population required for GA, each of which using one core. So each population and therefore each core runs an OpenSees file. 
The model is subjected to static and transient loadings. The code works with no error when running the static analysis but when it comes to running the transient analysis in parallel, the program crashes. While the code works using only one core, even though it is excruciatingly time-consuming.

**Comment by mhscott** [comment]
I'm closing this issue. You can re-open the issue, or start a new one, when you find more specific details about what causes OpenSees to "crash". Creating a minimal working example will be beneficial for you and for anyone else who looks into the issue after you have narrowed it down. In the meantime, utilize online resources for help with OpenSees modeling, e.g., the message board, Facebook group, and search engines.
