### ISSUE TITLE
multiple definition errors when building OpenSeesMP 3.4.0 with Mumps

### ISSUE THREAD

**Issue by marianalevineu** [OpenSees/OpenSees#840]
Hi OpenSees developers, <br />

We've been trying to install OpenSeesMP 3.4.0 on our research cluster (Linux CentOS 7 system) for a while now. <br />
We are using the installation scripts and makefiles available here (We're using Intel compilers 2019 , Intel MKL and mpich 3.3.2): <br />
https://github.com/marianalevineu/openseesmp-discovery <br />

We were able to successfully install and run OpenSees v. 3.0.0 with this setup. <br />
However, for OpenSees versions 3.3.0 or 3.4.0 we keep getting the following errors:

```
/shared/centos7/opensees/3.4.0-mp-new/OpenSees/lib/libOpenSees.a(MumpsParallelSolver.o):MumpsParallelSolver.cpp:(.text+0x810): first defined here
/shared/centos7/opensees/3.4.0-mp-new/OpenSees/SRC/system_of_eqn/linearSOE/mumps/MumpsParallelSolver.o: In function `MumpsParallelSolver::initializeMumps()':
MumpsParallelSolver.cpp:(.text+0xde0): multiple definition of `MumpsParallelSolver::initializeMumps()'
/shared/centos7/opensees/3.4.0-mp-new/OpenSees/lib/libOpenSees.a(MumpsParallelSolver.o):MumpsParallelSolver.cpp:(.text+0xde0): first defined here
```
<br />
Could you let me know why we're getting those errors with later versions and how to fix it? <br />

Thanks in advance for your help!

**Comment by kasrash** [comment]
Hello,

I am wondering if you have found the solution to this issue. I am also having the same problem.

**Comment by mhscott** [comment]
Have you tried with the latest updates to OpenSees CMake?

**Comment by fmckenna** [comment]
latest documentation should fix this .. see build process

https://opensees.github.io/OpenSeesDocumentation/developer/build.html

**Comment by marianalevineu** [comment]
Thanks for your response @fmckenna. Seems that there are instructions for Linux Ubuntu, would those work for Centos 7 as well?

**Comment by fmckenna** [comment]
yes
