### ISSUE TITLE
beamIntegration destructor not called on "wipe" with tcl

### ISSUE THREAD

**Issue by mckee107** [OpenSees/OpenSees#841]
In the process of merging the Tcl and OPS_ constructor methods for some elements that we are developing, I've noticed that the `beamIntegration` destructor is not called if a Tcl script is used, instead of OpenSeesPy. 

I know that the `beamIntegration` method isn't used if the element uses a `Tcl______Command.cpp` constructor method instead of `OPS_`, but if the `beamIntegration` object can be constructed, it should also be destructed.

I'm not sure if this really matters at this point since, as I understand it, everything is supposed to be merging to `OPS_` (correct?). But incase it actually does matter, I've provided a MWE to demonstrate it. 

In this example, the `beamIntegration` isn't actually used, it's just created and ignored by the model.

```
# MWE	
for {set ii 0} {$ii < 5} {incr ii} {
	puts "\nTrial $ii\n";
	model basic -ndm 2 -ndf 3;		
	geomTransf Linear 1
	node 1 0. 0.
	node 2 0. 50.
	fix 1 1 1 1
	fix 2 1 0 1 	
	uniaxialMaterial Elastic 1 29000.;
	section Fiber 1 {
		patch circ 1 10 2 0.0 0.0 0.0 1.27 0.0 360.;
	}
	beamIntegration Lobatto 1 1 5;
	element dispBeamColumn 1 1 2 1 Lobatto 1 5;
	timeSeries Linear 1 ;
	pattern Plain 1 1 {
		load 2 0.0 -1.00 0.0
	}
	puts "Apply Loads" ;
	test EnergyIncr 1.0e-6 10 5;
	algorithm Newton;
	constraints Plain; 
	system FullGeneral;
	numberer RCM;
	integrator LoadControl 0.1 10.
	analysis Static;
	set ok [analyze 10];
	puts "Loads Done";
	puts "Wipe..."
	wipe;
	after 2000;
} 
puts "Complete";
```

**Comment by mhscott** [comment]
Thanks! Give it a try now after pulling this change https://github.com/OpenSees/OpenSees/commit/f9e656a357cafee97f49c2d35060efe6340df34e

**Comment by mckee107** [comment]
All good now! Thank you
