### ISSUE TITLE
save as data in Tsunami example

### ISSUE THREAD

**Issue by Maryliuo** [OpenSees/OpenSees#85]
Hello everyone, 
I  work with opensees and openseespy recently. I run the example of Openseespy, Dambreak with Elastic Obstacle Analysis. I would like to save the maximum of displacement and velocity at the free end of the obstacle. I think the command in FSI solver is different with the other solvers. If there is any command to get the maximum displacement or velocity in the specific period time for example from t=0s to t=4s, please send me the command. 
my objective:
Max (displacement node 13)-from t=0s to t=4s

node tag= 13;
time=0-4s

Many Thanks,

**Comment by mhscott** [comment]
Please post modeling issues to the OpenSees message board https://opensees.berkeley.edu/community
