### ISSUE TITLE
Sorcecode Repository link on OpenSees homepage

### ISSUE THREAD

**Issue by ramubhai** [OpenSees/OpenSees#856]
I came to know about OpenSees today only and looked for source code on official website(?) which is first result on google. 

https://opensees.berkeley.edu/

The source code link points to https://opensees.berkeley.edu/WebSVN/listing.php?repname=OpenSees&path=%2Ftrunk%2FSRC which is giving an error. It seems that link should point to this Git repository instead?

**Comment by jaabell** [comment]
Hi. Thanks! That's the old repository based on SVN. All current OpenSees development occurs on github. I'll leave this open in case @fmckenna wants to update that link.

**Comment by fmckenna** [comment]
fixed . thanks.
