### ISSUE TITLE
Compilation error in DistributedSuperLU.cpp

### ISSUE THREAD

**Issue by jyepesr1** [OpenSees/OpenSees#90]
Hello, 

I have been trying to compile OpenSeesMP with MUMPS, using the Intel MPI compiler, but it's failing to compile the file `DistributedSuperLU.cpp` in `SRC/system_of_eqn/linearSOE/sparseGEN`. The error is shown below.

```
DistributedSuperLU.cpp(237): error: argument of type "LUstruct_t *" is incompatible with parameter of type "int_t={int}"
      LUstructInit(n, &LUstruct);
                      ^

DistributedSuperLU.cpp(237): error #165: too few arguments in function call
      LUstructInit(n, &LUstruct);
                               ^
```

I would like to know what I am missing. Thanks.

**Comment by johnnyontheweb** [comment]
I'm trying to compile with `LUstructInit(n, n, &LUstruct);`

**Comment by mckee107** [comment]
Are the files pointing to the correct version of the SuperLU_Dist source code? I recently got that to compile, and had to update the source files in the DistributedSuperLU project to match

**Comment by mckee107** [comment]
I think that's the issue. 

In SuperLU_DIST_2.5:
`void LUstructInit(const int_t m, const int_t n, LUstruct_t *LUstruct)`

In SuperLU_DIST_4.3:
`void LUstructInit(const int_t n, LUstruct_t *LUstruct)`

**Comment by fmckenna** [comment]
resolved with latest cmake process.
