### ISSUE TITLE
elasticBeamColumn3d with release

### ISSUE THREAD

**Issue by silviamazzoni** [OpenSees/OpenSees#929]
It looks like releasey and releasez have been implemented in the elasticBeamColumn3d. this feature is not documented.
I did a simple test on releasez and it seems to work.
Are these options reliable?

**Comment by mhscott** [comment]
Yeah, they were implemented in 3D, but there was a bug and the input command wasn't correct either.
Those issues should be fixed now and are working. I'll update the documentation.
