### ISSUE TITLE
OpenSeesSP compile problems using VS2022

### ISSUE THREAD

**Issue by MXW1993** [OpenSees/OpenSees#947]
Hi OpenSees developers：
   I tried to compile OpenSeesSP using VS2022 in windows. But I got an error :
   LNK1181: “blacs_MPI-Win32.lib”,” blacsCinit_MPI-Win32.lib”,” scalapackd.lib”,” scalapack.lib” file cannot be opened 
   I know that I need to install BLAS, LAPACK, BLACS and SCALAPACK libraries to compile, but I can't find the corresponding "blacs_MPI-Win32.lib", "blacsCinit_MPI-Win32.lib", what do I need to compile to get these library files.

**Comment by mhscott** [comment]
The OpenSeesSP visual studio project is out of date, broken, and will not be fixed. @fmckenna will sort out CMake for OpenSeesSP and MP on Windows.
